-- 000 · Baseline: lo que existía antes de la primera migración (T-48)
-- ===========================================================================
-- ⚠️ NO SE APLICA EN PRODUCCIÓN. Producción ya tiene todo esto. Este archivo
-- existe para que el repositorio pueda **reconstruir el esquema desde cero**
-- (staging T-09, restauración T-07), cosa que hasta el 2026-09-23 no podía:
-- `001` declara «Requiere: public.questions» y ninguna migración crea
-- `questions`, `tests`, `profiles`, `guestbook`, `visitor`, `contacto` ni
-- `is_admin()`.
--
-- ── De dónde sale cada cosa ────────────────────────────────────────────────
-- 1. Las cinco tablas del sitio anterior al MVP (`questions`, `tests`,
--    `guestbook`, `visitor`, `contacto`) se crearon en el dashboard de Supabase
--    y nunca se versionaron. Acá van **en la forma que tenían antes de `001`**:
--    solo las columnas que ninguna migración agrega después. Las demás las
--    agregan `001`, `010`, `013`, `016`, `017`, `021`, `027`, `048`, `057`,
--    `061`, `067` y `070`, igual que pasó en producción.
-- 2. `profiles`, `is_admin()` y `handle_new_user()` vienen de
--    `supabase/admin_rls.sql`, y el tri-estado de `guestbook` de
--    `supabase/guestbook_tri_state.sql`: dos scripts que se corrieron a mano en
--    el SQL Editor antes de que existiera la numeración. Se incorporan acá
--    tal cual quedaron, y los dos archivos siguen donde están como historia.
--
-- ── Cómo se verificó ───────────────────────────────────────────────────────
-- `scripts/reconstruir_esquema.sh` levanta un PostgreSQL vacío, carga el stub
-- de Supabase (`supabase/baseline/stub_supabase.sql`), aplica este archivo y
-- después todas las migraciones en el orden de `SCHEMA.md`, y compara la
-- huella del catálogo contra producción. El resultado está en `SCHEMA.md`.
--
-- Los nombres de restricción son los de producción (`Tests_pkey` con
-- mayúscula incluida), porque es lo que las migraciones posteriores y la
-- huella esperan encontrar.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Tablas del sitio anterior al MVP
-- ---------------------------------------------------------------------------

create table if not exists public.visitor (
  id         bigint generated by default as identity,
  created_at timestamptz not null default now(),
  pais       character varying,
  ciudad     character varying,
  timezone   character varying,
  idioma     character varying,
  email      text,
  constraint visitor_pkey primary key (id)
);

create table if not exists public.guestbook (
  id          bigint generated by default as identity,
  created_at  timestamptz not null default now(),
  name        character varying not null,
  email       character varying,
  phone       character varying,
  message     text,
  is_approved boolean,
  id_visitor  bigint,
  constraint guestbook_pkey primary key (id),
  constraint guestbook_id_visitor_fkey foreign key (id_visitor) references public.visitor (id)
);

create table if not exists public.contacto (
  id         bigint generated by default as identity,
  created_at timestamptz not null default now(),
  mensaje    text,
  extra      jsonb,
  constraint contacto_pkey primary key (id)
);

create table if not exists public.questions (
  id             bigint generated always as identity,
  created_at     timestamptz default now(),
  question       text not null,
  option_a       text not null,
  option_b       text not null,
  option_c       text not null,
  option_d       text not null,
  correct_option character(1) not null,
  error_a        text,
  error_b        text,
  error_c        text,
  error_d        text,
  topic          text not null,
  order_index    integer,
  difficulty     real,
  constraint questions_pkey primary key (id),
  constraint questions_correct_option_check
    check (correct_option = any (array['A'::bpchar, 'B'::bpchar, 'C'::bpchar, 'D'::bpchar]))
);

create table if not exists public.tests (
  id           bigint generated by default as identity,
  created_at   timestamptz not null default now(),
  test         jsonb,
  "email-user" text not null,
  user_id      uuid default auth.uid(),
  constraint "Tests_pkey" primary key (id),
  constraint tests_user_id_fkey foreign key (user_id) references auth.users (id)
);

alter table public.visitor   enable row level security;
alter table public.guestbook enable row level security;
alter table public.contacto  enable row level security;
alter table public.questions enable row level security;
alter table public.tests     enable row level security;

-- Las policies del sitio anterior que ninguna migración reescribe después.
drop policy if exists "guestbook_insert" on public.guestbook;
create policy "guestbook_insert" on public.guestbook
  for insert to anon, authenticated
  with check (char_length(trim(both from name)) > 0 and coalesce(is_approved, false) = false);

drop policy if exists "guestbook_select_approved" on public.guestbook;
create policy "guestbook_select_approved" on public.guestbook
  for select to public
  using (is_approved = true);

drop policy if exists "allow insert" on public.contacto;
create policy "allow insert" on public.contacto
  for insert to anon, authenticated
  with check (true);

-- ---------------------------------------------------------------------------
-- 2. `supabase/admin_rls.sql` — profiles, is_admin() y el alta automática
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  role text not null default 'user'
    check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create index if not exists profiles_role_idx on public.profiles (role);
create index if not exists profiles_email_idx on public.profiles (email);

alter table public.profiles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated, anon;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'user')
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  to authenticated
  using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (
    id = auth.uid()
    and role = (select p.role from public.profiles p where p.id = auth.uid())
  );

drop policy if exists "guestbook_select_admin" on public.guestbook;
create policy "guestbook_select_admin"
  on public.guestbook for select
  to authenticated
  using (public.is_admin());

drop policy if exists "guestbook_update_admin" on public.guestbook;
create policy "guestbook_update_admin"
  on public.guestbook for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- 3. `supabase/guestbook_tri_state.sql` — null = pendiente, true, false = papelera
-- ---------------------------------------------------------------------------

alter table public.guestbook alter column is_approved drop not null;
alter table public.guestbook alter column is_approved set default null;

drop policy if exists "guestbook_delete_admin" on public.guestbook;
create policy "guestbook_delete_admin"
  on public.guestbook for delete
  to authenticated
  using (public.is_admin());
