-- EXPERIMENTO · Banco de ítems, bloque III: momento angular (43 ítems).
-- Topics: mq_momento_angular · mq_armonicos_esfericos · mq_espin · mq_suma_momentos
--
-- ⚠ APLICAR DESPUÉS DE 033, 034, 035 y 036.
-- Patrón de inserción: ver cabecera de 035.
--
-- ── Por qué este bloque es más grande que los otros ────────────────────────
-- Es el temario que el profesor marcó como de máxima prioridad ("es casi seguro
-- que aparezcan problemas de este tipo, usualmente más de uno") y el que cubren
-- los apuntes de origen. Los cuatro topics de acá se corresponden con los
-- problemas 1, 2, 3 y 4 de la estructura de examen declarada:
--
--   Problema 1 · conmutadores mixtos [L_i,R_j], [L_i,P_j], [L_i,P²]  → mq_momento_angular
--   Problema 2 · álgebra de operadores escalera y degeneración        → mq_momento_angular
--   Problema 3 · suma de momentos angulares                          → mq_suma_momentos
--   Problema 4 · armónicos esféricos o matrices de Pauli   → mq_armonicos_esfericos / mq_espin
--
-- 15 ítems en `mq_momento_angular` no es capricho: con `max_items = 12` (040)
-- el banco tiene que ser mayor que el test para que la selección adaptativa
-- tenga de dónde elegir. Un banco del mismo tamaño que el test convierte al
-- diagnóstico adaptativo en un cuestionario fijo.

with items (topic, module_slug, difficulty, order_index,
            question, option_a, option_b, option_c, option_d, correct_option,
            error_a, error_b, error_c, error_d,
            mis_a, mis_b, mis_c, mis_d) as (
  values

  -- ===========================================================================
  -- mq_momento_angular · Álgebra, conmutadores mixtos y operadores escalera
  -- ===========================================================================

  ($qm$mq_momento_angular$qm$::text, $qm$cuantica/momento_angular$qm$::text,
   (-1.1)::double precision, 10::int,
   $qm$¿Cuál es la relación de conmutación fundamental de las componentes del momento angular?$qm$::text,
   $qm$$[L_i, L_j] = i\hbar\,\epsilon_{ijk}L_k$$qm$::text,
   $qm$$[L_i, L_j] = 0$$qm$::text,
   $qm$$[L_i, L_j] = i\hbar\,\delta_{ij}L_k$$qm$::text,
   $qm$$[L_i, L_j] = \hbar\,\epsilon_{ijk}L_k$$qm$::text,
   $qm$A$qm$::text,
   $qm$Correcto. Es el álgebra de Lie del grupo de rotaciones, y de ella sola -- sin resolver ninguna ecuación diferencial -- salen los autovalores $\hbar^2 l(l+1)$ y $\hbar m$.$qm$::text,
   $qm$Si conmutaran, las tres componentes serían simultáneamente medibles y el momento angular sería un vector clásico bien definido. Todo lo característico del tema (que solo se pueda fijar una componente, la escalera, la degeneración $2l+1$) nace de que **no** conmutan.$qm$::text,
   $qm$Con $\delta_{ij}$ el lado derecho se anula para $i\neq j$, o sea $L_x$ y $L_y$ conmutarían: es la respuesta anterior disfrazada. Además $k$ quedaría como índice libre no apareado, lo que ya delata que la expresión está mal.$qm$::text,
   $qm$Falta la unidad imaginaria. Es obligatoria: $L_i$ y $L_j$ son hermíticos, y el conmutador de dos hermíticos es antihermítico, así que tiene que ser $i$ por un hermítico.$qm$::text,
   null::text, $qm$mq/conmutadores/asume-conmutatividad$qm$::text,
   $qm$mq/conmutadores/asume-conmutatividad$qm$::text,
   $qm$mq/conmutadores/canonico-sin-i$qm$::text),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, -0.7, 20,
   $qm$¿Cuánto vale $[L^{2}, L_z]$?$qm$,
   $qm$$i\hbar L_x$$qm$,
   $qm$$0$$qm$,
   $qm$$i\hbar L_y$$qm$,
   $qm$$0$, y por la misma razón también $[L_x,L_y] = 0$.$qm$,
   $qm$B$qm$,
   $qm$Si no fuera cero, no existiría la base $|l,m\rangle$ de autovectores comunes, que es el andamio de todo el tema. El cálculo por componentes da $[L_x^2,L_z] = -i\hbar(L_xL_y+L_yL_x)$ y $[L_y^2,L_z] = +i\hbar(L_yL_x+L_xL_y)$: se cancelan exactamente.$qm$,
   $qm$Correcto. $L^2$ conmuta con **todas** las componentes de $\vec L$, no solo con $L_z$. Físicamente: se pueden conocer a la vez el módulo del momento angular y una de sus proyecciones, pero no dos proyecciones.$qm$,
   $qm$Mismo error que la primera alternativa, con otra componente. Conviene rehacer la cuenta: la clave es que los dos términos que sobreviven, el de $L_x^2$ y el de $L_y^2$, son iguales y de signo opuesto.$qm$,
   $qm$La primera parte es correcta y la segunda es falsa. $[L_x,L_y] = i\hbar L_z \neq 0$: por eso hay que elegir **una sola** componente para etiquetar los estados. Que $L^2$ conmute con cada componente no implica que las componentes conmuten entre sí.$qm$,
   $qm$mq/momento-angular/l2-no-conmuta-con-lz$qm$, null,
   $qm$mq/momento-angular/l2-no-conmuta-con-lz$qm$,
   $qm$mq/conmutadores/asume-conmutatividad$qm$),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, -0.3, 30,
   $qm$Para el estado $|l,m\rangle$, ¿cuáles son los autovalores de $L^{2}$ y de $L_z$?$qm$,
   $qm$$\hbar^{2}l^{2}$ y $\hbar m$$qm$,
   $qm$$\hbar^{2}l(l+1)$ y $\hbar m$$qm$,
   $qm$$\hbar\, l(l+1)$ y $\hbar^{2} m$$qm$,
   $qm$$\hbar^{2}m(m+1)$ y $\hbar l$$qm$,
   $qm$B$qm$,
   $qm$El autovalor de $L^2$ es $\hbar^2l(l+1)$, no $\hbar^2l^2$. La diferencia no es cosmética: implica que $|\vec L| = \hbar\sqrt{l(l+1)} > \hbar l = (L_z)_{max}$, o sea que el vector **nunca** puede alinearse del todo con el eje $z$.$qm$,
   $qm$Correcto. $L^2|l,m\rangle = \hbar^2l(l+1)|l,m\rangle$ y $L_z|l,m\rangle = \hbar m|l,m\rangle$, con $m = -l, -l+1, \dots, l$.$qm$,
   $qm$Las potencias de $\hbar$ están cambiadas. $L^2$ tiene unidades de momento angular al cuadrado, así que su autovalor lleva $\hbar^2$; $L_z$ es un momento angular y lleva $\hbar$ a la primera. Chequear unidades descarta esta opción sin hacer ninguna cuenta.$qm$,
   $qm$Los papeles de $l$ y $m$ están intercambiados. $l$ fija el **módulo** (y por eso aparece en $L^2$) y $m$ la **proyección** (y por eso aparece en $L_z$).$qm$,
   $qm$mq/momento-angular/autovalor-de-l2$qm$, null,
   $qm$mq/momento-angular/autovalor-de-l2$qm$,
   $qm$mq/momento-angular/autovalor-de-l2$qm$),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 0.1, 40,
   $qm$Para $l = 2$, ¿cuántos valores puede tomar $m$ y cuáles son?$qm$,
   $qm$4 valores, porque son $2l$.$qm$,
   $qm$5 valores: $m = -2, -1, 0, 1, 2$.$qm$,
   $qm$6 valores: $m = -3, -2, -1, 0, 1, 2$.$qm$,
   $qm$3 valores: $m = 0, 1, 2$.$qm$,
   $qm$B$qm$,
   $qm$La multiplicidad es $2l+1$, no $2l$. El $+1$ es el estado $m=0$, que existe siempre que $l$ sea entero y que se pierde al contar solo los pares $\pm m$.$qm$,
   $qm$Correcto. $m$ va de $-l$ a $+l$ de a saltos enteros: $2l+1 = 5$ estados degenerados en $L^2$, todos con el mismo autovalor $6\hbar^2$.$qm$,
   $qm$$m = -3$ no está permitido: la proyección no puede superar en módulo a $l$. Además $|m|\leq l$ es lo que garantiza que $\langle L_x^2+L_y^2\rangle = \hbar^2[l(l+1)-m^2]$ sea no negativo.$qm$,
   $qm$Faltan las proyecciones negativas. $m$ es la proyección sobre $z$ y puede apuntar en sentido contrario: el rango es simétrico, de $-l$ a $+l$.$qm$,
   $qm$mq/momento-angular/degeneracion-2l$qm$, null,
   $qm$mq/momento-angular/lz-supera-el-modulo$qm$,
   $qm$mq/momento-angular/degeneracion-2l$qm$),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 0.5, 50,
   $qm$Se quiere calcular $[L_i, R_j]$. ¿Cuál sustitución de $L_i$ es la adecuada?$qm$,
   $qm$$L_i = \epsilon_{ijk}R_jP_k$$qm$,
   $qm$$L_i = \epsilon_{ikl}R_kP_l$$qm$,
   $qm$$L_i = \epsilon_{ijk}R_kP_j$$qm$,
   $qm$$L_i = \epsilon_{lki}R_kP_l$$qm$,
   $qm$B$qm$,
   $qm$Es la definición correcta en abstracto, pero **no** sirve acá: $j$ ya está ocupado como índice libre del conmutador. Reusarlo como índice mudo mezcla dos cosas distintas y produce una expresión sin sentido, con $j$ apareciendo tres veces.$qm$,
   $qm$Correcto. Con $i$ y $j$ ya ocupados por el conmutador, los índices mudos tienen que ser letras nuevas: $k$ y $l$. Es la regla de oro de todo cálculo con índices, y el único paso donde suele romperse este problema.$qm$,
   $qm$Tiene el mismo problema de reutilizar $j$, y encima intercambia $R$ y $P$ respecto de la definición, lo que cambia el signo del resultado.$qm$,
   $qm$Los índices mudos son nuevos, pero el orden está mal: $\epsilon_{lki} = \epsilon_{ilk} = -\epsilon_{ikl}$ (la primera igualdad es una permutación cíclica, que conserva el signo; la segunda intercambia dos índices y lo invierte). Esta sustitución define $-L_i$, no $L_i$.$qm$,
   $qm$mq/indices/reusa-indice-libre-como-mudo$qm$, null,
   $qm$mq/indices/reusa-indice-libre-como-mudo$qm$,
   $qm$mq/levi-civita/antisimetria-ignorada$qm$),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 0.9, 60,
   $qm$¿Cuánto vale $[L_i, R_j]$?$qm$,
   $qm$$i\hbar\,\epsilon_{ijk}R_k$$qm$,
   $qm$$-i\hbar\,\epsilon_{ijk}R_k$$qm$,
   $qm$$i\hbar\,\delta_{ij}R_k$$qm$,
   $qm$$0$$qm$,
   $qm$A$qm$,
   $qm$Correcto. El desarrollo llega a $-i\hbar\,\epsilon_{ikj}R_k$, y la antisimetría $\epsilon_{ikj} = -\epsilon_{ijk}$ absorbe el signo. La forma final dice que $\vec R$ se transforma como un vector bajo rotaciones, que es exactamente lo que uno esperaría.$qm$,
   $qm$Es el resultado justo antes del último paso: quedó $\epsilon_{ikj}$ y falta permutar los dos últimos índices, lo que cambia el signo. Es el error más frecuente de este cálculo.$qm$,
   $qm$La delta no corresponde: se usa para **colapsar** la suma sobre un índice mudo, no para quedarse escrita en el resultado. Además $k$ queda libre y sin sumar, lo que hace la expresión ambigua.$qm$,
   $qm$Si fuera cero, la posición sería compatible con el momento angular y ambos tendrían valores definidos a la vez. La posición **no** es invariante bajo rotaciones: rotar mueve el punto.$qm$,
   null, $qm$mq/levi-civita/antisimetria-ignorada$qm$,
   $qm$mq/delta/no-colapsa-la-suma$qm$,
   $qm$mq/conmutadores/asume-conmutatividad$qm$),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 1.0, 70,
   $qm$Al calcular $[L_i, P_j]$ se llega a $i\hbar\,\epsilon_{ijl}P_l$, pero el resultado buscado es $i\hbar\,\epsilon_{ijk}P_k$. ¿Qué hace falta para cerrarlo?$qm$,
   $qm$Renombrar el índice mudo $l \to k$: al estar sumado, su nombre es irrelevante.$qm$,
   $qm$Permutar dos índices de $\epsilon$, lo que cambia el signo.$qm$,
   $qm$Nada: son expresiones distintas y el cálculo tiene un error previo.$qm$,
   $qm$Aplicar la identidad de contracción $\epsilon\epsilon = \delta\delta - \delta\delta$.$qm$,
   $qm$A$qm$,
   $qm$Correcto. $l$ es un índice **mudo** (aparece dos veces y está sumado), así que puede llamarse como se quiera. A diferencia de $[L_i,R_j]$, este cálculo no necesita ningún cambio de signo: sale directo.$qm$,
   $qm$Acá no hace falta permutar nada: los índices ya están en el orden $ijl$, que es el mismo orden que $ijk$. Ese paso es el que sí hace falta en $[L_i,R_j]$, donde se llega a $\epsilon_{ikj}$.$qm$,
   $qm$Son la misma expresión. Cambiar el nombre de un índice sumado no cambia nada, igual que $\sum_l a_l$ y $\sum_k a_k$ son el mismo número.$qm$,
   $qm$La identidad de contracción sirve cuando hay **dos** tensores $\epsilon$ multiplicados y un índice compartido. Acá hay uno solo, así que no aplica.$qm$,
   null, $qm$mq/levi-civita/antisimetria-ignorada$qm$, null,
   $qm$mq/levi-civita/contraccion-mal-aplicada$qm$),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 1.2, 80,
   $qm$En el cálculo de $[L_i, P^{2}]$ se llega a $2i\hbar\,\epsilon_{ijk}P_jP_k$. ¿Por qué esa expresión vale cero?$qm$,
   $qm$Porque $P_jP_k = 0$ cuando $j \neq k$.$qm$,
   $qm$Porque $\epsilon_{ijk} = 0$ siempre que hay índices repetidos, y acá $j$ y $k$ están sumados.$qm$,
   $qm$Porque $\epsilon_{ijk}$ es antisimétrico al intercambiar $j$ y $k$, mientras que $P_jP_k$ es simétrico (los momentos conmutan entre sí): la suma se cancela término a término.$qm$,
   $qm$No vale cero: $[L_i,P^{2}] = 2i\hbar\,\epsilon_{ijk}P_jP_k$ es el resultado final.$qm$,
   $qm$C$qm$,
   $qm$Componentes distintas del momento no se anulan al multiplicarse: $P_xP_y$ es un operador perfectamente no nulo. Lo que sí es cierto es que **conmutan**, y esa es la propiedad que se necesita.$qm$,
   $qm$$\epsilon_{ijk}$ se anula si dos de sus índices toman el mismo **valor**, pero $j$ y $k$ recorren valores distintos en la suma; los términos con $j=k$ son solo algunos de los sumandos. La cancelación viene de otro lado.$qm$,
   $qm$Correcto. Llamando $S = \epsilon_{ijk}P_jP_k$ y renombrando los mudos $j \leftrightarrow k$, queda $S = \epsilon_{ikj}P_kP_j = -\epsilon_{ijk}P_jP_k = -S$, y $S = -S$ obliga a $S=0$. Es el argumento general: la contracción de algo antisimétrico con algo simétrico siempre se anula.$qm$,
   $qm$Sí vale cero, y es el punto del ejercicio: $[L_i,P^2]=0$ expresa la invariancia rotacional de la energía cinética. Si no se anulara, el momento angular no se conservaría para una partícula libre.$qm$,
   null, $qm$mq/levi-civita/contraccion-mal-aplicada$qm$, null, null),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 1.4, 90,
   $qm$¿Qué consecuencia física tiene $[L_i, P^{2}] = 0$?$qm$,
   $qm$Que $L_i$ y $P^{2}$ tienen los mismos autovalores.$qm$,
   $qm$Que el momento angular de una partícula libre es nulo.$qm$,
   $qm$Que $L_i$ conmuta también con cada componente $P_j$ por separado.$qm$,
   $qm$Que el momento angular es una constante de movimiento para una partícula libre, porque $H = P^{2}/2m$.$qm$,
   $qm$D$qm$,
   $qm$Conmutar significa compartir **autovectores**, no autovalores. Los de $L_i$ tienen unidades de momento angular y los de $P^2$ de momento al cuadrado: ni siquiera son comparables.$qm$,
   $qm$Nada obliga a que sea nulo: una partícula libre puede tener cualquier momento angular respecto de un origen elegido. Lo que dice el resultado es que ese valor **no cambia** con el tiempo.$qm$,
   $qm$Justamente no: $[L_i,P_j] = i\hbar\epsilon_{ijk}P_k \neq 0$. Lo notable del resultado es que la combinación invariante $P^2 = P_jP_j$ sí conmuta, aunque sus piezas no lo hagan. La invariancia es de la magnitud, no de las componentes.$qm$,
   $qm$Correcto. Por Ehrenfest, $[L_i,H]=0$ implica $d\langle L_i\rangle/dt = 0$. Es el teorema de Noether en versión cuántica: la isotropía del espacio (ninguna dirección privilegiada) equivale a la conservación del momento angular.$qm$,
   null, null, $qm$mq/conmutadores/asume-conmutatividad$qm$, null),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 1.6, 100,
   $qm$Con $L_{\pm} = L_x \pm iL_y$, ¿cuánto vale $[L_z, L_{\pm}]$?$qm$,
   $qm$$\pm i\hbar L_{\pm}$$qm$,
   $qm$$0$$qm$,
   $qm$$\pm\hbar L_{\pm}$$qm$,
   $qm$$\pm\hbar L_z$$qm$,
   $qm$C$qm$,
   $qm$Sobra la $i$. El desarrollo es $[L_z,L_x] \pm i[L_z,L_y] = i\hbar L_y \pm i(-i\hbar L_x) = i\hbar L_y \pm \hbar L_x = \pm\hbar(L_x \pm iL_y)$: las dos $i$ se combinan y desaparecen.$qm$,
   $qm$Si conmutaran, $L_{\pm}$ no movería el autovalor de $L_z$ y no habría escalera. Justamente porque **no** conmutan, $L_{\pm}|l,m\rangle$ es autoestado de $L_z$ con autovalor corrido en $\pm\hbar$.$qm$,
   $qm$Correcto. Es la relación que hace de $L_{\pm}$ operadores escalera: $L_z(L_{\pm}|l,m\rangle) = \hbar(m\pm1)(L_{\pm}|l,m\rangle)$.$qm$,
   $qm$El resultado tiene que ser proporcional a $L_{\pm}$, no a $L_z$: es lo que permite reordenar $L_zL_{\pm} = L_{\pm}(L_z \pm \hbar)$ y leer el nuevo autovalor.$qm$,
   $qm$mq/conmutadores/canonico-sin-i$qm$,
   $qm$mq/conmutadores/asume-conmutatividad$qm$, null, null),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 1.8, 110,
   $qm$De $[L_z, L_+] = \hbar L_+$ se deduce que $L_+|l,m\rangle$ es autoestado de $L_z$. ¿Con qué autovalor, y qué pasa con $l$?$qm$,
   $qm$Autovalor $\hbar(m+1)$, con $l$ inalterado.$qm$,
   $qm$Autovalor $\hbar(m+1)$, y además $l$ pasa a $l+1$.$qm$,
   $qm$Autovalor $\hbar m$: $L_+$ no cambia la proyección.$qm$,
   $qm$Autovalor $\hbar(m+1)$, pero solo si $m < 0$.$qm$,
   $qm$A$qm$,
   $qm$Correcto. $L_z(L_+|l,m\rangle) = (L_+L_z + \hbar L_+)|l,m\rangle = \hbar(m+1)L_+|l,m\rangle$. Y $l$ no cambia porque $[L^2,L_+] = 0$: ese es exactamente el contenido de la degeneración.$qm$,
   $qm$La primera parte está bien, la segunda no. $L^2$ conmuta con $L_{\pm}$, así que el autovalor $\hbar^2l(l+1)$ **no** se toca: la escalera se mueve dentro de un mismo multiplete de $2l+1$ estados, no entre multipletes.$qm$,
   $qm$Si no cambiara la proyección, el conmutador con $L_z$ sería cero. Todo el mecanismo consiste en que $L_+$ desplaza $m$ en una unidad.$qm$,
   $qm$La relación vale para todo $m$; el único caso especial es el tope $m = l$, donde $L_+|l,l\rangle = 0$ y no hay estado nuevo. El signo de $m$ es irrelevante.$qm$,
   null, $qm$mq/momento-angular/escalera-cambia-l$qm$, null, null),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 2.0, 120,
   $qm$¿Qué demuestra el hecho de que $[L^{2}, L_{\pm}] = 0$?$qm$,
   $qm$Que $L_{\pm}$ no modifica el estado.$qm$,
   $qm$Que $L^{2}$ y $L_{\pm}$ son observables compatibles y pueden medirse a la vez.$qm$,
   $qm$Que $L_{\pm}|l,m\rangle$ sigue siendo autoestado de $L^{2}$ con el **mismo** autovalor $\hbar^{2}l(l+1)$: los $2l+1$ estados de distinto $m$ son degenerados.$qm$,
   $qm$Que al aplicar $L_{\pm}$ el autovalor de $L^{2}$ pasa a $\hbar^{2}(l+1)(l+2)$.$qm$,
   $qm$C$qm$,
   $qm$Sí lo modifica: cambia $m$ en una unidad. Lo que no modifica es el autovalor de $L^2$, y esa es toda la gracia.$qm$,
   $qm$$L_{\pm}$ no es hermítico ($L_+^{\dagger} = L_-$), así que no es un observable y no tiene sentido hablar de medirlo. Es una herramienta algebraica, igual que $a$ y $a^{\dagger}$ en el oscilador.$qm$,
   $qm$Correcto. De $L^2L_{\pm} = L_{\pm}L^2$ sale $L^2(L_{\pm}|l,m\rangle) = \hbar^2l(l+1)(L_{\pm}|l,m\rangle)$: el autovalor escalar sale afuera intacto. Varios estados distintos (distinto $m$) comparten el mismo autovalor de $L^2$, que es la definición de degeneración.$qm$,
   $qm$Eso exigiría $[L^2,L_{\pm}] \neq 0$. Como el conmutador se anula, el autovalor de $L^2$ es intocable: $L_{\pm}$ se mueve **dentro** del multiplete, nunca entre multipletes.$qm$,
   null, $qm$mq/oscilador/escalera-hermitica$qm$, null,
   $qm$mq/momento-angular/escalera-cambia-l$qm$),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 2.1, 130,
   $qm$¿Por qué la escalera se corta por arriba, es decir por qué $L_+|l,l\rangle = 0$?$qm$,
   $qm$Porque $L_+$ es nilpotente: $(L_+)^{2} = 0$.$qm$,
   $qm$Porque $\langle L_x^{2}+L_y^{2}\rangle = \hbar^{2}[l(l+1)-m^{2}] \geq 0$ acota $m$, y como $L_+$ no cambia $l$, la única salida consistente es que aplicado al tope dé el vector nulo.$qm$,
   $qm$Porque $m$ no puede superar a $l$ por una convención de notación.$qm$,
   $qm$No se corta: aplicando $L_+$ repetidamente, $m$ crece indefinidamente.$qm$,
   $qm$B$qm$,
   $qm$$L_+$ no es nilpotente en general: $(L_+)^2|l,-l\rangle \neq 0$ si $l\geq 1$. Lo que se anula es su acción sobre el estado **tope**, no el operador.$qm$,
   $qm$Correcto. $L_x^2+L_y^2 = L^2-L_z^2$ es una suma de cuadrados de hermíticos, así que su valor esperado no puede ser negativo. Eso acota $m^2 \leq l(l+1)$, y como la escalera sube de a pasos enteros sin cambiar $l$, tiene que terminar exactamente en $m=l$.$qm$,
   $qm$No es convención: es una consecuencia forzada de que $L^2 - L_z^2$ sea un operador semidefinido positivo. Y de ahí, junto con que la escalera avanza de a 1, sale además que $2l$ debe ser entero.$qm$,
   $qm$Si $m$ creciera sin cota, $\langle L_x^2+L_y^2\rangle = \hbar^2[l(l+1)-m^2]$ terminaría siendo negativo, lo que es imposible para una suma de cuadrados de operadores hermíticos.$qm$,
   null, null, null,
   $qm$mq/momento-angular/lz-supera-el-modulo$qm$),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 2.3, 140,
   $qm$¿Cuál es la expresión completa de $L_{\pm}|l,m\rangle$, con el estado resultante normalizado?$qm$,
   $qm$$|l, m\pm1\rangle$$qm$,
   $qm$$\hbar\sqrt{l(l+1)-m(m\pm1)}\;|l,m\pm1\rangle$$qm$,
   $qm$$\hbar^{2}\sqrt{l(l+1)-m(m\pm1)}\;|l,m\pm1\rangle$$qm$,
   $qm$$\hbar\sqrt{m(m\pm1)}\;|l,m\pm1\rangle$$qm$,
   $qm$B$qm$,
   $qm$La dirección es correcta pero falta el coeficiente, y no es un detalle: es justamente ese factor el que se anula en $m = \pm l$ y corta la escalera. Sin él, nada impediría subir para siempre.$qm$,
   $qm$Correcto. El factor sale de $\|L_{\pm}|l,m\rangle\|^2 = \langle l,m|L_{\mp}L_{\pm}|l,m\rangle = \hbar^2[l(l+1)-m(m\pm1)]$, usando $L_{\mp}L_{\pm} = L^2 - L_z^2 \mp \hbar L_z$. En $m=l$ con el signo $+$ da cero.$qm$,
   $qm$Las unidades no cierran: $L_{\pm}$ es un momento angular y su acción debe llevar un $\hbar$ a la primera potencia, no al cuadrado. El $\hbar^2$ pertenece al autovalor de $L^2$, no a este factor.$qm$,
   $qm$Falta el término $l(l+1)$. Con este factor, en $m = l$ el coeficiente daría $\hbar\sqrt{l(l+1)} \neq 0$ y la escalera no se cortaría, lo que contradice la cota $|m|\leq l$.$qm$,
   $qm$mq/momento-angular/norma-escalera-omitida$qm$, null,
   $qm$mq/momento-angular/autovalor-de-l2$qm$,
   $qm$mq/momento-angular/norma-escalera-omitida$qm$),

  ($qm$mq_momento_angular$qm$, $qm$cuantica/momento_angular$qm$, 2.4, 150,
   $qm$El álgebra $[J_i,J_j] = i\hbar\epsilon_{ijk}J_k$ admite, por sí sola, valores de $j$ enteros **y** semienteros. ¿Por qué el momento angular **orbital** $\vec L = \vec R\times\vec P$ solo admite $l$ entero?$qm$,
   $qm$Porque el álgebra de $\vec L$ no es la misma que la de $\vec J$.$qm$,
   $qm$Porque los momentos angulares semienteros no existen en la naturaleza.$qm$,
   $qm$Porque $\vec L$ tiene módulo bien definido y $\vec J$ no.$qm$,
   $qm$Porque sus autofunciones son funciones del ángulo, y la condición de univaluación $\psi(\varphi+2\pi) = \psi(\varphi)$ obliga a que $m$ (y por lo tanto $l$) sea entero.$qm$,
   $qm$D$qm$,
   $qm$El álgebra es idéntica: $\vec L$ la satisface exactamente. La restricción a valores enteros es información **adicional**, que viene de realizar el álgebra sobre funciones de posición y no del álgebra misma.$qm$,
   $qm$Sí existen: el espín $1/2$ del electrón es semientero, y es lo que explica los dos haces de Stern-Gerlach. Lo que no admite semienteros es el momento angular orbital.$qm$,
   $qm$Los dos tienen módulo bien definido, $\hbar\sqrt{j(j+1)}$. La diferencia no está ahí.$qm$,
   $qm$Correcto. La parte azimutal es $e^{im\varphi}$, y exigir que la función de onda tome un solo valor en cada punto del espacio fuerza $m \in \mathbb{Z}$. El espín no vive en funciones de posición, así que esa condición no lo alcanza y puede ser semientero.$qm$,
   null, $qm$mq/momento-angular/semienteros-no-existen$qm$, null, null),

  -- ===========================================================================
  -- mq_armonicos_esfericos · Armónicos esféricos y potencial central
  -- ===========================================================================

  ($qm$mq_armonicos_esfericos$qm$, $qm$cuantica/armonicos_esfericos$qm$, -0.8, 10,
   $qm$¿De qué operadores son autofunciones simultáneas los armónicos esféricos $Y_l^m(\theta,\varphi)$?$qm$,
   $qm$De $L^{2}$ y $L_z$.$qm$,
   $qm$De $L_x$, $L_y$ y $L_z$ a la vez.$qm$,
   $qm$Del Hamiltoniano, sea cual sea el potencial.$qm$,
   $qm$Solo de $L^{2}$.$qm$,
   $qm$A$qm$,
   $qm$Correcto. $L^2Y_l^m = \hbar^2l(l+1)Y_l^m$ y $L_zY_l^m = \hbar m Y_l^m$: los dos números cuánticos angulares corresponden exactamente a esos dos operadores, que conmutan entre sí.$qm$,
   $qm$Imposible: las componentes no conmutan entre sí ($[L_x,L_y]=i\hbar L_z$), así que no admiten autofunciones comunes salvo el caso trivial $l=0$.$qm$,
   $qm$Solo lo son si el potencial es **central**, $V = V(r)$; ahí $[H,L^2]=[H,L_z]=0$ y la parte angular de las soluciones son los $Y_l^m$. Con un potencial que dependa de los ángulos, esto se cae.$qm$,
   $qm$También lo son de $L_z$, y por eso llevan **dos** índices: $l$ para $L^2$ y $m$ para $L_z$. Con solo $L^2$ no se distinguirían los $2l+1$ estados degenerados.$qm$,
   null, $qm$mq/momento-angular/l2-no-conmuta-con-lz$qm$, null, null),

  ($qm$mq_armonicos_esfericos$qm$, $qm$cuantica/armonicos_esfericos$qm$, -0.3, 20,
   $qm$¿Cómo es el armónico esférico $Y_0^0$, correspondiente a $l = 0$?$qm$,
   $qm$Proporcional a $\cos\theta$.$qm$,
   $qm$Constante: la distribución angular de probabilidad es isótropa.$qm$,
   $qm$Idénticamente nulo, porque $l=0$ significa ausencia de estado.$qm$,
   $qm$No normalizable.$qm$,
   $qm$B$qm$,
   $qm$Eso es $Y_1^0$, el estado con $l=1$, $m=0$. La dependencia en $\cos\theta$ es lo que le da al orbital $p_z$ su forma de dos lóbulos.$qm$,
   $qm$Correcto. $Y_0^0 = 1/\sqrt{4\pi}$, una constante: sin momento angular no hay dirección privilegiada, y por eso los orbitales $s$ son esféricamente simétricos.$qm$,
   $qm$$l = 0$ es un estado perfectamente válido -- de hecho es el fundamental del hidrógeno. Lo que vale cero es el momento angular, no la función de onda.$qm$,
   $qm$Está normalizado justamente por el factor $1/\sqrt{4\pi}$, que es el que hace que su integral sobre toda la esfera (de área $4\pi$) dé 1.$qm$,
   null, null, null, null),

  ($qm$mq_armonicos_esfericos$qm$, $qm$cuantica/armonicos_esfericos$qm$, 0.2, 30,
   $qm$En un potencial central la solución se separa como $\psi = R_{nl}(r)\,Y_l^m(\theta,\varphi)$. ¿Qué parte depende de la forma concreta de $V(r)$?$qm$,
   $qm$Ambas: la angular también cambia con el potencial.$qm$,
   $qm$Solo la angular.$qm$,
   $qm$Solo la radial $R_{nl}$; la parte angular es la misma para **cualquier** potencial central.$qm$,
   $qm$Ninguna: la separación de variables solo funciona con el potencial de Coulomb.$qm$,
   $qm$C$qm$,
   $qm$La angular es universal. Es lo que hace que el oscilador isótropo, el pozo esférico y el átomo de hidrógeno -- potenciales completamente distintos -- compartan exactamente los mismos $Y_l^m$.$qm$,
   $qm$Es al revés: la angular es la que **no** depende del potencial, y la radial la que sí.$qm$,
   $qm$Correcto. La parte angular queda fijada por la simetría rotacional, no por la dinámica: el operador angular que aparece al separar variables es siempre $L^2$, valga lo que valga $V(r)$.$qm$,
   $qm$Funciona para todo potencial que dependa solo de $r$. Coulomb es especial por otra razón -- su degeneración accidental en $l$ --, no por admitir separación.$qm$,
   null, null, null, null),

  ($qm$mq_armonicos_esfericos$qm$, $qm$cuantica/armonicos_esfericos$qm$, 0.7, 40,
   $qm$¿Cuál es la condición de ortonormalidad de los armónicos esféricos?$qm$,
   $qm$$\displaystyle\int_0^{2\pi}\!\!\int_0^{\pi} Y_{l'}^{m'*}\,Y_l^m \;d\theta\,d\varphi = \delta_{ll'}\delta_{mm'}$$qm$,
   $qm$$\displaystyle\int_0^{2\pi}\!\!\int_0^{\pi} Y_{l'}^{m'*}\,Y_l^m \;\sin\theta\,d\theta\,d\varphi = \delta_{ll'}\delta_{mm'}$$qm$,
   $qm$$\displaystyle\int_0^{\infty}\!\!\int_0^{2\pi}\!\!\int_0^{\pi} Y_{l'}^{m'*}\,Y_l^m \;r^{2}\sin\theta\,dr\,d\theta\,d\varphi = \delta_{ll'}\delta_{mm'}$$qm$,
   $qm$$\displaystyle\sum_{\theta,\varphi} Y_{l'}^{m'*}\,Y_l^m = \delta_{ll'}\delta_{mm'}$$qm$,
   $qm$B$qm$,
   $qm$Falta el $\sin\theta$, que es parte del elemento de ángulo sólido $d\Omega = \sin\theta\,d\theta\,d\varphi$. Sin él la integral no da delta y la ortogonalidad se pierde: es el error más frecuente al proyectar un estado sobre un $Y_l^m$.$qm$,
   $qm$Correcto. El $\sin\theta$ viene del jacobiano de las coordenadas esféricas y refleja que cerca de los polos los "rectángulos" $d\theta\,d\varphi$ cubren menos superficie.$qm$,
   $qm$Los $Y_l^m$ no dependen de $r$: la integral radial pertenece a la normalización de $R_{nl}(r)$, y hacerla acá o bien diverge o bien es un factor ajeno a la condición angular.$qm$,
   $qm$Los ángulos son variables continuas: corresponde una integral, no una suma. La suma aparece sobre los índices discretos $l$ y $m$, en la relación de cierre.$qm$,
   $qm$mq/armonicos/integracion-sin-jacobiano$qm$, null, null, null),

  ($qm$mq_armonicos_esfericos$qm$, $qm$cuantica/armonicos_esfericos$qm$, 1.1, 50,
   $qm$La parte angular de un estado es $\frac{1}{\sqrt5}\left(2\,Y_1^0 + Y_1^1\right)$. ¿Cuál es la probabilidad de medir $L_z = \hbar$?$qm$,
   $qm$$1/5$$qm$,
   $qm$$4/5$$qm$,
   $qm$$1/\sqrt{5}$$qm$,
   $qm$$1/2$, porque hay dos términos igualmente posibles.$qm$,
   $qm$A$qm$,
   $qm$Correcto. $L_z = \hbar$ corresponde a $m = 1$, cuyo coeficiente es $1/\sqrt5$: la probabilidad es $|1/\sqrt5|^2 = 1/5$. (El estado ya está normalizado: $4/5 + 1/5 = 1$.)$qm$,
   $qm$Ese es el peso de $Y_1^0$, o sea de $m = 0$, que da $L_z = 0$. Conviene identificar primero qué $m$ corresponde al valor pedido y recién después buscar su coeficiente.$qm$,
   $qm$Ese es el **coeficiente**, no la probabilidad. La regla de Born exige elevar al cuadrado el módulo: $|c|^2$, no $|c|$.$qm$,
   $qm$Los dos términos no son igualmente probables: sus coeficientes son distintos ($2/\sqrt5$ y $1/\sqrt5$), y la probabilidad va con el cuadrado de cada uno.$qm$,
   null, null, $qm$mq/armonicos/probabilidad-por-coeficiente$qm$,
   $qm$mq/medida/probabilidad-sin-modulo-cuadrado$qm$),

  ($qm$mq_armonicos_esfericos$qm$, $qm$cuantica/armonicos_esfericos$qm$, 1.5, 60,
   $qm$Bajo la inversión espacial $\vec r \to -\vec r$, ¿cómo se transforma $Y_l^m$?$qm$,
   $qm$$Y_l^m \to (-1)^{m}\,Y_l^m$$qm$,
   $qm$$Y_l^m \to (-1)^{l}\,Y_l^m$$qm$,
   $qm$$Y_l^m \to Y_l^{-m}$$qm$,
   $qm$No cambia: la inversión no afecta a la parte angular.$qm$,
   $qm$B$qm$,
   $qm$La paridad la fija $l$, no $m$. Se ve en el caso más simple: los tres estados con $l=1$ ($m=-1,0,1$) tienen todos paridad impar, aunque sus $m$ sean distintos.$qm$,
   $qm$Correcto. La inversión es $\theta\to\pi-\theta$, $\varphi\to\varphi+\pi$, y bajo eso $Y_l^m$ toma el factor $(-1)^l$. De ahí sale la regla de selección dipolar $\Delta l = \pm1$: la integral $\langle l'|z|l\rangle$ se anula por paridad salvo que $l$ y $l'$ tengan paridades opuestas.$qm$,
   $qm$La inversión no conjuga ni refleja el índice $m$: multiplica por un signo global que depende solo de $l$.$qm$,
   $qm$La inversión es precisamente una operación **angular**: manda cada dirección a la opuesta, dejando $r$ intacto. Es la parte angular la única que se ve afectada.$qm$,
   $qm$mq/armonicos/paridad-equivocada$qm$, null, null,
   $qm$mq/armonicos/paridad-equivocada$qm$),

  ($qm$mq_armonicos_esfericos$qm$, $qm$cuantica/armonicos_esfericos$qm$, 1.9, 70,
   $qm$La ecuación radial de un potencial central contiene el término $\dfrac{l(l+1)\hbar^{2}}{2mr^{2}}$. ¿Qué papel cumple?$qm$,
   $qm$Es parte del potencial de Coulomb, escrito en otra forma.$qm$,
   $qm$No influye: se cancela con el término de energía cinética radial.$qm$,
   $qm$Es atractivo y aumenta la ligadura de los estados con $l$ grande.$qm$,
   $qm$Es una barrera **centrífuga** repulsiva, que crece con $l$ y mantiene alejada del origen a la partícula con momento angular.$qm$,
   $qm$D$qm$,
   $qm$Es independiente del potencial: aparece igual con Coulomb, con un oscilador isótropo o con un pozo esférico. Sale de la parte angular del laplaciano, no de $V$.$qm$,
   $qm$No se cancela: se **suma** al potencial y define un potencial efectivo $V_{ef}(r) = V(r) + l(l+1)\hbar^2/2mr^2$, que es el que gobierna el movimiento radial.$qm$,
   $qm$Es repulsivo, no atractivo: su signo es positivo. Por eso los estados con $l$ grande están **menos** ligados en un potencial genérico, y por eso solo los estados $s$ ($l=0$) tienen densidad de probabilidad no nula en el origen.$qm$,
   $qm$Correcto. Es el análogo cuántico exacto de la barrera centrífuga clásica $L^2/2mr^2$: la conservación del momento angular impide que una partícula con $l\neq0$ caiga al centro.$qm$,
   $qm$mq/central/potencial-centrifugo-omitido$qm$,
   $qm$mq/central/potencial-centrifugo-omitido$qm$,
   $qm$mq/central/potencial-centrifugo-omitido$qm$, null),

  ($qm$mq_armonicos_esfericos$qm$, $qm$cuantica/armonicos_esfericos$qm$, 2.3, 80,
   $qm$¿Cuál es la razón de fondo por la que los $Y_l^m$ aparecen en **todo** problema de potencial central?$qm$,
   $qm$Porque $[H,\vec L] = 0$ cuando $V$ depende solo de $r$: es una consecuencia de la simetría rotacional del Hamiltoniano.$qm$,
   $qm$Porque es una casualidad matemática heredada de la ecuación de Laplace.$qm$,
   $qm$Porque en el fondo todos los potenciales centrales son de tipo Coulomb.$qm$,
   $qm$Porque $L^{2}$ es una constante de movimiento siempre, haya o no simetría.$qm$,
   $qm$A$qm$,
   $qm$Correcto. La simetría del Hamiltoniano determina la estructura de sus autoestados: si $H$ es invariante bajo rotaciones, sus autoestados se organizan en multipletes de momento angular. Es el mismo argumento con el que Wigner reescribió la teoría atómica en términos de grupos.$qm$,
   $qm$Los armónicos esféricos aparecieron con Laplace y Legendre en 1780, pero no es casualidad que reaparezcan: en ambos casos el operador de fondo es el laplaciano, y su parte angular es siempre $L^2$.$qm$,
   $qm$Un oscilador isótropo $V \propto r^2$ y un pozo esférico no tienen nada de coulombianos, y sus soluciones angulares son igualmente los $Y_l^m$. Lo que comparten es la simetría, no la forma del potencial.$qm$,
   $qm$$L^2$ es constante de movimiento **solo si** $[H,L^2]=0$, que es exactamente lo que garantiza la simetría central. Con un potencial que dependa de los ángulos deja de serlo.$qm$,
   null, null, null, null),

  -- ===========================================================================
  -- mq_espin · Espín 1/2, Pauli y Stern-Gerlach
  -- ===========================================================================

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, -1.0, 10,
   $qm$Un haz de átomos de plata atraviesa un imán de Stern-Gerlach orientado según $z$. ¿Qué se observa en la pantalla?$qm$,
   $qm$Una banda continua, como predecía la física clásica.$qm$,
   $qm$Tres manchas discretas.$qm$,
   $qm$Dos manchas discretas.$qm$,
   $qm$Una sola mancha, sin desviación.$qm$,
   $qm$C$qm$,
   $qm$La predicción clásica era esa -- momentos magnéticos orientados al azar dan una distribución continua -- y fue justamente lo que el experimento refutó en 1922.$qm$,
   $qm$Tres manchas corresponderían a $l=1$ ($m=-1,0,1$), o en general a un momento angular entero. El electrón de valencia de la plata tiene $l=0$, y lo que se parte es su **espín**.$qm$,
   $qm$Correcto. Dos manchas significan $2s+1 = 2$, o sea $s = 1/2$: el primer indicio experimental del espín, aunque en 1922 nadie lo leyó así (el concepto llegó en 1925, con Uhlenbeck y Goudsmit).$qm$,
   $qm$Sin momento magnético no habría desviación, pero el átomo de plata sí lo tiene, aportado por su electrón desapareado.$qm$,
   null, $qm$mq/momento-angular/degeneracion-2l$qm$, null, null),

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, -0.5, 20,
   $qm$¿Cuál de estas afirmaciones sobre el espín es correcta?$qm$,
   $qm$Es la rotación de la partícula sobre su propio eje, y su valor depende del radio de la partícula.$qm$,
   $qm$Es un momento angular **intrínseco**, sin análogo clásico: no supone ninguna estructura interna girando.$qm$,
   $qm$Es el momento angular del electrón en su órbita alrededor del núcleo.$qm$,
   $qm$Solo lo tienen las partículas con carga eléctrica.$qm$,
   $qm$B$qm$,
   $qm$Es la imagen que sugiere el nombre y no resiste el cálculo: para reproducir el momento angular observado, un electrón del tamaño clásico tendría que girar en su superficie a mucho más que la velocidad de la luz. Uhlenbeck y Goudsmit lo propusieron con esa imagen, y Lorentz les mostró enseguida el problema.$qm$,
   $qm$Correcto. Es una propiedad del tipo de partícula, como la masa o la carga: el electrón tiene $s=1/2$ siempre, en cualquier estado. Satisface la misma álgebra que $\vec L$, pero no proviene de $\vec r \times \vec p$.$qm$,
   $qm$Ese es el momento angular **orbital**, $\vec L$, que es una cosa distinta y puede valer cero (por ejemplo en un estado $s$) mientras el espín sigue valiendo $1/2$.$qm$,
   $qm$El neutrón no tiene carga neta y tiene espín $1/2$; también lo tienen los neutrinos. El espín no requiere carga -- lo que sí requiere carga (o momento magnético) es que se lo pueda detectar con un campo magnético.$qm$,
   $qm$mq/espin/rotacion-clasica$qm$, null,
   $qm$mq/espin/rotacion-clasica$qm$, null),

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, 0.0, 30,
   $qm$¿Cuáles son los autovalores de $S_z$ para una partícula de espín $1/2$?$qm$,
   $qm$$\pm\hbar/2$$qm$,
   $qm$$\pm\hbar$$qm$,
   $qm$$0, \pm\hbar$$qm$,
   $qm$$\pm 1/2$, adimensional.$qm$,
   $qm$A$qm$,
   $qm$Correcto. $S_z|s,m_s\rangle = \hbar m_s|s,m_s\rangle$ con $m_s = \pm1/2$. Los dos valores son los dos haces de Stern-Gerlach.$qm$,
   $qm$Eso correspondería a $m_s = \pm1$, o sea a espín entero. Para $s=1/2$ la proyección es $m_s = \pm 1/2$ y el autovalor lleva ese factor.$qm$,
   $qm$Ese es el espectro de $S_z$ para espín 1 ($m_s = -1,0,1$), como el del fotón o el de un bosón vectorial. Para $s = 1/2$ no existe estado con proyección nula.$qm$,
   $qm$Falta el $\hbar$: $m_s$ es adimensional, pero el **autovalor de $S_z$** es un momento angular y sus unidades son las de $\hbar$.$qm$,
   null, null, null, null),

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, 0.4, 40,
   $qm$¿Cuánto vale $\sigma_x^{2}$, siendo $\sigma_x$ la matriz de Pauli?$qm$,
   $qm$$\sigma_x$$qm$,
   $qm$$0$$qm$,
   $qm$$I$ (la identidad de $2\times2$)$qm$,
   $qm$$i\sigma_z$$qm$,
   $qm$C$qm$,
   $qm$Eso la haría un proyector ($P^2=P$), pero sus autovalores son $\pm1$, no $0$ y $1$. Un operador con autovalores $\pm1$ elevado al cuadrado da la identidad.$qm$,
   $qm$$\sigma_x$ es invertible (su propia inversa, de hecho), así que su cuadrado no puede anularse.$qm$,
   $qm$Correcto. Las tres matrices de Pauli cumplen $\sigma_i^2 = I$, lo que refleja que sus autovalores son $\pm1$. De ahí sale $S^2 = \frac{3}{4}\hbar^2 I$, coherente con $\hbar^2 s(s+1)$ para $s=1/2$.$qm$,
   $qm$$i\sigma_z$ es el resultado de $\sigma_x\sigma_y$, no de $\sigma_x^2$. El producto de dos Pauli **distintas** da la tercera con un factor $i$; el de una consigo misma da la identidad.$qm$,
   null, null, null, $qm$mq/espin/pauli-conmutan$qm$),

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, 0.8, 50,
   $qm$¿Cuánto vale $[\sigma_x,\sigma_y]$?$qm$,
   $qm$$0$$qm$,
   $qm$$2i\sigma_z$$qm$,
   $qm$$i\hbar\sigma_z$$qm$,
   $qm$$\sigma_z$$qm$,
   $qm$B$qm$,
   $qm$Las matrices de Pauli no conmutan: satisfacen la misma álgebra de momento angular que $\vec L$, que es toda la razón por la que el espín se comporta como un momento angular.$qm$,
   $qm$Correcto. $[\sigma_i,\sigma_j] = 2i\epsilon_{ijk}\sigma_k$. Con $\vec S = \frac{\hbar}{2}\vec\sigma$ eso se traduce en $[S_i,S_j] = i\hbar\epsilon_{ijk}S_k$, el álgebra estándar.$qm$,
   $qm$Las $\sigma$ son adimensionales, así que su conmutador no puede llevar $\hbar$. El $\hbar$ aparece recién al pasar a $\vec S = \frac{\hbar}{2}\vec\sigma$, y ahí el factor 2 se cancela con el $1/2$.$qm$,
   $qm$Falta el factor $2i$. Sin la $i$ el conmutador de dos hermíticas no sería antihermítico, que es lo que obliga la estructura del álgebra.$qm$,
   $qm$mq/espin/pauli-conmutan$qm$, null,
   $qm$mq/conmutadores/canonico-sin-i$qm$,
   $qm$mq/conmutadores/canonico-sin-i$qm$),

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, 1.2, 60,
   $qm$Un haz pasa por un Stern-Gerlach en $z$ y se selecciona la salida $+z$. Ese haz pasa por otro en $x$ y se selecciona $+x$. Finalmente pasa por un tercero en $z$. ¿Qué se mide?$qm$,
   $qm$$100\,\%$ en $+z$: ya había sido seleccionado en $+z$ antes.$qm$,
   $qm$$50\,\%$ en $+z$ y $50\,\%$ en $-z$.$qm$,
   $qm$$100\,\%$ en $+x$.$qm$,
   $qm$Nada: los filtros en ejes distintos se bloquean entre sí y no pasa ningún átomo.$qm$,
   $qm$B$qm$,
   $qm$Es el corazón del experimento: el segundo aparato **reprepara** el estado en $|+x\rangle$ y con eso destruye toda la información sobre $z$. Los filtros no se acumulan como en óptica clásica con polarizadores paralelos.$qm$,
   $qm$Correcto. $|+x\rangle = \frac{1}{\sqrt2}(|{\uparrow}_z\rangle + |{\downarrow}_z\rangle)$, así que al volver a medir $z$ las dos salidas son equiprobables. Es la consecuencia directa de $[S_x,S_z]\neq0$.$qm$,
   $qm$El tercer aparato mide $z$, no $x$: sus salidas posibles son $\pm z$. Un aparato solo puede devolver autovalores del observable que mide.$qm$,
   $qm$Sí pasan átomos: la mitad por cada salida en cada etapa. Lo que se pierde en cada paso es la información sobre el eje anterior, no el haz.$qm$,
   $qm$mq/espin/stern-gerlach-secuencial$qm$, null, null, null),

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, 1.6, 70,
   $qm$Se rota un espinor de espín $1/2$ un ángulo de $2\pi$ alrededor de un eje. ¿Qué le ocurre?$qm$,
   $qm$Vuelve exactamente a su estado inicial, como cualquier objeto rotado una vuelta completa.$qm$,
   $qm$Cambia de signo: hacen falta $4\pi$ para volver al estado original.$qm$,
   $qm$Se destruye: la rotación completa no está definida para espinores.$qm$,
   $qm$Cambia de signo, pero eso es siempre inobservable por tratarse de una fase global.$qm$,
   $qm$B$qm$,
   $qm$Es lo que dicta la intuición y es falso para espín semientero. El operador de rotación es $e^{-i\theta\sigma_n/2}$, y ese factor $1/2$ hace que a $\theta = 2\pi$ dé $-I$.$qm$,
   $qm$Correcto. Es la propiedad que distingue a los espinores de los vectores: el grupo relevante es SU(2), que cubre dos veces al de rotaciones SO(3).$qm$,
   $qm$Está perfectamente definida: da el mismo estado con signo opuesto. Nada se destruye.$qm$,
   $qm$Es una fase global **solo si** se rota todo el sistema. Si se rota una rama de un interferómetro y no la otra, la fase pasa a ser relativa y el signo es medible: se hizo con neutrones en 1975 (Rauch y colaboradores; Werner y colaboradores), y el patrón de interferencia se invierte.$qm$,
   $qm$mq/espin/rotacion-2pi-identidad$qm$, null, null,
   $qm$mq/estados/fase-global-observable$qm$),

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, 1.9, 80,
   $qm$En la base $\{|{\uparrow}\rangle,|{\downarrow}\rangle\}$ de $S_z$, ¿cuál es el autoestado de $S_x$ con autovalor $+\hbar/2$?$qm$,
   $qm$$|{\uparrow}\rangle$$qm$,
   $qm$$\frac{1}{\sqrt2}\left(|{\uparrow}\rangle - |{\downarrow}\rangle\right)$$qm$,
   $qm$$\frac{1}{2}\left(|{\uparrow}\rangle + |{\downarrow}\rangle\right)$$qm$,
   $qm$$\frac{1}{\sqrt2}\left(|{\uparrow}\rangle + |{\downarrow}\rangle\right)$$qm$,
   $qm$D$qm$,
   $qm$$|{\uparrow}\rangle$ es autoestado de $S_z$, no de $S_x$. Como $[S_x,S_z]\neq0$, no pueden compartir autovectores.$qm$,
   $qm$Ese es el autoestado con autovalor $-\hbar/2$. El signo relativo entre las dos componentes es lo único que los distingue, y define en qué sentido apunta el espín sobre el eje $x$.$qm$,
   $qm$La combinación es la correcta pero la normalización no: $|1/2|^2 + |1/2|^2 = 1/2 \neq 1$. El factor tiene que ser $1/\sqrt2$.$qm$,
   $qm$Correcto. Aplicando $\sigma_x = \begin{pmatrix}0&1\\1&0\end{pmatrix}$ al vector $(1,1)/\sqrt2$ se recupera el mismo vector, o sea autovalor $+1$ para $\sigma_x$ y $+\hbar/2$ para $S_x$.$qm$,
   null, null, $qm$mq/estados/normalizacion-omitida$qm$, null),

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, 2.1, 90,
   $qm$¿Qué tienen en común $\vec S$ y $\vec L$?$qm$,
   $qm$Que ambos tienen autovalores enteros.$qm$,
   $qm$Que ambos derivan de $\vec r \times \vec p$.$qm$,
   $qm$Que satisfacen la misma álgebra de conmutación, y por eso comparten toda la estructura: autovalores $\hbar^{2}j(j+1)$, proyecciones $\hbar m$, operadores escalera y multiplicidad $2j+1$.$qm$,
   $qm$Nada: son magnitudes sin relación entre sí.$qm$,
   $qm$C$qm$,
   $qm$$\vec L$ tiene $l$ entero, pero $\vec S$ puede tener $s$ semientero: el electrón tiene $s = 1/2$. Es la diferencia entre los dos, no lo que comparten.$qm$,
   $qm$Solo $\vec L$ tiene esa forma. El espín no proviene de ningún producto vectorial de posición por momento: es intrínseco, y en la teoría relativista aparece directamente de la ecuación de Dirac.$qm$,
   $qm$Correcto. Todo lo que se deduce del álgebra vale para ambos, y por eso se los suma como $\vec J = \vec L+\vec S$ sin ningún trabajo extra. Lo que **no** se deduce del álgebra -- que $l$ sea entero -- es lo único que los separa.$qm$,
   $qm$Se suman entre sí para dar el momento angular total, y su acoplamiento produce la estructura fina de los espectros. La relación es directa.$qm$,
   $qm$mq/momento-angular/semienteros-no-existen$qm$,
   $qm$mq/espin/rotacion-clasica$qm$, null, null),

  ($qm$mq_espin$qm$, $qm$cuantica/espin$qm$, 2.4, 100,
   $qm$El experimento de Stern-Gerlach (1922) se leyó en su momento como confirmación de la "cuantización espacial" de Bohr-Sommerfeld. ¿Por qué esa lectura era incorrecta?$qm$,
   $qm$Porque el experimento estaba mal hecho y el resultado no era reproducible.$qm$,
   $qm$Porque para un momento angular orbital $l=1$ se esperaban **tres** haces ($m=-1,0,1$); los dos observados corresponden al espín $1/2$, concepto que no existía hasta 1925.$qm$,
   $qm$Porque la plata no tiene momento magnético y la desviación se debía a otra causa.$qm$,
   $qm$Porque para cualquier $l$ siempre se esperan dos haces.$qm$,
   $qm$B$qm$,
   $qm$El experimento era correcto y se reprodujo muchas veces: lo que estaba mal era la interpretación disponible en 1922.$qm$,
   $qm$Correcto. Todo momento angular **orbital** da un número impar de haces, $2l+1$. Un número par exige $j$ semientero, cosa que la teoría de Bohr-Sommerfeld no contemplaba. El resultado correcto se obtuvo por la razón equivocada, y encima la plata tiene $l=0$: no había cuantización espacial orbital que confirmar.$qm$,
   $qm$Sí lo tiene, aportado por su electrón de valencia desapareado -- y es exactamente por eso que el haz se desvía.$qm$,
   $qm$Los haces son $2l+1$: uno para $l=0$, tres para $l=1$, cinco para $l=2$. Dos haces es imposible con momento angular orbital, y ahí está el punto.$qm$,
   null, null, null,
   $qm$mq/momento-angular/degeneracion-2l$qm$),

  -- ===========================================================================
  -- mq_suma_momentos · Suma de momentos angulares y Clebsch-Gordan
  -- ===========================================================================

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, -0.9, 10,
   $qm$Sean $\vec J_1$ y $\vec J_2$ momentos angulares que actúan sobre espacios de Hilbert **distintos** (dos partículas, o el orbital y el espín de una misma). ¿Cuánto vale $[J_{1i}, J_{2j}]$?$qm$,
   $qm$$0$, para todo par $i,j$.$qm$,
   $qm$$i\hbar\,\epsilon_{ijk}J_k$$qm$,
   $qm$$i\hbar\,\delta_{ij}$$qm$,
   $qm$Depende del estado sobre el que se evalúe.$qm$,
   $qm$A$qm$,
   $qm$Correcto. Actúan sobre factores distintos del producto tensorial: $J_{1i}\otimes I$ e $I\otimes J_{2j}$ conmutan por construcción. Es la hipótesis clave de todo el problema de suma de momentos angulares, y la que hace desaparecer los términos cruzados.$qm$,
   $qm$Esa es la relación entre componentes del **mismo** momento angular. Entre momentos de subsistemas distintos no hay ninguna relación de este tipo: simplemente conmutan.$qm$,
   $qm$Esa es la forma del conmutador canónico posición-momento, que no tiene nada que ver acá. Y además el resultado sería no nulo, contradiciendo la independencia de los subsistemas.$qm$,
   $qm$Un conmutador es una identidad entre **operadores**: vale sobre cualquier estado o no vale. No hay dependencia del estado.$qm$,
   null, $qm$mq/suma/cruzados-no-nulos$qm$,
   $qm$mq/suma/cruzados-no-nulos$qm$,
   $qm$mq/suma/cruzados-no-nulos$qm$),

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, -0.4, 20,
   $qm$Con $\vec J = \vec J_1 + \vec J_2$, se calcula $[J_i, J_j]$ expandiendo por bilinealidad. ¿Qué se obtiene?$qm$,
   $qm$$[J_i,J_j] = 2i\hbar\,\epsilon_{ijk}J_k$, por haber dos sumandos.$qm$,
   $qm$$[J_i,J_j] = 0$, porque los términos cruzados se anulan.$qm$,
   $qm$$[J_i,J_j] = i\hbar\,\epsilon_{ijk}(J_{1k}+J_{2k})$, que **no** es lo mismo que $i\hbar\epsilon_{ijk}J_k$.$qm$,
   $qm$$[J_i,J_j] = i\hbar\,\epsilon_{ijk}J_k$: la suma de dos momentos angulares es un momento angular.$qm$,
   $qm$D$qm$,
   $qm$No hay factor 2: los dos términos que sobreviven son $i\hbar\epsilon_{ijk}J_{1k}$ e $i\hbar\epsilon_{ijk}J_{2k}$, y al factorizar $i\hbar\epsilon_{ijk}$ queda $(J_{1k}+J_{2k}) = J_k$, no $2J_k$.$qm$,
   $qm$Se anulan los **cruzados**, pero quedan los propios: $[J_{1i},J_{1j}]$ y $[J_{2i},J_{2j}]$, que no son cero. Si todo se anulara, $\vec J$ no sería un momento angular.$qm$,
   $qm$Sí es lo mismo: $J_k = J_{1k}+J_{2k}$ es la definición de la componente $k$ del momento angular total. Reconocer esa suma es el último paso del ejercicio.$qm$,
   $qm$Correcto. Los cuatro términos de la expansión se reducen a dos (los cruzados mueren porque actúan en espacios distintos), y al factorizar reaparece la definición de $J_k$. La consecuencia es fuerte: **todo** lo demostrado a partir del álgebra vale automáticamente para $\vec J$.$qm$,
   null, $qm$mq/suma/cruzados-no-nulos$qm$, null, null),

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, 0.1, 30,
   $qm$Se acoplan $j_1 = 1$ y $j_2 = 1/2$. ¿Qué valores puede tomar el momento angular total $j$?$qm$,
   $qm$Solamente $3/2$.$qm$,
   $qm$$3/2$ y $1/2$.$qm$,
   $qm$$1/2$, $1$ y $3/2$.$qm$,
   $qm$Cualquier valor entre $0$ y $3/2$.$qm$,
   $qm$B$qm$,
   $qm$$j_1+j_2$ es el valor **máximo**, no el único. Los momentos angulares no se suman como números: se acoplan, y el resultado abarca un rango.$qm$,
   $qm$Correcto. La regla es $|j_1-j_2| \leq j \leq j_1+j_2$ de a saltos enteros: acá $1/2 \leq j \leq 3/2$, o sea $j = 1/2$ y $j = 3/2$.$qm$,
   $qm$$j=1$ no aparece: los valores avanzan de **uno en uno** desde $|j_1-j_2| = 1/2$, así que son $1/2$ y $3/2$. Un $j$ entero acá haría que la paridad del semientero no cerrara.$qm$,
   $qm$Ni es continuo ni empieza en cero. El mínimo es $|j_1-j_2| = 1/2$ y los valores son discretos.$qm$,
   $qm$mq/suma/j-solo-suma-directa$qm$, null, null,
   $qm$mq/suma/j-solo-suma-directa$qm$),

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, 0.5, 40,
   $qm$Con $j_1 = 1$ y $j_2 = 1/2$: ¿cuántos estados tiene el espacio producto, y cómo se reparten entre los valores de $j$?$qm$,
   $qm$$3 + 2 = 5$ estados.$qm$,
   $qm$$3 \times 2 = 6$ estados: 4 con $j=3/2$ y 2 con $j=1/2$.$qm$,
   $qm$6 estados, todos con $j = 3/2$.$qm$,
   $qm$$2 \times 2 = 4$ estados.$qm$,
   $qm$B$qm$,
   $qm$Las dimensiones de subsistemas se **multiplican**, no se suman: el espacio conjunto es un producto tensorial. Sumarlas correspondería a una suma directa, que describe otra cosa.$qm$,
   $qm$Correcto. $(2j_1+1)(2j_2+1) = 3\times2 = 6$, y el reparto es $(2\cdot\frac32+1) + (2\cdot\frac12+1) = 4 + 2 = 6$. Que las cuentas cierren es la verificación estándar de un acoplamiento.$qm$,
   $qm$El multiplete $j=3/2$ tiene $2j+1 = 4$ estados, no 6. Los 2 restantes forman el multiplete $j=1/2$, y sin ellos el conteo no cerraría.$qm$,
   $qm$$j_1 = 1$ da $2j_1+1 = 3$ estados, no 2. La multiplicidad es $2j+1$, y confundirla con $2j$ (o con $j+1$) desarma todo el conteo.$qm$,
   $qm$mq/suma/dimension-como-suma$qm$, null,
   $qm$mq/suma/j-solo-suma-directa$qm$,
   $qm$mq/momento-angular/degeneracion-2l$qm$),

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, 0.9, 50,
   $qm$En la base **acoplada** $|j_1,j_2;j,m\rangle$, ¿qué números cuánticos tienen valor definido?$qm$,
   $qm$$j_1, j_2, m_1, m_2$ y también $j$.$qm$,
   $qm$$j_1, j_2, j$ y $m$; **no** $m_1$ ni $m_2$ por separado.$qm$,
   $qm$Solo $j$ y $m$.$qm$,
   $qm$$m_1$, $m_2$ y $j$.$qm$,
   $qm$B$qm$,
   $qm$No pueden estar todos: $J^2$ no conmuta con $J_{1z}$ ni con $J_{2z}$. Elegir la base acoplada es precisamente renunciar a $m_1$ y $m_2$ definidos, a cambio de $j$ definido.$qm$,
   $qm$Correcto. Los dos conjuntos completos de observables compatibles son $\{J_1^2,J_2^2,J_{1z},J_{2z}\}$ (base desacoplada) y $\{J_1^2,J_2^2,J^2,J_z\}$ (base acoplada). $J_1^2$ y $J_2^2$ están en ambos; lo que se intercambia es el resto.$qm$,
   $qm$Faltan $j_1$ y $j_2$: sin ellos no se sabe qué se está acoplando. Por eso la notación completa lleva los cuatro índices.$qm$,
   $qm$$m_1$ y $m_2$ son los números cuánticos de la base **desacoplada**, y son incompatibles con $j$ definido. Mezclar los dos conjuntos es el error clásico de este tema.$qm$,
   $qm$mq/suma/base-acoplada-y-desacoplada-mezcladas$qm$, null, null,
   $qm$mq/suma/base-acoplada-y-desacoplada-mezcladas$qm$),

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, 1.3, 60,
   $qm$¿Qué tiene de particular el estado tope $|j = j_1+j_2,\; m = j_1+j_2\rangle$?$qm$,
   $qm$Es una combinación lineal de todos los estados desacoplados.$qm$,
   $qm$Es el único estado del espacio con ese $m$ máximo, así que coincide exactamente con $|m_1 = j_1\rangle|m_2 = j_2\rangle$: su coeficiente de Clebsch-Gordan vale 1.$qm$,
   $qm$Es nulo, porque $m$ no puede alcanzar el valor de $j$.$qm$,
   $qm$Es el estado de menor energía del sistema acoplado.$qm$,
   $qm$B$qm$,
   $qm$Al revés: es el único que **no** necesita combinarse. Como $m = m_1+m_2$ y el máximo de cada uno es $j_1$ y $j_2$, hay una sola manera de alcanzar el tope.$qm$,
   $qm$Correcto. Ese es el punto de partida del método estándar: se identifica el estado tope y se aplica $J_-$ repetidamente para generar todo el multiplete, y luego se construye el siguiente por ortogonalidad. Así se obtienen todos los coeficientes sin consultar ninguna tabla.$qm$,
   $qm$$m = j$ sí está permitido -- es justamente el extremo del rango $-j \leq m \leq j$. Lo que no se puede es superarlo.$qm$,
   $qm$El acoplamiento es cinemático: no dice nada de energías. Cuál estado tiene menor energía depende del Hamiltoniano (con espín-órbita, por ejemplo, depende del signo de la constante de acoplamiento).$qm$,
   $qm$mq/suma/base-acoplada-y-desacoplada-mezcladas$qm$, null,
   $qm$mq/momento-angular/lz-supera-el-modulo$qm$, null),

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, 1.6, 70,
   $qm$Se acoplan dos espines $1/2$. ¿Cómo se reparten los 4 estados del espacio producto?$qm$,
   $qm$En dos dobletes de $s = 1/2$.$qm$,
   $qm$Un triplete con $s=1$ (simétrico bajo intercambio) y un singlete con $s=0$ (antisimétrico).$qm$,
   $qm$En cuatro estados, todos con $s = 1$.$qm$,
   $qm$En un cuadruplete con $s = 3/2$.$qm$,
   $qm$B$qm$,
   $qm$Los valores posibles de $s$ son $|1/2-1/2| = 0$ y $1/2+1/2 = 1$: no aparece $s=1/2$. Un $s$ semientero es imposible al acoplar dos semienteros.$qm$,
   $qm$Correcto. $3 + 1 = 4$, con el triplete simétrico ($|{\uparrow\uparrow}\rangle$, $\frac{1}{\sqrt2}(|{\uparrow\downarrow}\rangle+|{\downarrow\uparrow}\rangle)$, $|{\downarrow\downarrow}\rangle$) y el singlete antisimétrico $\frac{1}{\sqrt2}(|{\uparrow\downarrow}\rangle-|{\downarrow\uparrow}\rangle)$. Esa simetría es la que, combinada con Pauli, explica el ortohelio y el parahelio.$qm$,
   $qm$El multiplete $s=1$ tiene $2s+1 = 3$ estados, no 4. El cuarto es el singlete, que tiene $s=0$ y es esencial: es el estado entrelazado de las desigualdades de Bell.$qm$,
   $qm$$s = 3/2$ exigiría acoplar tres espines $1/2$, no dos. Con dos, el máximo es $s=1$.$qm$,
   null, null, $qm$mq/suma/j-solo-suma-directa$qm$,
   $qm$mq/suma/j-solo-suma-directa$qm$),

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, 1.9, 80,
   $qm$El acoplamiento espín-órbita aporta al Hamiltoniano un término $\propto \vec L\cdot\vec S$. ¿Cuál es la forma práctica de evaluarlo?$qm$,
   $qm$Multiplicando los autovalores: $\hbar^{2}\,l\,m_l \cdot s\,m_s$.$qm$,
   $qm$No se puede evaluar: $\vec L\cdot\vec S$ no es hermítico.$qm$,
   $qm$Es idénticamente cero, porque $[\vec L,\vec S] = 0$.$qm$,
   $qm$Usando $\vec L\cdot\vec S = \tfrac{1}{2}\left(J^{2}-L^{2}-S^{2}\right)$, que es diagonal en la base acoplada.$qm$,
   $qm$D$qm$,
   $qm$$\vec L\cdot\vec S = L_xS_x+L_yS_y+L_zS_z$, y solo el último término es diagonal en la base desacoplada; los otros dos mezclan estados. Multiplicar autovalores supone, sin decirlo, que todos los operadores involucrados son diagonales a la vez.$qm$,
   $qm$Sí es hermítico: es una suma de productos de operadores hermíticos que actúan sobre espacios distintos y por lo tanto conmutan entre sí, lo que hace hermítico a cada producto.$qm$,
   $qm$Que conmuten significa que se pueden multiplicar en cualquier orden, no que el producto se anule. $\vec L\cdot\vec S$ es un operador perfectamente no nulo, y es el responsable de la estructura fina.$qm$,
   $qm$Correcto. De $J^2 = (\vec L+\vec S)^2 = L^2+S^2+2\vec L\cdot\vec S$ (usando que los cruzados conmutan) sale el despeje, y su autovalor es $\frac{\hbar^2}{2}[j(j+1)-l(l+1)-s(s+1)]$. Es el ejemplo más útil de por qué conviene la base acoplada.$qm$,
   $qm$mq/suma/base-acoplada-y-desacoplada-mezcladas$qm$,
   $qm$mq/formalismo/operador-hermitico-vs-unitario$qm$,
   $qm$mq/conmutadores/asume-conmutatividad$qm$, null),

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, 2.1, 90,
   $qm$Al agregar el término $\vec L\cdot\vec S$ al Hamiltoniano, ¿qué observables siguen siendo constantes de movimiento?$qm$,
   $qm$Todos los de antes: nada cambia.$qm$,
   $qm$$J^{2}$, $J_z$, $L^{2}$ y $S^{2}$; ya no $L_z$ ni $S_z$ por separado.$qm$,
   $qm$Solo $L^{2}$ y $S^{2}$.$qm$,
   $qm$$L_z$ y $S_z$ siguen conservándose, pero $J_z$ no.$qm$,
   $qm$B$qm$,
   $qm$Sí cambia, y es la razón por la que se introduce la base acoplada: $\vec L\cdot\vec S$ contiene $L_xS_x+L_yS_y$, que no conmuta con $L_z$ ni con $S_z$.$qm$,
   $qm$Correcto. El término respeta la simetría rotacional **conjunta** (rotar espín y órbita juntos), pero no las rotaciones separadas de cada uno. Por eso los estados buenos pasan a etiquetarse $|n,l,s,j,m_j\rangle$ y el nivel se desdobla según $j$: la estructura fina.$qm$,
   $qm$$J^2$ y $J_z$ también se conservan, y son justamente los que reemplazan a $L_z$ y $S_z$ como números cuánticos buenos.$qm$,
   $qm$Está invertido. $J_z = L_z+S_z$ sí conmuta con $\vec L\cdot\vec S$; los que dejan de conmutar son sus dos sumandos por separado.$qm$,
   null, null, null,
   $qm$mq/suma/base-acoplada-y-desacoplada-mezcladas$qm$),

  ($qm$mq_suma_momentos$qm$, $qm$cuantica/suma_momentos$qm$, 2.4, 100,
   $qm$¿Qué representa un coeficiente de Clebsch-Gordan $\langle j_1m_1\,j_2m_2 | j\,m\rangle$?$qm$,
   $qm$La probabilidad de que los dos momentos se acoplen al valor $j$.$qm$,
   $qm$La **amplitud** de un estado desacoplado dentro de uno acoplado: es el elemento de matriz del cambio de base entre ambas descripciones.$qm$,
   $qm$El autovalor del operador $\vec J_1\cdot\vec J_2$.$qm$,
   $qm$Un factor de normalización elegido por convención, sin contenido físico.$qm$,
   $qm$B$qm$,
   $qm$Es una amplitud, no una probabilidad: puede ser negativa, y de hecho lo es en la mitad de la tabla. La probabilidad correspondiente es su **cuadrado**.$qm$,
   $qm$Correcto. Son los elementos de la matriz unitaria que conecta las dos bases completas del mismo espacio, y por eso cumplen relaciones de ortogonalidad y completitud. Wigner mostró que son los mismos coeficientes que descomponen un producto de representaciones del grupo de rotaciones.$qm$,
   $qm$$\vec J_1\cdot\vec J_2$ tiene autovalor $\frac{\hbar^2}{2}[j(j+1)-j_1(j_1+1)-j_2(j_2+1)]$, que es un número por cada multiplete, no un coeficiente por cada par de estados.$qm$,
   $qm$Hay convenciones de fase (la de Condon-Shortley, que los hace reales y fija el signo del estado tope), pero los módulos son física: determinan probabilidades medibles en, por ejemplo, intensidades relativas de líneas espectrales.$qm$,
   $qm$mq/medida/probabilidad-sin-modulo-cuadrado$qm$, null, null, null)

)
insert into public.questions
  (topic, module_id, difficulty, order_index,
   question, option_a, option_b, option_c, option_d, correct_option,
   error_a, error_b, error_c, error_d,
   misconception_a_id, misconception_b_id, misconception_c_id, misconception_d_id)
select i.topic, m.id, i.difficulty, i.order_index,
       i.question, i.option_a, i.option_b, i.option_c, i.option_d, i.correct_option,
       i.error_a, i.error_b, i.error_c, i.error_d,
       xa.id, xb.id, xc.id, xd.id
from items i
left join public.modules m       on m.slug  = i.module_slug
left join public.misconceptions xa on xa.slug = i.mis_a
left join public.misconceptions xb on xb.slug = i.mis_b
left join public.misconceptions xc on xc.slug = i.mis_c
left join public.misconceptions xd on xd.slug = i.mis_d
where not exists (
  select 1 from public.questions q
   where q.topic = i.topic and q.question = i.question
);

-- Verificación: mq_momento_angular 15 · mq_armonicos_esfericos 8 ·
--               mq_espin 10 · mq_suma_momentos 10
