-- EXPERIMENTO · Banco de ítems, bloque IV: aplicaciones e interpretación (28 ítems).
-- Topics: mq_hidrogeno · mq_perturbaciones · mq_identicas · mq_interpretacion
--
-- ⚠ APLICAR DESPUÉS DE 033, 034, 035, 036 y 037.
-- Patrón de inserción: ver cabecera de 035.
--
-- Con este archivo el banco queda completo: 122 ítems en 15 topics. La cuenta
-- por topic y las consultas de control están en 040.

with items (topic, module_slug, difficulty, order_index,
            question, option_a, option_b, option_c, option_d, correct_option,
            error_a, error_b, error_c, error_d,
            mis_a, mis_b, mis_c, mis_d) as (
  values

  -- ===========================================================================
  -- mq_hidrogeno · Átomo de hidrógeno y potencial central
  -- ===========================================================================

  ($qm$mq_hidrogeno$qm$::text, $qm$cuantica/hidrogeno$qm$::text,
   (-0.9)::double precision, 10::int,
   $qm$En el átomo de hidrógeno con potencial de Coulomb puro (sin correcciones finas), ¿de qué números cuánticos depende la energía?$qm$::text,
   $qm$De $n$ y de $l$.$qm$::text,
   $qm$Solo de $n$.$qm$::text,
   $qm$De $n$, $l$ y $m$.$qm$::text,
   $qm$Solo de $l$, que es el que fija el momento angular.$qm$::text,
   $qm$B$qm$::text,
   $qm$Es lo que ocurre en cualquier **otro** potencial central, pero no en el de Coulomb: ahí $2s$ y $2p$ tienen exactamente la misma energía. Esa coincidencia es la degeneración accidental.$qm$::text,
   $qm$Correcto. $E_n = -13{,}6\ \mathrm{eV}/n^{2}$, y cada nivel $n$ agrupa $n^{2}$ estados orbitales distintos (o $2n^{2}$ contando el espín), todos con la misma energía.$qm$::text,
   $qm$La degeneración en $m$ está garantizada por la simetría rotacional en **todo** potencial central, así que ningún potencial de ese tipo puede dar energías que dependan de $m$. Solo un campo externo que rompa la isotropía lo consigue.$qm$::text,
   $qm$$l$ no fija la energía: los estados $3s$, $3p$ y $3d$ tienen distinto $l$ y la misma energía. Y sin $n$ no hay siquiera un rango definido para $l$.$qm$::text,
   $qm$mq/hidrogeno/energia-depende-de-l$qm$::text, null::text,
   $qm$mq/hidrogeno/energia-depende-de-l$qm$::text,
   $qm$mq/hidrogeno/energia-depende-de-l$qm$::text),

  ($qm$mq_hidrogeno$qm$, $qm$cuantica/hidrogeno$qm$, -0.4, 20,
   $qm$Para $n = 3$, ¿qué valores puede tomar $l$?$qm$,
   $qm$$l = 1, 2, 3$$qm$,
   $qm$$l = 0, 1, 2$$qm$,
   $qm$$l = 0, 1, 2, 3$$qm$,
   $qm$Cualquier entero no negativo.$qm$,
   $qm$B$qm$,
   $qm$$l=0$ sí está permitido (es el estado $3s$) y $l=3$ no lo está. La regla es $0 \leq l \leq n-1$.$qm$,
   $qm$Correcto. $l$ va de $0$ a $n-1$: para $n=3$ son los estados $3s$, $3p$ y $3d$. Contando $2l+1$ valores de $m$ en cada uno: $1+3+5 = 9 = n^{2}$.$qm$,
   $qm$$l = n$ nunca está permitido. La cota $l \leq n-1$ sale de exigir que la solución radial no diverja; con $l=n$ la serie no se corta y la función de onda no sería normalizable.$qm$,
   $qm$$l$ está acotado por $n$. Sin esa cota, cada nivel tendría infinitos estados y la degeneración $n^{2}$ (que se mide, por ejemplo, en la estructura del efecto Stark) no existiría.$qm$,
   $qm$mq/hidrogeno/rango-de-l-y-m$qm$, null,
   $qm$mq/hidrogeno/rango-de-l-y-m$qm$,
   $qm$mq/hidrogeno/rango-de-l-y-m$qm$),

  ($qm$mq_hidrogeno$qm$, $qm$cuantica/hidrogeno$qm$, 0.1, 30,
   $qm$¿Cuántos estados distintos hay con $n = 2$ en el hidrógeno, contando el espín del electrón?$qm$,
   $qm$4$qm$,
   $qm$8$qm$,
   $qm$3$qm$,
   $qm$2$qm$,
   $qm$B$qm$,
   $qm$Ese es el conteo **orbital** ($n^{2} = 4$: un $2s$ y tres $2p$), al que falta multiplicar por los dos estados de espín del electrón.$qm$,
   $qm$Correcto. $2n^{2} = 8$: cuatro estados orbitales ($l=0$ con $m=0$; $l=1$ con $m=-1,0,1$) por dos proyecciones de espín. Es el mismo 8 que explica el largo del segundo período de la tabla periódica.$qm$,
   $qm$Tres son solo los $2p$. Falta el $2s$ y falta el factor de espín.$qm$,
   $qm$Dos serían solo las proyecciones de espín de un único estado orbital. El nivel $n=2$ tiene cuatro estados orbitales.$qm$,
   $qm$mq/hidrogeno/degeneracion-mal-contada$qm$, null,
   $qm$mq/hidrogeno/degeneracion-mal-contada$qm$,
   $qm$mq/hidrogeno/degeneracion-mal-contada$qm$),

  ($qm$mq_hidrogeno$qm$, $qm$cuantica/hidrogeno$qm$, 0.6, 40,
   $qm$¿Por qué se llama "accidental" a la degeneración en $l$ del átomo de hidrógeno?$qm$,
   $qm$Porque es una casualidad numérica sin ninguna explicación.$qm$,
   $qm$Porque solo ocurre para valores pequeños de $n$.$qm$,
   $qm$Porque la simetría rotacional explica la degeneración en $m$, pero no la de $l$: esta viene de una simetría adicional propia del potencial $1/r$.$qm$,
   $qm$Porque la degeneración en $m$ es real y la de $l$ en realidad no existe.$qm$,
   $qm$C$qm$,
   $qm$Sí tiene explicación, aunque tardó nueve años en encontrarse: Vladimir Fock mostró en 1935 que el problema de Coulomb tiene la simetría del grupo de rotaciones en **cuatro** dimensiones, más grande que la rotacional ordinaria. El nombre "accidental" quedó de cuando no se sabía.$qm$,
   $qm$Vale para todo $n$: en cada nivel, los $n$ valores de $l$ tienen la misma energía. No es un efecto de nivel bajo.$qm$,
   $qm$Correcto. La conserva el vector de Runge-Lenz, la misma cantidad que en mecánica celeste explica por qué las órbitas de Kepler no precesan. Pauli la usó en 1926 para resolver el hidrógeno sin ecuación diferencial.$qm$,
   $qm$La degeneración en $l$ existe y se mide: $2s$ y $2p$ coinciden hasta las correcciones finas, que son unas $10^{4}$ veces menores. Lo que no existe es una explicación **rotacional** para ella.$qm$,
   null, null, null,
   $qm$mq/hidrogeno/energia-depende-de-l$qm$),

  ($qm$mq_hidrogeno$qm$, $qm$cuantica/hidrogeno$qm$, 1.0, 50,
   $qm$¿Qué estados del hidrógeno tienen densidad de probabilidad no nula en el origen ($r = 0$)?$qm$,
   $qm$Todos.$qm$,
   $qm$Ninguno.$qm$,
   $qm$Los de $l$ grande, que están más cerca del núcleo.$qm$,
   $qm$Solo los estados $s$ ($l = 0$).$qm$,
   $qm$D$qm$,
   $qm$Los estados con $l>0$ se anulan en el origen: cerca de cero, $R_{nl}(r) \sim r^{l}$. Es el efecto de la barrera centrífuga, que mantiene alejada del centro a toda partícula con momento angular.$qm$,
   $qm$Los estados $s$ sí lo tienen, y no es un detalle: de ahí sale el desplazamiento isotópico y el acoplamiento hiperfino de contacto de Fermi, que produce la línea de 21 cm de la astronomía del hidrógeno.$qm$,
   $qm$Es al revés: cuanto mayor es $l$, más fuerte es la barrera centrífuga $l(l+1)\hbar^{2}/2mr^{2}$ y más se aleja del origen la densidad de probabilidad.$qm$,
   $qm$Correcto. Con $l=0$ no hay barrera centrífuga en la ecuación radial, y $R_{n0}(0) \neq 0$.$qm$,
   $qm$mq/central/potencial-centrifugo-omitido$qm$, null,
   $qm$mq/central/potencial-centrifugo-omitido$qm$, null),

  ($qm$mq_hidrogeno$qm$, $qm$cuantica/hidrogeno$qm$, 1.4, 60,
   $qm$Con $E_n = -13{,}6\ \mathrm{eV}/n^{2}$, ¿cuánta energía hace falta para ionizar un átomo de hidrógeno que está en $n=2$?$qm$,
   $qm$$13{,}6$ eV$qm$,
   $qm$$10{,}2$ eV$qm$,
   $qm$$3{,}4$ eV$qm$,
   $qm$$6{,}8$ eV$qm$,
   $qm$C$qm$,
   $qm$Esa es la energía de ionización desde el **estado fundamental** ($n=1$). Desde $n=2$ el electrón ya está mucho menos ligado.$qm$,
   $qm$Esa es la energía de la transición $n=1 \to n=2$ ($13{,}6 - 3{,}4$), o sea la primera línea de la serie de Lyman. Ionizar es llevar el electrón hasta $E=0$, no hasta otro nivel ligado.$qm$,
   $qm$Correcto. $E_2 = -13{,}6/4 = -3{,}4$ eV, e ionizar es llevarlo a $E = 0$: hacen falta $3{,}4$ eV.$qm$,
   $qm$Sería $13{,}6/2$, pero la dependencia es con $n^{2}$, no con $n$: para $n=2$ el divisor es 4, no 2.$qm$,
   null, null, null, null),

  ($qm$mq_hidrogeno$qm$, $qm$cuantica/hidrogeno$qm$, 1.9, 70,
   $qm$¿Qué rompe la degeneración en $m$ de los niveles del hidrógeno?$qm$,
   $qm$Un campo magnético externo (efecto Zeeman).$qm$,
   $qm$El acoplamiento espín-órbita.$qm$,
   $qm$Nada: la degeneración en $m$ es indestructible.$qm$,
   $qm$La corrección por masa reducida del núcleo.$qm$,
   $qm$A$qm$,
   $qm$Correcto. Mientras el Hamiltoniano sea isótropo, todos los $m$ tienen la misma energía. Un campo externo define un eje privilegiado, rompe la simetría rotacional y desdobla el nivel en $2l+1$ componentes, separadas proporcionalmente a $m$.$qm$,
   $qm$El espín-órbita desdobla según $j$ (estructura fina), pero deja intacta la degeneración en $m_j$: sigue sin haber ninguna dirección privilegiada, porque $\vec L\cdot\vec S$ es un escalar bajo rotaciones conjuntas.$qm$,
   $qm$Es destructible, y romperla es una técnica experimental estándar: el efecto Zeeman fue durante décadas la principal herramienta para identificar los números cuánticos de un nivel atómico.$qm$,
   $qm$La masa reducida corre **todos** los niveles por igual (cambia la constante de Rydberg y por eso se distingue el deuterio del hidrógeno), pero no desdobla nada.$qm$,
   null, null, null, null),

  ($qm$mq_hidrogeno$qm$, $qm$cuantica/hidrogeno$qm$, 2.3, 80,
   $qm$En un átomo con muchos electrones, el potencial efectivo que siente un electrón externo ya no es $1/r$ puro (los electrones internos apantallan el núcleo). ¿Qué consecuencia tiene?$qm$,
   $qm$Ninguna: la energía sigue dependiendo solo de $n$.$qm$,
   $qm$Los armónicos esféricos dejan de servir como parte angular.$qm$,
   $qm$Desaparece la degeneración en $m$.$qm$,
   $qm$La energía pasa a depender también de $l$: se levanta la degeneración accidental, y de ahí sale que el $4s$ se llene antes que el $3d$.$qm$,
   $qm$D$qm$,
   $qm$La degeneración en $l$ es exclusiva del $1/r$ exacto. Con apantallamiento, los estados de $l$ chico penetran más cerca del núcleo, sienten menos apantallamiento y bajan su energía respecto de los de $l$ grande.$qm$,
   $qm$Siguen sirviendo: el potencial apantallado es aproximadamente **central**, y la parte angular de todo potencial central son los $Y_l^m$. Lo que cambia es únicamente la parte radial y el orden de las energías.$qm$,
   $qm$La degeneración en $m$ sobrevive mientras el potencial siga siendo central, que es la aproximación de campo autoconsistente usada habitualmente. Solo un campo externo la rompe.$qm$,
   $qm$Correcto. Es el origen de la regla de llenado ($n+l$, regla de Madelung) y, con ella, de la forma de la tabla periódica. La degeneración accidental del hidrógeno es la excepción, no la regla.$qm$,
   $qm$mq/hidrogeno/energia-depende-de-l$qm$, null, null, null),

  -- ===========================================================================
  -- mq_perturbaciones · Perturbaciones estacionarias y método variacional
  -- ===========================================================================

  ($qm$mq_perturbaciones$qm$, $qm$cuantica/perturbaciones$qm$, -0.8, 10,
   $qm$Con $H = H_0 + \lambda H'$ y $H_0$ resuelto, ¿cuál es la corrección de **primer orden a la energía** de un nivel no degenerado?$qm$,
   $qm$$E_n^{(1)} = \langle n^{(0)}|H'|n^{(0)}\rangle$$qm$,
   $qm$$E_n^{(1)} = \displaystyle\sum_{k\neq n}\frac{|\langle k^{(0)}|H'|n^{(0)}\rangle|^{2}}{E_n^{(0)}-E_k^{(0)}}$$qm$,
   $qm$$E_n^{(1)} = \displaystyle\sum_{k\neq n}\frac{\langle k^{(0)}|H'|n^{(0)}\rangle}{E_n^{(0)}-E_k^{(0)}}\,|k^{(0)}\rangle$$qm$,
   $qm$$E_n^{(1)} = \langle n^{(0)}|H_0|n^{(0)}\rangle$$qm$,
   $qm$A$qm$,
   $qm$Correcto. Es el resultado más útil de toda la teoría: el corrimiento de primer orden es simplemente el **valor esperado de la perturbación en el estado sin perturbar**. No hace falta resolver nada nuevo.$qm$,
   $qm$Esa es la corrección de **segundo** orden a la energía. Se reconoce por el módulo al cuadrado en el numerador y por la suma sobre estados intermedios.$qm$,
   $qm$Eso es la corrección de primer orden al **estado**, no a la energía: se nota porque el resultado es un ket y no un número.$qm$,
   $qm$Ese es el autovalor sin perturbar, $E_n^{(0)}$: la corrección tiene que involucrar a $H'$, que es lo único nuevo.$qm$,
   null, $qm$mq/perturbaciones/primer-orden-mal-identificado$qm$,
   $qm$mq/perturbaciones/primer-orden-mal-identificado$qm$, null),

  ($qm$mq_perturbaciones$qm$, $qm$cuantica/perturbaciones$qm$, -0.2, 20,
   $qm$¿En qué caso **no** se puede aplicar la fórmula de perturbaciones no degenerada?$qm$,
   $qm$Cuando $H'$ no es hermítico.$qm$,
   $qm$Nunca falla: es válida siempre.$qm$,
   $qm$Cuando el nivel es degenerado: los denominadores $E_n^{(0)}-E_k^{(0)}$ se anulan.$qm$,
   $qm$Cuando $H'$ es demasiado pequeño.$qm$,
   $qm$C$qm$,
   $qm$Una perturbación no hermítica no sería un Hamiltoniano válido, así que ese caso ni se plantea. El problema aparece con perturbaciones perfectamente hermíticas sobre niveles degenerados.$qm$,
   $qm$Falla, y de forma escandalosa: los denominadores se anulan y las correcciones divergen. Aplicarla igual es el error más frecuente del tema en un examen.$qm$,
   $qm$Correcto. Con degeneración hay estados distintos con $E_k^{(0)} = E_n^{(0)}$, y la expresión se indetermina. La señal es inequívoca: si aparece una división por cero, el nivel era degenerado.$qm$,
   $qm$Cuanto más chica sea $H'$, **mejor** funciona la aproximación. El problema es el opuesto: perturbaciones grandes comparadas con las separaciones entre niveles.$qm$,
   null, $qm$mq/perturbaciones/degenerada-sin-diagonalizar$qm$, null, null),

  ($qm$mq_perturbaciones$qm$, $qm$cuantica/perturbaciones$qm$, 0.3, 30,
   $qm$Ante un nivel **degenerado**, ¿cuál es el procedimiento correcto a primer orden?$qm$,
   $qm$Aplicar la fórmula no degenerada a cada estado del subespacio por separado.$qm$,
   $qm$Diagonalizar la matriz de $H'$ **dentro** del subespacio degenerado: sus autovalores son las correcciones de primer orden.$qm$,
   $qm$Promediar $\langle H'\rangle$ sobre los estados del subespacio.$qm$,
   $qm$Ignorar la degeneración: es un caso de medida nula que no ocurre en la práctica.$qm$,
   $qm$B$qm$,
   $qm$La base original del subespacio degenerado es arbitraria (cualquier combinación de sus estados es igual de válida), así que aplicar la fórmula estado por estado da resultados que dependen de una elección arbitraria. Hay que dejar que $H'$ elija la base.$qm$,
   $qm$Correcto. La perturbación selecciona la base "buena": los autovectores de $H'$ restringida al subespacio. Es lo que convierte un nivel degenerado en varios niveles separados, y es el mecanismo del efecto Stark lineal y de la estructura fina.$qm$,
   $qm$Un promedio da un solo número, y lo que se observa es un **desdoblamiento**: el nivel se parte en varios. La diagonalización devuelve tantos corrimientos como estados haya.$qm$,
   $qm$La degeneración es la regla, no la excepción, y aparece siempre que hay simetría: todo nivel del hidrógeno con $l>0$ es degenerado. Es precisamente el caso más frecuente en los problemas reales.$qm$,
   $qm$mq/perturbaciones/degenerada-sin-diagonalizar$qm$, null,
   $qm$mq/perturbaciones/degenerada-sin-diagonalizar$qm$,
   $qm$mq/perturbaciones/degenerada-sin-diagonalizar$qm$),

  ($qm$mq_perturbaciones$qm$, $qm$cuantica/perturbaciones$qm$, 0.8, 40,
   $qm$¿Qué signo tiene la corrección de **segundo orden** a la energía del estado **fundamental**?$qm$,
   $qm$Siempre positiva.$qm$,
   $qm$Depende del signo de $H'$.$qm$,
   $qm$Siempre negativa o nula: baja la energía del fundamental.$qm$,
   $qm$Depende del estado que se elija.$qm$,
   $qm$C$qm$,
   $qm$Es al revés. En $\sum_{k\neq0}|\langle k|H'|0\rangle|^{2}/(E_0-E_k)$ el numerador es no negativo y el denominador es **negativo** para todo $k$, porque $E_0$ es la energía más baja de todas.$qm$,
   $qm$No depende del signo de $H'$: el numerador lleva un módulo al cuadrado, así que cambiar $H' \to -H'$ no cambia nada a segundo orden.$qm$,
   $qm$Correcto. Es un resultado general y muy útil como control: si un cálculo da una corrección de segundo orden positiva para el fundamental, hay un error. Se conecta con el método variacional, que también acota $E_0$ por arriba.$qm$,
   $qm$Para estados excitados sí depende (hay niveles por encima y por debajo, con denominadores de ambos signos). Para el fundamental, no: todos los denominadores son negativos.$qm$,
   null, null, null, null),

  ($qm$mq_perturbaciones$qm$, $qm$cuantica/perturbaciones$qm$, 1.2, 50,
   $qm$El método variacional evalúa $E[\phi] = \dfrac{\langle\phi|H|\phi\rangle}{\langle\phi|\phi\rangle}$ para una función de prueba $|\phi\rangle$. ¿Qué garantiza?$qm$,
   $qm$Que $E[\phi]$ es una cota **inferior** de la energía del estado fundamental.$qm$,
   $qm$Que $E[\phi]$ es una cota **superior**: $E[\phi] \geq E_0$, con igualdad solo si $|\phi\rangle$ es el estado fundamental.$qm$,
   $qm$Que $E[\phi] = E_0$ exactamente, si $|\phi\rangle$ está normalizada.$qm$,
   $qm$Nada, salvo que $|\phi\rangle$ sea autofunción de $H$.$qm$,
   $qm$B$qm$,
   $qm$La desigualdad va al revés. Expandiendo $|\phi\rangle$ en autoestados de $H$, $E[\phi] = \sum_n |c_n|^{2}E_n \geq E_0\sum_n|c_n|^{2} = E_0$: es un promedio de energías, y ningún promedio puede quedar por debajo del mínimo.$qm$,
   $qm$Correcto. Por eso el método consiste en **minimizar** sobre una familia de funciones de prueba: cuanto menor sale, mejor es la estimación. Y por eso nunca se sabe qué tan cerca se está sin información adicional.$qm$,
   $qm$Normalizar solo elimina el denominador; no convierte una función cualquiera en autofunción. En general $E[\phi] > E_0$ estrictamente.$qm$,
   $qm$Garantiza bastante más: la cota superior vale para **cualquier** función de prueba, sea o no autofunción. Ahí está toda su utilidad, porque permite estimar $E_0$ sin resolver nada.$qm$,
   $qm$mq/variacional/da-cota-inferior$qm$, null, null, null),

  ($qm$mq_perturbaciones$qm$, $qm$cuantica/perturbaciones$qm$, 1.6, 60,
   $qm$El efecto Stark sobre el estado **fundamental** del hidrógeno es cuadrático en el campo, no lineal. ¿Por qué?$qm$,
   $qm$Porque un campo eléctrico no afecta a los estados $s$.$qm$,
   $qm$Porque el estado fundamental es degenerado.$qm$,
   $qm$Porque $\langle 1s|z|1s\rangle = 0$ por paridad: la corrección de primer orden se anula y el primer efecto no nulo es el de segundo orden.$qm$,
   $qm$Porque el operador $z$ no es hermítico.$qm$,
   $qm$C$qm$,
   $qm$Sí los afecta: los polariza, y el efecto es real -- solo que aparece a segundo orden, proporcional a $\mathcal{E}^{2}$.$qm$,
   $qm$El fundamental del hidrógeno ($1s$) **no** es degenerado: es el único nivel que no lo es (salvo por el espín, que no interviene acá). Justamente el nivel $n=2$, que sí lo es, tiene efecto Stark **lineal**.$qm$,
   $qm$Correcto. $|1s|^{2}$ es par y $z$ es impar, así que la integral se anula. El átomo no tiene momento dipolar permanente; el campo se lo **induce**, y la energía de un dipolo inducido va como $\mathcal{E}^{2}$.$qm$,
   $qm$$z$ es hermítico: es una componente del operador posición. Lo que anula el elemento de matriz es la paridad, no una falla de hermiticidad.$qm$,
   null, $qm$mq/perturbaciones/degenerada-sin-diagonalizar$qm$, null,
   $qm$mq/formalismo/operador-hermitico-vs-unitario$qm$),

  ($qm$mq_perturbaciones$qm$, $qm$cuantica/perturbaciones$qm$, 2.0, 70,
   $qm$¿Cuál es la condición que hace confiable el desarrollo perturbativo?$qm$,
   $qm$Que $H'$ tenga valores pequeños en términos absolutos.$qm$,
   $qm$Que $H_0$ tenga espectro puramente discreto.$qm$,
   $qm$Que la serie converja, cosa que siempre ocurre.$qm$,
   $qm$Que $|\langle k^{(0)}|H'|n^{(0)}\rangle| \ll |E_n^{(0)}-E_k^{(0)}|$: la perturbación debe ser pequeña **comparada con las separaciones entre niveles**.$qm$,
   $qm$D$qm$,
   $qm$"Pequeño" no significa nada sin una escala de comparación. Una perturbación de $0{,}1$ eV es despreciable frente a separaciones de eV y es enorme frente a una estructura hiperfina de $10^{-6}$ eV.$qm$,
   $qm$La teoría funciona igual con espectro continuo (dispersión), reemplazando la suma por una integral. Lo que importa son las separaciones de energía relevantes, no la naturaleza del espectro.$qm$,
   $qm$No siempre converge, y de hecho la serie perturbativa es a menudo **asintótica**: mejora hasta cierto orden y después empeora. En electrodinámica cuántica se sabe que la serie en $\alpha$ diverge, y aun así los primeros términos dan la predicción más precisa de la física.$qm$,
   $qm$Correcto. Es el criterio operativo, y explica por qué la degeneración rompe el método: ahí el denominador es cero y ningún numerador, por chico que sea, cumple la condición.$qm$,
   null, null, null, null),

  ($qm$mq_perturbaciones$qm$, $qm$cuantica/perturbaciones$qm$, 2.4, 80,
   $qm$¿Cuál es la diferencia práctica entre teoría de perturbaciones y método variacional?$qm$,
   $qm$Son el mismo método con distinta notación.$qm$,
   $qm$El variacional es exacto y el perturbativo aproximado.$qm$,
   $qm$Perturbaciones exige un problema exacto cercano y da correcciones sistemáticas orden por orden; el variacional no exige nada de eso, pero solo entrega una cota y su calidad depende enteramente de la función de prueba elegida.$qm$,
   $qm$El variacional sirve para cualquier estado excitado sin ninguna restricción.$qm$,
   $qm$C$qm$,
   $qm$Son métodos independientes: uno desarrolla en un parámetro chico alrededor de una solución conocida, el otro minimiza un funcional sobre una familia de funciones arbitrarias.$qm$,
   $qm$El variacional tampoco es exacto: da una cota superior, y sin información adicional no se sabe qué tan lejos está de $E_0$. Su ventaja es la robustez, no la exactitud.$qm$,
   $qm$Correcto. Por eso se usan en situaciones distintas: perturbaciones para desdoblamientos finos de un espectro conocido, variacional para estimar el fundamental de un sistema que no se parece a nada resuelto (el helio es el ejemplo clásico).$qm$,
   $qm$Para un estado excitado el variacional exige que la función de prueba sea **ortogonal** a todos los estados de menor energía; si no, el mínimo se escapa hacia el fundamental. Esa restricción es su principal limitación.$qm$,
   null, $qm$mq/variacional/da-cota-inferior$qm$, null, null),

  -- ===========================================================================
  -- mq_identicas · Partículas idénticas y exclusión
  -- ===========================================================================

  ($qm$mq_identicas$qm$, $qm$cuantica/identicas$qm$, -0.7, 10,
   $qm$Bajo el intercambio de dos partículas idénticas, ¿cómo se comporta la función de onda total?$qm$,
   $qm$Antisimétrica para bosones y simétrica para fermiones.$qm$,
   $qm$Simétrica para bosones y antisimétrica para fermiones.$qm$,
   $qm$Siempre simétrica: las partículas son idénticas, así que nada puede cambiar.$qm$,
   $qm$Cambia de forma arbitraria, dependiendo del sistema.$qm$,
   $qm$B$qm$,
   $qm$Están intercambiados. La regla mnemotécnica que no falla: los fermiones obedecen a Pauli, y Pauli sale de la **antisimetría** (si dos fermiones estuvieran en el mismo estado, la función antisimétrica se anularía).$qm$,
   $qm$Correcto. Y por el teorema espín-estadística, bosones son los de espín entero y fermiones los de espín semientero.$qm$,
   $qm$Lo que no puede cambiar es $|\psi|^{2}$, y eso deja **dos** posibilidades para $\psi$: el signo $+$ y el signo $-$. La naturaleza usa las dos, y esa es toda la diferencia entre un láser y la tabla periódica.$qm$,
   $qm$No es arbitrario: aplicar dos veces el intercambio devuelve el estado original, así que el factor al cuadrado debe ser 1 y el factor solo puede valer $+1$ o $-1$.$qm$,
   $qm$mq/identicas/simetria-intercambiada$qm$, null,
   $qm$mq/identicas/simetria-intercambiada$qm$,
   $qm$mq/identicas/particulas-distinguibles$qm$),

  ($qm$mq_identicas$qm$, $qm$cuantica/identicas$qm$, -0.1, 20,
   $qm$¿Cuál es el enunciado más general del principio de exclusión de Pauli?$qm$,
   $qm$Dos electrones no pueden estar en el mismo orbital.$qm$,
   $qm$Dos electrones no pueden tener la misma energía.$qm$,
   $qm$La función de onda total de un sistema de fermiones idénticos es antisimétrica bajo intercambio; de ahí se sigue que no puede haber dos en el mismo estado completo.$qm$,
   $qm$Ninguna partícula puede compartir su estado con otra.$qm$,
   $qm$C$qm$,
   $qm$Es la versión escolar y es incompleta: dos electrones **sí** comparten orbital, si tienen espín opuesto. Lo que no pueden compartir es el estado completo, incluyendo el espín.$qm$,
   $qm$Muchísimos electrones comparten energía: todo nivel degenerado los tiene. Lo que no pueden compartir es el conjunto completo de números cuánticos.$qm$,
   $qm$Correcto. El principio es una consecuencia de la antisimetría, no un postulado aparte: si dos fermiones ocuparan el mismo estado, intercambiarlos daría $\psi = -\psi$, o sea $\psi = 0$.$qm$,
   $qm$Los **bosones** no solo pueden, sino que tienden a acumularse en el mismo estado: ahí están el láser y el condensado de Bose-Einstein. La exclusión es exclusiva de los fermiones.$qm$,
   $qm$mq/identicas/pauli-solo-como-regla-de-orbitales$qm$,
   $qm$mq/identicas/pauli-solo-como-regla-de-orbitales$qm$, null,
   $qm$mq/identicas/simetria-intercambiada$qm$),

  ($qm$mq_identicas$qm$, $qm$cuantica/identicas$qm$, 0.4, 30,
   $qm$Dos partículas pueden ocupar dos estados de una partícula, $a$ y $b$. ¿Cuántos estados de dos partículas hay en cada caso?$qm$,
   $qm$4 en todos los casos: $aa$, $ab$, $ba$, $bb$.$qm$,
   $qm$3 si son bosones ($aa$, $bb$ y la combinación simétrica de $ab$), 1 si son fermiones (la combinación antisimétrica), y 4 si fueran distinguibles.$qm$,
   $qm$2 en todos los casos.$qm$,
   $qm$3 si son fermiones y 1 si son bosones.$qm$,
   $qm$B$qm$,
   $qm$Ese es el conteo de partículas **distinguibles**, donde $ab$ y $ba$ son estados diferentes. Si son idénticas, no hay ningún experimento que las separe, y $ab$/$ba$ colapsan en una sola combinación (simétrica o antisimétrica).$qm$,
   $qm$Correcto. Es el origen de las tres estadísticas: Maxwell-Boltzmann (4), Bose-Einstein (3) y Fermi-Dirac (1). Que los pesos estadísticos sean distintos es lo que hace medible la diferencia -- ahí está, por ejemplo, la ley de Planck.$qm$,
   $qm$Faltan los estados con ambas partículas en el mismo nivel, que existen para bosones y para distinguibles.$qm$,
   $qm$Está invertido: los **fermiones** son los restringidos (solo 1 estado, porque $aa$ y $bb$ están prohibidos) y los bosones los permisivos (3).$qm$,
   $qm$mq/identicas/particulas-distinguibles$qm$, null, null,
   $qm$mq/identicas/simetria-intercambiada$qm$),

  ($qm$mq_identicas$qm$, $qm$cuantica/identicas$qm$, 1.0, 40,
   $qm$¿Para qué sirve el determinante de Slater?$qm$,
   $qm$Para normalizar la función de onda de un sistema de muchas partículas.$qm$,
   $qm$Para construir automáticamente una función de onda **antisimétrica** de $N$ fermiones.$qm$,
   $qm$Para calcular la energía total del sistema.$qm$,
   $qm$Para construir estados simétricos de bosones.$qm$,
   $qm$B$qm$,
   $qm$La normalización es solo el prefactor $1/\sqrt{N!}$, un detalle. Lo esencial es la estructura de determinante.$qm$,
   $qm$Correcto. La antisimetría sale gratis de una propiedad conocida de los determinantes: intercambiar dos partículas equivale a intercambiar dos columnas, lo que cambia el signo. Y Pauli aparece solo: si dos fermiones están en el mismo estado, hay dos filas iguales y el determinante se anula.$qm$,
   $qm$No calcula energías: es una forma de escribir el estado. La energía se obtiene después, evaluando $\langle H\rangle$ sobre él (eso es el método de Hartree-Fock).$qm$,
   $qm$Para bosones se usa el **permanente**, que es como el determinante pero con todos los signos positivos. El determinante es específicamente la construcción antisimétrica.$qm$,
   null, null, null,
   $qm$mq/identicas/simetria-intercambiada$qm$),

  ($qm$mq_identicas$qm$, $qm$cuantica/identicas$qm$, 1.6, 50,
   $qm$En el átomo de helio, los estados con espín triplete (ortohelio) tienen menor energía que el estado singlete correspondiente (parahelio). ¿Por qué?$qm$,
   $qm$Porque el triplete tiene mayor energía magnética.$qm$,
   $qm$Porque los espines interactúan directamente entre sí y alinearse baja la energía.$qm$,
   $qm$Porque el triplete de espín es simétrico, así que la parte espacial debe ser antisimétrica; esa función mantiene a los electrones más separados y reduce la repulsión de Coulomb.$qm$,
   $qm$Porque el triplete tiene tres estados y la energía se reparte entre ellos.$qm$,
   $qm$C$qm$,
   $qm$La interacción magnética entre los momentos de espín existe, pero es varios órdenes de magnitud menor que el efecto observado. La separación orto/para es de fracciones de eV, demasiado grande para un origen magnético.$qm$,
   $qm$No hay ningún término de interacción espín-espín en el Hamiltoniano electrostático del helio. El espín entra **indirectamente**, a través de la simetría que impone a la parte espacial. Ese es el punto sutil y hermoso del tema.$qm$,
   $qm$Correcto. Es la "interacción de intercambio": una consecuencia puramente estadística que se manifiesta como si fuera una fuerza dependiente del espín. Es el mismo mecanismo que produce el ferromagnetismo.$qm$,
   $qm$La energía no se "reparte" entre estados degenerados: cada uno de los tres estados del triplete tiene la misma energía, y esa energía es menor que la del singlete.$qm$,
   null, null, null, null),

  ($qm$mq_identicas$qm$, $qm$cuantica/identicas$qm$, 2.2, 60,
   $qm$¿Qué conecta el espín de una partícula con su estadística?$qm$,
   $qm$Es un postulado independiente, sin demostración.$qm$,
   $qm$Es una regla empírica extraída de la tabla periódica.$qm$,
   $qm$Nada: son propiedades independientes entre sí.$qm$,
   $qm$El teorema espín-estadística: espín semientero implica fermión y espín entero implica bosón, y Pauli lo demostró en 1940 dentro de la teoría cuántica de campos relativista.$qm$,
   $qm$D$qm$,
   $qm$En la mecánica cuántica **no relativista** funciona efectivamente como un postulado, y así se lo suele presentar. Pero tiene demostración, y ese es el punto: exige relatividad.$qm$,
   $qm$Pauli formuló el principio de exclusión en 1925 como regla empírica para salvar la tabla periódica, es cierto. La conexión con el espín es otra cosa y llegó quince años más tarde, como teorema.$qm$,
   $qm$Están rígidamente conectadas, y la conexión es una de las predicciones más profundas de la teoría cuántica de campos: no se conoce ninguna partícula que la viole.$qm$,
   $qm$Correcto. La demostración usa causalidad relativista (los operadores en puntos separados espacialmente deben conmutar o anticonmutar) y positividad de la energía. Sin relatividad, la conexión no se puede derivar.$qm$,
   null, null, null, null),

  -- ===========================================================================
  -- mq_interpretacion · Medida, EPR y Bell
  -- ===========================================================================

  ($qm$mq_interpretacion$qm$, $qm$cuantica/interpretacion$qm$, -0.6, 10,
   $qm$¿Qué pretendían mostrar Einstein, Podolsky y Rosen en su artículo de 1935?$qm$,
   $qm$Que la mecánica cuántica es internamente inconsistente.$qm$,
   $qm$Que la mecánica cuántica es **incompleta**: aceptando realismo y localidad, hay elementos de realidad que la teoría no describe.$qm$,
   $qm$Que se puede transmitir información más rápido que la luz.$qm$,
   $qm$Que el colapso instantáneo es matemáticamente imposible.$qm$,
   $qm$B$qm$,
   $qm$EPR nunca acusó a la teoría de inconsistente: aceptaban que sus predicciones eran correctas. El reclamo era que faltaba algo, no que estuviera mal.$qm$,
   $qm$Correcto. El argumento es un condicional: **si** se acepta el criterio de realidad de EPR y la localidad, **entonces** la descripción cuántica es incompleta. Bell mostró treinta años después que esa premisa es falsable experimentalmente, y el experimento la falsó.$qm$,
   $qm$EPR no propuso eso, y sería falso: las correlaciones no permiten señalizar. Lo que les incomodaba era la "acción fantasmal a distancia" como imagen, no una violación de la relatividad en las predicciones.$qm$,
   $qm$El formalismo del colapso es matemáticamente consistente; lo que EPR cuestionaba era su interpretación física y su completitud.$qm$,
   null, null, $qm$mq/entrelazamiento/senal-superluminica$qm$, null),

  ($qm$mq_interpretacion$qm$, $qm$cuantica/interpretacion$qm$, 0.0, 20,
   $qm$Alice y Bob comparten un par de espines en estado singlete y se alejan. Alice mide el suyo. ¿Puede así enviarle información a Bob?$qm$,
   $qm$Sí, eligiendo el eje sobre el que mide.$qm$,
   $qm$No: la estadística local de Bob es la misma mida Alice o no; la correlación solo aparece al comparar los resultados por un canal clásico.$qm$,
   $qm$Sí, pero solo un bit por par compartido.$qm$,
   $qm$No, porque el estado se destruye al medir.$qm$,
   $qm$B$qm$,
   $qm$El eje que elija Alice no cambia nada de lo que Bob observa: él sigue viendo $50\,\%$ y $50\,\%$, sea cual sea la elección de Alice e incluso si Alice no mide. Ese es el teorema de no-señalización.$qm$,
   $qm$Correcto. El entrelazamiento produce correlaciones más fuertes que cualquier explicación local, pero no permite señalizar: por eso convive sin conflicto con la relatividad. Es la distinción entre correlación y comunicación.$qm$,
   $qm$Ni un bit: la distribución marginal de Bob es exactamente la misma en todos los casos, así que no hay ninguna diferencia detectable localmente.$qm$,
   $qm$La conclusión es correcta pero la razón no. Aunque el estado se "destruya", Bob no tiene forma de saber si eso ocurrió: sus estadísticas locales son idénticas en ambos escenarios.$qm$,
   $qm$mq/entrelazamiento/senal-superluminica$qm$, null,
   $qm$mq/entrelazamiento/senal-superluminica$qm$, null),

  ($qm$mq_interpretacion$qm$, $qm$cuantica/interpretacion$qm$, 0.6, 30,
   $qm$Sobre el estado singlete $\frac{1}{\sqrt2}\left(|{\uparrow\downarrow}\rangle - |{\downarrow\uparrow}\rangle\right)$, ¿cuál afirmación es correcta?$qm$,
   $qm$Es el producto de $|{\uparrow}\rangle$ de la partícula 1 por $|{\downarrow}\rangle$ de la 2.$qm$,
   $qm$Describe a la partícula 1 con espín arriba y a la 2 con espín abajo.$qm$,
   $qm$No se puede escribir como producto de un estado de la partícula 1 por uno de la 2: ninguna de las dos tiene un estado propio definido.$qm$,
   $qm$Es una mezcla estadística: mitad $|{\uparrow\downarrow}\rangle$ y mitad $|{\downarrow\uparrow}\rangle$.$qm$,
   $qm$C$qm$,
   $qm$Si lo fuera, sería $|{\uparrow\downarrow}\rangle$ a secas. La superposición de dos productos con signo relativo es precisamente lo que **no** se puede factorizar: eso es el entrelazamiento.$qm$,
   $qm$Ninguna de las dos tiene espín definido antes de medir. Lo que está definido es la **relación** entre ambas: apuntan en sentidos opuestos, sea cual sea el eje que se elija.$qm$,
   $qm$Correcto. Cada partícula por separado está en un estado mixto máximamente desordenado (la traza parcial da la identidad sobre 2), aunque el estado conjunto sea puro y perfectamente conocido. Es la firma del entrelazamiento.$qm$,
   $qm$Una mezcla daría las mismas estadísticas que el singlete al medir en el eje $z$, pero no al medir en $x$: la mezcla no viola las desigualdades de Bell y el singlete sí. La diferencia es experimental.$qm$,
   $qm$mq/entrelazamiento/estado-producto$qm$,
   $qm$mq/entrelazamiento/estado-producto$qm$, null,
   $qm$mq/estados/superposicion-como-mezcla$qm$),

  ($qm$mq_interpretacion$qm$, $qm$cuantica/interpretacion$qm$, 1.2, 40,
   $qm$¿Qué demuestra el teorema de Bell (1964)?$qm$,
   $qm$Que la mecánica cuántica es incorrecta.$qm$,
   $qm$Que ninguna teoría de variables ocultas es posible, de ningún tipo.$qm$,
   $qm$Que las variables ocultas locales siguen siendo perfectamente compatibles con lo observado.$qm$,
   $qm$Que toda teoría de variables ocultas **locales** obedece una desigualdad que la mecánica cuántica viola: la discusión de EPR pasa a ser experimental.$qm$,
   $qm$D$qm$,
   $qm$Bell no puso en duda las predicciones cuánticas: lo que hizo fue derivar una consecuencia contrastable de la hipótesis contraria (realismo local) y mostrar que discrepa de ellas.$qm$,
   $qm$El teorema excluye las **locales**. La teoría de De Broglie-Bohm es una teoría de variables ocultas explícitamente no local, reproduce todas las predicciones cuánticas y no está excluida por Bell.$qm$,
   $qm$Los experimentos violan la desigualdad de forma masiva y repetida. Esa es la razón del Nobel de 2022.$qm$,
   $qm$Correcto. La contribución de Bell fue convertir un debate de treinta años sobre interpretación en una pregunta de laboratorio. Su artículo se titula, precisamente, "On the Einstein Podolsky Rosen Paradox".$qm$,
   null, null,
   $qm$mq/bell/variables-ocultas-locales-viables$qm$, null),

  ($qm$mq_interpretacion$qm$, $qm$cuantica/interpretacion$qm$, 1.8, 50,
   $qm$¿Qué mostraron los experimentos de Clauser, Aspect y Zeilinger, premiados con el Nobel de Física 2022?$qm$,
   $qm$Que se puede comunicar información más rápido que la luz.$qm$,
   $qm$Violación de las desigualdades de Bell, cerrando progresivamente los resquicios experimentales (detección, localidad, libertad de elección).$qm$,
   $qm$Que el colapso de la función de onda es un proceso observable directamente.$qm$,
   $qm$Que la desigualdad se cumple, confirmando el realismo local.$qm$,
   $qm$B$qm$,
   $qm$Ninguno de esos experimentos transmitió información superlumínica, ni podría: la no-señalización es un teorema, no una limitación técnica.$qm$,
   $qm$Correcto. El progreso fue justamente metodológico: cada generación de experimentos cerró una escapatoria posible. Aspect (1982) cambió la orientación de los analizadores mientras los fotones estaban en vuelo; Zeilinger llevó la separación a escala de kilómetros y usó fuentes cósmicas para elegir los ajustes.$qm$,
   $qm$Lo que se mide son coincidencias de detección en función de los ángulos de los analizadores. El colapso no se observa como proceso: se infiere de la estadística.$qm$,
   $qm$El resultado fue el contrario: la desigualdad se **viola**, y por márgenes de decenas de desviaciones estándar.$qm$,
   $qm$mq/entrelazamiento/senal-superluminica$qm$, null, null,
   $qm$mq/bell/variables-ocultas-locales-viables$qm$),

  ($qm$mq_interpretacion$qm$, $qm$cuantica/interpretacion$qm$, 2.3, 60,
   $qm$¿Qué explica la decoherencia y qué deja sin explicar?$qm$,
   $qm$Explica completamente el colapso: resuelto el problema de la medición.$qm$,
   $qm$Demuestra que las superposiciones no existen realmente.$qm$,
   $qm$Es simplemente otro nombre para la interpretación de Copenhague.$qm$,
   $qm$Explica por qué las superposiciones macroscópicas se vuelven inobservables -- la coherencia se dispersa irreversiblemente en el entorno --, pero no por qué se obtiene **un** resultado concreto y no otro.$qm$,
   $qm$D$qm$,
   $qm$La decoherencia es evolución unitaria del sistema más el entorno, y una evolución unitaria no puede producir un resultado único: solo transforma una superposición del sistema en una del conjunto. El paso de "muchos términos" a "uno solo" no está ahí.$qm$,
   $qm$Al contrario: la decoherencia describe cómo la superposición se **dispersa** en las correlaciones con el entorno, no cómo desaparece. En sistemas bien aislados se mantiene, y eso es lo que explota la computación cuántica.$qm$,
   $qm$Copenhague es una interpretación (con un postulado de colapso); la decoherencia es un mecanismo físico calculable a partir del formalismo, sin postulados nuevos, y compatible con varias interpretaciones distintas.$qm$,
   $qm$Correcto. Explica muy bien la ausencia de gatos macroscópicos en superposición y por qué ciertas bases ("preferidas") son las que sobreviven. El problema del resultado único -- el problema de la medición propiamente dicho -- sigue abierto.$qm$,
   $qm$mq/medida/colapso-reversible$qm$,
   $qm$mq/estados/superposicion-como-mezcla$qm$, null, null)

)
insert into public.questions
  (topic, module_id, difficulty, order_index,
   question, option_a, option_b, option_c, option_d, correct_option,
   error_a, error_b, error_c, error_d,
   misconception_a_id, misconception_b_id, misconception_c_id, misconception_d_id)
select i.topic, m.id, i.difficulty, i.order_index,
       i.question, i.option_a, i.option_b, i.option_c, i.option_d, i.correct_option,
       i.error_a, i.error_b, i.error_c, i.error_d,
       xa.id, xb.id, xc.id, xd.id
from items i
left join public.modules m       on m.slug  = i.module_slug
left join public.misconceptions xa on xa.slug = i.mis_a
left join public.misconceptions xb on xb.slug = i.mis_b
left join public.misconceptions xc on xc.slug = i.mis_c
left join public.misconceptions xd on xd.slug = i.mis_d
where not exists (
  select 1 from public.questions q
   where q.topic = i.topic and q.question = i.question
);

-- Verificación: mq_hidrogeno 8 · mq_perturbaciones 8 · mq_identicas 6 ·
--               mq_interpretacion 6
