-- Banco consolidado del eje de números — primera tanda
-- 100 ítems · topic `numeros` · 47 ideas erróneas nuevas
--
-- GENERADA por scripts/generar_migracion_items.py desde el JSON de la tanda.
-- No editar a mano: corregir el JSON, volver a verificar y regenerar. Un cambio
-- hecho acá se pierde en la siguiente regeneración y deja de estar verificado.
--
-- Verificada con scripts/verificar_items.py, que comprueba lo que este banco
-- aprendió a golpes: clave repartida entre las cuatro letras (R-35), una sola
-- alternativa correcta, las cuatro explicaciones escritas, la correcta sin idea
-- errónea, LaTeX con escape simple (047) y cobertura de dificultad sin huecos.
--
-- 100 ítems repartidos en los seis módulos de aritmética, cubriendo toda la escala
-- [-3, 3] con al menos 6 ítems por tramo de 1,0 logit.
--
-- REQUIERE la migración 049 aplicada (bandas explícitas del eje). Sin ella, las
-- bandas derivadas meten todo el eje en [-2,85, -0,54] y estos ítems quedan
-- declarando dificultades fuera de la banda de su propio módulo.
--
-- `difficulty` es una HIPÓTESIS EDITORIAL, no una medición. Sigue vigente R-17:
-- la validez psicométrica solo puede venir de calibrar con respuestas reales (G-2),
-- y estas cifras son la hipótesis contra la que se contrastará.

-- -----------------------------------------------------------------------------
-- 1. Ideas erróneas nuevas
-- -----------------------------------------------------------------------------
-- Van ANTES de los ítems y en el mismo archivo: el `left join` de abajo
-- resuelve por slug, así que si no existen todavía los ítems entrarían con
-- `misconception_*_id` en null y en silencio.
--
-- `on conflict (slug) do nothing`: si una ya está catalogada, se respeta la
-- que hay. Reaplicar contenido no pisa una corrección hecha en el panel.

insert into public.misconceptions (slug, name, description, module_id)
select v.slug, v.name, v.description, m.id
  from (values
    ($it$numeros/lee-el-digito-y-no-su-valor$it$, $it$Confunde el dígito con el valor posicional que representa$it$, $it$Usar cuando responde con la cifra escrita en vez de lo que vale según su posición. NO usar si el error es de conteo de posiciones (para eso está numeros/desplaza-una-posicion).$it$, $it$aritmetica/numeros$it$),
    ($it$numeros/desplaza-una-posicion$it$, $it$Cuenta mal las posiciones y se corre un lugar$it$, $it$Usar cuando el valor entregado es diez veces mayor o menor que el correcto. Reconoce que la posición importa, y se equivoca al contarla.$it$, $it$aritmetica/numeros$it$),
    ($it$numeros/mas-cifras-decimales-es-mayor$it$, $it$Cree que un decimal con más cifras es mayor$it$, $it$Usar cuando ordena decimales por cantidad de cifras y no por valor. Viene de trasladar a los decimales la regla de los enteros, donde más cifras sí es mayor.$it$, $it$aritmetica/numeros$it$),
    ($it$numeros/divisibilidad-mira-solo-la-ultima-cifra$it$, $it$Aplica a todos los divisores el criterio de la última cifra$it$, $it$Usar cuando decide divisibilidad por 3, 9 u 11 mirando el dígito final. Es el criterio del 2, 5 y 10 generalizado sin permiso.$it$, $it$aritmetica/numeros$it$),
    ($it$numeros/redondea-truncando$it$, $it$Trunca en vez de redondear$it$, $it$Usar cuando corta las cifras sobrantes sin mirar la siguiente. NO usar cuando redondea correctamente pero en la posición equivocada.$it$, $it$aritmetica/numeros$it$),
    ($it$numeros/confunde-primo-con-impar$it$, $it$Cree que todo número impar es primo$it$, $it$Usar cuando marca como primo un impar compuesto (9, 21, 51, 57, 91). Es la regla «no divisible por 2» tomada como suficiente.$it$, $it$aritmetica/numeros$it$),
    ($it$numeros/factorizacion-sin-agotar-primos$it$, $it$Deja factores compuestos en la descomposición prima$it$, $it$Usar cuando entrega una factorización correcta como producto pero con algún factor que todavía se puede descomponer.$it$, $it$aritmetica/numeros$it$),
    ($it$numeros/confunde-mcd-con-mcm$it$, $it$Intercambia máximo común divisor con mínimo común múltiplo$it$, $it$Usar cuando el número entregado es el otro de los dos. Es el error de traducir mal el enunciado, no de calcular.$it$, $it$aritmetica/numeros$it$),
    ($it$numeros/opera-de-izquierda-a-derecha$it$, $it$Resuelve en el orden en que está escrito, ignorando la prioridad$it$, $it$Usar cuando suma antes de multiplicar, o resta antes de dividir, y el resultado es coherente con ese orden.$it$, $it$aritmetica/numeros$it$),
    ($it$enteros/mas-lejos-del-cero-es-mayor$it$, $it$Ordena los negativos por su valor absoluto$it$, $it$Usar cuando dice que -8 es mayor que -5 porque 8 es mayor que 5. Es la recta numérica leída sin considerar el signo.$it$, $it$aritmetica/enteros$it$),
    ($it$enteros/restar-negativo-como-restar-positivo$it$, $it$Trata $a-(-b)$ como si fuera $a-b$$it$, $it$Usar cuando ignora el doble signo y resta en vez de sumar. NO usar para errores de signo en multiplicación o división, que tienen su propia regla.$it$, $it$aritmetica/enteros$it$),
    ($it$enteros/regla-de-signos-a-medias$it$, $it$Arrastra el signo negativo aunque los dos factores lo tengan$it$, $it$Usar cuando el producto o cociente de dos negativos queda negativo. Reconoce que hay negativos y no que se cancelan entre sí.$it$, $it$aritmetica/enteros$it$),
    ($it$enteros/pierde-el-signo-del-producto$it$, $it$Entrega positivo un producto con un solo factor negativo$it$, $it$Usar cuando calcula bien el valor y suelta el signo. Es distinto de la regla de signos a medias: acá el problema es que el signo desaparece, no que sobra.$it$, $it$aritmetica/enteros$it$),
    ($it$enteros/valor-absoluto-como-cambio-de-signo$it$, $it$Cree que el valor absoluto invierte el signo en vez de quitarlo$it$, $it$Usar cuando aplica el valor absoluto a un positivo y lo devuelve negativo, o cuando lo describe como «cambiar el signo».$it$, $it$aritmetica/enteros$it$),
    ($it$enteros/suma-los-valores-y-conserva-un-signo$it$, $it$Suma los valores absolutos y le pone el signo de uno de los términos$it$, $it$Usar cuando con signos distintos suma en vez de restar. Es no distinguir «avanzar» de «retroceder» en la recta.$it$, $it$aritmetica/enteros$it$),
    ($it$enteros/exponente-impar-borra-el-signo$it$, $it$Cree que toda potencia da resultado positivo$it$, $it$Usar cuando entrega positivo una potencia de base negativa y exponente impar. La paridad del exponente es lo que decide el signo.$it$, $it$aritmetica/enteros$it$),
    ($it$enteros/diferencia-sin-cruzar-el-cero$it$, $it$Calcula la diferencia entre un negativo y un positivo restando los valores$it$, $it$Usar cuando la variación entre -8 y 5 la da como 3 en vez de 13. Cuenta solo un lado del cero.$it$, $it$aritmetica/enteros$it$),
    ($it$fracciones/suma-numeradores-y-denominadores$it$, $it$Suma fracciones sumando numeradores y denominadores$it$, $it$El error más frecuente: $\frac{a}{b}+\frac{c}{d}=\frac{a+c}{b+d}$. Usar solo para suma o resta; en la multiplicación esa forma es casi correcta y el error es otro.$it$, $it$aritmetica/fracciones$it$),
    ($it$fracciones/simplificacion-incompleta$it$, $it$Deja la fracción a medio simplificar$it$, $it$Usar cuando divide por un factor común pero no por el máximo, y entrega una fracción equivalente y correcta pero no irreducible.$it$, $it$aritmetica/fracciones$it$),
    ($it$fracciones/invierte-el-dividendo-al-dividir$it$, $it$Al dividir invierte la primera fracción en vez de la segunda$it$, $it$Usar cuando aplica invertir-y-multiplicar sobre el término equivocado. Sabe que hay que invertir algo, y eso lo distingue de quien multiplica directo.$it$, $it$aritmetica/fracciones$it$),
    ($it$fracciones/denominador-mayor-fraccion-mayor$it$, $it$Cree que a mayor denominador, mayor fracción$it$, $it$Usar cuando ordena fracciones de igual numerador por el tamaño del denominador. Es trasladar a las partes la intuición de los enteros: más partes, más cantidad.$it$, $it$aritmetica/fracciones$it$),
    ($it$fracciones/compara-mirando-un-solo-termino$it$, $it$Compara fracciones mirando solo los numeradores o solo los denominadores$it$, $it$Usar cuando decide cuál es mayor sin igualar denominadores ni pasar a decimal.$it$, $it$aritmetica/fracciones$it$),
    ($it$fracciones/mixto-pega-los-numeros$it$, $it$Arma o deshace un número mixto pegando las cifras$it$, $it$Usar cuando convierte $\frac{5}{4}$ en «$5$ enteros y $\frac{1}{4}$» o similar: toma el numerador como parte entera.$it$, $it$aritmetica/fracciones$it$),
    ($it$fracciones/decimal-a-fraccion-por-las-cifras$it$, $it$Convierte un decimal a fracción usando sus cifras como denominador$it$, $it$Usar cuando $0{,}25$ se transforma en $\frac{1}{25}$ o $\frac{25}{10}$: no identifica la posición decimal como potencia de diez.$it$, $it$aritmetica/fracciones$it$),
    ($it$fracciones/multiplica-en-vez-de-dividir$it$, $it$Multiplica las fracciones cuando la operación es una división$it$, $it$Usar cuando el resultado coincide con el producto directo. NO usar si invirtió alguna fracción: eso es otro error.$it$, $it$aritmetica/fracciones$it$),
    ($it$potencias/multiplica-base-por-exponente$it$, $it$Calcula $a^n$ como $a \times n$$it$, $it$Usar cuando el resultado es el producto de base por exponente. Es leer la potencia como una multiplicación y no como un producto repetido.$it$, $it$aritmetica/potencias$it$),
    ($it$potencias/opera-las-bases-al-multiplicar$it$, $it$Multiplica también las bases al multiplicar potencias de igual base$it$, $it$Usar cuando $2^3 \times 2^2$ da una potencia de base $4$. Aplica la operación a los dos pisos en vez de solo al exponente.$it$, $it$aritmetica/potencias$it$),
    ($it$potencias/multiplica-exponentes-al-multiplicar$it$, $it$Multiplica los exponentes cuando debía sumarlos$it$, $it$Usar cuando $a^m \times a^n$ da $a^{mn}$. Es la regla de la potencia de una potencia aplicada al caso equivocado.$it$, $it$aritmetica/potencias$it$),
    ($it$potencias/suma-exponentes-en-potencia-de-potencia$it$, $it$Suma los exponentes en $(a^m)^n$ en vez de multiplicarlos$it$, $it$Usar cuando $(a^m)^n$ da $a^{m+n}$. Es el reverso exacto del error anterior: las dos reglas quedaron intercambiadas.$it$, $it$aritmetica/potencias$it$),
    ($it$potencias/exponente-cero-da-cero$it$, $it$Cree que cualquier número elevado a cero da cero$it$, $it$Usar cuando $a^0$ se responde $0$. Viene de leer el exponente como un factor: «cero veces, nada».$it$, $it$aritmetica/potencias$it$),
    ($it$potencias/exponente-negativo-da-resultado-negativo$it$, $it$Cree que un exponente negativo vuelve negativo el resultado$it$, $it$Usar cuando $a^{-n}$ se responde con signo negativo. El exponente negativo indica recíproco, no signo.$it$, $it$aritmetica/potencias$it$),
    ($it$potencias/signo-dentro-o-fuera-del-parentesis$it$, $it$No distingue $(-a)^n$ de $-a^n$$it$, $it$Usar cuando responde igual para las dos formas. El paréntesis decide si el signo entra a la potencia o queda multiplicando afuera.$it$, $it$aritmetica/potencias$it$),
    ($it$potencias/raiz-como-division-por-el-indice$it$, $it$Calcula la raíz dividiendo por el índice$it$, $it$Usar cuando $\sqrt{49}$ se responde $24{,}5$ o similar. Confunde la operación inversa de la potencia con la de la multiplicación.$it$, $it$aritmetica/potencias$it$),
    ($it$proporciones/aplica-directa-donde-es-inversa$it$, $it$Trata como directa una relación inversamente proporcional$it$, $it$Usar cuando al aumentar una magnitud aumenta la otra y debía disminuir (más obreros, más días). Es la regla de tres aplicada sin preguntarse el sentido.$it$, $it$aritmetica/proporciones$it$),
    ($it$proporciones/aplica-inversa-donde-es-directa$it$, $it$Trata como inversa una relación directamente proporcional$it$, $it$Usar cuando al aumentar una magnitud disminuye la otra y debía aumentar. Es el reverso del error anterior.$it$, $it$aritmetica/proporciones$it$),
    ($it$proporciones/razona-por-diferencias$it$, $it$Escala sumando la diferencia en vez de multiplicando por la razón$it$, $it$Usar cuando pasa de 3 a 5 sumando 2 a la otra magnitud, en vez de multiplicar por 5/3. Es pensamiento aditivo donde el problema es multiplicativo.$it$, $it$aritmetica/proporciones$it$),
    ($it$proporciones/velocidad-media-como-promedio-simple$it$, $it$Calcula la velocidad media promediando las velocidades$it$, $it$Usar cuando promedia sin pesar por el tiempo o la distancia de cada tramo. La velocidad media es distancia total dividida por tiempo total.$it$, $it$aritmetica/proporciones$it$),
    ($it$proporciones/reparte-en-partes-iguales$it$, $it$Reparte en partes iguales ignorando la razón dada$it$, $it$Usar cuando divide el total por la cantidad de participantes y no por la suma de las partes de la razón.$it$, $it$aritmetica/proporciones$it$),
    ($it$proporciones/escala-en-el-sentido-contrario$it$, $it$Multiplica donde había que dividir al aplicar una escala$it$, $it$Usar cuando el resultado es la escala aplicada al revés y da un tamaño absurdo (un edificio de metros o un mapa de kilómetros).$it$, $it$aritmetica/proporciones$it$),
    ($it$proporciones/razon-sin-simplificar$it$, $it$Entrega la razón sin llevarla a su forma mínima$it$, $it$Usar cuando la razón es correcta pero no está simplificada, y el enunciado pedía la forma mínima.$it$, $it$aritmetica/proporciones$it$),
    ($it$porcentajes/confunde-puntos-con-porcentaje$it$, $it$Confunde puntos porcentuales con variación porcentual$it$, $it$Usar cuando pasar de 20% a 25% se describe como «subió 5%». Subió 5 puntos porcentuales, que es un aumento del 25% sobre el valor anterior.$it$, $it$aritmetica/porcentajes$it$),
    ($it$porcentajes/suma-porcentajes-sucesivos$it$, $it$Suma porcentajes aplicados uno después del otro$it$, $it$Usar cuando dos aumentos del 20% se toman como 40%, o dos descuentos del 50% y 20% como 70%. Cada porcentaje se aplica sobre un total distinto.$it$, $it$aritmetica/porcentajes$it$),
    ($it$porcentajes/base-equivocada$it$, $it$Calcula el porcentaje sobre la cantidad equivocada$it$, $it$Usar cuando aplica el porcentaje al valor final en vez de al inicial, o al revés. Es el error típico al deshacer un descuento.$it$, $it$aritmetica/porcentajes$it$),
    ($it$porcentajes/deshace-el-descuento-sumandolo$it$, $it$Cree que sumar el mismo porcentaje deshace un descuento$it$, $it$Usar cuando para recuperar el precio original tras un 20% de descuento le suma 20% al precio rebajado. El 20% se aplicó sobre una base mayor.$it$, $it$aritmetica/porcentajes$it$),
    ($it$porcentajes/porcentaje-de-porcentaje-como-suma$it$, $it$Suma dos porcentajes encadenados en vez de multiplicarlos$it$, $it$Usar cuando «el 25% del 40%» se responde 65% o 15%. Un porcentaje de un porcentaje es un producto.$it$, $it$aritmetica/porcentajes$it$),
    ($it$porcentajes/promedia-porcentajes-sin-ponderar$it$, $it$Promedia porcentajes sin considerar el tamaño de cada grupo$it$, $it$Usar cuando saca el promedio simple de dos porcentajes calculados sobre bases distintas.$it$, $it$aritmetica/porcentajes$it$),
    ($it$porcentajes/interes-compuesto-como-simple$it$, $it$Aplica interés simple donde el interés se capitaliza$it$, $it$Usar cuando multiplica la tasa por los años en vez de componerla. En el interés compuesto, cada período se calcula sobre el saldo acumulado.$it$, $it$aritmetica/porcentajes$it$)
  ) as v(slug, name, description, module_slug)
  left join public.modules m on m.slug = v.module_slug
on conflict (slug) do nothing;

-- -----------------------------------------------------------------------------
-- 2. Ítems
-- -----------------------------------------------------------------------------

with items (topic, module_slug, difficulty, order_index,
            question, option_a, option_b, option_c, option_d, correct_option,
            error_a, error_b, error_c, error_d,
            mis_a, mis_b, mis_c, mis_d) as (
  values

  -- ===========================================================================
  -- aritmetica/numeros
  -- ===========================================================================
  ($it$numeros$it$::text, $it$aritmetica/numeros$it$::text,
   (-3.0)::double precision, 10::int,
   $it$En el número $4.507$, ¿cuánto vale la cifra $5$?$it$::text,
   $it$$500$$it$::text,
   $it$$5$$it$::text,
   $it$$50$$it$::text,
   $it$$5.000$$it$::text,
   $it$A$it$::text,
   $it$Correcto. El $5$ ocupa el lugar de las centenas, así que aporta $5 \times 100 = 500$.$it$::text,
   $it$Ese es el dígito escrito, no lo que vale. En un número posicional cada cifra vale según el lugar que ocupa: acá el $5$ está en las centenas.$it$::text,
   $it$Te corriste una posición: $50$ sería si el $5$ estuviera en las decenas. Contando desde la derecha, $7$ son unidades, $0$ decenas y $5$ centenas.$it$::text,
   $it$Te corriste una posición hacia el otro lado: las unidades de mil las ocupa el $4$.$it$::text,
   null::text, $it$numeros/lee-el-digito-y-no-su-valor$it$::text, $it$numeros/desplaza-una-posicion$it$::text, $it$numeros/desplaza-una-posicion$it$::text),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.9), 20,
   $it$Ordena de mayor a menor: $0{,}7$, $0{,}65$ y $0{,}689$$it$,
   $it$$0{,}689 > 0{,}65 > 0{,}7$$it$,
   $it$$0{,}65 > 0{,}689 > 0{,}7$$it$,
   $it$$0{,}7 > 0{,}65 > 0{,}689$$it$,
   $it$$0{,}7 > 0{,}689 > 0{,}65$$it$,
   $it$D$it$,
   $it$Ordenaste por cantidad de cifras. En los decimales eso no funciona: $0{,}7$ es lo mismo que $0{,}700$, y $700$ milésimas son más que $689$.$it$,
   $it$Acá se juntan dos cosas: ordenar por cantidad de cifras y además comparar mal $0{,}65$ con $0{,}689$. Iguala las cifras primero: $650$, $689$ y $700$ milésimas.$it$,
   $it$Empezaste bien con $0{,}7$, pero después ordenaste $0{,}65$ antes que $0{,}689$. Con tres cifras cada uno: $650 < 689$.$it$,
   $it$Correcto. Igualando cifras quedan $700$, $689$ y $650$ milésimas.$it$,
   $it$numeros/mas-cifras-decimales-es-mayor$it$, $it$numeros/mas-cifras-decimales-es-mayor$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.8), 30,
   $it$¿Cuál de estos números es divisible por $3$?$it$,
   $it$$103$$it$,
   $it$$231$$it$,
   $it$$430$$it$,
   $it$$517$$it$,
   $it$B$it$,
   $it$Termina en $3$, pero eso no dice nada sobre la divisibilidad por $3$. El criterio es sumar las cifras: $1+0+3 = 4$, que no es múltiplo de $3$.$it$,
   $it$Correcto. $2+3+1 = 6$, y $6$ es múltiplo de $3$, así que $231$ también lo es.$it$,
   $it$Termina en $0$, que sirve para el $2$, el $5$ y el $10$, no para el $3$. Sumando: $4+3+0 = 7$.$it$,
   $it$Sumando las cifras: $5+1+7 = 13$, que no es múltiplo de $3$.$it$,
   $it$numeros/divisibilidad-mira-solo-la-ultima-cifra$it$, null, $it$numeros/divisibilidad-mira-solo-la-ultima-cifra$it$, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.7), 40,
   $it$Redondea $3{,}48$ a la décima más cercana.$it$,
   $it$$3{,}4$$it$,
   $it$$3{,}0$$it$,
   $it$$3{,}5$$it$,
   $it$$4{,}0$$it$,
   $it$C$it$,
   $it$Cortaste las cifras sobrantes en vez de redondear. Hay que mirar la cifra siguiente: como es $8$, la décima sube.$it$,
   $it$Redondeaste a la unidad, no a la décima. La décima es la primera cifra después de la coma.$it$,
   $it$Correcto. La cifra que sigue a la décima es $8$, que es $5$ o más, así que el $4$ sube a $5$.$it$,
   $it$Redondeaste a la unidad y además hacia arriba. A la décima el resultado conserva una cifra decimal.$it$,
   $it$numeros/redondea-truncando$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.6), 50,
   $it$¿Cuál de estos números es primo?$it$,
   $it$$51$$it$,
   $it$$57$$it$,
   $it$$53$$it$,
   $it$$91$$it$,
   $it$C$it$,
   $it$Es impar, pero impar no es lo mismo que primo: $51 = 3 \times 17$. Sumando cifras, $5+1 = 6$, ya se ve que lo divide el $3$.$it$,
   $it$Mismo caso: $57 = 3 \times 19$. La suma de sus cifras es $12$, múltiplo de $3$.$it$,
   $it$Correcto. $53$ no se divide por $2$, $3$, $5$ ni $7$, y con eso basta porque $7^2 = 49 < 53 < 64 = 8^2$.$it$,
   $it$$91 = 7 \times 13$. Es el compuesto que más se cuela: no lo delata ningún criterio rápido, hay que probar el $7$.$it$,
   $it$numeros/confunde-primo-con-impar$it$, $it$numeros/confunde-primo-con-impar$it$, null, $it$numeros/confunde-primo-con-impar$it$),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.5), 60,
   $it$¿Cuál es la descomposición en factores **primos** de $60$?$it$,
   $it$$2^2 \times 3 \times 5$$it$,
   $it$$4 \times 15$$it$,
   $it$$2 \times 30$$it$,
   $it$$6 \times 10$$it$,
   $it$A$it$,
   $it$Correcto. $60 = 2 \times 2 \times 3 \times 5$, y los cuatro factores son primos.$it$,
   $it$El producto da $60$, pero $4$ y $15$ no son primos: falta seguir bajando hasta $2 \times 2 \times 3 \times 5$.$it$,
   $it$El producto da $60$ y el $2$ sí es primo, pero $30$ no: todavía se puede descomponer.$it$,
   $it$Ni $6$ ni $10$ son primos. Descomponer significa llegar hasta donde ya no se puede seguir dividiendo.$it$,
   null, $it$numeros/factorizacion-sin-agotar-primos$it$, $it$numeros/factorizacion-sin-agotar-primos$it$, $it$numeros/factorizacion-sin-agotar-primos$it$),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.4), 70,
   $it$¿Cuántas centenas completas hay en $3.400$?$it$,
   $it$$3$$it$,
   $it$$400$$it$,
   $it$$3.400$$it$,
   $it$$34$$it$,
   $it$D$it$,
   $it$Esas son las unidades de mil. Una centena es $100$, así que la pregunta es cuántas veces cabe $100$ en $3.400$.$it$,
   $it$Ese es lo que sobra después de las tres mil unidades, no la cantidad de centenas.$it$,
   $it$Ese es el número completo. La pregunta es cuántos grupos de $100$ contiene.$it$,
   $it$Correcto. $3.400 \div 100 = 34$.$it$,
   $it$numeros/lee-el-digito-y-no-su-valor$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.3), 80,
   $it$¿Cuál es el máximo común divisor de $12$ y $18$?$it$,
   $it$$36$$it$,
   $it$$6$$it$,
   $it$$2$$it$,
   $it$$3$$it$,
   $it$B$it$,
   $it$Ese es el **mínimo común múltiplo**. El divisor común más grande tiene que ser menor o igual que el menor de los dos números.$it$,
   $it$Correcto. Los divisores comunes de $12$ y $18$ son $1$, $2$, $3$ y $6$; el mayor es $6$.$it$,
   $it$Es divisor común, pero no el mayor: $6$ también divide a los dos.$it$,
   $it$Mismo caso: divide a los dos, pero $6$ es más grande y también los divide.$it$,
   $it$numeros/confunde-mcd-con-mcm$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.2), 90,
   $it$¿Cuál es el mínimo común múltiplo de $4$ y $6$?$it$,
   $it$$12$$it$,
   $it$$2$$it$,
   $it$$24$$it$,
   $it$$10$$it$,
   $it$A$it$,
   $it$Correcto. Los múltiplos de $4$ son $4, 8, 12\dots$ y los de $6$ son $6, 12\dots$: el primero que comparten es $12$.$it$,
   $it$Ese es el máximo común **divisor**. Un múltiplo común tiene que ser mayor o igual que los dos números.$it$,
   $it$Es múltiplo de los dos, pero no el menor: $12$ también lo es y viene antes.$it$,
   $it$Sumaste los dos números. Un múltiplo común no sale de sumar.$it$,
   null, $it$numeros/confunde-mcd-con-mcm$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.1), 100,
   $it$¿Cuál es el valor de $2 + 3 \times 4$?$it$,
   $it$$20$$it$,
   $it$$24$$it$,
   $it$$14$$it$,
   $it$$9$$it$,
   $it$C$it$,
   $it$Sumaste primero y multiplicaste después. La multiplicación tiene prioridad sobre la suma, aunque esté escrita a la derecha.$it$,
   $it$Acá se multiplicó todo junto. La expresión tiene una suma y un producto, y solo el producto se resuelve primero.$it$,
   $it$Correcto. Primero $3 \times 4 = 12$, y después $2 + 12 = 14$.$it$,
   $it$Se sumaron los tres números. El signo entre el $3$ y el $4$ es un producto, no una suma.$it$,
   $it$numeros/opera-de-izquierda-a-derecha$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-2.0), 110,
   $it$Redondea $12.847$ a la unidad de mil más cercana.$it$,
   $it$$12.000$$it$,
   $it$$12.800$$it$,
   $it$$12.900$$it$,
   $it$$13.000$$it$,
   $it$D$it$,
   $it$Truncaste: cortaste desde las centenas sin mirar qué había. Como hay $847$, que pasa de $500$, la unidad de mil sube.$it$,
   $it$Redondeaste a la centena, no a la unidad de mil. El resultado tiene que terminar en tres ceros.$it$,
   $it$También es un redondeo a la centena, y esta vez hacia arriba. La posición pedida es la de los miles.$it$,
   $it$Correcto. $847$ es más que $500$, así que $12$ mil sube a $13$ mil.$it$,
   $it$numeros/redondea-truncando$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-1.9), 120,
   $it$¿Cuál de estos números es divisible por $4$?$it$,
   $it$$1.318$$it$,
   $it$$2.316$$it$,
   $it$$5.430$$it$,
   $it$$7.102$$it$,
   $it$B$it$,
   $it$Es par, pero eso solo asegura divisibilidad por $2$. Para el $4$ hay que mirar las **dos** últimas cifras: $18$ no es múltiplo de $4$.$it$,
   $it$Correcto. Las dos últimas cifras forman $16$, que es $4 \times 4$.$it$,
   $it$Termina en $0$, que sirve para el $2$, el $5$ y el $10$. Las dos últimas cifras son $30$, que no es múltiplo de $4$.$it$,
   $it$Las dos últimas cifras son $02$, y $2$ no es múltiplo de $4$.$it$,
   $it$numeros/divisibilidad-mira-solo-la-ultima-cifra$it$, null, $it$numeros/divisibilidad-mira-solo-la-ultima-cifra$it$, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-1.8), 130,
   $it$Dos micros salen del terminal a la misma hora: uno cada $12$ minutos y otro cada $18$. ¿Cada cuántos minutos vuelven a salir juntos?$it$,
   $it$$36$$it$,
   $it$$6$$it$,
   $it$$30$$it$,
   $it$$216$$it$,
   $it$A$it$,
   $it$Correcto. Coinciden en los múltiplos comunes de $12$ y $18$, y el primero es $36$.$it$,
   $it$Ese es el máximo común **divisor**. Acá se buscan momentos que sean múltiplo de los dos intervalos, no un divisor.$it$,
   $it$Sumaste los dos intervalos. Que salgan juntos a los $30$ minutos exigiría que $30$ fuera múltiplo de $12$, y no lo es.$it$,
   $it$Multiplicaste $12 \times 18$. Es un múltiplo común, pero no el primero: a los $36$ minutos ya coinciden.$it$,
   null, $it$numeros/confunde-mcd-con-mcm$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-1.7), 140,
   $it$¿Qué número tiene $3$ unidades de mil, $0$ centenas, $5$ decenas y $2$ unidades?$it$,
   $it$$3.520$$it$,
   $it$$352$$it$,
   $it$$3.052$$it$,
   $it$$3.502$$it$,
   $it$C$it$,
   $it$Pusiste el $5$ en las centenas y el $2$ en las decenas, corriendo todo un lugar. La centena vale $0$, y ese cero ocupa lugar.$it$,
   $it$Se perdieron las unidades de mil. El $3$ está en la cuarta posición, así que el número tiene cuatro cifras.$it$,
   $it$Correcto. Es $3 \times 1.000 + 0 \times 100 + 5 \times 10 + 2 = 3.052$.$it$,
   $it$Cambiaste de lugar el $5$ y el $0$: acá el $5$ quedó en las centenas y el $0$ en las decenas, al revés de lo que dice el enunciado.$it$,
   $it$numeros/desplaza-una-posicion$it$, $it$numeros/desplaza-una-posicion$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-1.65), 150,
   $it$¿Entre qué dos números enteros consecutivos está $\dfrac{47}{6}$?$it$,
   $it$Entre $6$ y $7$$it$,
   $it$Entre $47$ y $48$$it$,
   $it$Entre $8$ y $9$$it$,
   $it$Entre $7$ y $8$$it$,
   $it$D$it$,
   $it$Tomaste el denominador como referencia. Lo que hay que hacer es dividir: $47 \div 6$ da $7$ y sobra $5$.$it$,
   $it$Ese es el numerador. La fracción vale bastante menos: dividir por $6$ achica el número.$it$,
   $it$Te pasaste por uno: $8 \times 6 = 48$, que ya es más que $47$. El cociente entero es $7$.$it$,
   $it$Correcto. $7 \times 6 = 42$ y $8 \times 6 = 48$, así que $\frac{47}{6}$ cae entre $7$ y $8$.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/numeros$it$,
   (-1.6), 160,
   $it$Se quieren repartir $24$ lápices y $36$ cuadernos en cajas iguales, sin que sobre nada y con la **mayor** cantidad posible de cajas. ¿Cuántas cajas se arman?$it$,
   $it$$72$$it$,
   $it$$12$$it$,
   $it$$6$$it$,
   $it$$60$$it$,
   $it$B$it$,
   $it$Ese es un múltiplo común. Acá el número de cajas tiene que **dividir** a $24$ y a $36$: no puede haber más cajas que lápices.$it$,
   $it$Correcto. El número de cajas divide a los dos totales, y el mayor divisor común de $24$ y $36$ es $12$: quedan $2$ lápices y $3$ cuadernos por caja.$it$,
   $it$Es divisor común de los dos, así que funciona, pero no es el máximo: con $12$ cajas también alcanza y son más.$it$,
   $it$Sumaste los dos totales. Eso da cuántos objetos hay, no en cuántas cajas se pueden repartir.$it$,
   $it$numeros/confunde-mcd-con-mcm$it$, null, null, null),

  -- ===========================================================================
  -- aritmetica/enteros
  -- ===========================================================================
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-2.4), 10,
   $it$¿Cuál es el **menor** de estos números: $-5$, $-8$, $3$ y $0$?$it$,
   $it$$0$$it$,
   $it$$-5$$it$,
   $it$$-8$$it$,
   $it$$3$$it$,
   $it$C$it$,
   $it$El cero no es el menor: hay dos números a su izquierda en la recta numérica, y los dos son negativos.$it$,
   $it$Es negativo, pero no el menor. En la recta, $-8$ queda más a la izquierda que $-5$.$it$,
   $it$Correcto. Cuanto más a la izquierda en la recta numérica, menor es el número, y $-8$ es el que está más lejos del cero por ese lado.$it$,
   $it$Ese es el mayor de los cuatro. La pregunta pide el menor.$it$,
   null, $it$enteros/mas-lejos-del-cero-es-mayor$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-2.32), 20,
   $it$¿Cuál es el resultado de $-3 + 7$?$it$,
   $it$$4$$it$,
   $it$$-4$$it$,
   $it$$10$$it$,
   $it$$-10$$it$,
   $it$A$it$,
   $it$Correcto. Partes en $-3$ y avanzas $7$: cruzas el cero y quedas en $4$.$it$,
   $it$El valor está bien y el signo no. Avanzas $7$ desde $-3$, así que terminas a la derecha del cero.$it$,
   $it$Sumaste los dos valores sin mirar que uno es negativo. Con signos distintos se restan, no se suman.$it$,
   $it$Acá se juntan dos cosas: sumar los valores en vez de restarlos, y quedarse con el signo del primero.$it$,
   null, null, $it$enteros/suma-los-valores-y-conserva-un-signo$it$, $it$enteros/suma-los-valores-y-conserva-un-signo$it$),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-2.24), 30,
   $it$¿Cuál es el resultado de $-3 - 7$?$it$,
   $it$$4$$it$,
   $it$$-4$$it$,
   $it$$10$$it$,
   $it$$-10$$it$,
   $it$D$it$,
   $it$Calculaste $7-3$. Los dos términos son negativos acá: no hay nada que avance hacia la derecha.$it$,
   $it$Llegaste a $4$ y le pusiste el signo del primer término. El error está antes: $-3-7$ no es una resta entre $3$ y $7$.$it$,
   $it$El valor está bien —los dos términos suman $10$— pero los dos empujan hacia la izquierda, así que el resultado es negativo.$it$,
   $it$Correcto. Partes en $-3$ y retrocedes $7$ más: quedas en $-10$.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-2.16), 40,
   $it$¿Cuál es el resultado de $7 - (-3)$?$it$,
   $it$$4$$it$,
   $it$$10$$it$,
   $it$$-10$$it$,
   $it$$-4$$it$,
   $it$B$it$,
   $it$Restaste $3$ en vez de restar $-3$. Restar un número negativo equivale a sumarlo: $7-(-3) = 7+3$.$it$,
   $it$Correcto. El opuesto de $-3$ es $3$, así que la operación es $7+3 = 10$.$it$,
   $it$El valor es el correcto, el signo no: partes de $7$ y le sumas, así que el resultado crece.$it$,
   $it$Se juntan dos errores: restar $3$ en vez de sumarlo, y además cambiar el signo del resultado.$it$,
   $it$enteros/restar-negativo-como-restar-positivo$it$, null, null, $it$enteros/restar-negativo-como-restar-positivo$it$),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-2.08), 50,
   $it$¿Cuál es el valor de $|-6|$?$it$,
   $it$$6$$it$,
   $it$$-6$$it$,
   $it$$0$$it$,
   $it$$\dfrac{1}{6}$$it$,
   $it$A$it$,
   $it$Correcto. El valor absoluto es la distancia al cero, y una distancia nunca es negativa.$it$,
   $it$El valor absoluto no cambia el signo: lo **quita**. $|-6|$ y $|6|$ dan lo mismo, porque los dos están a $6$ del cero.$it$,
   $it$El valor absoluto de un número solo da cero si el número es cero.$it$,
   $it$Esa es la operación de invertir, que es otra cosa. El valor absoluto no divide ni da vuelta nada.$it$,
   null, $it$enteros/valor-absoluto-como-cambio-de-signo$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-2.0), 60,
   $it$¿Cuál es el resultado de $(-4) \times 3$?$it$,
   $it$$12$$it$,
   $it$$-1$$it$,
   $it$$-12$$it$,
   $it$$7$$it$,
   $it$C$it$,
   $it$El valor está bien, el signo se perdió. Un solo factor negativo deja el producto negativo.$it$,
   $it$Ese es el resultado de sumar $-4$ y $3$. El signo entre ellos es un producto.$it$,
   $it$Correcto. $4 \times 3 = 12$, y como hay un único factor negativo el resultado es $-12$.$it$,
   $it$Se sumaron los valores sin mirar el signo, y además la operación es una multiplicación.$it$,
   $it$enteros/pierde-el-signo-del-producto$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.92), 70,
   $it$¿Cuál es el resultado de $(-4) \times (-3)$?$it$,
   $it$$-7$$it$,
   $it$$-12$$it$,
   $it$$7$$it$,
   $it$$12$$it$,
   $it$D$it$,
   $it$Se sumaron los valores en vez de multiplicarlos, y se conservó el signo.$it$,
   $it$El valor está bien. Arrastraste el signo negativo, pero acá hay **dos** factores negativos y se cancelan entre sí.$it$,
   $it$Se sumaron los valores en vez de multiplicarlos. El resultado positivo sí es correcto para el signo.$it$,
   $it$Correcto. $4 \times 3 = 12$, y dos factores negativos dan producto positivo.$it$,
   null, $it$enteros/regla-de-signos-a-medias$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.84), 80,
   $it$¿Cuál es el resultado de $\dfrac{-6}{-2}$?$it$,
   $it$$-4$$it$,
   $it$$3$$it$,
   $it$$-3$$it$,
   $it$$4$$it$,
   $it$B$it$,
   $it$Ese es el resultado de $-6-(-2)$, o sea de restar en vez de dividir.$it$,
   $it$Correcto. Los dos signos negativos se cancelan al dividir, así que queda $\frac{6}{2} = 3$.$it$,
   $it$El valor está bien, el signo no. Al dividir, dos negativos se cancelan igual que al multiplicar.$it$,
   $it$Se juntan dos errores: restar en vez de dividir, y perder el signo por el camino.$it$,
   null, null, $it$enteros/regla-de-signos-a-medias$it$, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.76), 90,
   $it$En Putre la temperatura marcaba $-3\ ^\circ$C al amanecer y subió $8$ grados durante el día. ¿Qué temperatura marcó?$it$,
   $it$$5\ ^\circ$C$it$,
   $it$$-11\ ^\circ$C$it$,
   $it$$11\ ^\circ$C$it$,
   $it$$-5\ ^\circ$C$it$,
   $it$A$it$,
   $it$Correcto. Partiendo de $-3$ y subiendo $8$ se cruza el cero: $-3+8 = 5$.$it$,
   $it$Sumaste los dos valores y dejaste el signo negativo, pero la temperatura **subió**: tiene que quedar más arriba que $-3$, no más abajo.$it$,
   $it$Sumaste $3+8$ como si se partiera desde $3$ grados sobre cero. Los primeros $3$ grados se gastan solo en llegar al cero.$it$,
   $it$El valor absoluto está bien, pero el resultado quedó bajo cero. Subir $8$ desde $-3$ deja la temperatura sobre cero.$it$,
   null, $it$enteros/suma-los-valores-y-conserva-un-signo$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.68), 100,
   $it$Una persona tiene una deuda de $\$12.000$ y abona $\$5.000$. Si la deuda se representa con números negativos, ¿cuál es su saldo?$it$,
   $it$$-17.000$$it$,
   $it$$17.000$$it$,
   $it$$-7.000$$it$,
   $it$$7.000$$it$,
   $it$C$it$,
   $it$Sumaste el abono a la deuda. Pagar reduce lo que se debe: el saldo tiene que acercarse al cero, no alejarse.$it$,
   $it$Además de sumar el abono, quedó positivo. Un saldo positivo significaría que le deben a ella.$it$,
   $it$Correcto. $-12.000 + 5.000 = -7.000$: sigue debiendo, pero $\$5.000$ menos.$it$,
   $it$El valor está bien, el signo no. Todavía debe, así que el saldo sigue siendo negativo.$it$,
   $it$enteros/suma-los-valores-y-conserva-un-signo$it$, $it$enteros/suma-los-valores-y-conserva-un-signo$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.6), 110,
   $it$¿Cuál es el resultado de $-2 - (-5)$?$it$,
   $it$$-7$$it$,
   $it$$7$$it$,
   $it$$-3$$it$,
   $it$$3$$it$,
   $it$D$it$,
   $it$Restaste $5$ en vez de restar $-5$. Restar un negativo es sumar: la operación es $-2+5$.$it$,
   $it$El valor sale de sumar los dos números sin mirar que el primero es negativo.$it$,
   $it$El valor está bien, el signo no. Desde $-2$ avanzas $5$: cruzas el cero y quedas del lado positivo.$it$,
   $it$Correcto. $-2-(-5) = -2+5 = 3$.$it$,
   $it$enteros/restar-negativo-como-restar-positivo$it$, $it$enteros/suma-los-valores-y-conserva-un-signo$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.5), 120,
   $it$Un ascensor está en el piso $-3$ (tercer subterráneo) y sube $5$ pisos. ¿En qué piso queda?$it$,
   $it$$-8$$it$,
   $it$$2$$it$,
   $it$$8$$it$,
   $it$$-2$$it$,
   $it$B$it$,
   $it$El ascensor **sube**, así que el número de piso tiene que crecer. Bajar $5$ desde $-3$ daría $-8$.$it$,
   $it$Correcto. $-3+5 = 2$: pasa por el cero (la planta baja) y sigue dos pisos más arriba.$it$,
   $it$Sumaste $3+5$ como si se partiera del tercer piso hacia arriba. Los primeros $3$ pisos se gastan en llegar a la planta baja.$it$,
   $it$Quedó bajo tierra. Desde el tercer subterráneo, subir $5$ pisos alcanza para salir a la superficie.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.42), 130,
   $it$¿Cuál es el valor de $(-2)^3$?$it$,
   $it$$-8$$it$,
   $it$$8$$it$,
   $it$$-6$$it$,
   $it$$6$$it$,
   $it$A$it$,
   $it$Correcto. Son tres factores $(-2)$, y con un número **impar** de negativos el resultado queda negativo: $-8$.$it$,
   $it$El valor está bien. El signo depende de la paridad del exponente: con exponente $3$ quedan tres factores negativos, que no se cancelan de a pares.$it$,
   $it$Multiplicaste la base por el exponente. Una potencia es un producto repetido: $(-2)\times(-2)\times(-2)$.$it$,
   $it$Se juntan dos errores: multiplicar base por exponente, y perder el signo.$it$,
   null, $it$enteros/exponente-impar-borra-el-signo$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.34), 140,
   $it$¿Cuál es el resultado de $-5 + 3 - 8$?$it$,
   $it$$16$$it$,
   $it$$-6$$it$,
   $it$$-10$$it$,
   $it$$6$$it$,
   $it$C$it$,
   $it$Se sumaron los tres valores ignorando los signos. Solo el $3$ empuja hacia la derecha.$it$,
   $it$Acá el $8$ se sumó en vez de restarse en algún paso. Yendo por partes: $-5+3 = -2$, y $-2-8 = -10$.$it$,
   $it$Correcto. $-5+3 = -2$, y después $-2-8 = -10$.$it$,
   $it$El valor no corresponde a ninguna combinación correcta de los tres términos, y además quedó positivo pese a que dos de los tres empujan hacia la izquierda.$it$,
   $it$enteros/suma-los-valores-y-conserva-un-signo$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.26), 150,
   $it$¿Cuál es el **opuesto** de $-7$?$it$,
   $it$$-7$$it$,
   $it$$\dfrac{1}{7}$$it$,
   $it$$0$$it$,
   $it$$7$$it$,
   $it$D$it$,
   $it$Ese es el mismo número. El opuesto está a la misma distancia del cero pero del otro lado.$it$,
   $it$Ese es el **inverso multiplicativo**, que es otra cosa: al multiplicarlo da $1$. El opuesto es el que al sumarlo da $0$.$it$,
   $it$El cero es el resultado de sumar un número con su opuesto, no el opuesto en sí.$it$,
   $it$Correcto. $-7 + 7 = 0$, y ambos están a distancia $7$ del cero.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.18), 160,
   $it$¿Cuál es el resultado de $10 - 4 \times (-2)$?$it$,
   $it$$-12$$it$,
   $it$$18$$it$,
   $it$$12$$it$,
   $it$$2$$it$,
   $it$B$it$,
   $it$Se restó primero y se multiplicó después: $(10-4)\times(-2)$. La multiplicación va antes que la resta.$it$,
   $it$Correcto. Primero $4 \times (-2) = -8$, y después $10-(-8) = 10+8 = 18$.$it$,
   $it$Se resolvió de izquierda a derecha y además se perdió el signo del producto.$it$,
   $it$Se calculó $4\times(-2) = -8$ y luego se restó: $10-8$. Pero restar $-8$ es **sumar** $8$.$it$,
   $it$numeros/opera-de-izquierda-a-derecha$it$, null, $it$numeros/opera-de-izquierda-a-derecha$it$, $it$enteros/restar-negativo-como-restar-positivo$it$),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.1), 170,
   $it$¿Cuál es el resultado de $(-3) \times 2 - (-4)$?$it$,
   $it$$-2$$it$,
   $it$$-10$$it$,
   $it$$2$$it$,
   $it$$10$$it$,
   $it$A$it$,
   $it$Correcto. Primero $(-3)\times 2 = -6$, y después $-6-(-4) = -6+4 = -2$.$it$,
   $it$El $-4$ se restó en vez de sumarse: $-6-4$. Restar un negativo es sumar.$it$,
   $it$El valor está bien, el signo no. Partiendo de $-6$ y sumando $4$ todavía no se alcanza el cero.$it$,
   $it$El producto perdió su signo. $(-3)\times 2$ es negativo, no positivo.$it$,
   null, $it$enteros/restar-negativo-como-restar-positivo$it$, null, $it$enteros/pierde-el-signo-del-producto$it$),
  ($it$numeros$it$, $it$aritmetica/enteros$it$,
   (-1.0), 180,
   $it$En la madrugada un pueblo marcó $-8\ ^\circ$C y al mediodía $5\ ^\circ$C. ¿Cuántos grados subió la temperatura?$it$,
   $it$$3$$it$,
   $it$$-3$$it$,
   $it$$13$$it$,
   $it$$40$$it$,
   $it$C$it$,
   $it$Restaste los valores sin cruzar el cero: $8-5$. La temperatura tuvo que subir primero $8$ grados solo para llegar a $0$, y después $5$ más.$it$,
   $it$Además de contar solo un lado del cero, quedó negativo: la temperatura subió, así que la variación es positiva.$it$,
   $it$Correcto. $5 - (-8) = 5 + 8 = 13$ grados: $8$ para llegar al cero y $5$ más hasta el mediodía.$it$,
   $it$Multiplicaste los dos valores. Una variación de temperatura se obtiene restando, no multiplicando.$it$,
   $it$enteros/diferencia-sin-cruzar-el-cero$it$, $it$enteros/diferencia-sin-cruzar-el-cero$it$, null, null),

  -- ===========================================================================
  -- aritmetica/fracciones
  -- ===========================================================================
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.8), 10,
   $it$Una barra de chocolate se divide en $4$ partes iguales y se comen $3$. ¿Qué fracción de la barra se comió?$it$,
   $it$$\dfrac{4}{3}$$it$,
   $it$$\dfrac{3}{4}$$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$$\dfrac{3}{1}$$it$,
   $it$B$it$,
   $it$Está invertida: el total va abajo. Además una fracción mayor que $1$ significaría haber comido más de una barra entera.$it$,
   $it$Correcto. El total de partes ($4$) va en el denominador y las comidas ($3$) en el numerador.$it$,
   $it$Esa es la parte que **quedó**, no la que se comió.$it$,
   $it$El denominador debe indicar en cuántas partes se dividió la barra, que son $4$, no $1$.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.72), 20,
   $it$Simplifica $\dfrac{18}{24}$ hasta su forma irreducible.$it$,
   $it$$\dfrac{9}{12}$$it$,
   $it$$\dfrac{6}{8}$$it$,
   $it$$\dfrac{4}{3}$$it$,
   $it$$\dfrac{3}{4}$$it$,
   $it$D$it$,
   $it$Es equivalente y correcta como fracción, pero no es irreducible: $9$ y $12$ todavía comparten el factor $3$. Dividiste por $2$ cuando el máximo común divisor de $18$ y $24$ es $6$.$it$,
   $it$Mismo caso, dividiendo por $3$: $6$ y $8$ siguen compartiendo el factor $2$. Simplificar hasta el final significa que numerador y denominador ya no tengan ningún divisor común.$it$,
   $it$La fracción quedó invertida. Además $\dfrac{4}{3}$ es mayor que $1$ y $\dfrac{18}{24}$ es menor.$it$,
   $it$Correcto. Dividiendo por $6$ arriba y abajo: $\dfrac{18}{24} = \dfrac{3}{4}$, que ya no se puede reducir.$it$,
   $it$fracciones/simplificacion-incompleta$it$, $it$fracciones/simplificacion-incompleta$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.64), 30,
   $it$¿Cuál de estas fracciones es equivalente a $\dfrac{1}{2}$?$it$,
   $it$$\dfrac{3}{6}$$it$,
   $it$$\dfrac{2}{3}$$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$$\dfrac{2}{1}$$it$,
   $it$A$it$,
   $it$Correcto. Multiplicando arriba y abajo por $3$: $\frac{1}{2} = \frac{3}{6}$.$it$,
   $it$Se sumó $1$ arriba y $1$ abajo. Eso no conserva el valor: para obtener una equivalente hay que **multiplicar** los dos términos por el mismo número.$it$,
   $it$Se duplicó solo el denominador. Al no tocar el numerador, la fracción quedó valiendo la mitad.$it$,
   $it$Es la fracción invertida, y vale $2$: cuatro veces más que $\frac{1}{2}$.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.56), 40,
   $it$¿Cuál es mayor, $\dfrac{2}{3}$ o $\dfrac{3}{4}$?$it$,
   $it$$\dfrac{2}{3}$, porque tiene el denominador más chico$it$,
   $it$Son iguales, porque en las dos falta una parte para el entero$it$,
   $it$$\dfrac{3}{4}$$it$,
   $it$$\dfrac{2}{3}$, porque $2$ y $3$ son números consecutivos$it$,
   $it$C$it$,
   $it$El denominador más chico hace **más grande** cada parte, pero acá también cambia el numerador. Con denominador común: $\frac{8}{12}$ contra $\frac{9}{12}$.$it$,
   $it$A las dos les falta una parte, pero de distinto tamaño: a $\frac{2}{3}$ le falta un tercio y a $\frac{3}{4}$ un cuarto, que es menos. Por eso $\frac{3}{4}$ está más cerca del entero.$it$,
   $it$Correcto. Igualando denominadores: $\frac{2}{3} = \frac{8}{12}$ y $\frac{3}{4} = \frac{9}{12}$.$it$,
   $it$Que los números sean consecutivos no dice nada sobre el tamaño: $\frac{3}{4}$ también los tiene.$it$,
   $it$fracciones/compara-mirando-un-solo-termino$it$, null, null, $it$fracciones/compara-mirando-un-solo-termino$it$),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.48), 50,
   $it$¿Cuál es el resultado de $\dfrac{1}{4} + \dfrac{1}{4}$?$it$,
   $it$$\dfrac{2}{8}$$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$$\dfrac{1}{8}$$it$,
   $it$$\dfrac{1}{16}$$it$,
   $it$B$it$,
   $it$Sumaste también los denominadores. Cuando ya son iguales, el denominador se mantiene: son cuartos en los dos casos, así que el resultado son cuartos.$it$,
   $it$Correcto. $\frac{1}{4}+\frac{1}{4} = \frac{2}{4} = \frac{1}{2}$.$it$,
   $it$Ese es el producto de las dos fracciones, no la suma.$it$,
   $it$Se multiplicaron los denominadores y se dejó el numerador en $1$. La suma de dos cantidades iguales tiene que dar el doble, no menos.$it$,
   $it$fracciones/suma-numeradores-y-denominadores$it$, null, $it$fracciones/multiplica-en-vez-de-dividir$it$, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.4), 60,
   $it$¿Cuál es el resultado de $\dfrac{1}{2} + \dfrac{1}{3}$?$it$,
   $it$$\dfrac{2}{5}$$it$,
   $it$$\dfrac{1}{6}$$it$,
   $it$$\dfrac{3}{5}$$it$,
   $it$$\dfrac{5}{6}$$it$,
   $it$D$it$,
   $it$Sumaste numeradores por un lado y denominadores por el otro. No puede ser: $\frac{1}{2}$ ya vale más que $\frac{2}{5}$, y una suma de positivos no achica.$it$,
   $it$Ese es el producto $\frac{1}{2}\times\frac{1}{3}$. Para sumar hace falta primero un denominador común.$it$,
   $it$El denominador salió de sumar los de abajo y el numerador de otra parte: no corresponden a la misma operación.$it$,
   $it$Correcto. Con denominador común $6$: $\frac{3}{6}+\frac{2}{6} = \frac{5}{6}$.$it$,
   $it$fracciones/suma-numeradores-y-denominadores$it$, $it$fracciones/multiplica-en-vez-de-dividir$it$, $it$fracciones/suma-numeradores-y-denominadores$it$, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.32), 70,
   $it$¿Cuál es el resultado de $\dfrac{3}{5} - \dfrac{1}{5}$?$it$,
   $it$$\dfrac{2}{5}$$it$,
   $it$$\dfrac{2}{0}$$it$,
   $it$$\dfrac{4}{5}$$it$,
   $it$$\dfrac{2}{10}$$it$,
   $it$A$it$,
   $it$Correcto. Con el mismo denominador se restan solo los numeradores: $\frac{3-1}{5} = \frac{2}{5}$.$it$,
   $it$Se restaron también los denominadores, y quedó una división por cero, que no existe. El denominador dice el tamaño de las partes y no cambia al restar.$it$,
   $it$Se sumaron los numeradores en vez de restarlos.$it$,
   $it$Se sumaron los denominadores. Al tener el mismo, se conserva: sigue habiendo quintos.$it$,
   null, $it$fracciones/suma-numeradores-y-denominadores$it$, null, $it$fracciones/suma-numeradores-y-denominadores$it$),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.24), 80,
   $it$¿Cuál es el resultado de $\dfrac{2}{3} \times \dfrac{3}{4}$?$it$,
   $it$$\dfrac{5}{7}$$it$,
   $it$$\dfrac{8}{9}$$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$$\dfrac{6}{7}$$it$,
   $it$C$it$,
   $it$Se sumaron numeradores y denominadores. En la multiplicación sí se opera término a término, pero **multiplicando**, no sumando.$it$,
   $it$Se multiplicó en cruz. Para multiplicar fracciones va numerador con numerador y denominador con denominador, en línea recta.$it$,
   $it$Correcto. $\frac{2\times 3}{3\times 4} = \frac{6}{12} = \frac{1}{2}$.$it$,
   $it$El numerador $6$ está bien, pero el denominador salió de sumar $3+4$ en vez de multiplicarlos.$it$,
   $it$fracciones/suma-numeradores-y-denominadores$it$, null, null, $it$fracciones/suma-numeradores-y-denominadores$it$),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.16), 90,
   $it$¿Cuál es el resultado de $\dfrac{3}{4} \div \dfrac{1}{2}$?$it$,
   $it$$\dfrac{3}{2}$$it$,
   $it$$\dfrac{3}{8}$$it$,
   $it$$\dfrac{2}{3}$$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$A$it$,
   $it$Correcto. $\frac{3}{4}\times\frac{2}{1} = \frac{6}{4} = \frac{3}{2}$. Dividir por algo menor que $1$ agranda el resultado.$it$,
   $it$Multiplicaste en vez de dividir. Dividir por $\frac{1}{2}$ es multiplicar por $2$, así que el resultado tiene que ser **mayor** que $\frac{3}{4}$.$it$,
   $it$Invertiste la fracción equivocada: la que se da vuelta es la segunda. Quedaría $\frac{3}{4}\times\frac{2}{1}$.$it$,
   $it$Restaste las fracciones en vez de dividirlas.$it$,
   null, $it$fracciones/multiplica-en-vez-de-dividir$it$, $it$fracciones/invierte-el-dividendo-al-dividir$it$, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.08), 100,
   $it$En un curso de $30$ estudiantes, $\dfrac{2}{5}$ juega básquetbol. ¿Cuántos son?$it$,
   $it$$75$$it$,
   $it$$12$$it$,
   $it$$6$$it$,
   $it$$60$$it$,
   $it$B$it$,
   $it$Dividiste por $\frac{2}{5}$ en vez de multiplicar. Una parte del curso no puede superar al curso entero.$it$,
   $it$Correcto. $30 \times \frac{2}{5} = 12$.$it$,
   $it$Eso es $\frac{1}{5}$ de $30$. Falta multiplicar por el numerador, que es $2$.$it$,
   $it$Se multiplicó por el numerador y se olvidó el denominador. Dividir en cinco partes también es parte de la operación.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-1.0), 110,
   $it$¿Qué fracción irreducible equivale a $0{,}25$?$it$,
   $it$$\dfrac{1}{25}$$it$,
   $it$$\dfrac{25}{10}$$it$,
   $it$$\dfrac{25}{1000}$$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$D$it$,
   $it$Usaste las cifras como denominador. La posición manda: $0{,}25$ son $25$ **centésimas**, o sea $\frac{25}{100}$.$it$,
   $it$El denominador corresponde a las décimas, no a las centésimas. Además $\frac{25}{10}$ vale $2{,}5$, diez veces más.$it$,
   $it$Ese denominador es de milésimas. $0{,}25$ tiene dos cifras decimales, así que el denominador es $100$.$it$,
   $it$Correcto. $0{,}25 = \frac{25}{100}$, y dividiendo por $25$ arriba y abajo queda $\frac{1}{4}$.$it$,
   $it$fracciones/decimal-a-fraccion-por-las-cifras$it$, $it$fracciones/decimal-a-fraccion-por-las-cifras$it$, $it$fracciones/decimal-a-fraccion-por-las-cifras$it$, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-0.92), 120,
   $it$¿Cómo se escribe $\dfrac{5}{4}$ como número mixto?$it$,
   $it$$5\dfrac{1}{4}$$it$,
   $it$$4\dfrac{1}{5}$$it$,
   $it$$1\dfrac{1}{4}$$it$,
   $it$$\dfrac{9}{4}$$it$,
   $it$C$it$,
   $it$Tomaste el numerador como parte entera. Hay que dividir: $5 \div 4$ da $1$ entero y sobra $1$.$it$,
   $it$Se usó el denominador como parte entera y el numerador como nuevo denominador. La parte entera sale de la división.$it$,
   $it$Correcto. $5 \div 4 = 1$ con resto $1$, así que $\frac{5}{4} = 1\frac{1}{4}$.$it$,
   $it$Ese es el resultado de sumarle un entero de más: $\frac{9}{4}$ equivale a $2\frac{1}{4}$.$it$,
   $it$fracciones/mixto-pega-los-numeros$it$, $it$fracciones/mixto-pega-los-numeros$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-0.84), 130,
   $it$¿Cuál es el resultado de $\dfrac{3}{4} - \dfrac{1}{6}$?$it$,
   $it$$\dfrac{7}{12}$$it$,
   $it$$\dfrac{2}{2}$$it$,
   $it$$\dfrac{2}{10}$$it$,
   $it$$\dfrac{11}{12}$$it$,
   $it$A$it$,
   $it$Correcto. Con denominador común $12$: $\frac{9}{12}-\frac{2}{12} = \frac{7}{12}$.$it$,
   $it$Se restaron numeradores y denominadores por separado. Eso da $1$, y $\frac{3}{4}$ menos algo positivo no puede llegar a un entero.$it$,
   $it$Mismo error de restar los dos términos, esta vez sumando los de abajo. El denominador común de $4$ y $6$ es $12$.$it$,
   $it$Se sumaron las fracciones en vez de restarlas: $\frac{9}{12}+\frac{2}{12}$.$it$,
   null, $it$fracciones/suma-numeradores-y-denominadores$it$, $it$fracciones/suma-numeradores-y-denominadores$it$, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-0.76), 140,
   $it$¿Cuál es mayor, $\dfrac{5}{8}$ o $0{,}6$?$it$,
   $it$$0{,}6$, porque $6$ es mayor que $5$$it$,
   $it$$\dfrac{5}{8}$$it$,
   $it$Son iguales$it$,
   $it$$0{,}6$, porque un decimal siempre es mayor que una fracción$it$,
   $it$B$it$,
   $it$Comparaste el numerador con la cifra decimal, que no son la misma unidad. Hay que llevar los dos a la misma forma: $\frac{5}{8} = 0{,}625$.$it$,
   $it$Correcto. $\frac{5}{8} = 0{,}625$, que es mayor que $0{,}6$.$it$,
   $it$Están cerca, pero no son iguales: $\frac{5}{8}$ da exactamente $0{,}625$, dos centésimas y media más.$it$,
   $it$Un decimal y una fracción son dos formas de escribir un número: cualquiera de las dos puede ser mayor. $\frac{3}{4}$ es mayor que $0{,}6$ y $\frac{1}{4}$ es menor.$it$,
   $it$fracciones/compara-mirando-un-solo-termino$it$, null, null, $it$fracciones/compara-mirando-un-solo-termino$it$),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-0.68), 150,
   $it$¿Cuál es el resultado de $2\dfrac{1}{3} + \dfrac{1}{2}$?$it$,
   $it$$\dfrac{3}{5}$$it$,
   $it$$2\dfrac{2}{5}$$it$,
   $it$$\dfrac{4}{6}$$it$,
   $it$$\dfrac{17}{6}$$it$,
   $it$D$it$,
   $it$Se sumaron numeradores y denominadores y se perdieron los $2$ enteros por el camino.$it$,
   $it$Los enteros se conservaron bien, pero las fracciones se sumaron numerador con numerador y denominador con denominador. Con denominador común: $\frac{2}{6}+\frac{3}{6} = \frac{5}{6}$.$it$,
   $it$Se sumaron los dos términos de cada fracción y desaparecieron los enteros. El resultado tiene que ser mayor que $2$.$it$,
   $it$Correcto. $2\frac{1}{3} = \frac{7}{3} = \frac{14}{6}$, y $\frac{14}{6}+\frac{3}{6} = \frac{17}{6}$.$it$,
   $it$fracciones/suma-numeradores-y-denominadores$it$, $it$fracciones/suma-numeradores-y-denominadores$it$, $it$fracciones/suma-numeradores-y-denominadores$it$, null),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-0.6), 160,
   $it$Queda $\dfrac{3}{4}$ de una pizza y una persona se come $\dfrac{1}{3}$ de lo que queda. ¿Qué fracción de la pizza **entera** se comió?$it$,
   $it$$\dfrac{1}{3}$$it$,
   $it$$\dfrac{4}{7}$$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$$\dfrac{9}{4}$$it$,
   $it$C$it$,
   $it$Ese es un tercio de la pizza entera, pero se comió un tercio de lo que **quedaba**, que es menos.$it$,
   $it$Se sumaron las dos fracciones término a término. La operación es «un tercio **de** tres cuartos», que es un producto.$it$,
   $it$Correcto. $\frac{1}{3}\times\frac{3}{4} = \frac{3}{12} = \frac{1}{4}$ de la pizza entera.$it$,
   $it$Se dividió en vez de multiplicar, y el resultado da más de una pizza entera, que es imposible.$it$,
   null, $it$fracciones/suma-numeradores-y-denominadores$it$, null, $it$fracciones/invierte-el-dividendo-al-dividir$it$),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-0.52), 170,
   $it$Ordena de menor a mayor: $\dfrac{1}{2}$, $\dfrac{1}{5}$ y $\dfrac{1}{3}$.$it$,
   $it$$\dfrac{1}{5} < \dfrac{1}{3} < \dfrac{1}{2}$$it$,
   $it$$\dfrac{1}{2} < \dfrac{1}{3} < \dfrac{1}{5}$$it$,
   $it$$\dfrac{1}{3} < \dfrac{1}{2} < \dfrac{1}{5}$$it$,
   $it$Las tres son iguales, porque todas tienen numerador $1$$it$,
   $it$A$it$,
   $it$Correcto. Con el mismo numerador, mientras mayor es el denominador más chicas son las partes: $\frac{1}{5}$ es la menor.$it$,
   $it$Ordenaste por el tamaño del denominador. Dividir algo en $5$ partes da pedazos **más chicos** que dividirlo en $2$.$it$,
   $it$Se mezclaron los dos criterios: $\frac{1}{3}$ quedó bien ubicado respecto de $\frac{1}{2}$, pero $\frac{1}{5}$ terminó como la mayor.$it$,
   $it$El numerador igual solo dice que se toma una parte en cada caso; el tamaño de esa parte lo fija el denominador.$it$,
   null, $it$fracciones/denominador-mayor-fraccion-mayor$it$, $it$fracciones/denominador-mayor-fraccion-mayor$it$, $it$fracciones/compara-mirando-un-solo-termino$it$),
  ($it$numeros$it$, $it$aritmetica/fracciones$it$,
   (-0.4), 180,
   $it$¿Cuántos vasos de $\dfrac{1}{8}$ de litro se pueden llenar con $\dfrac{3}{4}$ de litro de jugo?$it$,
   $it$$\dfrac{3}{32}$$it$,
   $it$$6$$it$,
   $it$$\dfrac{1}{6}$$it$,
   $it$$3$$it$,
   $it$B$it$,
   $it$Multiplicaste las dos fracciones. Acá se pregunta cuántas veces cabe una cantidad en otra, que es una división.$it$,
   $it$Correcto. $\frac{3}{4} \div \frac{1}{8} = \frac{3}{4}\times\frac{8}{1} = 6$ vasos.$it$,
   $it$Se invirtió la fracción equivocada: la que se da vuelta al dividir es la segunda, no la primera.$it$,
   $it$Ese es el numerador del jugo disponible. La cantidad de vasos depende también de cuánto entra en cada uno.$it$,
   $it$fracciones/multiplica-en-vez-de-dividir$it$, null, $it$fracciones/invierte-el-dividendo-al-dividir$it$, null),

  -- ===========================================================================
  -- aritmetica/potencias
  -- ===========================================================================
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-1.0), 10,
   $it$¿Cuál es el valor de $2^3$?$it$,
   $it$$6$$it$,
   $it$$9$$it$,
   $it$$8$$it$,
   $it$$5$$it$,
   $it$C$it$,
   $it$Multiplicaste la base por el exponente. La potencia indica cuántas veces se repite la base como factor: $2\times 2\times 2$.$it$,
   $it$Ese es $3^2$: la base y el exponente están intercambiados. En $2^3$ el $2$ es el que se repite.$it$,
   $it$Correcto. $2^3 = 2\times 2\times 2 = 8$.$it$,
   $it$Se sumaron la base y el exponente. El exponente cuenta factores, no se suma.$it$,
   $it$potencias/multiplica-base-por-exponente$it$, null, null, $it$potencias/multiplica-base-por-exponente$it$),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-0.89), 20,
   $it$¿Qué operación representa $3^4$?$it$,
   $it$$3 \times 4$$it$,
   $it$$3 \times 3 \times 3 \times 3$$it$,
   $it$$4 \times 4 \times 4$$it$,
   $it$$3 + 3 + 3 + 3$$it$,
   $it$B$it$,
   $it$Esa es una multiplicación simple. El exponente no multiplica a la base: indica cuántas veces la base se repite como factor.$it$,
   $it$Correcto. El $4$ dice cuántas veces aparece el $3$ multiplicándose.$it$,
   $it$La base y el exponente están intercambiados, y además hay tres factores en vez de cuatro. La base es la que se repite.$it$,
   $it$Eso es una suma repetida, que corresponde a $3\times 4$. La potencia es un **producto** repetido.$it$,
   $it$potencias/multiplica-base-por-exponente$it$, null, null, $it$potencias/multiplica-base-por-exponente$it$),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-0.79), 30,
   $it$¿Cuál es el valor de $2^3 \times 2^2$?$it$,
   $it$$4^5$$it$,
   $it$$2^6$$it$,
   $it$$4^6$$it$,
   $it$$32$$it$,
   $it$D$it$,
   $it$Multiplicaste también las bases. Cuando la base es la misma, se conserva y solo se suman los exponentes.$it$,
   $it$Multiplicaste los exponentes. Esa es la regla de $(a^m)^n$; acá, al multiplicar potencias de igual base, los exponentes se **suman**.$it$,
   $it$Acá se juntan los dos errores: se multiplicaron las bases y también los exponentes.$it$,
   $it$Correcto. $2^3 \times 2^2 = 2^{3+2} = 2^5 = 32$.$it$,
   $it$potencias/opera-las-bases-al-multiplicar$it$, $it$potencias/multiplica-exponentes-al-multiplicar$it$, $it$potencias/opera-las-bases-al-multiplicar$it$, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-0.68), 40,
   $it$¿Cuál es el valor de $\left(2^3\right)^2$?$it$,
   $it$$64$$it$,
   $it$$32$$it$,
   $it$$12$$it$,
   $it$$16$$it$,
   $it$A$it$,
   $it$Correcto. $(2^3)^2 = 2^{3\times 2} = 2^6 = 64$. También se ve así: $8^2 = 64$.$it$,
   $it$Sumaste los exponentes. Esa es la regla de multiplicar potencias de igual base; en una potencia de potencia los exponentes se **multiplican**.$it$,
   $it$Se multiplicaron base y exponentes entre sí. La base se mantiene: lo que se combina son los exponentes.$it$,
   $it$Ese es $2^4$. Acá el exponente resultante es $3\times 2 = 6$, no $4$.$it$,
   null, $it$potencias/suma-exponentes-en-potencia-de-potencia$it$, $it$potencias/multiplica-base-por-exponente$it$, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-0.57), 50,
   $it$¿Cuál es el valor de $\dfrac{2^5}{2^2}$?$it$,
   $it$$2^{10}$$it$,
   $it$$1^3$$it$,
   $it$$8$$it$,
   $it$$2^{2{,}5}$$it$,
   $it$C$it$,
   $it$Sumaste los exponentes, que es la regla del producto. Al dividir potencias de igual base, se **restan**.$it$,
   $it$Se dividieron también las bases. La base se conserva: lo que se opera es el exponente.$it$,
   $it$Correcto. $2^{5-2} = 2^3 = 8$.$it$,
   $it$Se dividieron los exponentes. La división de potencias de igual base resta exponentes, no los divide.$it$,
   null, $it$potencias/opera-las-bases-al-multiplicar$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-0.47), 60,
   $it$¿Cuál es el valor de $5^0$?$it$,
   $it$$0$$it$,
   $it$$1$$it$,
   $it$$5$$it$,
   $it$No está definido$it$,
   $it$B$it$,
   $it$El exponente no multiplica: no es «cero veces cinco». Mirando $\frac{5^2}{5^2} = 5^0$, y una cantidad dividida por sí misma da $1$.$it$,
   $it$Correcto. Cualquier número distinto de cero elevado a $0$ da $1$, porque $a^n \div a^n = a^0$ y también vale $1$.$it$,
   $it$Ese es $5^1$. El exponente $0$ es un caso distinto.$it$,
   $it$Sí está definido para toda base distinta de cero. El único caso discutido es $0^0$.$it$,
   $it$potencias/exponente-cero-da-cero$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-0.36), 70,
   $it$¿Cuál es el valor de $2^{-1}$?$it$,
   $it$$-2$$it$,
   $it$$0$$it$,
   $it$$-\dfrac{1}{2}$$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$D$it$,
   $it$El exponente negativo no cambia el signo del resultado: indica que hay que tomar el recíproco. $2^{-1} = \frac{1}{2}$.$it$,
   $it$Un exponente negativo nunca anula la potencia. La base sigue estando: lo que cambia es que pasa al denominador.$it$,
   $it$El valor está bien, el signo sobra. El menos del exponente ya se usó para invertir la fracción; no se aplica dos veces.$it$,
   $it$Correcto. $a^{-n} = \frac{1}{a^n}$, así que $2^{-1} = \frac{1}{2}$.$it$,
   $it$potencias/exponente-negativo-da-resultado-negativo$it$, null, $it$potencias/exponente-negativo-da-resultado-negativo$it$, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-0.25), 80,
   $it$¿Cuál es el valor de $\sqrt{49}$?$it$,
   $it$$7$$it$,
   $it$$24{,}5$$it$,
   $it$$98$$it$,
   $it$$2.401$$it$,
   $it$A$it$,
   $it$Correcto. $7 \times 7 = 49$, así que $\sqrt{49} = 7$.$it$,
   $it$Dividiste por $2$. La raíz cuadrada no divide por el índice: busca el número que multiplicado por sí mismo da $49$.$it$,
   $it$Multiplicaste por $2$. La raíz es la operación **inversa** de elevar al cuadrado.$it$,
   $it$Ese es $49^2$. La raíz hace lo contrario: baja, no sube.$it$,
   null, $it$potencias/raiz-como-division-por-el-indice$it$, $it$potencias/raiz-como-division-por-el-indice$it$, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-0.15), 90,
   $it$¿Cuál es el valor de $\sqrt{\dfrac{16}{25}}$?$it$,
   $it$$\dfrac{16}{5}$$it$,
   $it$$\dfrac{8}{12{,}5}$$it$,
   $it$$\dfrac{4}{5}$$it$,
   $it$$\dfrac{4}{25}$$it$,
   $it$C$it$,
   $it$Sacaste la raíz solo del denominador. La raíz de un cociente actúa sobre los dos términos.$it$,
   $it$Dividiste por $2$ arriba y abajo. Eso es simplificar, no calcular una raíz.$it$,
   $it$Correcto. $\sqrt{\frac{16}{25}} = \frac{\sqrt{16}}{\sqrt{25}} = \frac{4}{5}$.$it$,
   $it$Sacaste la raíz solo del numerador. Faltó aplicarla también abajo: $\sqrt{25} = 5$.$it$,
   null, $it$potencias/raiz-como-division-por-el-indice$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (-0.04), 100,
   $it$¿Cuál es el valor de $(-3)^2$?$it$,
   $it$$-6$$it$,
   $it$$9$$it$,
   $it$$-9$$it$,
   $it$$6$$it$,
   $it$B$it$,
   $it$Se multiplicó base por exponente y se arrastró el signo. La potencia es $(-3)\times(-3)$.$it$,
   $it$Correcto. $(-3)\times(-3) = 9$: dos factores negativos dan producto positivo.$it$,
   $it$Ese es el valor de $-3^2$, sin paréntesis, donde el signo queda **afuera** de la potencia. Con paréntesis el signo también se eleva.$it$,
   $it$Se multiplicó base por exponente. El exponente cuenta factores, no multiplica.$it$,
   $it$potencias/multiplica-base-por-exponente$it$, null, $it$potencias/signo-dentro-o-fuera-del-parentesis$it$, $it$potencias/multiplica-base-por-exponente$it$),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (0.07), 110,
   $it$¿Cuál es el valor de $-3^2$ (sin paréntesis en la base)?$it$,
   $it$$9$$it$,
   $it$$6$$it$,
   $it$$-6$$it$,
   $it$$-9$$it$,
   $it$D$it$,
   $it$Ese es $(-3)^2$, con el signo dentro de la potencia. Sin paréntesis, el exponente afecta solo al $3$ y el menos queda multiplicando afuera.$it$,
   $it$Se multiplicó base por exponente y se perdió el signo.$it$,
   $it$Se multiplicó base por exponente. El signo quedó bien, pero la potencia no se calculó.$it$,
   $it$Correcto. Sin paréntesis se lee $-(3^2) = -9$: primero la potencia, después el signo.$it$,
   $it$potencias/signo-dentro-o-fuera-del-parentesis$it$, $it$potencias/multiplica-base-por-exponente$it$, $it$potencias/multiplica-base-por-exponente$it$, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (0.17), 120,
   $it$¿Cómo se escribe $4.500$ en notación científica?$it$,
   $it$$4{,}5 \times 10^3$$it$,
   $it$$45 \times 10^2$$it$,
   $it$$4{,}5 \times 10^4$$it$,
   $it$$0{,}45 \times 10^4$$it$,
   $it$A$it$,
   $it$Correcto. La notación científica pide un solo dígito distinto de cero antes de la coma, y la coma se corrió tres lugares: $4{,}5 \times 10^3$.$it$,
   $it$El valor es correcto, pero no está en notación científica: la parte decimal debe quedar entre $1$ y $10$, y $45$ se pasa.$it$,
   $it$El exponente está corrido en uno: $4{,}5 \times 10^4$ vale $45.000$. Cuenta los lugares que se movió la coma: son tres.$it$,
   $it$El valor también es correcto, pero $0{,}45$ es menor que $1$: la notación científica exige que la parte decimal esté entre $1$ y $10$.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (0.28), 130,
   $it$¿Cuál es el valor de $3^2 \times 3^{-1}$?$it$,
   $it$$3^{-2}$$it$,
   $it$$9$$it$,
   $it$$3$$it$,
   $it$$-3$$it$,
   $it$C$it$,
   $it$Multiplicaste los exponentes. Al multiplicar potencias de igual base se suman: $2 + (-1) = 1$.$it$,
   $it$Se ignoró el segundo factor. $3^{-1}$ vale $\frac{1}{3}$, así que divide el resultado por $3$.$it$,
   $it$Correcto. $3^{2+(-1)} = 3^1 = 3$.$it$,
   $it$El exponente negativo no vuelve negativo el resultado: indica recíproco. Todos los factores acá son positivos.$it$,
   $it$potencias/multiplica-exponentes-al-multiplicar$it$, null, null, $it$potencias/exponente-negativo-da-resultado-negativo$it$),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (0.39), 140,
   $it$¿Cuál es el valor de $\sqrt{8} \times \sqrt{2}$?$it$,
   $it$$\sqrt{10}$$it$,
   $it$$4$$it$,
   $it$$16$$it$,
   $it$$2\sqrt{2}$$it$,
   $it$B$it$,
   $it$Sumaste lo de adentro. Al multiplicar raíces del mismo índice, lo de adentro se **multiplica**: $\sqrt{8}\times\sqrt{2} = \sqrt{16}$.$it$,
   $it$Correcto. $\sqrt{8}\times\sqrt{2} = \sqrt{16} = 4$.$it$,
   $it$Ese es el valor de adentro de la raíz. Falta el último paso: sacar la raíz de $16$.$it$,
   $it$Ese es el valor de $\sqrt{8}$ simplificado, sin haber multiplicado todavía por $\sqrt{2}$.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (0.49), 150,
   $it$¿Cuál es el valor de $\left(\dfrac{2}{3}\right)^2$?$it$,
   $it$$\dfrac{2}{9}$$it$,
   $it$$\dfrac{4}{3}$$it$,
   $it$$\dfrac{4}{6}$$it$,
   $it$$\dfrac{4}{9}$$it$,
   $it$D$it$,
   $it$Elevaste solo el denominador. El exponente de una fracción se aplica a los dos términos.$it$,
   $it$Elevaste solo el numerador. Falta hacer lo mismo abajo: $3^2 = 9$.$it$,
   $it$El numerador está elevado y el denominador multiplicado por $2$. Al denominador también hay que elevarlo.$it$,
   $it$Correcto. $\left(\frac{2}{3}\right)^2 = \frac{2^2}{3^2} = \frac{4}{9}$.$it$,
   null, null, $it$potencias/multiplica-base-por-exponente$it$, null),
  ($it$numeros$it$, $it$aritmetica/potencias$it$,
   (0.6), 160,
   $it$¿Cuál es el valor de $2^{-2}$?$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$$-4$$it$,
   $it$$-\dfrac{1}{4}$$it$,
   $it$$4$$it$,
   $it$A$it$,
   $it$Correcto. $2^{-2} = \frac{1}{2^2} = \frac{1}{4}$.$it$,
   $it$El exponente negativo no cambia el signo del resultado: manda la potencia al denominador.$it$,
   $it$El valor está bien y el signo sobra: el menos del exponente ya se usó al invertir. No se aplica dos veces.$it$,
   $it$Ese es $2^2$. El signo del exponente sí importa: lo lleva al denominador.$it$,
   null, $it$potencias/exponente-negativo-da-resultado-negativo$it$, $it$potencias/exponente-negativo-da-resultado-negativo$it$, null),

  -- ===========================================================================
  -- aritmetica/proporciones
  -- ===========================================================================
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (-0.2), 10,
   $it$En un taller hay $12$ bicicletas y $8$ scooters. ¿Cuál es la razón entre bicicletas y scooters, en su forma más simple?$it$,
   $it$$12 : 8$$it$,
   $it$$3 : 2$$it$,
   $it$$2 : 3$$it$,
   $it$$4 : 1$$it$,
   $it$B$it$,
   $it$Esa es la razón correcta, pero sin simplificar: los dos números se pueden dividir por $4$.$it$,
   $it$Correcto. Dividiendo ambos por $4$: $12:8 = 3:2$.$it$,
   $it$La razón está invertida. El enunciado pide bicicletas respecto de scooters, y hay más bicicletas, así que el primer número debe ser mayor.$it$,
   $it$Se restaron los términos en vez de dividirlos. Una razón compara por cociente, no por diferencia.$it$,
   $it$proporciones/razon-sin-simplificar$it$, null, null, $it$proporciones/razona-por-diferencias$it$),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (-0.08), 20,
   $it$Si $3$ kg de manzanas cuestan $\$4.500$, ¿cuánto cuestan $5$ kg al mismo precio?$it$,
   $it$$\$7.500$$it$,
   $it$$\$6.500$$it$,
   $it$$\$2.700$$it$,
   $it$$\$9.000$$it$,
   $it$A$it$,
   $it$Correcto. Cada kilo cuesta $\$1.500$, así que $5$ kilos cuestan $\$7.500$.$it$,
   $it$Se sumaron $\$2.000$ porque hay $2$ kilos más, pero el precio de un kilo es $\$1.500$, no $\$1.000$. Conviene sacar primero el valor unitario.$it$,
   $it$Se trató la relación como inversa: más kilos, menos plata. A mayor cantidad, mayor precio.$it$,
   $it$Se duplicó el precio de los $3$ kg. Eso correspondería a $6$ kilos, no a $5$.$it$,
   null, $it$proporciones/razona-por-diferencias$it$, $it$proporciones/aplica-inversa-donde-es-directa$it$, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (0.04), 30,
   $it$Si $\dfrac{2}{3} = \dfrac{x}{12}$, ¿cuánto vale $x$?$it$,
   $it$$18$$it$,
   $it$$4$$it$,
   $it$$11$$it$,
   $it$$8$$it$,
   $it$D$it$,
   $it$Se multiplicó en cruz al revés: $\frac{3 \times 12}{2}$. La incógnita está arriba, así que se despeja como $x = \frac{2 \times 12}{3}$.$it$,
   $it$Se dividió $12$ por $3$ y se olvidó multiplicar por $2$. Ese es el valor de $\frac{1}{3}$ de $12$.$it$,
   $it$Se razonó por diferencias: de $3$ a $12$ hay $9$, y se le sumaron $9$ al $2$. La proporción se resuelve multiplicando, no sumando.$it$,
   $it$Correcto. $x = \frac{2 \times 12}{3} = 8$.$it$,
   null, null, $it$proporciones/razona-por-diferencias$it$, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (0.16), 40,
   $it$En un plano a escala $1:100$, un muro mide $3$ cm. ¿Cuánto mide en la realidad?$it$,
   $it$$0{,}03$ cm$it$,
   $it$$30$ cm$it$,
   $it$$3$ m$it$,
   $it$$300$ m$it$,
   $it$C$it$,
   $it$Se dividió por la escala. La escala $1:100$ significa que la realidad es $100$ veces **mayor** que el plano.$it$,
   $it$Se multiplicó por $10$ en vez de por $100$. El resultado es $3 \times 100 = 300$ cm.$it$,
   $it$Correcto. $3 \times 100 = 300$ cm, o sea $3$ metros.$it$,
   $it$El número está bien pero la unidad no: son $300$ **centímetros**, que equivalen a $3$ metros. Un muro de $300$ m no es un muro.$it$,
   $it$proporciones/escala-en-el-sentido-contrario$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (0.28), 50,
   $it$Un vehículo recorre $120$ km en $2$ horas a rapidez constante. ¿Cuál es su rapidez?$it$,
   $it$$60$ km/h$it$,
   $it$$240$ km/h$it$,
   $it$$122$ km/h$it$,
   $it$$2$ km/h$it$,
   $it$A$it$,
   $it$Correcto. La rapidez es distancia dividida por tiempo: $120 \div 2 = 60$ km/h.$it$,
   $it$Se multiplicó por el tiempo en vez de dividir. Más tiempo para la misma distancia significa **menos** rapidez.$it$,
   $it$Se sumaron las dos cantidades, que además están en unidades distintas. Kilómetros y horas no se suman.$it$,
   $it$Ese es el tiempo, no la rapidez. La rapidez relaciona las dos magnitudes por cociente.$it$,
   null, $it$proporciones/aplica-inversa-donde-es-directa$it$, $it$proporciones/razona-por-diferencias$it$, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (0.4), 60,
   $it$Si $4$ trabajadores terminan una obra en $6$ días, ¿cuánto demoran $8$ trabajadores con el mismo rendimiento?$it$,
   $it$$12$ días$it$,
   $it$$3$ días$it$,
   $it$$10$ días$it$,
   $it$$2$ días$it$,
   $it$B$it$,
   $it$Se aplicó una proporción directa: al doble de trabajadores, el doble de días. Más gente trabajando termina **antes**, no después.$it$,
   $it$Correcto. Es inversamente proporcional: al doble de trabajadores, la mitad del tiempo. $6 \div 2 = 3$ días.$it$,
   $it$Se sumaron los días de más trabajadores como si cada uno aportara días. La relación es inversa y multiplicativa.$it$,
   $it$Se dividió por $4$, que es el número original de trabajadores. Lo que se duplicó fue la cantidad de gente, así que el tiempo se divide por $2$.$it$,
   $it$proporciones/aplica-directa-donde-es-inversa$it$, null, $it$proporciones/aplica-directa-donde-es-inversa$it$, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (0.52), 70,
   $it$Dos amigos se reparten $\$40.000$ en la razón $3:5$. ¿Cuánto recibe cada uno?$it$,
   $it$$\$20.000$ y $\$20.000$$it$,
   $it$$\$3.000$ y $\$5.000$$it$,
   $it$$\$12.000$ y $\$28.000$$it$,
   $it$$\$15.000$ y $\$25.000$$it$,
   $it$D$it$,
   $it$Se repartió en partes iguales, ignorando la razón. Si fuera mitad y mitad la razón sería $1:1$.$it$,
   $it$Esos son los números de la razón, no las cantidades. La razón dice la proporción, y hay que repartir los $\$40.000$ completos.$it$,
   $it$El total está bien, pero las partes no siguen la razón $3:5$: $12.000$ y $28.000$ están en razón $3:7$.$it$,
   $it$Correcto. La razón tiene $3+5 = 8$ partes; cada parte vale $\$5.000$, así que reciben $\$15.000$ y $\$25.000$.$it$,
   $it$proporciones/reparte-en-partes-iguales$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (0.64), 80,
   $it$Si $\dfrac{5}{8} = \dfrac{x}{24}$, ¿cuánto vale $x$?$it$,
   $it$$21$$it$,
   $it$$3$$it$,
   $it$$15$$it$,
   $it$$38{,}4$$it$,
   $it$C$it$,
   $it$Se razonó por diferencias: de $8$ a $24$ hay $16$, y se sumaron al $5$. En una proporción se multiplica por el mismo factor, no se suma la misma cantidad.$it$,
   $it$Ese es el factor de escala ($24 \div 8 = 3$), no el valor de $x$. Falta multiplicarlo por $5$.$it$,
   $it$Correcto. $24$ es el triple de $8$, así que $x$ es el triple de $5$: $15$.$it$,
   $it$Se multiplicó en cruz al revés: $\frac{8 \times 24}{5}$. Como la incógnita está arriba, queda $x = \frac{5 \times 24}{8}$.$it$,
   $it$proporciones/razona-por-diferencias$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (0.76), 90,
   $it$Tres llaves iguales llenan un estanque en $8$ horas. ¿En cuánto tiempo lo llenan $4$ llaves iguales a las anteriores?$it$,
   $it$$6$ horas$it$,
   $it$$10{,}67$ horas$it$,
   $it$$9$ horas$it$,
   $it$$2$ horas$it$,
   $it$A$it$,
   $it$Correcto. Es inversa: $3 \times 8 = 24$ «llave-horas», y con $4$ llaves son $24 \div 4 = 6$ horas.$it$,
   $it$Se aplicó proporción directa: más llaves, más tiempo. Agregar una llave hace que se llene **antes**.$it$,
   $it$Se sumó una hora por cada llave nueva. La relación no es aditiva: cada llave aporta caudal, y el tiempo total baja por división.$it$,
   $it$Se dividieron las $8$ horas por $4$ como si las tres llaves originales no contaran. El producto que se conserva es $\text{llaves} \times \text{horas}$.$it$,
   null, $it$proporciones/aplica-directa-donde-es-inversa$it$, $it$proporciones/razona-por-diferencias$it$, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (0.88), 100,
   $it$¿Cuál de estas tablas representa una proporcionalidad **directa** entre $x$ e $y$?$it$,
   $it$$x: 1, 2, 3$ — $y: 5, 6, 7$$it$,
   $it$$x: 1, 2, 3$ — $y: 4, 8, 12$$it$,
   $it$$x: 1, 2, 3$ — $y: 12, 6, 4$$it$,
   $it$$x: 1, 2, 3$ — $y: 1, 4, 9$$it$,
   $it$B$it$,
   $it$Los valores de $y$ crecen, pero sumando $1$ cada vez. En una proporcionalidad directa el **cociente** $y/x$ es constante, y acá da $5$, $3$ y $2{,}33$.$it$,
   $it$Correcto. $y/x$ vale $4$ en los tres casos: al doble de $x$, el doble de $y$.$it$,
   $it$Esa es una proporcionalidad **inversa**: el producto $x \cdot y$ es constante e igual a $12$, y $y$ baja cuando $x$ sube.$it$,
   $it$Ahí $y = x^2$, que crece más rápido que proporcionalmente: el cociente $y/x$ da $1$, $2$ y $3$.$it$,
   $it$proporciones/razona-por-diferencias$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (1.0), 110,
   $it$En un mapa a escala $1:50.000$, dos pueblos están a $4$ cm. ¿Cuál es la distancia real?$it$,
   $it$$200$ m$it$,
   $it$$20$ km$it$,
   $it$$12.500$ cm$it$,
   $it$$2$ km$it$,
   $it$D$it$,
   $it$El cálculo $4 \times 50.000 = 200.000$ está bien, pero esos son **centímetros**. Al pasar a metros hay que dividir por $100$.$it$,
   $it$Se corrió una posición al convertir: $200.000$ cm son $2.000$ m, o sea $2$ km, no $20$.$it$,
   $it$Se dividió por la escala en vez de multiplicar. En un mapa la realidad es mayor que el dibujo.$it$,
   $it$Correcto. $4 \times 50.000 = 200.000$ cm $= 2.000$ m $= 2$ km.$it$,
   null, null, $it$proporciones/escala-en-el-sentido-contrario$it$, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (1.12), 120,
   $it$Se reparten $60$ dulces entre dos cursos en la razón $2:3$. ¿Cuántos recibe el curso que recibe **menos**?$it$,
   $it$$30$$it$,
   $it$$20$$it$,
   $it$$24$$it$,
   $it$$2$$it$,
   $it$C$it$,
   $it$Se repartió en partes iguales. La razón $2:3$ dice que uno recibe más que el otro.$it$,
   $it$Se dividió el total por $3$, que es una de las partes de la razón, no la suma. Las partes en total son $2+3 = 5$.$it$,
   $it$Correcto. Hay $5$ partes de $12$ dulces cada una: el curso menor recibe $2 \times 12 = 24$ y el otro $36$.$it$,
   $it$Ese es el número de la razón, no la cantidad de dulces.$it$,
   $it$proporciones/reparte-en-partes-iguales$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (1.24), 130,
   $it$Un ciclista recorre $60$ km a $60$ km/h y luego otros $60$ km a $30$ km/h. ¿Cuál es su rapidez media en todo el trayecto?$it$,
   $it$$40$ km/h$it$,
   $it$$45$ km/h$it$,
   $it$$90$ km/h$it$,
   $it$$50$ km/h$it$,
   $it$A$it$,
   $it$Correcto. Tarda $1$ h en el primer tramo y $2$ h en el segundo: $120$ km en $3$ h dan $40$ km/h.$it$,
   $it$Promediaste las dos rapideces. Eso solo vale si pasa el **mismo tiempo** a cada una, y acá pasa el doble de tiempo en el tramo lento.$it$,
   $it$Se sumaron las dos rapideces. Sumar rapideces no tiene sentido físico: el ciclista nunca fue a $90$ km/h.$it$,
   $it$Es un promedio ponderado, pero con pesos que no corresponden. Lo seguro es siempre: distancia total dividida por tiempo total.$it$,
   null, $it$proporciones/velocidad-media-como-promedio-simple$it$, null, $it$proporciones/velocidad-media-como-promedio-simple$it$),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (1.36), 140,
   $it$Dos magnitudes cumplen $x \cdot y = 24$. Si $x$ se triplica, ¿qué le pasa a $y$?$it$,
   $it$Se triplica$it$,
   $it$Se divide por $3$$it$,
   $it$Aumenta en $3$$it$,
   $it$No cambia$it$,
   $it$B$it$,
   $it$Si las dos se triplicaran, el producto quedaría multiplicado por $9$ y ya no sería $24$.$it$,
   $it$Correcto. El producto debe seguir valiendo $24$, así que si un factor se triplica el otro se divide por $3$.$it$,
   $it$Sumar $3$ no conserva el producto: depende de qué valores tengan $x$ e $y$, y aquí la relación es multiplicativa.$it$,
   $it$Si $y$ no cambiara, el producto se triplicaría y dejaría de valer $24$.$it$,
   $it$proporciones/aplica-directa-donde-es-inversa$it$, null, $it$proporciones/razona-por-diferencias$it$, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (1.48), 150,
   $it$Seis obreros terminan una obra en $10$ días trabajando $8$ horas diarias. ¿Cuántos días demoran $4$ obreros trabajando $12$ horas diarias?$it$,
   $it$$15$ días$it$,
   $it$$6{,}67$ días$it$,
   $it$$20$ días$it$,
   $it$$10$ días$it$,
   $it$D$it$,
   $it$Se ajustó por la cantidad de obreros y no por las horas diarias. Trabajar más horas al día compensa parte de la falta de gente.$it$,
   $it$Se ajustó por las horas diarias y no por los obreros. Faltan dos personas, y eso empuja el plazo hacia arriba.$it$,
   $it$Se aplicaron los dos ajustes en el mismo sentido, cuando uno alarga el plazo y el otro lo acorta.$it$,
   $it$Correcto. El trabajo total es $6 \times 10 \times 8 = 480$ horas-obrero. Con $4$ obreros y $12$ horas diarias son $48$ horas-obrero por día: $480 \div 48 = 10$ días.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/proporciones$it$,
   (1.6), 160,
   $it$Para preparar jugo se mezcla $1$ parte de concentrado con $4$ partes de agua. ¿Cuánto concentrado se necesita para obtener $2$ litros de jugo listo?$it$,
   $it$$500$ mL$it$,
   $it$$1.000$ mL$it$,
   $it$$400$ mL$it$,
   $it$$2.000$ mL$it$,
   $it$C$it$,
   $it$Se dividió por $4$, tomando el agua como si fuera el total. El jugo listo tiene $1+4 = 5$ partes, no $4$.$it$,
   $it$Se repartió mitad y mitad. La razón $1:4$ dice que el concentrado es una quinta parte, no la mitad.$it$,
   $it$Correcto. El jugo listo son $5$ partes iguales; cada una es $2.000 \div 5 = 400$ mL, y el concentrado es una de ellas.$it$,
   $it$Ese es el total del jugo preparado, no la parte de concentrado.$it$,
   null, $it$proporciones/reparte-en-partes-iguales$it$, null, null),

  -- ===========================================================================
  -- aritmetica/porcentajes
  -- ===========================================================================
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (0.6), 10,
   $it$¿Cuánto es el $20\%$ de $50$?$it$,
   $it$$20$$it$,
   $it$$10$$it$,
   $it$$30$$it$,
   $it$$100$$it$,
   $it$B$it$,
   $it$Ese es el número del porcentaje, no la cantidad. El $20\%$ significa $20$ de cada $100$, y acá el total es $50$.$it$,
   $it$Correcto. $50 \times 0{,}20 = 10$, que es la quinta parte de $50$.$it$,
   $it$Ese es lo que **queda** después de sacar el $20\%$, no el $20\%$ mismo.$it$,
   $it$Se multiplicó $50 \times 2$. El $20\%$ es una parte del total, así que tiene que ser menor que $50$.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (0.75), 20,
   $it$¿Qué porcentaje de $60$ es $15$?$it$,
   $it$$15\%$$it$,
   $it$$40\%$$it$,
   $it$$4\%$$it$,
   $it$$25\%$$it$,
   $it$D$it$,
   $it$Ese es el valor de la parte, no su porcentaje. Hay que comparar la parte con el total: $15 \div 60$.$it$,
   $it$Se dividió al revés: $60 \div 15 = 4$, y eso se leyó como $40\%$. La parte va arriba y el total abajo.$it$,
   $it$El cociente $60 \div 15$ da $4$, pero está invertido y sin convertir a porcentaje.$it$,
   $it$Correcto. $\frac{15}{60} = 0{,}25$, o sea $25\%$.$it$,
   null, $it$porcentajes/base-equivocada$it$, $it$porcentajes/base-equivocada$it$, null),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (0.9), 30,
   $it$Una chaqueta cuesta $\$20.000$ y tiene $30\%$ de descuento. ¿Cuánto se paga?$it$,
   $it$$\$14.000$$it$,
   $it$$\$6.000$$it$,
   $it$$\$17.000$$it$,
   $it$$\$26.000$$it$,
   $it$A$it$,
   $it$Correcto. El descuento es $\$6.000$, así que se paga $20.000 - 6.000 = \$14.000$. También sale directo: $20.000 \times 0{,}70$.$it$,
   $it$Ese es el descuento, no lo que se paga. Falta restarlo del precio original.$it$,
   $it$Se restaron $\$3.000$, que sería un $15\%$. El $30\%$ de $\$20.000$ es $\$6.000$.$it$,
   $it$Se sumó el descuento en vez de restarlo. Un descuento baja el precio.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (1.05), 40,
   $it$Un producto tiene precio neto de $\$10.000$ y se le aplica $19\%$ de IVA. ¿Cuál es el precio final?$it$,
   $it$$\$1.900$$it$,
   $it$$\$10.019$$it$,
   $it$$\$11.900$$it$,
   $it$$\$8.100$$it$,
   $it$C$it$,
   $it$Ese es el IVA, no el precio final. Falta sumarlo al precio neto.$it$,
   $it$Se sumaron $19$ pesos. El $19\%$ de $\$10.000$ son $\$1.900$, no $\$19$.$it$,
   $it$Correcto. $\$10.000 \times 1{,}19 = \$11.900$.$it$,
   $it$Se restó el IVA en vez de sumarlo. El IVA es un impuesto que se agrega al precio neto.$it$,
   null, null, null, null),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (1.2), 50,
   $it$Un precio sube $10\%$ y después baja $10\%$. ¿Cómo queda respecto del precio original?$it$,
   $it$Igual que al principio$it$,
   $it$Un poco menor$it$,
   $it$Un poco mayor$it$,
   $it$Un $20\%$ menor$it$,
   $it$B$it$,
   $it$Es la respuesta intuitiva y no funciona, porque los dos porcentajes se calculan sobre **bases distintas**: el alza sobre el precio original y la baja sobre el precio ya subido, que es mayor.$it$,
   $it$Correcto. Con $\$100$: sube a $\$110$ y luego baja $\$11$, quedando en $\$99$. La baja se calcula sobre una base mayor, así que pesa más.$it$,
   $it$Sería mayor si la baja se calculara sobre el precio original, pero se calcula sobre el precio ya aumentado.$it$,
   $it$Los dos porcentajes no se suman ni se restan entre sí: el efecto neto es de apenas $1\%$ hacia abajo.$it$,
   $it$porcentajes/base-equivocada$it$, null, $it$porcentajes/base-equivocada$it$, $it$porcentajes/suma-porcentajes-sucesivos$it$),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (1.35), 60,
   $it$Si el $25\%$ de un número es $30$, ¿cuál es el número?$it$,
   $it$$7{,}5$$it$,
   $it$$55$$it$,
   $it$$75$$it$,
   $it$$120$$it$,
   $it$D$it$,
   $it$Se calculó el $25\%$ de $30$. Acá $30$ **es** el $25\%$: el número buscado es mayor, no menor.$it$,
   $it$Se sumaron los dos datos. El porcentaje y la parte no se suman.$it$,
   $it$Se multiplicó por $2{,}5$. Si $30$ es la cuarta parte, el total es cuatro veces $30$.$it$,
   $it$Correcto. El $25\%$ es la cuarta parte, así que el número es $30 \times 4 = 120$.$it$,
   $it$porcentajes/base-equivocada$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (1.5), 70,
   $it$La aprobación de un curso pasó del $20\%$ al $25\%$. ¿Cuál de estas afirmaciones es **correcta**?$it$,
   $it$Subió $5$ puntos porcentuales, que equivalen a un aumento del $25\%$$it$,
   $it$Subió un $5\%$$it$,
   $it$Subió un $20\%$$it$,
   $it$Subió $5$ puntos porcentuales, que equivalen a un aumento del $5\%$$it$,
   $it$A$it$,
   $it$Correcto. La diferencia es de $5$ puntos porcentuales, y respecto del $20\%$ inicial eso es $\frac{5}{20} = 25\%$ de aumento.$it$,
   $it$«Subió un $5\%$» describiría un aumento del $5\%$ sobre el $20\%$, o sea llegar a $21\%$. Lo que subió $5$ son los **puntos**, no el porcentaje.$it$,
   $it$El $20\%$ es el valor de partida, no el aumento. El aumento relativo se calcula dividiendo la diferencia por ese valor inicial.$it$,
   $it$La primera mitad está bien: son $5$ puntos porcentuales. La segunda confunde esos puntos con un aumento porcentual, que es del $25\%$.$it$,
   null, $it$porcentajes/confunde-puntos-con-porcentaje$it$, $it$porcentajes/base-equivocada$it$, $it$porcentajes/confunde-puntos-con-porcentaje$it$),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (1.7), 80,
   $it$Después de un $20\%$ de descuento, un artículo cuesta $\$24.000$. ¿Cuál era el precio original?$it$,
   $it$$\$28.800$$it$,
   $it$$\$26.000$$it$,
   $it$$\$30.000$$it$,
   $it$$\$19.200$$it$,
   $it$C$it$,
   $it$Le sumaste el $20\%$ al precio con descuento. Ese $20\%$ se calculó sobre el precio **original**, que es mayor, así que sumarlo sobre el rebajado no alcanza.$it$,
   $it$Se sumó un valor aproximado sin usar la relación exacta. El precio con descuento es el $80\%$ del original.$it$,
   $it$Correcto. $\$24.000$ es el $80\%$ del original, así que el original es $24.000 \div 0{,}80 = \$30.000$.$it$,
   $it$Se aplicó el descuento otra vez, en vez de deshacerlo. El precio original tiene que ser mayor que $\$24.000$.$it$,
   $it$porcentajes/deshace-el-descuento-sumandolo$it$, $it$porcentajes/deshace-el-descuento-sumandolo$it$, null, $it$porcentajes/base-equivocada$it$),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (1.9), 90,
   $it$Se depositan $\$200.000$ a una tasa de **interés simple** del $5\%$ anual. ¿Cuánto interés se gana en $2$ años?$it$,
   $it$$\$10.000$$it$,
   $it$$\$20.000$$it$,
   $it$$\$20.500$$it$,
   $it$$\$220.000$$it$,
   $it$B$it$,
   $it$Ese es el interés de un solo año. La pregunta abarca dos.$it$,
   $it$Correcto. En interés simple cada año rinde $\$10.000$ sobre el capital inicial: $\$20.000$ en dos años.$it$,
   $it$Ese es el resultado del interés **compuesto**, donde el segundo año rinde también sobre los intereses del primero. El enunciado dice interés simple.$it$,
   $it$Ese es el capital final, no el interés ganado. El interés es lo que se suma al capital.$it$,
   null, null, $it$porcentajes/interes-compuesto-como-simple$it$, null),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (2.05), 100,
   $it$Un precio sube $20\%$ y al mes siguiente vuelve a subir $20\%$. ¿Cuál es el aumento total respecto del precio inicial?$it$,
   $it$$40\%$$it$,
   $it$$20\%$$it$,
   $it$$4\%$$it$,
   $it$$44\%$$it$,
   $it$D$it$,
   $it$Sumaste los dos porcentajes. El segundo $20\%$ se calcula sobre el precio **ya aumentado**, que es mayor, así que aporta más que el primero.$it$,
   $it$Ese es el aumento de una sola de las dos alzas. Hay dos, encadenadas.$it$,
   $it$Se multiplicaron los porcentajes entre sí como números sueltos. Lo que se multiplica son los **factores** $1{,}2 \times 1{,}2$.$it$,
   $it$Correcto. $1{,}20 \times 1{,}20 = 1{,}44$: partiendo de $\$100$ se llega a $\$144$, o sea $44\%$ más.$it$,
   $it$porcentajes/suma-porcentajes-sucesivos$it$, null, null, null),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (2.2), 110,
   $it$En un colegio, el $40\%$ de los estudiantes son mujeres y, de ellas, el $25\%$ juega vóleibol. ¿Qué porcentaje del **total** de estudiantes son mujeres que juegan vóleibol?$it$,
   $it$$10\%$$it$,
   $it$$65\%$$it$,
   $it$$25\%$$it$,
   $it$$15\%$$it$,
   $it$A$it$,
   $it$Correcto. Es el $25\%$ del $40\%$: $0{,}25 \times 0{,}40 = 0{,}10$, o sea el $10\%$ del total.$it$,
   $it$Se sumaron los dos porcentajes. Están calculados sobre bases distintas: el segundo se aplica solo a las mujeres, no a todo el colegio.$it$,
   $it$Ese es el porcentaje **dentro del grupo de mujeres**. Referido al total del colegio la cifra es menor, porque las mujeres son solo el $40\%$.$it$,
   $it$Se restaron los dos porcentajes. Un porcentaje de un porcentaje es un producto, no una diferencia.$it$,
   null, $it$porcentajes/porcentaje-de-porcentaje-como-suma$it$, $it$porcentajes/base-equivocada$it$, $it$porcentajes/porcentaje-de-porcentaje-como-suma$it$),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (2.35), 120,
   $it$Una tienda ofrece $50\%$ de descuento y, sobre ese precio, un $20\%$ adicional. ¿A qué descuento único equivale?$it$,
   $it$$70\%$$it$,
   $it$$30\%$$it$,
   $it$$60\%$$it$,
   $it$$10\%$$it$,
   $it$C$it$,
   $it$Sumaste los dos descuentos. El segundo se aplica sobre el precio ya rebajado, que es la mitad, así que descuenta menos de lo que parece.$it$,
   $it$Se restaron los dos porcentajes. Los descuentos encadenados se combinan multiplicando los factores que quedan.$it$,
   $it$Correcto. Queda $0{,}50 \times 0{,}80 = 0{,}40$ del precio, o sea se paga el $40\%$ y el descuento total es del $60\%$.$it$,
   $it$Ese es el segundo descuento medido sobre el precio original ($20\%$ de la mitad). Falta sumarle el primer $50\%$.$it$,
   $it$porcentajes/suma-porcentajes-sucesivos$it$, $it$porcentajes/suma-porcentajes-sucesivos$it$, null, $it$porcentajes/base-equivocada$it$),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (2.5), 130,
   $it$Un valor sube de $40$ a $50$ y después vuelve a bajar de $50$ a $40$. ¿Qué relación hay entre el porcentaje de alza y el de baja?$it$,
   $it$Los dos son del $25\%$$it$,
   $it$El alza es del $25\%$ y la baja del $20\%$$it$,
   $it$Los dos son del $20\%$$it$,
   $it$El alza es del $20\%$ y la baja del $25\%$$it$,
   $it$B$it$,
   $it$El alza sí es del $25\%$, pero la baja se calcula sobre $50$, no sobre $40$: $\frac{10}{50} = 20\%$.$it$,
   $it$Correcto. La misma diferencia de $10$ pesa distinto según la base: $\frac{10}{40} = 25\%$ al subir y $\frac{10}{50} = 20\%$ al bajar.$it$,
   $it$La baja sí es del $20\%$, pero el alza se calcula sobre $40$: $\frac{10}{40} = 25\%$.$it$,
   $it$Los porcentajes están intercambiados. La base del alza es $40$ (más chica, porcentaje mayor) y la de la baja es $50$.$it$,
   $it$porcentajes/base-equivocada$it$, null, $it$porcentajes/base-equivocada$it$, $it$porcentajes/base-equivocada$it$),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (2.65), 140,
   $it$Un sueldo sube $25\%$ y después baja $20\%$. ¿Cómo queda respecto del sueldo inicial?$it$,
   $it$Un $5\%$ mayor$it$,
   $it$Un $5\%$ menor$it$,
   $it$Un $45\%$ mayor$it$,
   $it$Exactamente igual$it$,
   $it$D$it$,
   $it$Se restaron los porcentajes. Hay que multiplicar los factores: $1{,}25 \times 0{,}80$.$it$,
   $it$Se restaron los porcentajes en el otro orden. El resultado exacto sale del producto de los dos factores.$it$,
   $it$Se sumaron las dos variaciones tratando la baja como si fuera un alza.$it$,
   $it$Correcto. $1{,}25 \times 0{,}80 = 1{,}00$: la baja del $20\%$ se aplica sobre una base mayor y compensa exactamente el alza del $25\%$.$it$,
   $it$porcentajes/suma-porcentajes-sucesivos$it$, $it$porcentajes/suma-porcentajes-sucesivos$it$, null, null),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (2.8), 150,
   $it$En un colegio, el $30\%$ de los $200$ estudiantes de básica y el $60\%$ de los $300$ de media participan en un taller. ¿Qué porcentaje del total participa?$it$,
   $it$$48\%$$it$,
   $it$$45\%$$it$,
   $it$$90\%$$it$,
   $it$$30\%$$it$,
   $it$A$it$,
   $it$Correcto. Participan $60$ de básica y $180$ de media: $240$ de $500$, que es el $48\%$.$it$,
   $it$Promediaste los dos porcentajes. Solo sería válido si los dos grupos tuvieran el mismo tamaño, y acá media tiene $100$ estudiantes más.$it$,
   $it$Se sumaron los dos porcentajes. Están calculados sobre grupos distintos, así que no se suman entre sí.$it$,
   $it$Ese es el porcentaje de uno solo de los dos grupos, el más pequeño.$it$,
   null, $it$porcentajes/promedia-porcentajes-sin-ponderar$it$, $it$porcentajes/suma-porcentajes-sucesivos$it$, null),
  ($it$numeros$it$, $it$aritmetica/porcentajes$it$,
   (3.0), 160,
   $it$Se depositan $\$100.000$ a **interés compuesto** del $10\%$ anual. ¿Cuánto se tiene al cabo de $2$ años?$it$,
   $it$$\$120.000$$it$,
   $it$$\$110.000$$it$,
   $it$$\$121.000$$it$,
   $it$$\$102.000$$it$,
   $it$C$it$,
   $it$Ese es el resultado con interés **simple**: $10\%$ del capital inicial cada año. En el compuesto, el segundo año también rinde sobre los intereses del primero.$it$,
   $it$Ese es el saldo después del primer año. Falta el segundo.$it$,
   $it$Correcto. $100.000 \times 1{,}10 = 110.000$ el primer año, y $110.000 \times 1{,}10 = \$121.000$ el segundo.$it$,
   $it$Se aplicó el $10\%$ sobre una parte muy pequeña del capital. El $10\%$ de $\$100.000$ son $\$10.000$ por año.$it$,
   $it$porcentajes/interes-compuesto-como-simple$it$, null, null, null)

)
insert into public.questions
  (topic, module_id, difficulty, order_index,
   question, option_a, option_b, option_c, option_d, correct_option,
   error_a, error_b, error_c, error_d,
   misconception_a_id, misconception_b_id, misconception_c_id, misconception_d_id)
select i.topic, m.id, i.difficulty, i.order_index,
       i.question, i.option_a, i.option_b, i.option_c, i.option_d, i.correct_option,
       i.error_a, i.error_b, i.error_c, i.error_d,
       xa.id, xb.id, xc.id, xd.id
from items i
left join public.modules m        on m.slug  = i.module_slug
left join public.misconceptions xa on xa.slug = i.mis_a
left join public.misconceptions xb on xb.slug = i.mis_b
left join public.misconceptions xc on xc.slug = i.mis_c
left join public.misconceptions xd on xd.slug = i.mis_d
-- Idempotente por (topic, question). Reaplicar NO actualiza un ítem ya
-- cargado: para corregirlo, editarlo en Admin → Preguntas o borrarlo primero.
where not exists (
  select 1 from public.questions q
   where q.topic = i.topic and q.question = i.question
);

-- -----------------------------------------------------------------------------
-- Verificación (correr después de aplicar)
-- -----------------------------------------------------------------------------
--   select count(*) from public.questions where topic = 'numeros';
--   -- esperado: 100 (más lo que ya hubiera)
--
--   -- Ningún ítem sin módulo: delataría un module_slug mal escrito.
--   select id from public.questions where topic = 'numeros' and module_id is null;
--   -- 0 filas
--
--   -- Ningún distractor perdió su idea errónea en el join.
--   select id, question from public.questions q
--    where topic = 'numeros'
--      and misconception_a_id is null and misconception_b_id is null
--      and misconception_c_id is null and misconception_d_id is null;
--   -- revisar: un ítem sin ninguna catalogada puede ser legítimo, varios no
--
--   -- La clave repartida (R-35): ninguna letra debe pasar del 40 %.
--   select correct_option, count(*) from public.questions
--    where topic = 'numeros' group by 1 order by 1;
--
-- Reversión: delete from public.questions where topic = 'numeros';
--            delete from public.misconceptions where slug in ('numeros/lee-el-digito-y-no-su-valor', 'numeros/desplaza-una-posicion', 'numeros/mas-cifras-decimales-es-mayor', …);
