-- Banco del eje de álgebra — primera tanda
-- 100 ítems · topic `algebra` · 34 ideas erróneas nuevas
--
-- GENERADA por scripts/generar_migracion_items.py desde el JSON de la tanda.
-- No editar a mano: corregir el JSON, volver a verificar y regenerar. Un cambio
-- hecho acá se pierde en la siguiente regeneración y deja de estar verificado.
--
-- Verificada con scripts/verificar_items.py, que comprueba lo que este banco
-- aprendió a golpes: clave repartida entre las cuatro letras (R-35), una sola
-- alternativa correcta, las cuatro explicaciones escritas, la correcta sin idea
-- errónea, LaTeX con escape simple (047) y cobertura de dificultad sin huecos.
--
-- 100 ítems repartidos en los cinco módulos de álgebra, cubriendo toda la escala
-- [-3, 3] con al menos 6 ítems por tramo de 1,0 logit.
--
-- REQUIERE la migración 051 aplicada (bandas explícitas del eje de álgebra), por la
-- misma razón por la que 050 requería 049: sin ella las bandas derivadas comprimen el
-- eje entero en [-1,16, +0,87] y el diagnóstico se agota cuando el estudiante sube.
--
-- NO amplía el banco `polinomios` existente: lo reemplaza. Ese banco tiene 18 de sus
-- 20 ítems dentro de 0,045 logits — no es una escala de dificultad, es una constante
-- con ruido, y ningún test adaptativo puede discriminar dentro de él. Los 20 ítems
-- viejos NO se borran acá: siguen respondiendo a su propio topic y a su historial en
-- `tests`. Se retiran de circulación desactivándolos, que es una decisión de contenido
-- del owner y no de esta migración.
--
-- `difficulty` es una HIPÓTESIS EDITORIAL, no una medición (R-17). La validez solo
-- puede venir de calibrar con respuestas reales (G-2).

-- -----------------------------------------------------------------------------
-- 1. Ideas erróneas nuevas
-- -----------------------------------------------------------------------------
-- Van ANTES de los ítems y en el mismo archivo: el `left join` de abajo
-- resuelve por slug, así que si no existen todavía los ítems entrarían con
-- `misconception_*_id` en null y en silencio.
--
-- `on conflict (slug) do nothing`: si una ya está catalogada, se respeta la
-- que hay. Reaplicar contenido no pisa una corrección hecha en el panel.

insert into public.misconceptions (slug, name, description, module_id)
select v.slug, v.name, v.description, m.id
  from (values
    ($it$algebra/coeficiente-incluye-la-letra$it$, $it$Toma el término completo como coeficiente$it$, $it$Usar cuando responde «5x» donde se pedía el coeficiente de $5x$. No separa la parte numérica de la literal.$it$, $it$algebra/expresiones$it$),
    ($it$algebra/suma-terminos-no-semejantes$it$, $it$Reduce términos que no son semejantes$it$, $it$Usar cuando junta $3x$ con $2y$, o $x$ con $x^2$. Es tratar las letras como si todas nombraran lo mismo.$it$, $it$algebra/expresiones$it$),
    ($it$algebra/letra-sola-no-tiene-coeficiente$it$, $it$Trata la letra sola como si tuviera coeficiente cero$it$, $it$Usar cuando $4x - x$ da $4x$ o $4$. La letra sola lleva un $1$ implícito.$it$, $it$algebra/expresiones$it$),
    ($it$algebra/no-distribuye-el-signo-menos$it$, $it$No aplica el signo menos a todo el paréntesis$it$, $it$Usar cuando $5-(x-2)$ da $5-x-2$. El menos multiplica a cada término de adentro, no solo al primero.$it$, $it$algebra/expresiones$it$),
    ($it$algebra/multiplica-monomios-sin-tocar-el-exponente$it$, $it$Multiplica los coeficientes y deja la letra sin exponente$it$, $it$Usar cuando $2x \cdot 3x$ da $6x$. Al multiplicar potencias de igual base los exponentes se suman.$it$, $it$algebra/expresiones$it$),
    ($it$algebra/potencia-antes-o-despues-del-signo$it$, $it$No distingue $-x^2$ de $(-x)^2$ al evaluar$it$, $it$Usar cuando reemplaza un valor negativo y aplica el exponente al signo sin que haya paréntesis, o al revés.$it$, $it$algebra/expresiones$it$),
    ($it$algebra/traduce-palabra-por-palabra$it$, $it$Traduce el enunciado en el orden en que está escrito, sin el paréntesis$it$, $it$Usar cuando «el doble de la suma de un número y 5» queda como $2n+5$. La palabra «de» agrupa lo que viene después.$it$, $it$algebra/expresiones$it$),
    ($it$algebra/cuadrado-de-suma-como-suma-de-cuadrados$it$, $it$Cree que $(a+b)^2 = a^2 + b^2$$it$, $it$Usar cuando reparte el exponente sobre una suma. Es la propiedad distributiva aplicada donde no vale; falta el doble producto.$it$, $it$algebra/expresiones$it$),
    ($it$algebra/no-distribuye-a-todos-los-terminos$it$, $it$Multiplica el factor solo por el primer término del paréntesis$it$, $it$Usar cuando $2(3x+4)$ da $6x+4$. La distributiva alcanza a todos los términos de adentro.$it$, $it$algebra/expresiones$it$),
    ($it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, $it$Cambia un término de lado sin cambiarle el signo$it$, $it$Usar cuando pasa un sumando al otro miembro y lo deja igual. Lo que se hace es restarlo a los dos lados, y por eso llega con el signo opuesto.$it$, $it$algebra/ecuaciones$it$),
    ($it$ecuaciones/divide-solo-un-termino$it$, $it$Divide solo uno de los términos del miembro$it$, $it$Usar cuando al dividir por un número lo aplica al término con incógnita y no al independiente, o al revés.$it$, $it$algebra/ecuaciones$it$),
    ($it$ecuaciones/invierte-la-operacion-al-despejar$it$, $it$Aplica la misma operación en vez de la inversa al despejar$it$, $it$Usar cuando multiplica donde había que dividir, o suma donde había que restar. Reconoce que hay que despejar y elige la operación equivocada.$it$, $it$algebra/ecuaciones$it$),
    ($it$ecuaciones/coeficiente-negativo-pierde-el-signo$it$, $it$Suelta el signo del coeficiente negativo al despejar$it$, $it$Usar cuando $-2x = 6$ da $x = 3$. Dividir por un número negativo cambia el signo del resultado.$it$, $it$algebra/ecuaciones$it$),
    ($it$ecuaciones/no-desarrolla-el-parentesis$it$, $it$Despeja sin desarrollar el paréntesis primero$it$, $it$Usar cuando opera con el contenido del paréntesis como si el factor de afuera no existiera.$it$, $it$algebra/ecuaciones$it$),
    ($it$ecuaciones/sin-solucion-como-cero$it$, $it$Confunde «no tiene solución» con «la solución es cero»$it$, $it$Usar cuando una identidad falsa como $6 = 1$ se responde $x = 0$. Que la incógnita desaparezca no significa que valga cero.$it$, $it$algebra/ecuaciones$it$),
    ($it$sistemas/solucion-como-un-solo-numero$it$, $it$Entrega un solo valor como solución de un sistema de dos incógnitas$it$, $it$Usar cuando responde solo $x$ o solo $y$. La solución de un sistema 2×2 es un par ordenado: hacen falta los dos valores.$it$, $it$algebra/sistemas$it$),
    ($it$sistemas/resuelve-una-sola-ecuacion$it$, $it$Usa una sola de las dos ecuaciones$it$, $it$Usar cuando el valor entregado cumple una ecuación y no la otra. Un sistema exige que las dos se cumplan a la vez.$it$, $it$algebra/sistemas$it$),
    ($it$sistemas/confunde-sin-solucion-con-infinitas$it$, $it$Confunde un sistema incompatible con uno de infinitas soluciones$it$, $it$Usar cuando llama «infinitas soluciones» a rectas paralelas, o «sin solución» a dos ecuaciones que son la misma recta.$it$, $it$algebra/sistemas$it$),
    ($it$sistemas/traduce-mal-el-enunciado$it$, $it$Plantea el sistema con las incógnitas cambiadas o una condición perdida$it$, $it$Usar cuando el error no está en resolver sino en escribir las ecuaciones: cambia cuál es cuál, o usa una sola condición.$it$, $it$algebra/sistemas$it$),
    ($it$polinomios/grado-como-cantidad-de-terminos$it$, $it$Confunde el grado del polinomio con su número de términos$it$, $it$Usar cuando responde 3 para un trinomio de grado 2. El grado es el mayor exponente, no cuántos sumandos hay.$it$, $it$algebra/polinomios$it$),
    ($it$polinomios/cuadrado-de-binomio-sin-doble-producto$it$, $it$Desarrolla $(a+b)^2$ como $a^2+b^2$$it$, $it$Usar cuando falta el término $2ab$. Es el error más frecuente de productos notables, y viene de repartir el exponente sobre la suma.$it$, $it$algebra/polinomios$it$),
    ($it$polinomios/factoriza-la-suma-de-cuadrados$it$, $it$Factoriza $a^2+b^2$ como si fuera una diferencia$it$, $it$Usar cuando entrega $(a+b)(a-b)$ para una suma de cuadrados. Solo la **diferencia** de cuadrados se factoriza así.$it$, $it$algebra/polinomios$it$),
    ($it$polinomios/factor-comun-incompleto$it$, $it$Extrae un factor común que no es el máximo$it$, $it$Usar cuando la factorización es correcta pero dentro del paréntesis todavía queda un factor común por sacar.$it$, $it$algebra/polinomios$it$),
    ($it$polinomios/signos-cambiados-al-factorizar$it$, $it$Equivoca los signos de los binomios al factorizar un trinomio$it$, $it$Usar cuando los dos números elegidos multiplican y suman mal por un tema de signos. Conviene comprobar desarrollando.$it$, $it$algebra/polinomios$it$),
    ($it$polinomios/cancela-terminos-sueltos-de-la-fraccion$it$, $it$Cancela términos sueltos de una fracción algebraica$it$, $it$Usar cuando tacha una $x$ de arriba con una de abajo sin haber factorizado. Solo se cancelan **factores** completos, no sumandos.$it$, $it$algebra/polinomios$it$),
    ($it$polinomios/multiplica-solo-los-primeros-terminos$it$, $it$Al multiplicar binomios solo multiplica primero con primero y último con último$it$, $it$Usar cuando faltan los términos cruzados. Cada término del primer paréntesis multiplica a todos los del segundo.$it$, $it$algebra/polinomios$it$),
    ($it$funciones/confunde-pendiente-con-intercepto$it$, $it$Intercambia la pendiente con el coeficiente de posición$it$, $it$Usar cuando en $y = mx + n$ señala el $n$ como pendiente o el $m$ como corte con el eje $y$.$it$, $it$algebra/funciones$it$),
    ($it$funciones/pendiente-invertida$it$, $it$Calcula la pendiente como $\Delta x / \Delta y$$it$, $it$Usar cuando divide la variación horizontal por la vertical. La pendiente es cuánto sube por cada unidad que avanza.$it$, $it$algebra/funciones$it$),
    ($it$funciones/confunde-los-dos-cortes$it$, $it$Confunde el corte con el eje $x$ con el corte con el eje $y$$it$, $it$Usar cuando iguala a cero la variable equivocada. El corte con el eje $x$ se obtiene con $y = 0$, y viceversa.$it$, $it$algebra/funciones$it$),
    ($it$funciones/raices-con-el-signo-de-la-factorizacion$it$, $it$Lee las raíces con el signo que aparece en los paréntesis$it$, $it$Usar cuando de $(x-2)(x-3)$ concluye que las raíces son $-2$ y $-3$. La raíz es el valor que **anula** el factor.$it$, $it$algebra/funciones$it$),
    ($it$funciones/vertice-con-el-signo-cambiado$it$, $it$Equivoca el signo en la fórmula del vértice$it$, $it$Usar cuando calcula $x = b/2a$ en vez de $-b/2a$, o cuando entrega la coordenada $y$ sin reemplazar.$it$, $it$algebra/funciones$it$),
    ($it$funciones/discriminante-negativo-como-sin-sentido$it$, $it$No interpreta el discriminante negativo$it$, $it$Usar cuando ante $\Delta < 0$ responde que hay una raíz, o que la raíz es cero. Un discriminante negativo significa que no hay raíces reales.$it$, $it$algebra/funciones$it$),
    ($it$funciones/relacion-con-dos-imagenes-es-funcion$it$, $it$Acepta como función una relación que asigna dos valores a un mismo elemento$it$, $it$Usar cuando no aplica la condición de unicidad. Una función asigna a cada valor de entrada exactamente uno de salida.$it$, $it$algebra/funciones$it$),
    ($it$funciones/confunde-costo-fijo-con-variable$it$, $it$Confunde el término constante con el coeficiente en una función de costo$it$, $it$Usar cuando en $C(x) = mx + n$ señala el $m$ como costo fijo. El costo fijo es el que no depende de la cantidad.$it$, $it$algebra/funciones$it$)
  ) as v(slug, name, description, module_slug)
  left join public.modules m on m.slug = v.module_slug
on conflict (slug) do nothing;

-- -----------------------------------------------------------------------------
-- 2. Ítems
-- -----------------------------------------------------------------------------

with items (topic, module_slug, difficulty, order_index,
            question, option_a, option_b, option_c, option_d, correct_option,
            error_a, error_b, error_c, error_d,
            mis_a, mis_b, mis_c, mis_d) as (
  values

  -- ===========================================================================
  -- algebra/expresiones
  -- ===========================================================================
  ($it$algebra$it$::text, $it$algebra/expresiones$it$::text,
   (-3.0)::double precision, 10::int,
   $it$¿Cuál es el **coeficiente** del término $5x$?$it$::text,
   $it$$x$$it$::text,
   $it$$5x$$it$::text,
   $it$$5$$it$::text,
   $it$$1$$it$::text,
   $it$C$it$::text,
   $it$Esa es la parte **literal**, la letra. El coeficiente es el número que la multiplica.$it$::text,
   $it$Ese es el término completo. El coeficiente es solo su parte numérica.$it$::text,
   $it$Correcto. En $5x$ el $5$ multiplica a la letra: ese es el coeficiente.$it$::text,
   $it$El $1$ es el coeficiente implícito cuando la letra aparece sola, como en $x$. Acá el número está escrito.$it$::text,
   null::text, $it$algebra/coeficiente-incluye-la-letra$it$::text, null::text, null::text),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.92), 20,
   $it$En el término $3x^2$, ¿cuál es la **parte literal**?$it$,
   $it$$x^2$$it$,
   $it$$3$$it$,
   $it$$x$$it$,
   $it$$3x$$it$,
   $it$A$it$,
   $it$Correcto. La parte literal es todo lo que no es el número, exponente incluido.$it$,
   $it$Ese es el coeficiente, la parte numérica.$it$,
   $it$Falta el exponente. $x$ y $x^2$ no son la misma parte literal, y por eso $3x$ y $3x^2$ no son términos semejantes.$it$,
   $it$Ahí quedó incluido el coeficiente. La parte literal es solo la letra con su exponente.$it$,
   null, null, null, $it$algebra/coeficiente-incluye-la-letra$it$),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.84), 30,
   $it$¿Cuántos **términos** tiene la expresión $2x + 3y - 5$?$it$,
   $it$$1$$it$,
   $it$$2$$it$,
   $it$$6$$it$,
   $it$$3$$it$,
   $it$D$it$,
   $it$Una expresión con signos de suma y resta entre medio tiene varios términos: los separan justamente esos signos.$it$,
   $it$Se contaron solo los que llevan letra. El $-5$ también es un término, llamado término independiente.$it$,
   $it$Se contaron los símbolos sueltos. Un término puede tener número y letra juntos, como $2x$.$it$,
   $it$Correcto. Los términos son $2x$, $3y$ y $-5$: los separan los signos $+$ y $-$.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.76), 40,
   $it$¿Cuál de estos términos es **semejante** a $3x$?$it$,
   $it$$3x^2$$it$,
   $it$$5x$$it$,
   $it$$3y$$it$,
   $it$$3$$it$,
   $it$B$it$,
   $it$Comparte la letra pero no el exponente. $x$ y $x^2$ representan cosas distintas: no se pueden reducir juntos.$it$,
   $it$Correcto. Dos términos son semejantes si tienen la misma parte literal; el coeficiente puede ser cualquiera.$it$,
   $it$Comparte el coeficiente pero no la letra. Lo que tiene que coincidir es la parte literal, no el número.$it$,
   $it$Es un término independiente, sin parte literal. No es semejante a uno que sí la tiene.$it$,
   $it$algebra/suma-terminos-no-semejantes$it$, null, $it$algebra/suma-terminos-no-semejantes$it$, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.68), 50,
   $it$Reduce la expresión $3x + 2x$.$it$,
   $it$$5x$$it$,
   $it$$6x^2$$it$,
   $it$$5x^2$$it$,
   $it$$5$$it$,
   $it$A$it$,
   $it$Correcto. Son términos semejantes: se suman los coeficientes y la parte literal se mantiene.$it$,
   $it$Se multiplicaron los términos en vez de sumarlos. Sumar $3$ manzanas y $2$ manzanas da $5$ manzanas, no $6$ manzanas al cuadrado.$it$,
   $it$Los coeficientes se sumaron bien, pero apareció un exponente que no estaba. Sumar no cambia la parte literal.$it$,
   $it$Se perdió la letra. El resultado sigue siendo una cantidad de $x$.$it$,
   null, $it$algebra/multiplica-monomios-sin-tocar-el-exponente$it$, null, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.61), 60,
   $it$Reduce todo lo posible la expresión $3x + 2y$.$it$,
   $it$$5xy$$it$,
   $it$$5x$$it$,
   $it$No se puede reducir más$it$,
   $it$$5$$it$,
   $it$C$it$,
   $it$Se juntaron los coeficientes y se pegaron las letras. $x$ e $y$ representan cantidades distintas: no se pueden sumar entre sí.$it$,
   $it$Se sumaron los coeficientes y se descartó la $y$. Ninguna de las dos letras desaparece por sumarlas.$it$,
   $it$Correcto. $3x$ y $2y$ no son semejantes —tienen parte literal distinta—, así que la expresión ya está reducida.$it$,
   $it$Se perdieron las dos letras. El resultado no puede ser un número puro.$it$,
   $it$algebra/suma-terminos-no-semejantes$it$, $it$algebra/suma-terminos-no-semejantes$it$, null, $it$algebra/suma-terminos-no-semejantes$it$),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.53), 70,
   $it$¿Cuál es el valor de $2x + 1$ cuando $x = 3$?$it$,
   $it$$21$$it$,
   $it$$6$$it$,
   $it$$5$$it$,
   $it$$7$$it$,
   $it$D$it$,
   $it$Se pegó el $3$ al lado del $2$ formando $21$. Reemplazar significa **multiplicar** $2$ por $3$, no escribirlos juntos.$it$,
   $it$Se calculó $2 \times 3$ y faltó sumar el $1$.$it$,
   $it$Se sumaron $2$ y $3$ en vez de multiplicarlos. En $2x$ el número y la letra están multiplicándose.$it$,
   $it$Correcto. $2 \times 3 + 1 = 6 + 1 = 7$.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.45), 80,
   $it$¿Cómo se escribe «el doble de un número, aumentado en $5$»?$it$,
   $it$$2(n+5)$$it$,
   $it$$2n + 5$$it$,
   $it$$n^2 + 5$$it$,
   $it$$2 + n + 5$$it$,
   $it$B$it$,
   $it$Ahí el doble se aplica a la suma completa. El enunciado dobla **el número** y recién después suma $5$.$it$,
   $it$Correcto. «El doble de un número» es $2n$, y «aumentado en $5$» le suma $5$ a eso.$it$,
   $it$«El doble» multiplica por $2$; elevar al cuadrado sería «el número al cuadrado».$it$,
   $it$El $2$ quedó sumando en vez de multiplicando. «El doble de» es un producto.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.37), 90,
   $it$¿Cómo se escribe «el doble de la suma entre un número y $5$»?$it$,
   $it$$2(n+5)$$it$,
   $it$$2n + 5$$it$,
   $it$$2n + 10$$it$,
   $it$$n + 10$$it$,
   $it$A$it$,
   $it$Correcto. Primero se forma la suma $n+5$ y después se dobla toda: por eso el paréntesis.$it$,
   $it$Esa es «el doble de un número, aumentado en $5$», que es otra cosa: acá lo que se dobla es la **suma completa**.$it$,
   $it$El resultado es correcto si se desarrolla el paréntesis, pero la pregunta pide la expresión que traduce el enunciado; además $2n+10$ ya está distribuido.$it$,
   $it$Se dobló solo el $5$ y no el número. El doble alcanza a los dos sumandos.$it$,
   null, $it$algebra/traduce-palabra-por-palabra$it$, null, $it$algebra/no-distribuye-a-todos-los-terminos$it$),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.29), 100,
   $it$Reduce la expresión $5a - 3a + a$.$it$,
   $it$$2a$$it$,
   $it$$9a$$it$,
   $it$$3a$$it$,
   $it$$1a^3$$it$,
   $it$C$it$,
   $it$Se reducieron los dos primeros y se olvidó el último término. La $a$ sola vale $1a$ y también suma.$it$,
   $it$Se sumaron los tres coeficientes ignorando el signo menos del segundo.$it$,
   $it$Correcto. $5 - 3 + 1 = 3$, así que queda $3a$. La letra sola cuenta como $1a$.$it$,
   $it$Se multiplicaron los términos en vez de sumarlos y restarlos: por eso apareció el exponente.$it$,
   $it$algebra/letra-sola-no-tiene-coeficiente$it$, null, null, $it$algebra/multiplica-monomios-sin-tocar-el-exponente$it$),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.21), 110,
   $it$¿Cuál es el valor de $x^2$ cuando $x = -2$?$it$,
   $it$$-4$$it$,
   $it$$-2$$it$,
   $it$$2$$it$,
   $it$$4$$it$,
   $it$D$it$,
   $it$El signo negativo también se eleva: $(-2)^2 = (-2)\times(-2)$, y dos negativos dan positivo.$it$,
   $it$Se reemplazó el valor y no se aplicó el exponente.$it$,
   $it$Se cambió el signo pero no se elevó al cuadrado.$it$,
   $it$Correcto. $(-2)^2 = (-2)\times(-2) = 4$.$it$,
   $it$algebra/potencia-antes-o-despues-del-signo$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.13), 120,
   $it$Suprime el paréntesis y reduce: $3 + (2x - 1)$.$it$,
   $it$$2x - 4$$it$,
   $it$$2x + 2$$it$,
   $it$$6x - 3$$it$,
   $it$$2x + 4$$it$,
   $it$B$it$,
   $it$El signo del $-1$ se mantiene, pero se restó del $3$ en vez de sumarse a él: $3 + (-1) = 2$.$it$,
   $it$Correcto. Con un $+$ delante, el paréntesis se abre sin cambiar nada: $3 + 2x - 1 = 2x + 2$.$it$,
   $it$Se multiplicó el $3$ por lo de adentro. El signo entre el $3$ y el paréntesis es una suma, no un producto.$it$,
   $it$El $-1$ se sumó en vez de restarse. Dentro del paréntesis el $1$ está restando.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-2.05), 130,
   $it$Suprime el paréntesis y reduce: $5 - (x - 2)$.$it$,
   $it$$7 - x$$it$,
   $it$$3 - x$$it$,
   $it$$3 + x$$it$,
   $it$$7 + x$$it$,
   $it$A$it$,
   $it$Correcto. El menos alcanza a los dos términos: $5 - x + 2 = 7 - x$.$it$,
   $it$El menos se aplicó solo al primer término del paréntesis. Al $-2$ de adentro también hay que cambiarle el signo, y queda $+2$.$it$,
   $it$Los dos signos quedaron cambiados al revés: el de la $x$ debía volverse negativo y el del $2$, positivo.$it$,
   $it$Se cambió el signo del $2$ pero no el de la $x$.$it$,
   null, $it$algebra/no-distribuye-el-signo-menos$it$, $it$algebra/no-distribuye-el-signo-menos$it$, $it$algebra/no-distribuye-el-signo-menos$it$),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-1.97), 140,
   $it$¿Cuál es el resultado de $2x \cdot 3x$?$it$,
   $it$$5x^2$$it$,
   $it$$6x$$it$,
   $it$$6x^2$$it$,
   $it$$5x$$it$,
   $it$C$it$,
   $it$Los coeficientes se sumaron en vez de multiplicarse. La parte literal quedó bien: $x \cdot x = x^2$.$it$,
   $it$Los coeficientes se multiplicaron bien, pero faltó el exponente: $x \cdot x = x^2$, no $x$.$it$,
   $it$Correcto. $2 \cdot 3 = 6$ y $x \cdot x = x^2$, así que queda $6x^2$.$it$,
   $it$Se sumaron los coeficientes y se dejó la letra sin exponente: es el resultado de tratar el producto como una suma.$it$,
   null, $it$algebra/multiplica-monomios-sin-tocar-el-exponente$it$, null, $it$algebra/multiplica-monomios-sin-tocar-el-exponente$it$),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-1.89), 150,
   $it$Reduce la expresión $4x - x$.$it$,
   $it$$4$$it$,
   $it$$4x$$it$,
   $it$$-4x$$it$,
   $it$$3x$$it$,
   $it$D$it$,
   $it$Se eliminó la letra al restarla. Restar una $x$ de cuatro $x$ deja tres $x$, no un número puro.$it$,
   $it$Se trató la $x$ sola como si valiera cero. La letra sin número delante lleva un $1$ implícito.$it$,
   $it$El signo quedó invertido. De $4x$ se está quitando $1x$, así que sobra una cantidad positiva.$it$,
   $it$Correcto. $4x - 1x = 3x$: la letra sola cuenta como $1x$.$it$,
   $it$algebra/letra-sola-no-tiene-coeficiente$it$, $it$algebra/letra-sola-no-tiene-coeficiente$it$, null, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-1.81), 160,
   $it$¿Cuál es el valor de $-x^2$ cuando $x = 3$?$it$,
   $it$$9$$it$,
   $it$$-9$$it$,
   $it$$6$$it$,
   $it$$-6$$it$,
   $it$B$it$,
   $it$El signo menos no está dentro de la potencia: sin paréntesis, primero se eleva $3$ al cuadrado y después se aplica el menos.$it$,
   $it$Correcto. $-x^2$ significa $-(x^2)$, así que es $-(3^2) = -9$.$it$,
   $it$Se multiplicó la base por el exponente. El cuadrado de $3$ es $3\times 3$, no $3\times 2$.$it$,
   $it$Además de multiplicar base por exponente, el signo quedó bien pero el valor no.$it$,
   $it$algebra/potencia-antes-o-despues-del-signo$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-1.74), 170,
   $it$Desarrolla $2(3x + 4)$.$it$,
   $it$$6x + 8$$it$,
   $it$$6x + 4$$it$,
   $it$$5x + 6$$it$,
   $it$$3x + 8$$it$,
   $it$A$it$,
   $it$Correcto. El $2$ multiplica a los dos términos: $2 \cdot 3x = 6x$ y $2 \cdot 4 = 8$.$it$,
   $it$El $2$ se aplicó solo al primer término. La propiedad distributiva alcanza a todo lo que está dentro del paréntesis.$it$,
   $it$Se sumó el $2$ en vez de multiplicar, y de forma distinta en cada término.$it$,
   $it$El $2$ se aplicó solo al segundo término, dejando el $3x$ intacto.$it$,
   null, $it$algebra/no-distribuye-a-todos-los-terminos$it$, null, $it$algebra/no-distribuye-a-todos-los-terminos$it$),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-1.66), 180,
   $it$Un rectángulo tiene lados de largo $x$ y $x+3$. ¿Cuál expresión representa su **perímetro**?$it$,
   $it$$x(x+3)$$it$,
   $it$$2x + 3$$it$,
   $it$$4x + 6$$it$,
   $it$$x^2 + 3x$$it$,
   $it$C$it$,
   $it$Esa es el **área**: el producto de los dos lados. El perímetro es la suma de los cuatro lados.$it$,
   $it$Se sumaron los dos lados una sola vez. Un rectángulo tiene cuatro lados: cada medida aparece dos veces.$it$,
   $it$Correcto. $2x + 2(x+3) = 2x + 2x + 6 = 4x + 6$.$it$,
   $it$Es el área con el paréntesis ya desarrollado, no el perímetro.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-1.58), 190,
   $it$Reduce la expresión $2(x+1) - (x-3)$.$it$,
   $it$$x - 1$$it$,
   $it$$3x - 2$$it$,
   $it$$x - 5$$it$,
   $it$$x + 5$$it$,
   $it$D$it$,
   $it$El signo menos del segundo paréntesis se aplicó solo a la $x$: al $-3$ también hay que cambiarle el signo, y queda $+3$.$it$,
   $it$Los dos paréntesis se sumaron en vez de restarse. El segundo va con un menos delante.$it$,
   $it$El $-3$ se mantuvo con su signo original. Al suprimir un paréntesis precedido de menos, todos los signos de adentro cambian.$it$,
   $it$Correcto. $2x + 2 - x + 3 = x + 5$.$it$,
   $it$algebra/no-distribuye-el-signo-menos$it$, null, $it$algebra/no-distribuye-el-signo-menos$it$, null),
  ($it$algebra$it$, $it$algebra/expresiones$it$,
   (-1.5), 200,
   $it$Si $a = 1$ y $b = 2$, ¿qué relación hay entre $(a+b)^2$ y $a^2 + b^2$?$it$,
   $it$Son iguales, valen $5$$it$,
   $it$$(a+b)^2 = 9$ y $a^2+b^2 = 5$: no son iguales$it$,
   $it$Son iguales, valen $9$$it$,
   $it$$(a+b)^2 = 5$ y $a^2+b^2 = 9$$it$,
   $it$B$it$,
   $it$$(a+b)^2$ se calculó repartiendo el exponente sobre la suma, y eso no vale: hay que sumar primero y elevar después.$it$,
   $it$Correcto. $(1+2)^2 = 3^2 = 9$, mientras que $1^2+2^2 = 5$. La diferencia de $4$ es el doble producto $2ab$ que falta.$it$,
   $it$Los dos valores no coinciden: $a^2+b^2$ da $5$, no $9$. El exponente no se reparte sobre una suma.$it$,
   $it$Los valores están intercambiados: el que da $9$ es $(a+b)^2$, porque primero se suma.$it$,
   $it$algebra/cuadrado-de-suma-como-suma-de-cuadrados$it$, null, $it$algebra/cuadrado-de-suma-como-suma-de-cuadrados$it$, $it$algebra/cuadrado-de-suma-como-suma-de-cuadrados$it$),

  -- ===========================================================================
  -- algebra/ecuaciones
  -- ===========================================================================
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-2.2), 10,
   $it$Resuelve la ecuación $x + 3 = 7$.$it$,
   $it$$x = 10$$it$,
   $it$$x = 4$$it$,
   $it$$x = 21$$it$,
   $it$$x = 3$$it$,
   $it$B$it$,
   $it$El $3$ pasó al otro lado sumando en vez de restando. Para dejar sola la $x$ hay que **restar** $3$ a los dos miembros.$it$,
   $it$Correcto. Restando $3$ a ambos lados: $x = 7 - 3 = 4$.$it$,
   $it$Se multiplicó en vez de restar. La operación que deshace una suma es la resta.$it$,
   $it$Ese es el número que acompaña a la $x$, no su valor.$it$,
   $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-2.12), 20,
   $it$Resuelve la ecuación $x - 2 = 5$.$it$,
   $it$$x = 3$$it$,
   $it$$x = 10$$it$,
   $it$$x = -3$$it$,
   $it$$x = 7$$it$,
   $it$D$it$,
   $it$El $2$ pasó restando en vez de sumando. Como está restando a la izquierda, hay que **sumar** $2$ a los dos lados.$it$,
   $it$Se multiplicó por $2$. La operación que deshace una resta es la suma.$it$,
   $it$Además de restar en vez de sumar, el resultado quedó con el signo cambiado.$it$,
   $it$Correcto. Sumando $2$ a ambos lados: $x = 5 + 2 = 7$.$it$,
   $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, null, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-2.03), 30,
   $it$Resuelve la ecuación $3x = 12$.$it$,
   $it$$x = 4$$it$,
   $it$$x = 36$$it$,
   $it$$x = 9$$it$,
   $it$$x = 15$$it$,
   $it$A$it$,
   $it$Correcto. Dividiendo ambos lados por $3$: $x = 12 \div 3 = 4$.$it$,
   $it$Se multiplicó por $3$ en vez de dividir. Como el $3$ está multiplicando a la $x$, se deshace dividiendo.$it$,
   $it$Se restó $3$. El $3$ no está sumando: está multiplicando.$it$,
   $it$Se sumó $3$. La operación inversa de multiplicar es dividir.$it$,
   null, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, $it$ecuaciones/invierte-la-operacion-al-despejar$it$),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.95), 40,
   $it$Resuelve la ecuación $\dfrac{x}{2} = 4$.$it$,
   $it$$x = 2$$it$,
   $it$$x = 6$$it$,
   $it$$x = 8$$it$,
   $it$$x = 4$$it$,
   $it$C$it$,
   $it$Se dividió otra vez por $2$. La $x$ ya está dividida: para liberarla hay que **multiplicar**.$it$,
   $it$Se sumó $2$. El $2$ está dividiendo, no restando.$it$,
   $it$Correcto. Multiplicando ambos lados por $2$: $x = 4 \times 2 = 8$.$it$,
   $it$Se dejó el valor del otro miembro sin deshacer la división.$it$,
   $it$ecuaciones/invierte-la-operacion-al-despejar$it$, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, null, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.87), 50,
   $it$Resuelve la ecuación $2x + 1 = 9$.$it$,
   $it$$x = 5$$it$,
   $it$$x = 4$$it$,
   $it$$x = 10$$it$,
   $it$$x = 8$$it$,
   $it$B$it$,
   $it$Se dividió $9$ por $2$ antes de restar el $1$, o se restó el $1$ después de dividir. El orden es: primero se quita lo que suma, después se deshace lo que multiplica.$it$,
   $it$Correcto. $2x = 9 - 1 = 8$, y dividiendo por $2$ queda $x = 4$.$it$,
   $it$El $1$ pasó sumando en vez de restando, y además faltó dividir por $2$.$it$,
   $it$Se restó bien el $1$, pero faltó el último paso: dividir por $2$.$it$,
   null, null, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.79), 60,
   $it$¿Cuál de estos valores **es solución** de $2x = 10$?$it$,
   $it$$x = 20$$it$,
   $it$$x = 8$$it$,
   $it$$x = 12$$it$,
   $it$$x = 5$$it$,
   $it$D$it$,
   $it$Al reemplazar queda $2 \times 20 = 40$, que no es $10$. Comprobar reemplazando es siempre la forma de verificar.$it$,
   $it$Reemplazando: $2 \times 8 = 16$. Ese valor sale de restar $2$ en vez de dividir.$it$,
   $it$Reemplazando: $2 \times 12 = 24$. Ese valor sale de sumar $2$.$it$,
   $it$Correcto. $2 \times 5 = 10$: al reemplazar, la igualdad se cumple.$it$,
   $it$ecuaciones/invierte-la-operacion-al-despejar$it$, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.7), 70,
   $it$Resuelve la ecuación $3x - 5 = 10$.$it$,
   $it$$x = 5$$it$,
   $it$$x = \dfrac{5}{3}$$it$,
   $it$$x = 15$$it$,
   $it$$x = 45$$it$,
   $it$A$it$,
   $it$Correcto. $3x = 10 + 5 = 15$, y dividiendo por $3$ queda $x = 5$.$it$,
   $it$El $5$ se restó en vez de sumarse: $10 - 5 = 5$, y de ahí salió $\frac{5}{3}$. Como el $5$ está restando, pasa **sumando**.$it$,
   $it$Se sumó bien el $5$, pero faltó dividir por $3$.$it$,
   $it$Se multiplicó por $3$ en vez de dividir, después de sumar el $5$.$it$,
   null, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null, $it$ecuaciones/invierte-la-operacion-al-despejar$it$),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.62), 80,
   $it$Resuelve la ecuación $4 - x = 1$.$it$,
   $it$$x = -3$$it$,
   $it$$x = 5$$it$,
   $it$$x = 3$$it$,
   $it$$x = -5$$it$,
   $it$C$it$,
   $it$Se llegó a $-x = -3$ y ahí quedó: falta el último paso, multiplicar por $-1$ para dejar la $x$ positiva.$it$,
   $it$El $4$ pasó sumando en vez de restando. Como está sumando a la izquierda, se resta a los dos lados.$it$,
   $it$Correcto. $-x = 1 - 4 = -3$, y multiplicando por $-1$ queda $x = 3$. Se comprueba: $4 - 3 = 1$.$it$,
   $it$Se juntan los dos errores: el $4$ pasó con el signo equivocado y quedó el $-x$ sin resolver.$it$,
   $it$ecuaciones/coeficiente-negativo-pierde-el-signo$it$, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.54), 90,
   $it$Resuelve la ecuación $2(x + 1) = 8$.$it$,
   $it$$x = 7$$it$,
   $it$$x = 3$$it$,
   $it$$x = 4$$it$,
   $it$$x = 6$$it$,
   $it$B$it$,
   $it$El $2$ de afuera se ignoró y se resolvió $x + 1 = 8$. Ese factor multiplica a todo el paréntesis.$it$,
   $it$Correcto. Dividiendo por $2$: $x + 1 = 4$, así que $x = 3$. También sirve desarrollar: $2x + 2 = 8$.$it$,
   $it$Se dividió $8$ por $2$ y ahí quedó. Falta restar el $1$ que acompaña a la $x$ dentro del paréntesis.$it$,
   $it$Se desarrolló como $2x + 1 = 8$: el $2$ multiplicó solo a la $x$ y no al $1$.$it$,
   $it$ecuaciones/no-desarrolla-el-parentesis$it$, null, null, $it$algebra/no-distribuye-a-todos-los-terminos$it$),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.45), 100,
   $it$Resuelve la ecuación $5x = 2x + 9$.$it$,
   $it$$x = 9$$it$,
   $it$$x = \dfrac{9}{7}$$it$,
   $it$$x = 1$$it$,
   $it$$x = 3$$it$,
   $it$D$it$,
   $it$Se ignoró el $2x$ del lado derecho. Los términos con incógnita hay que juntarlos en un mismo miembro antes de dividir.$it$,
   $it$El $2x$ pasó sumando en vez de restando: $5x + 2x = 7x$. Al cambiar de lado, cambia de signo.$it$,
   $it$Se restaron mal los coeficientes: $5x - 2x$ da $3x$, no $9x$ ni $x$.$it$,
   $it$Correcto. $5x - 2x = 9$, o sea $3x = 9$, así que $x = 3$.$it$,
   null, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.37), 110,
   $it$Resuelve la ecuación $\dfrac{x}{3} + 1 = 4$.$it$,
   $it$$x = 9$$it$,
   $it$$x = 15$$it$,
   $it$$x = 3$$it$,
   $it$$x = 12$$it$,
   $it$A$it$,
   $it$Correcto. $\frac{x}{3} = 4 - 1 = 3$, y multiplicando por $3$ queda $x = 9$.$it$,
   $it$El $1$ se sumó en vez de restarse: $4 + 1 = 5$, y de ahí $15$. Como está sumando, pasa restando.$it$,
   $it$Se restó bien el $1$, pero faltó multiplicar por $3$ para liberar la $x$.$it$,
   $it$Se multiplicó por $3$ antes de restar el $1$, aplicando el $3$ también al término independiente.$it$,
   null, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null, $it$ecuaciones/divide-solo-un-termino$it$),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.29), 120,
   $it$Resuelve la ecuación $2x + 3 = x + 7$.$it$,
   $it$$x = 10$$it$,
   $it$$x = \dfrac{10}{3}$$it$,
   $it$$x = 4$$it$,
   $it$$x = 2$$it$,
   $it$C$it$,
   $it$Se juntaron los términos independientes sumándolos: $3 + 7$. El $3$ pasa al otro lado restando.$it$,
   $it$Los términos con incógnita se sumaron en vez de restarse: $2x + x = 3x$. Al pasar de lado, el $x$ cambia de signo.$it$,
   $it$Correcto. $2x - x = 7 - 3$, o sea $x = 4$. Se comprueba: $2(4)+3 = 11$ y $4+7 = 11$.$it$,
   $it$Se restaron los coeficientes en el orden equivocado o se dividió de más. La resta correcta deja $x$ con coeficiente $1$.$it$,
   $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.2), 130,
   $it$Resuelve la ecuación $-2x = 6$.$it$,
   $it$$x = 3$$it$,
   $it$$x = -3$$it$,
   $it$$x = -12$$it$,
   $it$$x = 4$$it$,
   $it$B$it$,
   $it$Se dividió por $2$ y se soltó el signo. Dividir por $-2$ cambia el signo del resultado.$it$,
   $it$Correcto. $x = 6 \div (-2) = -3$. Se comprueba: $-2 \times (-3) = 6$.$it$,
   $it$Se multiplicó por $-2$ en vez de dividir.$it$,
   $it$Se sumó $2$ en vez de dividir, y además se perdió el signo.$it$,
   $it$ecuaciones/coeficiente-negativo-pierde-el-signo$it$, null, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, $it$ecuaciones/invierte-la-operacion-al-despejar$it$),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.12), 140,
   $it$Resuelve la ecuación $\dfrac{x+1}{2} = 3$.$it$,
   $it$$x = 2$$it$,
   $it$$x = 7$$it$,
   $it$$x = 6$$it$,
   $it$$x = 5$$it$,
   $it$D$it$,
   $it$Se dividió $3$ entre $2$ y se restó $1$, aplicando las operaciones al revés. El $2$ está dividiendo, así que pasa multiplicando.$it$,
   $it$Se multiplicó por $2$ y se sumó el $1$ en vez de restarlo. Dentro del numerador el $1$ está sumando: pasa restando.$it$,
   $it$Se multiplicó por $2$ y ahí quedó: falta restar el $1$ que acompaña a la $x$.$it$,
   $it$Correcto. Multiplicando por $2$: $x + 1 = 6$, así que $x = 5$.$it$,
   $it$ecuaciones/invierte-la-operacion-al-despejar$it$, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-1.04), 150,
   $it$Resuelve la ecuación $3(x - 2) = 2x + 1$.$it$,
   $it$$x = 7$$it$,
   $it$$x = 5$$it$,
   $it$$x = 3$$it$,
   $it$$x = 1$$it$,
   $it$A$it$,
   $it$Correcto. $3x - 6 = 2x + 1$, entonces $3x - 2x = 1 + 6$ y $x = 7$.$it$,
   $it$El $3$ multiplicó solo a la $x$ y no al $-2$: quedó $3x - 2 = 2x + 1$.$it$,
   $it$El paréntesis no se desarrolló: se resolvió $x - 2 = 2x + 1$ ignorando el factor $3$.$it$,
   $it$Los términos cambiaron de lado sin cambiar de signo, y el $-6$ quedó restando en el miembro equivocado.$it$,
   null, $it$algebra/no-distribuye-a-todos-los-terminos$it$, $it$ecuaciones/no-desarrolla-el-parentesis$it$, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-0.96), 160,
   $it$El triple de un número, disminuido en $4$, es igual a $11$. ¿Cuál es el número?$it$,
   $it$$\dfrac{7}{3}$$it$,
   $it$$45$$it$,
   $it$$5$$it$,
   $it$$3$$it$,
   $it$C$it$,
   $it$Se planteó bien la ecuación pero el $4$ se restó en vez de sumarse: $3n = 11 - 4$. Como está restando, pasa sumando.$it$,
   $it$Se multiplicó por $3$ en vez de dividir, después de sumar el $4$.$it$,
   $it$Correcto. La ecuación es $3n - 4 = 11$, así que $3n = 15$ y $n = 5$.$it$,
   $it$Ese es el número que multiplica, no el número buscado.$it$,
   $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, null, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-0.87), 170,
   $it$Resuelve la ecuación $\dfrac{x}{2} + \dfrac{x}{3} = 5$.$it$,
   $it$$x = 5$$it$,
   $it$$x = 6$$it$,
   $it$$x = 25$$it$,
   $it$$x = 30$$it$,
   $it$B$it$,
   $it$Se sumaron las fracciones como si dieran $x$: $\frac{x}{2}+\frac{x}{3}$ no es $x$, sino $\frac{5x}{6}$.$it$,
   $it$Correcto. Con denominador común $6$: $\frac{3x+2x}{6} = 5$, o sea $5x = 30$ y $x = 6$.$it$,
   $it$Se multiplicó por $5$ en vez de despejar. El $5$ es el resultado, no un factor de la incógnita.$it$,
   $it$Se multiplicó todo por $6$ y ahí quedó: $5x = 30$ es un paso intermedio, falta dividir por $5$.$it$,
   $it$fracciones/suma-numeradores-y-denominadores$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-0.79), 180,
   $it$¿Cuál es la solución de $2x + 6 = 2x + 1$?$it$,
   $it$$x = 0$$it$,
   $it$$x = -5$$it$,
   $it$$x = 5$$it$,
   $it$No tiene solución$it$,
   $it$D$it$,
   $it$Que la incógnita desaparezca no significa que valga cero: reemplazando $x = 0$ queda $6 = 1$, que es falso.$it$,
   $it$Se restaron los términos independientes y se tomó eso como la solución. Al cancelar los $2x$ no queda ninguna ecuación para la incógnita.$it$,
   $it$Mismo caso con el signo cambiado. Reemplazando $x = 5$: $16 = 11$, que tampoco se cumple.$it$,
   $it$Correcto. Al restar $2x$ a los dos lados queda $6 = 1$, que es falso para cualquier $x$: la ecuación no tiene solución.$it$,
   $it$ecuaciones/sin-solucion-como-cero$it$, $it$ecuaciones/sin-solucion-como-cero$it$, $it$ecuaciones/sin-solucion-como-cero$it$, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-0.71), 190,
   $it$La suma de dos números enteros consecutivos es $27$. ¿Cuáles son?$it$,
   $it$$13$ y $14$$it$,
   $it$$13{,}5$ y $13{,}5$$it$,
   $it$$12$ y $15$$it$,
   $it$$26$ y $1$$it$,
   $it$A$it$,
   $it$Correcto. Si el primero es $n$, el segundo es $n+1$: $2n + 1 = 27$, así que $n = 13$.$it$,
   $it$Se dividió $27$ entre $2$. Eso da dos números iguales y además no enteros; consecutivos significa que se diferencian en $1$.$it$,
   $it$Suman $27$, pero no son consecutivos: entre ellos hay tres unidades de diferencia.$it$,
   $it$Suman $27$, pero tampoco son consecutivos. La condición de consecutivos es la que fija la respuesta.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/ecuaciones$it$,
   (-0.6), 200,
   $it$Resuelve la ecuación $0{,}5x + 2 = 4{,}5$.$it$,
   $it$$x = 2{,}5$$it$,
   $it$$x = 1{,}25$$it$,
   $it$$x = 5$$it$,
   $it$$x = 13$$it$,
   $it$C$it$,
   $it$Se restó bien el $2$, pero faltó dividir por $0{,}5$. Ese valor es $0{,}5x$, no $x$.$it$,
   $it$Se multiplicó por $0{,}5$ en vez de dividir. Como $0{,}5$ está multiplicando a la $x$, se deshace dividiendo — y dividir por $0{,}5$ **duplica**.$it$,
   $it$Correcto. $0{,}5x = 4{,}5 - 2 = 2{,}5$, y $2{,}5 \div 0{,}5 = 5$.$it$,
   $it$El $2$ se sumó en vez de restarse: $4{,}5 + 2 = 6{,}5$, y de ahí $13$.$it$,
   null, $it$ecuaciones/invierte-la-operacion-al-despejar$it$, null, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$),

  -- ===========================================================================
  -- algebra/sistemas
  -- ===========================================================================
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-1.2), 10,
   $it$¿Qué es la **solución** de un sistema de dos ecuaciones con dos incógnitas?$it$,
   $it$El valor de $x$$it$,
   $it$La suma de las dos ecuaciones$it$,
   $it$El par $(x, y)$ que cumple las dos ecuaciones a la vez$it$,
   $it$Cualquier par que cumpla una de las dos$it$,
   $it$C$it$,
   $it$Falta la mitad: hay dos incógnitas, así que la solución tiene dos valores.$it$,
   $it$Sumar las ecuaciones es una **técnica** para resolver, no la solución.$it$,
   $it$Correcto. La solución es el par que satisface las dos ecuaciones simultáneamente.$it$,
   $it$Con una sola ecuación hay infinitos pares que la cumplen. Lo que distingue a la solución es que cumple **las dos**.$it$,
   $it$sistemas/solucion-como-un-solo-numero$it$, null, null, $it$sistemas/resuelve-una-sola-ecuacion$it$),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-1.11), 20,
   $it$¿Es $(x, y) = (2, 1)$ solución del sistema $x + y = 3$ y $x - y = 1$?$it$,
   $it$Sí, porque cumple las dos ecuaciones$it$,
   $it$No, porque $2 + 1 \neq 3$$it$,
   $it$Sí, pero solo cumple la primera$it$,
   $it$No, porque faltan más ecuaciones$it$,
   $it$A$it$,
   $it$Correcto. $2 + 1 = 3$ y $2 - 1 = 1$: las dos se cumplen.$it$,
   $it$$2 + 1$ sí es $3$. Conviene reemplazar con cuidado antes de descartar.$it$,
   $it$También cumple la segunda: $2 - 1 = 1$. Hay que comprobar las dos antes de concluir.$it$,
   $it$Con dos incógnitas bastan dos ecuaciones independientes, y acá las hay.$it$,
   null, null, $it$sistemas/resuelve-una-sola-ecuacion$it$, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-1.01), 30,
   $it$Resuelve el sistema $y = x + 1$ y $x + y = 5$.$it$,
   $it$$(3, 2)$$it$,
   $it$$(1, 2)$$it$,
   $it$$x = 2$$it$,
   $it$$(2, 3)$$it$,
   $it$D$it$,
   $it$Los valores están intercambiados: la primera ecuación dice que $y$ es **mayor** que $x$ en una unidad.$it$,
   $it$Se reemplazó sin sumar bien: con $x = 1$ queda $y = 2$, y $1 + 2 = 3$, no $5$.$it$,
   $it$Ese es el valor de $x$, pero falta $y$: la solución de un sistema es un par.$it$,
   $it$Correcto. Sustituyendo: $x + (x+1) = 5$, o sea $2x = 4$ y $x = 2$; entonces $y = 3$.$it$,
   null, null, $it$sistemas/solucion-como-un-solo-numero$it$, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.92), 40,
   $it$Resuelve el sistema $x + y = 10$ y $x - y = 2$.$it$,
   $it$$(4, 6)$$it$,
   $it$$(6, 4)$$it$,
   $it$$(5, 5)$$it$,
   $it$$(8, 2)$$it$,
   $it$B$it$,
   $it$Los valores están intercambiados: la segunda ecuación dice que $x$ es el **mayor**, porque al restarle $y$ queda positivo.$it$,
   $it$Correcto. Sumando las dos ecuaciones: $2x = 12$, así que $x = 6$ y $y = 4$.$it$,
   $it$Ese par cumple la primera ecuación pero no la segunda: $5 - 5 = 0$, no $2$.$it$,
   $it$Ese par cumple la primera, pero $8 - 2 = 6$, no $2$.$it$,
   null, null, $it$sistemas/resuelve-una-sola-ecuacion$it$, $it$sistemas/resuelve-una-sola-ecuacion$it$),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.82), 50,
   $it$Si $2x + y = 7$ y $y = 3$, ¿cuánto vale $x$?$it$,
   $it$$4$$it$,
   $it$$5$$it$,
   $it$$2$$it$,
   $it$$10$$it$,
   $it$C$it$,
   $it$Se restó el $3$ y ahí quedó: $2x = 4$ es un paso intermedio, falta dividir por $2$.$it$,
   $it$Se restó el $3$ del $7$ y después se sumó otra vez, o se despejó sin usar el $2$.$it$,
   $it$Correcto. $2x + 3 = 7$, entonces $2x = 4$ y $x = 2$.$it$,
   $it$El $3$ se sumó en vez de restarse. Como está sumando en el miembro izquierdo, pasa restando.$it$,
   null, null, null, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.73), 60,
   $it$Resuelve por eliminación el sistema $x + y = 5$ y $x - y = 1$.$it$,
   $it$$(3, 2)$$it$,
   $it$$(2, 3)$$it$,
   $it$$(6, 4)$$it$,
   $it$$(4, 1)$$it$,
   $it$A$it$,
   $it$Correcto. Sumando las dos ecuaciones se elimina $y$: $2x = 6$, así que $x = 3$ y $y = 2$.$it$,
   $it$Los valores están intercambiados: la segunda ecuación deja positivo a $x - y$, así que $x$ es el mayor.$it$,
   $it$Se sumaron las dos ecuaciones y no se dividió por $2$: $2x = 6$ da $x = 3$, no $6$.$it$,
   $it$Ese par cumple la segunda ecuación pero no la primera: $4 + 1 = 5$ sí… pero $4 - 1 = 3$, no $1$.$it$,
   null, null, null, $it$sistemas/resuelve-una-sola-ecuacion$it$),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.63), 70,
   $it$Si $3x + 2y = 12$ y $x = 2$, ¿cuánto vale $y$?$it$,
   $it$$6$$it$,
   $it$$9$$it$,
   $it$$4$$it$,
   $it$$3$$it$,
   $it$D$it$,
   $it$Se ignoró el término $3x$ y se resolvió $2y = 12$.$it$,
   $it$Se restó bien el $6$ pero después se sumó en vez de dividir, o se usó mal el coeficiente $2$.$it$,
   $it$Se reemplazó $x = 2$ y se restó $2$ en vez de $3 \times 2 = 6$.$it$,
   $it$Correcto. $3(2) + 2y = 12$, o sea $2y = 6$ y $y = 3$.$it$,
   $it$sistemas/resuelve-una-sola-ecuacion$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.54), 80,
   $it$Resuelve el sistema $x + 2y = 8$ y $x = 2y$.$it$,
   $it$$(2, 4)$$it$,
   $it$$(4, 2)$$it$,
   $it$$(8, 4)$$it$,
   $it$$(6, 1)$$it$,
   $it$B$it$,
   $it$Los valores están intercambiados: la segunda ecuación dice que $x$ es el **doble** de $y$.$it$,
   $it$Correcto. Sustituyendo: $2y + 2y = 8$, así que $y = 2$ y $x = 4$.$it$,
   $it$Cumple la relación $x = 2y$, pero no la primera ecuación: $8 + 8 = 16$, no $8$.$it$,
   $it$No cumple ninguna de las dos: $6 + 2 = 8$ es casualidad de la primera, pero $6 \neq 2$.$it$,
   null, null, $it$sistemas/resuelve-una-sola-ecuacion$it$, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.44), 90,
   $it$Resuelve el sistema $2x + 3y = 12$ y $2x - 3y = 0$.$it$,
   $it$$(6, 0)$$it$,
   $it$$(2, 3)$$it$,
   $it$$(3, 2)$$it$,
   $it$$(0, 4)$$it$,
   $it$C$it$,
   $it$Se sumaron las ecuaciones y no se dividió: $4x = 12$ da $x = 3$. Además con $y = 0$ la segunda ecuación daría $2x = 0$.$it$,
   $it$Los valores están intercambiados. Reemplazando: $2(2) + 3(3) = 13$, no $12$.$it$,
   $it$Correcto. Sumando: $4x = 12$, así que $x = 3$; y de la segunda, $3y = 6$ y $y = 2$.$it$,
   $it$Cumple la primera ecuación pero no la segunda: $0 - 12 = -12$, no $0$.$it$,
   null, null, null, $it$sistemas/resuelve-una-sola-ecuacion$it$),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.35), 100,
   $it$Dos cuadernos y un lápiz cuestan $\$3.500$. Un cuaderno y un lápiz cuestan $\$2.000$. ¿Cuánto cuesta un cuaderno?$it$,
   $it$$\$1.500$$it$,
   $it$$\$500$$it$,
   $it$$\$2.000$$it$,
   $it$$\$1.750$$it$,
   $it$A$it$,
   $it$Correcto. Restando la segunda ecuación de la primera se elimina el lápiz: $c = 3.500 - 2.000 = \$1.500$.$it$,
   $it$Ese es el precio del **lápiz**: $2.000 - 1.500$. La pregunta es por el cuaderno.$it$,
   $it$Ese es el total de la segunda compra, que incluye el lápiz.$it$,
   $it$Se dividió la primera compra por dos, como si los dos artículos costaran lo mismo.$it$,
   null, null, null, $it$sistemas/traduce-mal-el-enunciado$it$),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.25), 110,
   $it$¿Qué ocurre con el sistema $x + y = 2$ y $x + y = 5$?$it$,
   $it$Tiene infinitas soluciones$it$,
   $it$La solución es $(0, 0)$$it$,
   $it$La solución es $x = 3{,}5$$it$,
   $it$No tiene solución$it$,
   $it$D$it$,
   $it$Infinitas soluciones ocurre cuando las dos ecuaciones son **la misma recta**. Acá son paralelas: nunca se cruzan.$it$,
   $it$Reemplazando $(0,0)$: $0 = 2$ es falso. Que no haya solución no significa que sea el origen.$it$,
   $it$Se promediaron los dos valores. Una suma no puede valer $2$ y $5$ a la vez, sin importar qué valores tomen las incógnitas.$it$,
   $it$Correcto. Una misma expresión, $x+y$, no puede valer $2$ y $5$ simultáneamente: las rectas son paralelas.$it$,
   $it$sistemas/confunde-sin-solucion-con-infinitas$it$, $it$ecuaciones/sin-solucion-como-cero$it$, null, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.16), 120,
   $it$¿Qué ocurre con el sistema $x + y = 2$ y $2x + 2y = 4$?$it$,
   $it$No tiene solución$it$,
   $it$Tiene infinitas soluciones$it$,
   $it$La única solución es $(1, 1)$$it$,
   $it$La única solución es $(2, 4)$$it$,
   $it$B$it$,
   $it$Sin solución sería si las rectas fueran paralelas y distintas. Acá la segunda ecuación es la primera multiplicada por $2$: son la misma recta.$it$,
   $it$Correcto. La segunda es el doble de la primera, así que aportan la misma información: cualquier par que sume $2$ sirve.$it$,
   $it$$(1,1)$ es **una** de las soluciones, pero no la única: $(0,2)$ y $(3,-1)$ también cumplen las dos ecuaciones.$it$,
   $it$Ese par no cumple ninguna de las dos: $2 + 4 = 6$, no $2$.$it$,
   $it$sistemas/confunde-sin-solucion-con-infinitas$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (-0.06), 130,
   $it$Si las dos ecuaciones de un sistema se dibujan como rectas en el plano, ¿qué representa la solución?$it$,
   $it$El punto donde cada recta corta el eje $y$$it$,
   $it$La pendiente común de las dos rectas$it$,
   $it$El punto donde las dos rectas se cortan$it$,
   $it$El área encerrada entre las rectas$it$,
   $it$C$it$,
   $it$Ese punto pertenece a una sola recta cada vez. La solución tiene que estar en las **dos**.$it$,
   $it$Si las dos rectas tuvieran la misma pendiente serían paralelas, y el sistema no tendría solución única.$it$,
   $it$Correcto. El punto de intersección es el único par $(x,y)$ que pertenece a las dos rectas, o sea que cumple las dos ecuaciones.$it$,
   $it$Dos rectas no encierran ningún área. La solución es un punto, no una región.$it$,
   $it$sistemas/resuelve-una-sola-ecuacion$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (0.03), 140,
   $it$Resuelve el sistema $3x - y = 5$ y $x + y = 7$.$it$,
   $it$$(3, 4)$$it$,
   $it$$(4, 3)$$it$,
   $it$$(2, 5)$$it$,
   $it$$(1, 6)$$it$,
   $it$A$it$,
   $it$Correcto. Sumando las dos ecuaciones se elimina $y$: $4x = 12$, así que $x = 3$ y $y = 4$.$it$,
   $it$Los valores están intercambiados. Reemplazando: $3(4) - 3 = 9$, no $5$.$it$,
   $it$Cumple la segunda ecuación pero no la primera: $3(2) - 5 = 1$, no $5$.$it$,
   $it$También cumple solo la segunda: $3(1) - 6 = -3$.$it$,
   null, null, $it$sistemas/resuelve-una-sola-ecuacion$it$, $it$sistemas/resuelve-una-sola-ecuacion$it$),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (0.13), 150,
   $it$Dos hermanos suman $40$ años y se llevan $10$ años de diferencia. ¿Qué edad tiene cada uno?$it$,
   $it$$30$ y $10$$it$,
   $it$$20$ y $20$$it$,
   $it$$35$ y $5$$it$,
   $it$$25$ y $15$$it$,
   $it$D$it$,
   $it$La diferencia es de $20$ años, no de $10$. Suman bien, pero falta la segunda condición.$it$,
   $it$Suman $40$, pero la diferencia es $0$. Es la solución de repartir en partes iguales, no la del sistema.$it$,
   $it$La suma es correcta, pero la diferencia es de $30$ años.$it$,
   $it$Correcto. Con $x + y = 40$ y $x - y = 10$: sumando queda $2x = 50$, así que $x = 25$ y $y = 15$.$it$,
   $it$sistemas/resuelve-una-sola-ecuacion$it$, $it$sistemas/resuelve-una-sola-ecuacion$it$, $it$sistemas/resuelve-una-sola-ecuacion$it$, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (0.22), 160,
   $it$Resuelve el sistema $2x + y = 5$ y $3x - y = 5$.$it$,
   $it$$(1, 3)$$it$,
   $it$$(2, 1)$$it$,
   $it$$(5, 0)$$it$,
   $it$$(0, 5)$$it$,
   $it$B$it$,
   $it$Cumple la primera ecuación pero no la segunda: $3(1) - 3 = 0$, no $5$.$it$,
   $it$Correcto. Sumando se elimina $y$: $5x = 10$, así que $x = 2$ y $y = 1$.$it$,
   $it$Cumple la segunda ecuación pero no la primera: $2(5) + 0 = 10$, no $5$.$it$,
   $it$Cumple la primera, pero en la segunda da $-5$.$it$,
   $it$sistemas/resuelve-una-sola-ecuacion$it$, null, $it$sistemas/resuelve-una-sola-ecuacion$it$, $it$sistemas/resuelve-una-sola-ecuacion$it$),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (0.32), 170,
   $it$Tres entradas de adulto y dos de niño cuestan $\$26.000$. Dos de adulto y tres de niño cuestan $\$24.000$. ¿Cuánto cuesta una entrada de adulto?$it$,
   $it$$\$5.000$$it$,
   $it$$\$4.000$$it$,
   $it$$\$6.000$$it$,
   $it$$\$10.000$$it$,
   $it$C$it$,
   $it$Ese es el promedio de las dos entradas. Los precios no son iguales: el sistema los distingue.$it$,
   $it$Ese es el precio de la entrada de **niño**. La pregunta es por la de adulto.$it$,
   $it$Correcto. Sumando las dos ecuaciones: $5a + 5n = 50.000$, o sea $a + n = 10.000$; restándolas: $a - n = 2.000$. De ahí $a = \$6.000$.$it$,
   $it$Ese es el valor de $a + n$, o sea de una entrada de cada tipo, no de una sola de adulto.$it$,
   $it$sistemas/traduce-mal-el-enunciado$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (0.41), 180,
   $it$Resuelve el sistema $4x + 3y = 18$ y $2x - y = 4$.$it$,
   $it$$(3, 2)$$it$,
   $it$$(2, 3)$$it$,
   $it$$(4, 4)$$it$,
   $it$$(1, -2)$$it$,
   $it$A$it$,
   $it$Correcto. De la segunda, $y = 2x - 4$; sustituyendo: $4x + 6x - 12 = 18$, o sea $x = 3$ e $y = 2$.$it$,
   $it$Los valores están intercambiados. Reemplazando en la primera: $8 + 9 = 17$, no $18$.$it$,
   $it$Cumple la segunda ecuación pero no la primera: $4(4) + 3(4) = 28$, no $18$.$it$,
   $it$Cumple la segunda ecuación pero no la primera: $4 - 6 = -2$, no $18$.$it$,
   null, null, $it$sistemas/resuelve-una-sola-ecuacion$it$, $it$sistemas/resuelve-una-sola-ecuacion$it$),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (0.51), 190,
   $it$¿Para qué valor de $k$ el sistema $2x + 3y = 5$ y $4x + ky = 7$ **no tiene solución**?$it$,
   $it$$k = 3$$it$,
   $it$$k = 2$$it$,
   $it$$k = 12$$it$,
   $it$$k = 6$$it$,
   $it$D$it$,
   $it$Con $k = 3$ las rectas tienen pendientes distintas y se cortan: el sistema tendría solución única.$it$,
   $it$Mismo caso: con $k = 2$ las pendientes difieren y hay un único punto de corte.$it$,
   $it$Se multiplicó el $3$ por $4$ en vez de por el factor que relaciona los primeros coeficientes, que es $4 \div 2 = 2$.$it$,
   $it$Correcto. Para que sean paralelas, la segunda ecuación debe ser proporcional a la primera en los coeficientes: $4 = 2 \times 2$ y $k = 3 \times 2 = 6$. Como $7 \neq 5 \times 2$, son paralelas distintas y no hay solución.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/sistemas$it$,
   (0.6), 200,
   $it$Una alcancía tiene $100$ monedas, entre monedas de $\$100$ y de $\$500$, y suman $\$30.000$. ¿Cuántas monedas de $\$500$ hay?$it$,
   $it$$60$$it$,
   $it$$50$$it$,
   $it$$100$$it$,
   $it$$25$$it$,
   $it$B$it$,
   $it$Con $60$ monedas de $\$500$ y $40$ de $\$100$ el total sería $\$34.000$, no $\$30.000$.$it$,
   $it$Correcto. Con $c + q = 100$ y $100c + 500q = 30.000$: dividiendo la segunda por $100$ queda $c + 5q = 300$, y restando la primera, $4q = 200$, así que $q = 50$.$it$,
   $it$Si todas fueran de $\$500$ el total sería $\$50.000$. La condición del monto es la que fija la mezcla.$it$,
   $it$Con $25$ monedas de $\$500$ y $75$ de $\$100$ el total sería $\$20.000$.$it$,
   null, null, $it$sistemas/resuelve-una-sola-ecuacion$it$, null),

  -- ===========================================================================
  -- algebra/polinomios
  -- ===========================================================================
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (-0.4), 10,
   $it$¿Cuál es el **grado** del polinomio $3x^2 + 2x - 1$?$it$,
   $it$$3$$it$,
   $it$$1$$it$,
   $it$$2$$it$,
   $it$$6$$it$,
   $it$C$it$,
   $it$Ese es el número de términos, no el grado. El grado lo fija el mayor exponente que aparece.$it$,
   $it$Ese es el exponente del segundo término. Hay que quedarse con el **mayor** de todos.$it$,
   $it$Correcto. El mayor exponente es el $2$ de $3x^2$.$it$,
   $it$Se sumaron los exponentes. El grado es el máximo, no la suma.$it$,
   $it$polinomios/grado-como-cantidad-de-terminos$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (-0.29), 20,
   $it$Suma los polinomios $(2x + 3) + (x - 1)$.$it$,
   $it$$3x + 2$$it$,
   $it$$3x + 4$$it$,
   $it$$2x^2 + 2$$it$,
   $it$$3x - 3$$it$,
   $it$A$it$,
   $it$Correcto. Se reducen los términos semejantes: $2x + x = 3x$ y $3 - 1 = 2$.$it$,
   $it$El $-1$ se sumó en vez de restarse. Dentro del segundo paréntesis el $1$ está restando.$it$,
   $it$Los términos con $x$ se multiplicaron en vez de sumarse.$it$,
   $it$Se restó el $3$ en vez de sumarlo, y el $1$ también: los dos paréntesis se están **sumando**.$it$,
   null, null, $it$algebra/multiplica-monomios-sin-tocar-el-exponente$it$, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (-0.19), 30,
   $it$Resta los polinomios $(3x + 5) - (x + 2)$.$it$,
   $it$$2x + 7$$it$,
   $it$$4x + 7$$it$,
   $it$$2x - 7$$it$,
   $it$$2x + 3$$it$,
   $it$D$it$,
   $it$El signo menos se aplicó a la $x$ pero no al $2$. Alcanza a todos los términos del paréntesis.$it$,
   $it$Los dos paréntesis se sumaron en vez de restarse.$it$,
   $it$Los signos quedaron invertidos: $5 - 2$ da $3$ positivo.$it$,
   $it$Correcto. $3x - x = 2x$ y $5 - 2 = 3$.$it$,
   $it$algebra/no-distribuye-el-signo-menos$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (-0.08), 40,
   $it$Desarrolla $x(x + 3)$.$it$,
   $it$$x + 3x$$it$,
   $it$$x^2 + 3x$$it$,
   $it$$x^2 + 3$$it$,
   $it$$4x$$it$,
   $it$B$it$,
   $it$El primer producto quedó sin resolver: $x \cdot x$ es $x^2$, no $x$.$it$,
   $it$Correcto. $x \cdot x = x^2$ y $x \cdot 3 = 3x$.$it$,
   $it$La $x$ multiplicó al primer término pero no al $3$. La distributiva alcanza a los dos.$it$,
   $it$Se sumaron $x$ y $3x$ como si el paréntesis ya estuviera desarrollado y fueran semejantes.$it$,
   $it$algebra/multiplica-monomios-sin-tocar-el-exponente$it$, null, $it$algebra/no-distribuye-a-todos-los-terminos$it$, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.02), 50,
   $it$Desarrolla $(x + 2)(x + 3)$.$it$,
   $it$$x^2 + 6$$it$,
   $it$$x^2 + 6x + 6$$it$,
   $it$$x^2 + 5x + 6$$it$,
   $it$$2x + 5$$it$,
   $it$C$it$,
   $it$Solo se multiplicó primero con primero y último con último. Faltan los dos productos cruzados: $3x$ y $2x$.$it$,
   $it$El término independiente y el cuadrático están bien, pero el término del medio salió del producto $2 \times 3$ en vez de la **suma** $2+3$.$it$,
   $it$Correcto. $x^2 + 3x + 2x + 6 = x^2 + 5x + 6$.$it$,
   $it$Se sumaron los términos en vez de multiplicarlos.$it$,
   $it$polinomios/multiplica-solo-los-primeros-terminos$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.13), 60,
   $it$Desarrolla $(x + 3)^2$.$it$,
   $it$$x^2 + 6x + 9$$it$,
   $it$$x^2 + 9$$it$,
   $it$$x^2 + 3x + 9$$it$,
   $it$$2x + 6$$it$,
   $it$A$it$,
   $it$Correcto. $(x+3)^2 = x^2 + 2(3)x + 9 = x^2 + 6x + 9$.$it$,
   $it$Se repartió el exponente sobre la suma. Falta el doble producto: elevar al cuadrado no es elevar cada término por separado.$it$,
   $it$El doble producto quedó a la mitad: es $2 \cdot x \cdot 3 = 6x$, no $3x$.$it$,
   $it$Se multiplicó por $2$ en vez de elevar al cuadrado. El exponente $2$ no es un factor.$it$,
   null, $it$polinomios/cuadrado-de-binomio-sin-doble-producto$it$, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.23), 70,
   $it$Desarrolla $(x - 2)^2$.$it$,
   $it$$x^2 - 4$$it$,
   $it$$x^2 + 4x + 4$$it$,
   $it$$x^2 - 2x + 4$$it$,
   $it$$x^2 - 4x + 4$$it$,
   $it$D$it$,
   $it$Se repartió el exponente sobre la resta. Falta el doble producto, y además el término independiente es $+4$.$it$,
   $it$El signo del doble producto quedó positivo. Como el binomio resta, el término del medio es negativo.$it$,
   $it$El doble producto quedó a la mitad: es $2 \cdot x \cdot 2 = 4x$, con signo menos.$it$,
   $it$Correcto. $(x-2)^2 = x^2 - 2(2)x + 4 = x^2 - 4x + 4$. El término independiente es positivo porque $(-2)^2 = 4$.$it$,
   $it$polinomios/cuadrado-de-binomio-sin-doble-producto$it$, $it$polinomios/signos-cambiados-al-factorizar$it$, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.34), 80,
   $it$Desarrolla $(x + 3)(x - 3)$.$it$,
   $it$$x^2 + 9$$it$,
   $it$$x^2 - 9$$it$,
   $it$$x^2 - 6x - 9$$it$,
   $it$$x^2 + 6x - 9$$it$,
   $it$B$it$,
   $it$El signo del término independiente es negativo: $(+3)(-3) = -9$.$it$,
   $it$Correcto. Los productos cruzados $-3x$ y $+3x$ se cancelan, y queda $x^2 - 9$.$it$,
   $it$Los términos cruzados no se cancelaron: $-3x + 3x = 0$, así que no queda término en $x$.$it$,
   $it$Mismo caso con el signo cambiado. Cuando los binomios son suma y resta del mismo par, el término del medio desaparece.$it$,
   $it$polinomios/signos-cambiados-al-factorizar$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.44), 90,
   $it$Factoriza $6x^2 + 9x$ extrayendo el **máximo** factor común.$it$,
   $it$$3(2x^2 + 3x)$$it$,
   $it$$x(6x + 9)$$it$,
   $it$$3x(2x + 3)$$it$,
   $it$$6x(x + 9)$$it$,
   $it$C$it$,
   $it$El $3$ está bien, pero dentro del paréntesis todavía queda una $x$ común por sacar.$it$,
   $it$La $x$ está bien, pero los coeficientes $6$ y $9$ todavía comparten el factor $3$.$it$,
   $it$Correcto. El máximo factor común es $3x$: $6x^2 + 9x = 3x(2x + 3)$.$it$,
   $it$El factor extraído no divide al segundo término: $9x \div 6x$ no es $9$. Se comprueba desarrollando: $6x(x+9) = 6x^2 + 54x$.$it$,
   $it$polinomios/factor-comun-incompleto$it$, $it$polinomios/factor-comun-incompleto$it$, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.55), 100,
   $it$Factoriza $x^2 - 16$.$it$,
   $it$$(x + 4)(x - 4)$$it$,
   $it$$(x - 4)^2$$it$,
   $it$$(x + 4)^2$$it$,
   $it$$(x + 16)(x - 1)$$it$,
   $it$A$it$,
   $it$Correcto. Es una diferencia de cuadrados: $x^2 - 4^2 = (x+4)(x-4)$.$it$,
   $it$Al desarrollar da $x^2 - 8x + 16$, que tiene término del medio. La diferencia de cuadrados no lo tiene.$it$,
   $it$Al desarrollar da $x^2 + 8x + 16$: ni el signo ni el término del medio coinciden.$it$,
   $it$Al desarrollar da $x^2 + 15x - 16$. Los números elegidos deben ser la raíz cuadrada de $16$, no $16$ y $1$.$it$,
   null, $it$polinomios/cuadrado-de-binomio-sin-doble-producto$it$, $it$polinomios/cuadrado-de-binomio-sin-doble-producto$it$, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.65), 110,
   $it$Factoriza $x^2 + 5x + 6$.$it$,
   $it$$(x + 1)(x + 6)$$it$,
   $it$$(x - 2)(x - 3)$$it$,
   $it$$(x + 5)(x + 6)$$it$,
   $it$$(x + 2)(x + 3)$$it$,
   $it$D$it$,
   $it$Esos números multiplican $6$, pero suman $7$, no $5$. Hacen falta las dos condiciones a la vez.$it$,
   $it$El producto da $6$ y la suma da $-5$: los signos están invertidos. Con el término del medio positivo, los dos números son positivos.$it$,
   $it$Se usaron los coeficientes del polinomio como si fueran los números buscados. Hay que encontrar dos que multiplicados den $6$ y sumados den $5$.$it$,
   $it$Correcto. $2 \times 3 = 6$ y $2 + 3 = 5$.$it$,
   null, $it$polinomios/signos-cambiados-al-factorizar$it$, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.76), 120,
   $it$Factoriza $x^2 - 5x + 6$.$it$,
   $it$$(x + 2)(x + 3)$$it$,
   $it$$(x - 2)(x - 3)$$it$,
   $it$$(x + 2)(x - 3)$$it$,
   $it$$(x - 1)(x - 6)$$it$,
   $it$B$it$,
   $it$Al desarrollar da $x^2 + 5x + 6$: el término del medio queda positivo y el enunciado lo pide negativo.$it$,
   $it$Correcto. $(-2)(-3) = 6$ y $-2 + (-3) = -5$: con producto positivo y suma negativa, los dos números son negativos.$it$,
   $it$Al desarrollar da $x^2 - x - 6$: con signos distintos, el término independiente sale negativo.$it$,
   $it$Multiplican $6$ y suman $-7$, no $-5$.$it$,
   $it$polinomios/signos-cambiados-al-factorizar$it$, null, $it$polinomios/signos-cambiados-al-factorizar$it$, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.86), 130,
   $it$Factoriza $x^2 + 2x - 8$.$it$,
   $it$$(x + 2)(x - 4)$$it$,
   $it$$(x + 8)(x - 1)$$it$,
   $it$$(x + 4)(x - 2)$$it$,
   $it$$(x - 4)(x - 2)$$it$,
   $it$C$it$,
   $it$Los signos están al revés: al desarrollar da $x^2 - 2x - 8$. El número **mayor** tiene que llevar el signo del término del medio.$it$,
   $it$Multiplican $-8$, pero suman $7$, no $2$.$it$,
   $it$Correcto. $4 \times (-2) = -8$ y $4 + (-2) = 2$.$it$,
   $it$El producto da $+8$ y no $-8$: con los dos negativos, el término independiente queda positivo.$it$,
   $it$polinomios/signos-cambiados-al-factorizar$it$, null, null, $it$polinomios/signos-cambiados-al-factorizar$it$),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (0.97), 140,
   $it$Desarrolla $(2x + 1)^2$.$it$,
   $it$$4x^2 + 4x + 1$$it$,
   $it$$4x^2 + 1$$it$,
   $it$$2x^2 + 4x + 1$$it$,
   $it$$4x^2 + 2x + 1$$it$,
   $it$A$it$,
   $it$Correcto. $(2x)^2 = 4x^2$, el doble producto es $2(2x)(1) = 4x$, y $1^2 = 1$.$it$,
   $it$Falta el doble producto. Elevar al cuadrado no es elevar cada término por separado.$it$,
   $it$El coeficiente no se elevó: $(2x)^2$ es $4x^2$, porque el exponente afecta también al $2$.$it$,
   $it$El doble producto quedó a la mitad: es $2 \cdot 2x \cdot 1 = 4x$, no $2x$.$it$,
   null, $it$polinomios/cuadrado-de-binomio-sin-doble-producto$it$, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (1.07), 150,
   $it$Factoriza $x^2 + 9$ en los números reales.$it$,
   $it$$(x + 3)(x - 3)$$it$,
   $it$$(x + 3)^2$$it$,
   $it$$(x + 9)(x + 1)$$it$,
   $it$No se puede factorizar en los números reales$it$,
   $it$D$it$,
   $it$Esa es la factorización de $x^2 - 9$, la **diferencia** de cuadrados. Al desarrollarla queda $x^2 - 9$: el signo del término independiente sale negativo, nunca positivo.$it$,
   $it$Al desarrollar da $x^2 + 6x + 9$, que tiene término del medio. El polinomio original no lo tiene.$it$,
   $it$Al desarrollar da $x^2 + 10x + 9$. Esos números multiplican $9$, pero también dejan un término en $x$.$it$,
   $it$Correcto. Una suma de cuadrados no se factoriza en los reales: $x^2 + 9$ nunca vale cero, porque un cuadrado más un positivo siempre es positivo.$it$,
   $it$polinomios/factoriza-la-suma-de-cuadrados$it$, $it$polinomios/cuadrado-de-binomio-sin-doble-producto$it$, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (1.18), 160,
   $it$Factoriza $4a^2b + 6ab^2$ extrayendo el máximo factor común.$it$,
   $it$$2(2a^2b + 3ab^2)$$it$,
   $it$$2ab(2a + 3b)$$it$,
   $it$$ab(4a + 6b)$$it$,
   $it$$2ab(2a + 3ab)$$it$,
   $it$B$it$,
   $it$El $2$ está bien, pero dentro del paréntesis todavía quedan una $a$ y una $b$ comunes.$it$,
   $it$Correcto. El máximo factor común es $2ab$: queda $2ab(2a + 3b)$.$it$,
   $it$El $ab$ está bien, pero los coeficientes $4$ y $6$ todavía comparten el factor $2$.$it$,
   $it$El factor extraído es correcto, pero el segundo término de adentro no: $6ab^2 \div 2ab = 3b$, no $3ab$. Se comprueba desarrollando.$it$,
   $it$polinomios/factor-comun-incompleto$it$, null, $it$polinomios/factor-comun-incompleto$it$, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (1.28), 170,
   $it$Factoriza $x^2 - 6x + 9$.$it$,
   $it$$(x + 3)^2$$it$,
   $it$$(x + 3)(x - 3)$$it$,
   $it$$(x - 3)^2$$it$,
   $it$$(x - 9)(x + 1)$$it$,
   $it$C$it$,
   $it$Al desarrollar da $x^2 + 6x + 9$: el término del medio queda positivo y el enunciado lo pide negativo.$it$,
   $it$Esa es la factorización de $x^2 - 9$, que no tiene término del medio.$it$,
   $it$Correcto. Es un cuadrado de binomio perfecto: $x^2 - 2(3)x + 3^2 = (x-3)^2$.$it$,
   $it$Multiplican $-9$ y suman $-8$: ni el producto ni la suma coinciden con $+9$ y $-6$.$it$,
   $it$polinomios/signos-cambiados-al-factorizar$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (1.39), 180,
   $it$Desarrolla $(x + 1)(x^2 - x + 1)$.$it$,
   $it$$x^3 + 1$$it$,
   $it$$x^3 - 1$$it$,
   $it$$x^3 + 2x^2 + 1$$it$,
   $it$$x^3 + x^2 + x + 1$$it$,
   $it$A$it$,
   $it$Correcto. $x^3 - x^2 + x + x^2 - x + 1$: se cancelan los términos en $x^2$ y en $x$, y queda $x^3 + 1$.$it$,
   $it$Ese es el resultado de $(x-1)(x^2+x+1)$, que es la suma de cubos con los signos cambiados.$it$,
   $it$Los términos en $x^2$ no se cancelaron: $-x^2 + x^2 = 0$.$it$,
   $it$Se multiplicó cada término del segundo paréntesis por $x$ y por $1$, pero sin respetar el signo del $-x$.$it$,
   null, null, null, $it$polinomios/signos-cambiados-al-factorizar$it$),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (1.49), 190,
   $it$Factoriza por agrupación $x^3 + x^2 + x + 1$.$it$,
   $it$$(x + 1)^3$$it$,
   $it$$x(x^2 + x + 1)$$it$,
   $it$$(x^2 + 1)(x + 1)$ solo si $x > 0$$it$,
   $it$$(x + 1)(x^2 + 1)$$it$,
   $it$D$it$,
   $it$Al desarrollar da $x^3 + 3x^2 + 3x + 1$: los coeficientes del medio no coinciden.$it$,
   $it$El $+1$ final quedó fuera: la $x$ no es factor común de todos los términos, porque el último no la tiene.$it$,
   $it$La factorización es correcta y no depende del signo de $x$: es una identidad, vale para todo valor.$it$,
   $it$Correcto. Agrupando: $x^2(x+1) + 1(x+1) = (x+1)(x^2+1)$.$it$,
   null, $it$polinomios/factor-comun-incompleto$it$, null, null),
  ($it$algebra$it$, $it$algebra/polinomios$it$,
   (1.6), 200,
   $it$Simplifica $\dfrac{x^2 - 9}{x + 3}$, con $x \neq -3$.$it$,
   $it$$x^2 - 3$$it$,
   $it$$x - 3$$it$,
   $it$$\dfrac{x^2}{3}$$it$,
   $it$$x - 9$$it$,
   $it$B$it$,
   $it$Se canceló el $3$ de abajo con el $9$ de arriba. Solo se pueden cancelar **factores** completos, y acá arriba hay una resta, no un producto.$it$,
   $it$Correcto. Factorizando arriba: $\frac{(x+3)(x-3)}{x+3} = x - 3$, porque el factor $x+3$ se cancela entero.$it$,
   $it$Se cancelaron términos sueltos arriba y abajo. Hay que factorizar primero para que aparezca un factor común.$it$,
   $it$Se canceló la $x$ del denominador con parte del numerador, dejando el $9$ intacto.$it$,
   $it$polinomios/cancela-terminos-sueltos-de-la-fraccion$it$, null, $it$polinomios/cancela-terminos-sueltos-de-la-fraccion$it$, $it$polinomios/cancela-terminos-sueltos-de-la-fraccion$it$),

  -- ===========================================================================
  -- algebra/funciones
  -- ===========================================================================
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (0.6), 10,
   $it$Si $f(x) = 2x + 1$, ¿cuánto vale $f(3)$?$it$,
   $it$$2x + 1$$it$,
   $it$$6$$it$,
   $it$$7$$it$,
   $it$$5$$it$,
   $it$C$it$,
   $it$No se reemplazó nada. $f(3)$ significa poner $3$ en el lugar de la $x$.$it$,
   $it$Se calculó $2 \times 3$ y faltó sumar el $1$.$it$,
   $it$Correcto. $f(3) = 2(3) + 1 = 7$.$it$,
   $it$Se sumaron $2$ y $3$ en vez de multiplicarlos. En $2x$ el número y la letra están multiplicándose.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (0.73), 20,
   $it$En la función $y = 3x + 2$, ¿cuál es la **pendiente**?$it$,
   $it$$3$$it$,
   $it$$2$$it$,
   $it$$3x$$it$,
   $it$$5$$it$,
   $it$A$it$,
   $it$Correcto. En $y = mx + n$ la pendiente es $m$, el número que multiplica a la $x$.$it$,
   $it$Ese es el coeficiente de posición: dice dónde corta el eje $y$, no cuánto sube la recta.$it$,
   $it$La pendiente es solo el número, sin la letra.$it$,
   $it$Se sumaron los dos coeficientes. Cada uno cumple un papel distinto y no se combinan.$it$,
   null, $it$funciones/confunde-pendiente-con-intercepto$it$, null, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (0.85), 30,
   $it$¿En qué punto la recta $y = 3x + 2$ corta al eje $y$?$it$,
   $it$$(3, 0)$$it$,
   $it$$(0, 3)$$it$,
   $it$$\left(-\dfrac{2}{3}, 0\right)$$it$,
   $it$$(0, 2)$$it$,
   $it$D$it$,
   $it$En el eje $y$ la coordenada $x$ vale $0$, no al revés. Además el $3$ es la pendiente.$it$,
   $it$El punto está sobre el eje $y$, pero con el valor de la pendiente en vez del coeficiente de posición.$it$,
   $it$Ese es el corte con el eje **$x$**, que se obtiene haciendo $y = 0$.$it$,
   $it$Correcto. Reemplazando $x = 0$: $y = 2$.$it$,
   $it$funciones/confunde-los-dos-cortes$it$, $it$funciones/confunde-pendiente-con-intercepto$it$, $it$funciones/confunde-los-dos-cortes$it$, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (0.98), 40,
   $it$Si $f(x) = x^2 - 1$, ¿cuánto vale $f(-2)$?$it$,
   $it$$-5$$it$,
   $it$$3$$it$,
   $it$$5$$it$,
   $it$$-3$$it$,
   $it$B$it$,
   $it$El signo negativo no se elevó al cuadrado: $(-2)^2 = 4$, no $-4$.$it$,
   $it$Correcto. $f(-2) = (-2)^2 - 1 = 4 - 1 = 3$.$it$,
   $it$El cuadrado está bien, pero el $1$ se sumó en vez de restarse.$it$,
   $it$Se juntan dos errores: el cuadrado quedó negativo y el $1$ se restó de un valor equivocado.$it$,
   $it$algebra/potencia-antes-o-despues-del-signo$it$, null, null, $it$algebra/potencia-antes-o-despues-del-signo$it$),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (1.1), 50,
   $it$¿Cuál es la pendiente de la recta que pasa por los puntos $(1, 2)$ y $(3, 6)$?$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$$4$$it$,
   $it$$2$$it$,
   $it$$8$$it$,
   $it$C$it$,
   $it$La división quedó invertida: se calculó $\frac{\Delta x}{\Delta y}$. La pendiente es cuánto sube por cada unidad que avanza, o sea $\frac{\Delta y}{\Delta x}$.$it$,
   $it$Ese es solo el numerador: $6 - 2 = 4$. Falta dividir por la variación horizontal, que es $2$.$it$,
   $it$Correcto. $m = \frac{6-2}{3-1} = \frac{4}{2} = 2$.$it$,
   $it$Se sumaron las coordenadas en vez de restarlas y dividirlas.$it$,
   $it$funciones/pendiente-invertida$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (1.23), 60,
   $it$¿Qué se puede afirmar de la función $y = -2x + 5$?$it$,
   $it$Es decreciente: al aumentar $x$, disminuye $y$$it$,
   $it$Es creciente, porque el $5$ es positivo$it$,
   $it$Es constante$it$,
   $it$Corta el eje $y$ en $-2$$it$,
   $it$A$it$,
   $it$Correcto. La pendiente es $-2$, negativa: por cada unidad que avanza $x$, la recta baja $2$.$it$,
   $it$Lo que decide si crece o decrece es la **pendiente**, no el coeficiente de posición. Acá la pendiente es negativa.$it$,
   $it$Sería constante si la pendiente fuera $0$, o sea si no hubiera término en $x$.$it$,
   $it$Corta el eje $y$ en $5$. El $-2$ es la pendiente.$it$,
   null, $it$funciones/confunde-pendiente-con-intercepto$it$, null, $it$funciones/confunde-pendiente-con-intercepto$it$),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (1.35), 70,
   $it$¿En qué valor de $x$ la recta $y = 2x - 6$ corta al eje $x$?$it$,
   $it$$x = -6$$it$,
   $it$$x = 6$$it$,
   $it$$x = -3$$it$,
   $it$$x = 3$$it$,
   $it$D$it$,
   $it$Ese es el coeficiente de posición: el corte con el eje **$y$**. Para el eje $x$ hay que hacer $y = 0$.$it$,
   $it$Se despejó sin usar la pendiente: de $2x = 6$ falta dividir por $2$.$it$,
   $it$El signo quedó cambiado al despejar: de $2x - 6 = 0$ se pasa a $2x = 6$, no $2x = -6$.$it$,
   $it$Correcto. Haciendo $y = 0$: $2x - 6 = 0$, así que $x = 3$.$it$,
   $it$funciones/confunde-los-dos-cortes$it$, null, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (1.48), 80,
   $it$Si $f(x) = 2x + 1$, ¿para qué valor de $x$ se cumple $f(x) = 9$?$it$,
   $it$$19$$it$,
   $it$$4$$it$,
   $it$$5$$it$,
   $it$$4{,}5$$it$,
   $it$B$it$,
   $it$Se reemplazó $x = 9$ en la función en vez de despejar. La pregunta pide la entrada, no la salida.$it$,
   $it$Correcto. $2x + 1 = 9$, entonces $2x = 8$ y $x = 4$.$it$,
   $it$Se restó el $1$ después de dividir, o se dividió antes de restar. Primero se quita lo que suma.$it$,
   $it$Se dividió $9$ por $2$ y se olvidó el $1$.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (1.6), 90,
   $it$¿Cuál es la ecuación de la recta de pendiente $2$ que corta al eje $y$ en $-3$?$it$,
   $it$$y = -3x + 2$$it$,
   $it$$y = 2x + 3$$it$,
   $it$$y = 2x - 3$$it$,
   $it$$y = 2(x - 3)$$it$,
   $it$C$it$,
   $it$La pendiente y el coeficiente de posición están intercambiados.$it$,
   $it$El signo del corte quedó positivo. La recta corta el eje $y$ **bajo** el origen.$it$,
   $it$Correcto. En $y = mx + n$, con $m = 2$ y $n = -3$ queda $y = 2x - 3$.$it$,
   $it$Al desarrollar da $y = 2x - 6$, que corta el eje $y$ en $-6$, no en $-3$.$it$,
   $it$funciones/confunde-pendiente-con-intercepto$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (1.73), 100,
   $it$¿Cuál es la ecuación de la recta que pasa por $(1, 3)$ y $(2, 5)$?$it$,
   $it$$y = 2x + 1$$it$,
   $it$$y = 2x + 3$$it$,
   $it$$y = x + 2$$it$,
   $it$$y = \dfrac{1}{2}x + 3$$it$,
   $it$A$it$,
   $it$Correcto. La pendiente es $\frac{5-3}{2-1} = 2$, y reemplazando $(1,3)$: $3 = 2(1) + n$, así que $n = 1$.$it$,
   $it$La pendiente está bien, pero el coeficiente de posición se tomó de la coordenada $y$ del primer punto sin despejar. Hay que reemplazar el punto en la ecuación.$it$,
   $it$La pendiente quedó en $1$: la variación de $y$ es $2$ y la de $x$ es $1$, así que $m = 2$.$it$,
   $it$La pendiente quedó invertida ($\frac{\Delta x}{\Delta y}$) y el corte se tomó directo del punto.$it$,
   null, null, null, $it$funciones/pendiente-invertida$it$),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (1.85), 110,
   $it$Una relación asigna al número $2$ tanto el valor $5$ como el valor $7$. ¿Es una función?$it$,
   $it$Sí, porque a cada salida le corresponde una entrada$it$,
   $it$Sí, porque los tres números son distintos$it$,
   $it$Sí, siempre que $5$ y $7$ estén en el recorrido$it$,
   $it$No, porque a una misma entrada le corresponden dos salidas$it$,
   $it$D$it$,
   $it$La condición va en el otro sentido: lo que no puede repetirse es la **entrada**. Dos entradas distintas sí pueden compartir salida.$it$,
   $it$Que los valores sean distintos no basta: lo que define a una función es que cada entrada tenga una sola salida.$it$,
   $it$El recorrido no tiene nada que ver: aunque los dos valores existan, la entrada $2$ queda con dos imágenes.$it$,
   $it$Correcto. Una función asigna a cada elemento del dominio **exactamente una** imagen.$it$,
   $it$funciones/relacion-con-dos-imagenes-es-funcion$it$, $it$funciones/relacion-con-dos-imagenes-es-funcion$it$, $it$funciones/relacion-con-dos-imagenes-es-funcion$it$, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (1.98), 120,
   $it$¿Cuáles son las raíces de $f(x) = x^2 - 5x + 6$?$it$,
   $it$$-2$ y $-3$$it$,
   $it$$2$ y $3$$it$,
   $it$$5$ y $6$$it$,
   $it$$-5$ y $6$$it$,
   $it$B$it$,
   $it$Se leyeron los signos que aparecen en $(x-2)(x-3)$. La raíz es el valor que **anula** el factor: $x - 2 = 0$ da $x = 2$.$it$,
   $it$Correcto. $x^2 - 5x + 6 = (x-2)(x-3)$, así que se anula en $x = 2$ y $x = 3$.$it$,
   $it$Esos son los coeficientes del polinomio, no sus raíces. Reemplazando $x = 5$ da $6$, no $0$.$it$,
   $it$Se tomaron los coeficientes cambiándole el signo a uno. Conviene comprobar reemplazando.$it$,
   $it$funciones/raices-con-el-signo-de-la-factorizacion$it$, null, null, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (2.1), 130,
   $it$¿Cuál es el **vértice** de la parábola $y = x^2 - 4x + 3$?$it$,
   $it$$(-2, 15)$$it$,
   $it$$(2, 3)$$it$,
   $it$$(2, -1)$$it$,
   $it$$(4, 3)$$it$,
   $it$C$it$,
   $it$El signo de la fórmula quedó cambiado: es $x = -\frac{b}{2a} = -\frac{-4}{2} = 2$, no $-2$.$it$,
   $it$La coordenada $x$ está bien, pero la $y$ se tomó del término independiente sin reemplazar. Hay que evaluar la función en $x = 2$.$it$,
   $it$Correcto. $x = -\frac{-4}{2(1)} = 2$, y $y = 2^2 - 4(2) + 3 = -1$.$it$,
   $it$Se usó $b$ directamente sin dividir por $2a$, y la $y$ salió del término independiente.$it$,
   $it$funciones/vertice-con-el-signo-cambiado$it$, $it$funciones/vertice-con-el-signo-cambiado$it$, null, $it$funciones/vertice-con-el-signo-cambiado$it$),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (2.23), 140,
   $it$¿Hacia dónde abre la parábola $y = -x^2 + 2$?$it$,
   $it$Hacia abajo, porque el coeficiente de $x^2$ es negativo$it$,
   $it$Hacia arriba, porque el $+2$ es positivo$it$,
   $it$Hacia arriba, porque toda parábola abre hacia arriba$it$,
   $it$Hacia la derecha$it$,
   $it$A$it$,
   $it$Correcto. El signo del coeficiente de $x^2$ decide la orientación: negativo abre hacia abajo.$it$,
   $it$El término independiente solo desplaza la parábola verticalmente; no cambia hacia dónde abre.$it$,
   $it$Abren hacia arriba solo cuando el coeficiente de $x^2$ es positivo.$it$,
   $it$Las parábolas de la forma $y = ax^2 + bx + c$ abren hacia arriba o hacia abajo. Las que abren hacia los lados tienen la $x$ despejada en función de $y$.$it$,
   null, $it$funciones/confunde-pendiente-con-intercepto$it$, null, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (2.35), 150,
   $it$¿Cuántas raíces **reales** tiene $f(x) = x^2 + x + 1$?$it$,
   $it$Una, en $x = 0$$it$,
   $it$Dos, en $x = 1$ y $x = -1$$it$,
   $it$Una, en $x = -1$$it$,
   $it$Ninguna$it$,
   $it$D$it$,
   $it$Reemplazando $x = 0$ queda $f(0) = 1$, no $0$. El discriminante negativo indica que la parábola no toca el eje $x$.$it$,
   $it$Reemplazando $x = 1$ da $3$ y $x = -1$ da $1$: ninguno anula la función.$it$,
   $it$Una sola raíz ocurre cuando el discriminante es **cero**, no negativo. Acá $\Delta = 1 - 4 = -3$.$it$,
   $it$Correcto. $\Delta = b^2 - 4ac = 1 - 4 = -3 < 0$: la parábola queda entera sobre el eje $x$ y no lo corta.$it$,
   $it$funciones/discriminante-negativo-como-sin-sentido$it$, null, $it$funciones/discriminante-negativo-como-sin-sentido$it$, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (2.48), 160,
   $it$¿En qué punto la parábola $y = x^2 - 4x + 3$ corta al eje $y$?$it$,
   $it$$(3, 0)$$it$,
   $it$$(0, 3)$$it$,
   $it$$(1, 0)$ y $(3, 0)$$it$,
   $it$$(0, -4)$$it$,
   $it$B$it$,
   $it$Las coordenadas están intercambiadas. En el eje $y$ la primera coordenada vale $0$.$it$,
   $it$Correcto. Reemplazando $x = 0$: $y = 3$, el término independiente.$it$,
   $it$Esos son los cortes con el eje **$x$**, o sea las raíces. Se obtienen haciendo $y = 0$.$it$,
   $it$Se tomó el coeficiente de $x$ en vez del término independiente.$it$,
   $it$funciones/confunde-los-dos-cortes$it$, null, $it$funciones/confunde-los-dos-cortes$it$, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (2.6), 170,
   $it$El costo de producir $x$ unidades es $C(x) = 500x + 2.000$ pesos. ¿Cuál es el **costo fijo**?$it$,
   $it$$\$500$$it$,
   $it$$\$2.500$$it$,
   $it$$\$2.000$$it$,
   $it$Depende de $x$$it$,
   $it$C$it$,
   $it$Ese es el costo **variable** por unidad: lo que se agrega por cada unidad producida.$it$,
   $it$Se sumaron los dos coeficientes. Ese sería el costo de producir exactamente una unidad.$it$,
   $it$Correcto. El costo fijo es el término que no depende de $x$: se paga aunque no se produzca nada, o sea $C(0) = \$2.000$.$it$,
   $it$El costo **total** depende de $x$; el costo fijo, por definición, no.$it$,
   $it$funciones/confunde-costo-fijo-con-variable$it$, null, null, $it$funciones/confunde-costo-fijo-con-variable$it$),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (2.73), 180,
   $it$Con $C(x) = 500x + 2.000$, ¿cuántas unidades se producen con un costo de $\$7.000$?$it$,
   $it$$10$$it$,
   $it$$14$$it$,
   $it$$18$$it$,
   $it$$5.000$$it$,
   $it$A$it$,
   $it$Correcto. $500x + 2.000 = 7.000$, entonces $500x = 5.000$ y $x = 10$.$it$,
   $it$Se dividió $7.000$ por $500$ sin restar antes el costo fijo.$it$,
   $it$Se sumó el costo fijo en vez de restarlo antes de dividir.$it$,
   $it$Ese es el costo variable total, no la cantidad de unidades. Falta dividir por el costo unitario.$it$,
   null, null, $it$ecuaciones/pasa-el-termino-sin-cambiar-el-signo$it$, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (2.85), 190,
   $it$¿Cuáles son las raíces de $f(x) = x^2 - 4$?$it$,
   $it$$4$ y $-4$$it$,
   $it$Solo $2$$it$,
   $it$$0$ y $4$$it$,
   $it$$2$ y $-2$$it$,
   $it$D$it$,
   $it$Se despejó sin sacar la raíz cuadrada: de $x^2 = 4$ se llega a $x = \pm 2$, no $\pm 4$.$it$,
   $it$Falta la raíz negativa. Al despejar un cuadrado hay **dos** soluciones, porque $(-2)^2$ también da $4$.$it$,
   $it$Reemplazando $x = 0$ da $-4$, no $0$. El $4$ tampoco anula la función.$it$,
   $it$Correcto. $x^2 - 4 = (x+2)(x-2)$, así que se anula en $x = 2$ y $x = -2$.$it$,
   null, null, null, null),
  ($it$algebra$it$, $it$algebra/funciones$it$,
   (3.0), 200,
   $it$Una parábola corta el eje $x$ en $-1$ y en $3$, y tiene coeficiente principal $1$. ¿Cuál es su ecuación?$it$,
   $it$$y = x^2 + 2x - 3$$it$,
   $it$$y = x^2 - 2x - 3$$it$,
   $it$$y = (x-1)(x+3)$$it$,
   $it$$y = x^2 - 4x + 3$$it$,
   $it$B$it$,
   $it$Los signos de las raíces se usaron tal cual en los factores: quedó $(x+1)(x+3)$, cuyas raíces son $-1$ y $-3$.$it$,
   $it$Correcto. Las raíces $-1$ y $3$ dan los factores $(x+1)$ y $(x-3)$, y al desarrollar queda $x^2 - 2x - 3$.$it$,
   $it$Los factores están cambiados: esa parábola tiene raíces $1$ y $-3$, no $-1$ y $3$.$it$,
   $it$Sus raíces son $1$ y $3$: el signo de la primera no corresponde.$it$,
   $it$funciones/raices-con-el-signo-de-la-factorizacion$it$, null, $it$funciones/raices-con-el-signo-de-la-factorizacion$it$, null)

)
insert into public.questions
  (topic, module_id, difficulty, order_index,
   question, option_a, option_b, option_c, option_d, correct_option,
   error_a, error_b, error_c, error_d,
   misconception_a_id, misconception_b_id, misconception_c_id, misconception_d_id)
select i.topic, m.id, i.difficulty, i.order_index,
       i.question, i.option_a, i.option_b, i.option_c, i.option_d, i.correct_option,
       i.error_a, i.error_b, i.error_c, i.error_d,
       xa.id, xb.id, xc.id, xd.id
from items i
left join public.modules m        on m.slug  = i.module_slug
left join public.misconceptions xa on xa.slug = i.mis_a
left join public.misconceptions xb on xb.slug = i.mis_b
left join public.misconceptions xc on xc.slug = i.mis_c
left join public.misconceptions xd on xd.slug = i.mis_d
-- Idempotente por (topic, question). Reaplicar NO actualiza un ítem ya
-- cargado: para corregirlo, editarlo en Admin → Preguntas o borrarlo primero.
where not exists (
  select 1 from public.questions q
   where q.topic = i.topic and q.question = i.question
);

-- -----------------------------------------------------------------------------
-- Verificación (correr después de aplicar)
-- -----------------------------------------------------------------------------
--   select count(*) from public.questions where topic = 'algebra';
--   -- esperado: 100 (más lo que ya hubiera)
--
--   -- Ningún ítem sin módulo: delataría un module_slug mal escrito.
--   select id from public.questions where topic = 'algebra' and module_id is null;
--   -- 0 filas
--
--   -- Ningún distractor perdió su idea errónea en el join.
--   select id, question from public.questions q
--    where topic = 'algebra'
--      and misconception_a_id is null and misconception_b_id is null
--      and misconception_c_id is null and misconception_d_id is null;
--   -- revisar: un ítem sin ninguna catalogada puede ser legítimo, varios no
--
--   -- La clave repartida (R-35): ninguna letra debe pasar del 40 %.
--   select correct_option, count(*) from public.questions
--    where topic = 'algebra' group by 1 order by 1;
--
-- Reversión: delete from public.questions where topic = 'algebra';
--            delete from public.misconceptions where slug in ('algebra/coeficiente-incluye-la-letra', 'algebra/suma-terminos-no-semejantes', 'algebra/letra-sola-no-tiene-coeficiente', …);
