-- Banco del eje de geometría — primera tanda
-- 100 ítems · topic `geometria` · 33 ideas erróneas nuevas
--
-- GENERADA por scripts/generar_migracion_items.py desde el JSON de la tanda.
-- No editar a mano: corregir el JSON, volver a verificar y regenerar. Un cambio
-- hecho acá se pierde en la siguiente regeneración y deja de estar verificado.
--
-- Verificada con scripts/verificar_items.py, que comprueba lo que este banco
-- aprendió a golpes: clave repartida entre las cuatro letras (R-35), una sola
-- alternativa correcta, las cuatro explicaciones escritas, la correcta sin idea
-- errónea, LaTeX con escape simple (047) y cobertura de dificultad sin huecos.
--
-- 100 ítems repartidos en los siete módulos de geometría, cubriendo toda la escala
-- [-3, 3] con al menos 6 ítems por tramo de 1,0 logit.
--
-- REQUIERE la migración 053 aplicada (bandas explícitas del eje de geometría). Sin
-- ella, las bandas derivadas dejan el eje entero POR ENCIMA de θ = 0,26 y un
-- estudiante que todavía no llega ahí no encuentra ningún ítem lo bastante fácil.
-- Es el mismo defecto que 049 corrigió para números, por el otro extremo.
--
-- Tercer eje construido con la skill `banco-de-items`. Es el primero que se escribe
-- sin banco previo: geometría no tenía ningún topic identificable en `questions`.
--
-- `difficulty` es una HIPÓTESIS EDITORIAL, no una medición (R-17).

-- -----------------------------------------------------------------------------
-- 1. Ideas erróneas nuevas
-- -----------------------------------------------------------------------------
-- Van ANTES de los ítems y en el mismo archivo: el `left join` de abajo
-- resuelve por slug, así que si no existen todavía los ítems entrarían con
-- `misconception_*_id` en null y en silencio.
--
-- `on conflict (slug) do nothing`: si una ya está catalogada, se respeta la
-- que hay. Reaplicar contenido no pisa una corrección hecha en el panel.

insert into public.misconceptions (slug, name, description, module_id)
select v.slug, v.name, v.description, m.id
  from (values
    ($it$geometria/confunde-el-factor-entre-unidades$it$, $it$Usa el factor de conversión equivocado entre unidades de longitud$it$, $it$Usar cuando multiplica o divide por 10 donde correspondía 100 o 1.000. NO usar si la operación va en el sentido contrario: para eso está geometria/convierte-en-el-sentido-contrario.$it$, $it$geometria/basica$it$),
    ($it$geometria/convierte-en-el-sentido-contrario$it$, $it$Multiplica donde había que dividir al cambiar de unidad$it$, $it$Usar cuando el resultado es absurdamente grande o chico: pasar a una unidad mayor da un número menor, y al revés.$it$, $it$geometria/basica$it$),
    ($it$geometria/clasifica-el-angulo-por-apariencia$it$, $it$Clasifica un ángulo sin compararlo con 90° y 180°$it$, $it$Usar cuando llama obtuso a uno de 45° o agudo a uno de 120°. Los cortes son 90° (recto) y 180° (extendido).$it$, $it$geometria/basica$it$),
    ($it$geometria/confunde-paralelas-con-perpendiculares$it$, $it$Intercambia rectas paralelas con perpendiculares$it$, $it$Usar cuando llama paralelas a las que se cortan en ángulo recto, o perpendiculares a las que no se cortan nunca.$it$, $it$geometria/basica$it$),
    ($it$geometria/coordenadas-invertidas$it$, $it$Lee el par ordenado al revés$it$, $it$Usar cuando toma la primera coordenada como vertical. En $(x, y)$ la primera es horizontal.$it$, $it$geometria/basica$it$),
    ($it$geometria/perimetro-cuenta-mal-los-lados$it$, $it$Suma mal la cantidad de lados al calcular el perímetro$it$, $it$Usar cuando suma solo dos lados de un rectángulo, o multiplica por el número de lados equivocado. El perímetro recorre el contorno completo.$it$, $it$geometria/basica$it$),
    ($it$angulos/confunde-complemento-con-suplemento$it$, $it$Intercambia complementario (90°) con suplementario (180°)$it$, $it$Usar cuando resta de 180 donde correspondía 90, o al revés. Es el error más frecuente del módulo.$it$, $it$geometria/angulos$it$),
    ($it$angulos/opuestos-por-el-vertice-como-suplementarios$it$, $it$Cree que los ángulos opuestos por el vértice suman 180°$it$, $it$Usar cuando los trata como adyacentes. Los opuestos por el vértice son **iguales**; los adyacentes son los que suman 180°.$it$, $it$geometria/angulos$it$),
    ($it$angulos/en-paralelas-todos-los-angulos-son-iguales$it$, $it$Cree que en dos paralelas cortadas por una transversal todos los ángulos son iguales$it$, $it$Usar cuando aplica igualdad donde correspondía suplementariedad. Se forman solo dos medidas distintas, y entre ellas suman 180°.$it$, $it$geometria/angulos$it$),
    ($it$triangulos/suma-de-angulos-distinta-de-180$it$, $it$Usa un total distinto de 180° para los ángulos interiores$it$, $it$Usar cuando reparte 90°, 360° o cualquier otro total entre los tres ángulos de un triángulo.$it$, $it$geometria/triangulos$it$),
    ($it$triangulos/confunde-clasificacion-por-lados-y-angulos$it$, $it$Mezcla la clasificación por lados con la clasificación por ángulos$it$, $it$Usar cuando llama «equilátero» a un triángulo rectángulo, o «isósceles» a uno por tener un ángulo obtuso. Son dos criterios independientes.$it$, $it$geometria/triangulos$it$),
    ($it$triangulos/ignora-la-desigualdad-triangular$it$, $it$Acepta como triángulo tres longitudes que no cierran$it$, $it$Usar cuando no comprueba que la suma de dos lados supere al tercero. Con 2, 3 y 6 los dos lados cortos no alcanzan a juntarse.$it$, $it$geometria/triangulos$it$),
    ($it$triangulos/angulo-exterior-mal-relacionado$it$, $it$Relaciona el ángulo exterior con el interior equivocado$it$, $it$Usar cuando lo iguala a un solo interior lejano, o al adyacente. El exterior es igual a la **suma** de los dos interiores no adyacentes.$it$, $it$geometria/triangulos$it$),
    ($it$triangulos/semejanza-como-congruencia$it$, $it$Exige lados iguales para que dos triángulos sean semejantes$it$, $it$Usar cuando confunde semejanza con congruencia. Semejantes tienen los ángulos iguales y los lados **proporcionales**, no iguales.$it$, $it$geometria/triangulos$it$),
    ($it$circulo/confunde-radio-con-diametro$it$, $it$Usa el diámetro donde correspondía el radio, o al revés$it$, $it$Usar cuando el resultado sale multiplicado o dividido por 2 (o por 4 en áreas) respecto del correcto.$it$, $it$geometria/circulo$it$),
    ($it$circulo/confunde-area-con-perimetro$it$, $it$Aplica la fórmula del perímetro donde se pedía el área$it$, $it$Usar cuando entrega $2\pi r$ para un área o $\pi r^2$ para un contorno. Una se mide en unidades y la otra en unidades cuadradas.$it$, $it$geometria/circulo$it$),
    ($it$circulo/olvida-elevar-el-radio$it$, $it$Calcula el área sin elevar el radio al cuadrado$it$, $it$Usar cuando entrega $\pi r$ en vez de $\pi r^2$.$it$, $it$geometria/circulo$it$),
    ($it$circulo/escala-lineal-en-el-area$it$, $it$Escala el área con el mismo factor que el radio$it$, $it$Usar cuando al duplicar el radio dice que el área se duplica. El área crece con el **cuadrado** del factor.$it$, $it$geometria/circulo$it$),
    ($it$areas/confunde-area-con-perimetro$it$, $it$Suma los lados donde había que multiplicarlos, o al revés$it$, $it$Usar cuando entrega un perímetro para un área o viceversa. El área cubre la superficie y se mide en unidades cuadradas; el perímetro recorre el contorno.$it$, $it$geometria/areas$it$),
    ($it$areas/olvida-dividir-por-dos-en-el-triangulo$it$, $it$Calcula el área del triángulo sin dividir por 2$it$, $it$Usar cuando entrega $b \cdot h$ en vez de $\frac{b \cdot h}{2}$. El triángulo es la mitad del paralelogramo de igual base y altura.$it$, $it$geometria/areas$it$),
    ($it$areas/opera-con-unidades-distintas$it$, $it$Multiplica o suma medidas sin llevarlas a la misma unidad$it$, $it$Usar cuando mezcla metros con centímetros en un mismo cálculo. Antes de operar hay que igualar las unidades.$it$, $it$geometria/areas$it$),
    ($it$areas/escala-lineal-en-el-area$it$, $it$Escala el área con el mismo factor que el lado$it$, $it$Usar cuando al duplicar los lados dice que el área se duplica. El área crece con el cuadrado del factor.$it$, $it$geometria/areas$it$),
    ($it$areas/mismo-perimetro-misma-area$it$, $it$Cree que dos figuras con igual perímetro tienen igual área$it$, $it$Usar cuando concluye una cosa de la otra. Un rectángulo de 1×9 y uno de 3×7 tienen el mismo perímetro y áreas muy distintas.$it$, $it$geometria/areas$it$),
    ($it$volumenes/confunde-volumen-con-area$it$, $it$Usa una fórmula de área donde se pedía volumen$it$, $it$Usar cuando el resultado corresponde a una superficie. El volumen tiene tres dimensiones y se mide en unidades cúbicas.$it$, $it$geometria/volumenes$it$),
    ($it$volumenes/escala-lineal-en-el-volumen$it$, $it$Escala el volumen con el mismo factor que la arista$it$, $it$Usar cuando al duplicar la arista dice que el volumen se duplica o se cuadruplica. Crece con el **cubo** del factor.$it$, $it$geometria/volumenes$it$),
    ($it$volumenes/confunde-litros-con-metros-cubicos$it$, $it$Equivoca el factor entre unidades de capacidad y de volumen$it$, $it$Usar cuando falla la conversión entre cm³, litros y m³. Los factores son 1 L = 1.000 cm³ y 1 m³ = 1.000 L.$it$, $it$geometria/volumenes$it$),
    ($it$volumenes/olvida-el-area-de-la-base$it$, $it$Multiplica dimensiones sueltas en vez del área de la base por la altura$it$, $it$Usar cuando en un prisma o cilindro no calcula primero el área de la base, o se salta el factor que le corresponde.$it$, $it$geometria/volumenes$it$),
    ($it$pitagoras/aplica-el-teorema-en-triangulo-no-rectangulo$it$, $it$Usa el teorema sin comprobar que el triángulo sea rectángulo$it$, $it$Usar cuando aplica $a^2+b^2=c^2$ a un triángulo cualquiera. El teorema vale solo si hay un ángulo recto.$it$, $it$geometria/pitagoras$it$),
    ($it$pitagoras/confunde-cateto-con-hipotenusa$it$, $it$Pone la hipotenusa donde va un cateto, o al revés$it$, $it$Usar cuando suma los cuadrados de la hipotenusa y un cateto, o cuando entrega una hipotenusa menor que un cateto — lo que es imposible.$it$, $it$geometria/pitagoras$it$),
    ($it$pitagoras/suma-los-lados-sin-elevar$it$, $it$Suma los lados sin elevarlos al cuadrado$it$, $it$Usar cuando responde $a+b$ para la hipotenusa. El teorema relaciona los **cuadrados** de los lados, no los lados.$it$, $it$geometria/pitagoras$it$),
    ($it$pitagoras/olvida-la-raiz-final$it$, $it$Deja el resultado en el cuadrado, sin sacar la raíz$it$, $it$Usar cuando entrega $c^2$ en vez de $c$. El último paso siempre es la raíz cuadrada.$it$, $it$geometria/pitagoras$it$),
    ($it$pitagoras/resta-donde-corresponde-sumar$it$, $it$Resta los cuadrados cuando había que sumarlos, o al revés$it$, $it$Usar cuando busca la hipotenusa restando, o un cateto sumando. Se suma para hallar la hipotenusa y se resta para hallar un cateto.$it$, $it$geometria/pitagoras$it$),
    ($it$pitagoras/distancia-sin-restar-coordenadas$it$, $it$Usa las coordenadas directamente en vez de sus diferencias$it$, $it$Usar cuando calcula la distancia entre dos puntos sin restar primero las coordenadas correspondientes.$it$, $it$geometria/pitagoras$it$)
  ) as v(slug, name, description, module_slug)
  left join public.modules m on m.slug = v.module_slug
on conflict (slug) do nothing;

-- -----------------------------------------------------------------------------
-- 2. Ítems
-- -----------------------------------------------------------------------------

with items (topic, module_slug, difficulty, order_index,
            question, option_a, option_b, option_c, option_d, correct_option,
            error_a, error_b, error_c, error_d,
            mis_a, mis_b, mis_c, mis_d) as (
  values

  -- ===========================================================================
  -- geometria/basica
  -- ===========================================================================
  ($it$geometria$it$::text, $it$geometria/basica$it$::text,
   (-3.0)::double precision, 10::int,
   $it$¿Cuántos centímetros hay en $1$ metro?$it$::text,
   $it$$10$$it$::text,
   $it$$100$$it$::text,
   $it$$1.000$$it$::text,
   $it$$0{,}01$$it$::text,
   $it$B$it$::text,
   $it$Ese es el factor entre centímetros y decímetros, o entre milímetros y centímetros. Del metro al centímetro hay dos saltos de diez.$it$::text,
   $it$Correcto. $1$ m $= 100$ cm.$it$::text,
   $it$Ese es el factor entre metros y milímetros, o entre kilómetros y metros.$it$::text,
   $it$Ese es el camino inverso: $1$ cm $= 0{,}01$ m. La pregunta va del metro al centímetro, así que el número crece.$it$::text,
   $it$geometria/confunde-el-factor-entre-unidades$it$::text, null::text, $it$geometria/confunde-el-factor-entre-unidades$it$::text, $it$geometria/convierte-en-el-sentido-contrario$it$::text),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.91), 20,
   $it$¿Cuánto mide un ángulo **recto**?$it$,
   $it$$180^\circ$$it$,
   $it$$360^\circ$$it$,
   $it$$45^\circ$$it$,
   $it$$90^\circ$$it$,
   $it$D$it$,
   $it$Ese es el ángulo **extendido**, el que forma una línea recta. El recto es su mitad.$it$,
   $it$Esa es la vuelta completa.$it$,
   $it$Ese es la mitad de un ángulo recto, y es agudo.$it$,
   $it$Correcto. Un ángulo recto mide $90^\circ$: es el que forman dos rectas perpendiculares.$it$,
   null, null, null, null),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.83), 30,
   $it$Dos rectas en un mismo plano que **nunca** se cortan se llaman:$it$,
   $it$paralelas$it$,
   $it$perpendiculares$it$,
   $it$secantes$it$,
   $it$coincidentes$it$,
   $it$A$it$,
   $it$Correcto. Dos rectas del mismo plano que no se cortan en ningún punto son paralelas.$it$,
   $it$Las perpendiculares **sí** se cortan, y lo hacen formando un ángulo recto.$it$,
   $it$Secantes son justamente las que se cortan en un punto.$it$,
   $it$Coincidentes son las que comparten **todos** sus puntos: son la misma recta.$it$,
   null, $it$geometria/confunde-paralelas-con-perpendiculares$it$, null, null),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.74), 40,
   $it$Un ángulo de $45^\circ$ se clasifica como:$it$,
   $it$obtuso$it$,
   $it$recto$it$,
   $it$agudo$it$,
   $it$extendido$it$,
   $it$C$it$,
   $it$Obtuso es el que mide **más** de $90^\circ$ y menos de $180^\circ$.$it$,
   $it$Recto es exactamente $90^\circ$. Este mide la mitad.$it$,
   $it$Correcto. Un ángulo agudo mide menos de $90^\circ$.$it$,
   $it$Extendido es el de $180^\circ$, el que forma una línea recta.$it$,
   $it$geometria/clasifica-el-angulo-por-apariencia$it$, null, null, null),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.66), 50,
   $it$¿Cuál es el perímetro de un cuadrado de lado $5$ cm?$it$,
   $it$$25$ cm$it$,
   $it$$20$ cm$it$,
   $it$$10$ cm$it$,
   $it$$5$ cm$it$,
   $it$B$it$,
   $it$Ese es el **área**: $5 \times 5$. El perímetro recorre el contorno, no cubre la superficie.$it$,
   $it$Correcto. Un cuadrado tiene cuatro lados iguales: $4 \times 5 = 20$ cm.$it$,
   $it$Se sumaron solo dos lados. El contorno completo son cuatro.$it$,
   $it$Ese es un solo lado. El perímetro es la suma de todos.$it$,
   null, null, $it$geometria/perimetro-cuenta-mal-los-lados$it$, $it$geometria/perimetro-cuenta-mal-los-lados$it$),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.57), 60,
   $it$¿Cuántos milímetros hay en $3$ centímetros?$it$,
   $it$$300$$it$,
   $it$$0{,}3$$it$,
   $it$$3.000$$it$,
   $it$$30$$it$,
   $it$D$it$,
   $it$Se usó el factor $100$, que es el que va de metros a centímetros. Entre centímetro y milímetro el factor es $10$.$it$,
   $it$Se dividió en vez de multiplicar. Al pasar a una unidad **más chica** el número crece.$it$,
   $it$Se usó el factor $1.000$, que es el de metros a milímetros.$it$,
   $it$Correcto. $1$ cm $= 10$ mm, así que $3$ cm $= 30$ mm.$it$,
   $it$geometria/confunde-el-factor-entre-unidades$it$, $it$geometria/convierte-en-el-sentido-contrario$it$, $it$geometria/confunde-el-factor-entre-unidades$it$, null),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.49), 70,
   $it$Un ángulo de $120^\circ$ se clasifica como:$it$,
   $it$obtuso$it$,
   $it$agudo$it$,
   $it$recto$it$,
   $it$completo$it$,
   $it$A$it$,
   $it$Correcto. Está entre $90^\circ$ y $180^\circ$, así que es obtuso.$it$,
   $it$Agudo es el que mide **menos** de $90^\circ$. Este pasa de $90^\circ$.$it$,
   $it$Recto es exactamente $90^\circ$.$it$,
   $it$Completo es la vuelta entera, $360^\circ$.$it$,
   null, $it$geometria/clasifica-el-angulo-por-apariencia$it$, null, null),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.4), 80,
   $it$Dos rectas **perpendiculares** se cortan formando un ángulo de:$it$,
   $it$$180^\circ$$it$,
   $it$$45^\circ$$it$,
   $it$$90^\circ$$it$,
   $it$No se cortan$it$,
   $it$C$it$,
   $it$Ese es el ángulo extendido: dos rectas que forman $180^\circ$ entre sí son en realidad la misma recta.$it$,
   $it$Ese es la mitad del ángulo que forman dos perpendiculares.$it$,
   $it$Correcto. Perpendiculares significa que se cortan en ángulo recto.$it$,
   $it$Las que no se cortan nunca son las **paralelas**. Las perpendiculares sí se cortan.$it$,
   null, null, null, $it$geometria/confunde-paralelas-con-perpendiculares$it$),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.31), 90,
   $it$El punto medio de un segmento de $12$ cm está a:$it$,
   $it$$12$ cm de un extremo$it$,
   $it$$6$ cm de cada extremo$it$,
   $it$$3$ cm de cada extremo$it$,
   $it$$24$ cm de un extremo$it$,
   $it$B$it$,
   $it$Esa es la longitud completa del segmento: sería el otro extremo, no el punto medio.$it$,
   $it$Correcto. El punto medio divide el segmento en dos partes iguales: $12 \div 2 = 6$ cm cada una.$it$,
   $it$Se dividió por $4$. El punto medio parte el segmento en **dos**.$it$,
   $it$Se duplicó el segmento en vez de dividirlo.$it$,
   null, null, null, $it$geometria/convierte-en-el-sentido-contrario$it$),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.23), 100,
   $it$¿Cuál es el perímetro de un rectángulo de $3$ cm por $5$ cm?$it$,
   $it$$15$ cm$it$,
   $it$$8$ cm$it$,
   $it$$11$ cm$it$,
   $it$$16$ cm$it$,
   $it$D$it$,
   $it$Ese es el **área**: $3 \times 5$. El perímetro suma los lados, no los multiplica.$it$,
   $it$Se sumaron solo dos lados. Un rectángulo tiene cuatro: cada medida aparece dos veces.$it$,
   $it$Se contó dos veces un lado y una vez el otro. Los dos se repiten.$it$,
   $it$Correcto. $2(3) + 2(5) = 6 + 10 = 16$ cm.$it$,
   null, $it$geometria/perimetro-cuenta-mal-los-lados$it$, $it$geometria/perimetro-cuenta-mal-los-lados$it$, null),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.14), 110,
   $it$¿Cuántos metros hay en $2{,}5$ kilómetros?$it$,
   $it$$2.500$$it$,
   $it$$250$$it$,
   $it$$25$$it$,
   $it$$0{,}0025$$it$,
   $it$A$it$,
   $it$Correcto. $1$ km $= 1.000$ m, así que $2{,}5$ km $= 2.500$ m.$it$,
   $it$Se usó el factor $100$, que es el de metros a centímetros.$it$,
   $it$Se usó el factor $10$.$it$,
   $it$Se dividió en vez de multiplicar. Al pasar del kilómetro al metro el número crece.$it$,
   null, $it$geometria/confunde-el-factor-entre-unidades$it$, $it$geometria/confunde-el-factor-entre-unidades$it$, $it$geometria/convierte-en-el-sentido-contrario$it$),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-2.06), 120,
   $it$¿Cuánto mide un ángulo **extendido**?$it$,
   $it$$90^\circ$$it$,
   $it$$360^\circ$$it$,
   $it$$180^\circ$$it$,
   $it$$270^\circ$$it$,
   $it$C$it$,
   $it$Ese es el ángulo recto, que es la mitad del extendido.$it$,
   $it$Esa es la vuelta completa, que son dos ángulos extendidos.$it$,
   $it$Correcto. El ángulo extendido mide $180^\circ$: sus lados forman una línea recta.$it$,
   $it$Ese equivale a tres ángulos rectos, tres cuartos de vuelta.$it$,
   null, null, null, null),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-1.97), 130,
   $it$En el plano cartesiano, ¿dónde se ubica el punto $(3, 2)$ respecto del origen?$it$,
   $it$$3$ hacia arriba y $2$ hacia la derecha$it$,
   $it$$3$ hacia la derecha y $2$ hacia arriba$it$,
   $it$$3$ hacia la izquierda y $2$ hacia abajo$it$,
   $it$En el punto $5$ del eje $x$$it$,
   $it$B$it$,
   $it$Las coordenadas están al revés: en $(x, y)$ la **primera** es la horizontal.$it$,
   $it$Correcto. La primera coordenada se mide sobre el eje $x$ y la segunda sobre el eje $y$.$it$,
   $it$Los dos valores son positivos, así que el punto va hacia la derecha y hacia arriba.$it$,
   $it$Las coordenadas no se suman: cada una indica un desplazamiento en un eje distinto.$it$,
   $it$geometria/coordenadas-invertidas$it$, null, null, null),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-1.89), 140,
   $it$¿A cuántos metros equivalen $1.500$ centímetros?$it$,
   $it$$150$$it$,
   $it$$1{,}5$$it$,
   $it$$150.000$$it$,
   $it$$15$$it$,
   $it$D$it$,
   $it$Se dividió por $10$. Entre centímetro y metro el factor es $100$.$it$,
   $it$Se dividió por $1.000$, que es el factor entre milímetros y metros.$it$,
   $it$Se multiplicó en vez de dividir. Al pasar a una unidad **más grande** el número baja.$it$,
   $it$Correcto. $1.500 \div 100 = 15$ m.$it$,
   $it$geometria/confunde-el-factor-entre-unidades$it$, $it$geometria/confunde-el-factor-entre-unidades$it$, $it$geometria/convierte-en-el-sentido-contrario$it$, null),
  ($it$geometria$it$, $it$geometria/basica$it$,
   (-1.8), 150,
   $it$¿Cuál es el perímetro de un triángulo equilátero de lado $7$ cm?$it$,
   $it$$21$ cm$it$,
   $it$$14$ cm$it$,
   $it$$28$ cm$it$,
   $it$$49$ cm$it$,
   $it$A$it$,
   $it$Correcto. Equilátero significa tres lados iguales: $3 \times 7 = 21$ cm.$it$,
   $it$Se sumaron solo dos lados. El triángulo tiene tres.$it$,
   $it$Se multiplicó por $4$, como si fuera un cuadrilátero.$it$,
   $it$Se elevó al cuadrado. El perímetro es una suma de longitudes, no un producto de dos lados.$it$,
   null, $it$geometria/perimetro-cuenta-mal-los-lados$it$, $it$geometria/perimetro-cuenta-mal-los-lados$it$, null),

  -- ===========================================================================
  -- geometria/angulos
  -- ===========================================================================
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-2.6), 10,
   $it$¿Cuál es el **complemento** de un ángulo de $30^\circ$?$it$,
   $it$$150^\circ$$it$,
   $it$$330^\circ$$it$,
   $it$$60^\circ$$it$,
   $it$$30^\circ$$it$,
   $it$C$it$,
   $it$Ese es el **suplemento**: lo que falta para $180^\circ$. El complemento completa $90^\circ$.$it$,
   $it$Eso es lo que falta para la vuelta completa, $360^\circ$.$it$,
   $it$Correcto. $90^\circ - 30^\circ = 60^\circ$.$it$,
   $it$Ese es el mismo ángulo. Dos ángulos iguales solo son complementarios si ambos miden $45^\circ$.$it$,
   $it$angulos/confunde-complemento-con-suplemento$it$, $it$angulos/confunde-complemento-con-suplemento$it$, null, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-2.5), 20,
   $it$¿Cuál es el **suplemento** de un ángulo de $120^\circ$?$it$,
   $it$$60^\circ$$it$,
   $it$$240^\circ$$it$,
   $it$$-30^\circ$$it$,
   $it$$30^\circ$$it$,
   $it$A$it$,
   $it$Correcto. $180^\circ - 120^\circ = 60^\circ$.$it$,
   $it$Eso es lo que falta para $360^\circ$. El suplemento completa $180^\circ$.$it$,
   $it$Se restó de $90^\circ$, que es la regla del complemento, y dio negativo — señal de que un ángulo obtuso no tiene complemento.$it$,
   $it$Se restó de $150^\circ$. La referencia del suplemento es $180^\circ$.$it$,
   null, $it$angulos/confunde-complemento-con-suplemento$it$, $it$angulos/confunde-complemento-con-suplemento$it$, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-2.4), 30,
   $it$Dos ángulos **opuestos por el vértice** cumplen que:$it$,
   $it$suman $90^\circ$$it$,
   $it$suman $180^\circ$$it$,
   $it$suman $360^\circ$$it$,
   $it$son iguales$it$,
   $it$D$it$,
   $it$Esa es la condición de los ángulos complementarios, que es otra cosa.$it$,
   $it$Esa es la condición de los ángulos **adyacentes**, los que están uno al lado del otro sobre una recta. Los opuestos por el vértice están enfrentados.$it$,
   $it$Los cuatro ángulos que se forman al cortarse dos rectas suman $360^\circ$, pero de a pares opuestos no.$it$,
   $it$Correcto. Al cortarse dos rectas, los ángulos enfrentados por el vértice tienen la misma medida.$it$,
   null, $it$angulos/opuestos-por-el-vertice-como-suplementarios$it$, null, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-2.3), 40,
   $it$Dos ángulos **complementarios** suman:$it$,
   $it$$45^\circ$$it$,
   $it$$90^\circ$$it$,
   $it$$180^\circ$$it$,
   $it$$360^\circ$$it$,
   $it$B$it$,
   $it$Ese es el valor de cada uno cuando los dos complementarios son iguales, no la suma.$it$,
   $it$Correcto. Complementarios son los que juntos completan un ángulo recto.$it$,
   $it$Esa es la suma de dos ángulos **suplementarios**.$it$,
   $it$Esa es la vuelta completa.$it$,
   null, null, $it$angulos/confunde-complemento-con-suplemento$it$, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-2.2), 50,
   $it$¿Cuál es el complemento de un ángulo de $45^\circ$?$it$,
   $it$$135^\circ$$it$,
   $it$$90^\circ$$it$,
   $it$$45^\circ$$it$,
   $it$$0^\circ$$it$,
   $it$C$it$,
   $it$Ese es el suplemento: $180^\circ - 45^\circ$. El complemento se calcula sobre $90^\circ$.$it$,
   $it$Ese es el total que deben sumar los dos, no el segundo ángulo.$it$,
   $it$Correcto. $90^\circ - 45^\circ = 45^\circ$: es el único ángulo que es su propio complemento.$it$,
   $it$Se restó el ángulo de sí mismo. La referencia del complemento es $90^\circ$.$it$,
   $it$angulos/confunde-complemento-con-suplemento$it$, null, null, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-2.1), 60,
   $it$¿Cuál es el suplemento de un ángulo **recto**?$it$,
   $it$$90^\circ$$it$,
   $it$$0^\circ$$it$,
   $it$$180^\circ$$it$,
   $it$$270^\circ$$it$,
   $it$A$it$,
   $it$Correcto. $180^\circ - 90^\circ = 90^\circ$: el ángulo recto también es su propio suplemento.$it$,
   $it$Se restó de $90^\circ$, que es la regla del complemento.$it$,
   $it$Ese es el total que deben sumar los dos, no el segundo ángulo.$it$,
   $it$Se restó de $360^\circ$.$it$,
   null, $it$angulos/confunde-complemento-con-suplemento$it$, null, $it$angulos/confunde-complemento-con-suplemento$it$),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-2.0), 70,
   $it$Los ángulos que se forman alrededor de un punto, sin superponerse, suman:$it$,
   $it$$90^\circ$$it$,
   $it$$180^\circ$$it$,
   $it$$270^\circ$$it$,
   $it$$360^\circ$$it$,
   $it$D$it$,
   $it$Ese es un cuarto de vuelta.$it$,
   $it$Ese es media vuelta: es lo que suman los ángulos de un mismo lado de una recta.$it$,
   $it$Ese es tres cuartos de vuelta: falta un ángulo recto para cerrar.$it$,
   $it$Correcto. Dar la vuelta completa alrededor de un punto son $360^\circ$.$it$,
   null, null, null, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-1.9), 80,
   $it$Si un ángulo mide $70^\circ$, ¿cuánto mide su suplemento?$it$,
   $it$$20^\circ$$it$,
   $it$$110^\circ$$it$,
   $it$$290^\circ$$it$,
   $it$$140^\circ$$it$,
   $it$B$it$,
   $it$Ese es el **complemento**: $90^\circ - 70^\circ$.$it$,
   $it$Correcto. $180^\circ - 70^\circ = 110^\circ$.$it$,
   $it$Se restó de $360^\circ$, que corresponde a los ángulos que completan una vuelta.$it$,
   $it$Se duplicó el ángulo en vez de restarlo de $180^\circ$.$it$,
   $it$angulos/confunde-complemento-con-suplemento$it$, null, $it$angulos/confunde-complemento-con-suplemento$it$, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-1.8), 90,
   $it$Dos rectas paralelas son cortadas por una transversal. ¿Qué se cumple con los ángulos **correspondientes**?$it$,
   $it$Suman $90^\circ$$it$,
   $it$Suman $180^\circ$$it$,
   $it$Son iguales$it$,
   $it$Suman $360^\circ$$it$,
   $it$C$it$,
   $it$Los ángulos que se forman acá miden lo mismo o suman $180^\circ$; nunca $90^\circ$, salvo que la transversal sea perpendicular.$it$,
   $it$Eso lo cumplen los **conjugados** (los del mismo lado de la transversal, entre las paralelas), no los correspondientes.$it$,
   $it$Correcto. Al ser paralelas, los ángulos que ocupan la misma posición respecto de la transversal son iguales.$it$,
   $it$Esa es la suma de todos los ángulos alrededor de un punto de corte, no la relación entre dos.$it$,
   null, null, null, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-1.7), 100,
   $it$En dos paralelas cortadas por una transversal, los ángulos **alternos internos**:$it$,
   $it$son iguales$it$,
   $it$suman $90^\circ$$it$,
   $it$suman $180^\circ$$it$,
   $it$siempre miden $90^\circ$$it$,
   $it$A$it$,
   $it$Correcto. Los alternos internos —a distinto lado de la transversal y entre las paralelas— tienen la misma medida.$it$,
   $it$No hay ninguna pareja de estas que sume $90^\circ$ en general.$it$,
   $it$Eso lo cumplen los conjugados internos, que están al **mismo** lado de la transversal.$it$,
   $it$Solo si la transversal es perpendicular a las paralelas. En general no.$it$,
   null, null, $it$angulos/en-paralelas-todos-los-angulos-son-iguales$it$, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-1.6), 110,
   $it$Dos ángulos son complementarios y uno mide el doble del otro. ¿Cuánto mide el **menor**?$it$,
   $it$$60^\circ$$it$,
   $it$$45^\circ$$it$,
   $it$$120^\circ$$it$,
   $it$$30^\circ$$it$,
   $it$D$it$,
   $it$Ese es el **mayor** de los dos. La pregunta pide el menor.$it$,
   $it$Ese sería el valor si los dos fueran iguales, y entonces ninguno sería el doble del otro.$it$,
   $it$Ese valor sale de repartir $180^\circ$, o sea de tratarlos como suplementarios.$it$,
   $it$Correcto. Con $x + 2x = 90^\circ$ queda $3x = 90^\circ$, así que $x = 30^\circ$ y el otro $60^\circ$.$it$,
   null, null, $it$angulos/confunde-complemento-con-suplemento$it$, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-1.5), 120,
   $it$Dos ángulos adyacentes sobre una misma recta suman:$it$,
   $it$$90^\circ$$it$,
   $it$$180^\circ$$it$,
   $it$$360^\circ$$it$,
   $it$Son iguales entre sí$it$,
   $it$B$it$,
   $it$Eso lo cumplen los complementarios, que forman un ángulo recto.$it$,
   $it$Correcto. Juntos forman el ángulo extendido de la recta: $180^\circ$.$it$,
   $it$Esa es la vuelta completa alrededor del punto, que incluye también los dos ángulos del otro lado de la recta.$it$,
   $it$Son iguales solo si cada uno mide $90^\circ$. En general uno es agudo y el otro obtuso.$it$,
   $it$angulos/confunde-complemento-con-suplemento$it$, null, null, $it$angulos/opuestos-por-el-vertice-como-suplementarios$it$),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-1.4), 130,
   $it$Dos ángulos son suplementarios y uno mide el triple del otro. ¿Cuánto miden?$it$,
   $it$$30^\circ$ y $90^\circ$$it$,
   $it$$22{,}5^\circ$ y $67{,}5^\circ$$it$,
   $it$$45^\circ$ y $135^\circ$$it$,
   $it$$60^\circ$ y $120^\circ$$it$,
   $it$C$it$,
   $it$Uno es el triple del otro, pero suman $120^\circ$, no $180^\circ$.$it$,
   $it$Esa es la solución si el total fuera $90^\circ$, o sea si fueran complementarios.$it$,
   $it$Correcto. Con $x + 3x = 180^\circ$ queda $4x = 180^\circ$, así que $x = 45^\circ$ y el otro $135^\circ$.$it$,
   $it$Suman $180^\circ$, pero uno es el **doble** del otro, no el triple.$it$,
   null, $it$angulos/confunde-complemento-con-suplemento$it$, null, null),
  ($it$geometria$it$, $it$geometria/angulos$it$,
   (-1.3), 140,
   $it$Dos paralelas son cortadas por una transversal y uno de los ángulos mide $70^\circ$. ¿Cuánto mide el ángulo **conjugado interno** (el que está entre las paralelas y al mismo lado de la transversal)?$it$,
   $it$$110^\circ$$it$,
   $it$$70^\circ$$it$,
   $it$$20^\circ$$it$,
   $it$$140^\circ$$it$,
   $it$A$it$,
   $it$Correcto. Los conjugados internos son suplementarios: $180^\circ - 70^\circ = 110^\circ$.$it$,
   $it$No todos los ángulos de esta figura son iguales: se forman **dos** medidas distintas, y los conjugados internos son de la otra.$it$,
   $it$Se calculó el complemento. Acá la relación es de suplementariedad.$it$,
   $it$Se duplicó el ángulo. La relación correcta es restar de $180^\circ$.$it$,
   null, $it$angulos/en-paralelas-todos-los-angulos-son-iguales$it$, $it$angulos/confunde-complemento-con-suplemento$it$, null),

  -- ===========================================================================
  -- geometria/triangulos
  -- ===========================================================================
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-2.1), 10,
   $it$¿Cuánto suman los ángulos interiores de cualquier triángulo?$it$,
   $it$$90^\circ$$it$,
   $it$$180^\circ$$it$,
   $it$$360^\circ$$it$,
   $it$Depende del triángulo$it$,
   $it$B$it$,
   $it$Ese es el valor de un solo ángulo recto. En un triángulo rectángulo, los otros dos ángulos suman $90^\circ$, pero el total sigue siendo $180^\circ$.$it$,
   $it$Correcto. En todo triángulo los tres ángulos interiores suman $180^\circ$.$it$,
   $it$Esa es la suma de los ángulos interiores de un **cuadrilátero**, o la vuelta completa.$it$,
   $it$No depende: es el mismo total para cualquier triángulo, grande o chico.$it$,
   $it$triangulos/suma-de-angulos-distinta-de-180$it$, null, $it$triangulos/suma-de-angulos-distinta-de-180$it$, $it$triangulos/suma-de-angulos-distinta-de-180$it$),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-2.0), 20,
   $it$Un triángulo con sus tres lados iguales se llama:$it$,
   $it$isósceles$it$,
   $it$escaleno$it$,
   $it$rectángulo$it$,
   $it$equilátero$it$,
   $it$D$it$,
   $it$Isósceles tiene **dos** lados iguales. Un equilátero también cumple eso, pero el nombre preciso para tres lados iguales es otro.$it$,
   $it$Escaleno es el que tiene los tres lados **distintos**.$it$,
   $it$Rectángulo se refiere a los ángulos, no a los lados: es el que tiene un ángulo recto.$it$,
   $it$Correcto. Equilátero significa lados iguales: los tres miden lo mismo.$it$,
   null, null, $it$triangulos/confunde-clasificacion-por-lados-y-angulos$it$, null),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.9), 30,
   $it$Un triángulo que tiene un ángulo de $90^\circ$ se llama:$it$,
   $it$rectángulo$it$,
   $it$equilátero$it$,
   $it$acutángulo$it$,
   $it$obtusángulo$it$,
   $it$A$it$,
   $it$Correcto. El triángulo rectángulo es el que tiene un ángulo recto.$it$,
   $it$Equilátero clasifica por **lados**, y además sus tres ángulos miden $60^\circ$: nunca puede tener uno recto.$it$,
   $it$Acutángulo es el que tiene los **tres** ángulos agudos, o sea todos menores que $90^\circ$.$it$,
   $it$Obtusángulo es el que tiene un ángulo mayor que $90^\circ$.$it$,
   null, $it$triangulos/confunde-clasificacion-por-lados-y-angulos$it$, null, null),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.8), 40,
   $it$Dos ángulos de un triángulo miden $50^\circ$ y $60^\circ$. ¿Cuánto mide el tercero?$it$,
   $it$$110^\circ$$it$,
   $it$$250^\circ$$it$,
   $it$$70^\circ$$it$,
   $it$$-20^\circ$$it$,
   $it$C$it$,
   $it$Esa es la suma de los dos ángulos dados, no lo que falta para completar $180^\circ$.$it$,
   $it$Se restó de $360^\circ$. El total de un triángulo es $180^\circ$.$it$,
   $it$Correcto. $180^\circ - 50^\circ - 60^\circ = 70^\circ$.$it$,
   $it$Se restó de $90^\circ$. Un ángulo negativo no existe, y eso mismo delata que el total usado era el equivocado.$it$,
   null, $it$triangulos/suma-de-angulos-distinta-de-180$it$, null, $it$triangulos/suma-de-angulos-distinta-de-180$it$),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.7), 50,
   $it$Un triángulo **isósceles** se caracteriza por tener:$it$,
   $it$los tres lados distintos$it$,
   $it$dos lados iguales$it$,
   $it$un ángulo recto$it$,
   $it$los tres ángulos iguales$it$,
   $it$B$it$,
   $it$Ese es el escaleno.$it$,
   $it$Correcto. Isósceles tiene dos lados de igual longitud, y los ángulos opuestos a ellos también son iguales.$it$,
   $it$Eso clasifica por ángulos: es el triángulo rectángulo. Un isósceles puede ser rectángulo o no.$it$,
   $it$Ese es el equilátero, con sus tres ángulos de $60^\circ$.$it$,
   null, null, $it$triangulos/confunde-clasificacion-por-lados-y-angulos$it$, null),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.6), 60,
   $it$En un triángulo rectángulo, ¿cuánto suman los dos ángulos **agudos**?$it$,
   $it$$180^\circ$$it$,
   $it$$45^\circ$$it$,
   $it$$270^\circ$$it$,
   $it$$90^\circ$$it$,
   $it$D$it$,
   $it$Ese es el total de los **tres** ángulos. Falta descontar el ángulo recto.$it$,
   $it$Ese es el valor de cada uno cuando los dos agudos son iguales, no su suma.$it$,
   $it$Se sumó el ángulo recto en vez de restarlo.$it$,
   $it$Correcto. $180^\circ - 90^\circ = 90^\circ$: los dos agudos son complementarios entre sí.$it$,
   null, null, $it$triangulos/suma-de-angulos-distinta-de-180$it$, null),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.5), 70,
   $it$Un triángulo tiene ángulos de $30^\circ$, $60^\circ$ y $90^\circ$. ¿Cómo se clasifica?$it$,
   $it$Rectángulo y escaleno$it$,
   $it$Rectángulo y equilátero$it$,
   $it$Acutángulo e isósceles$it$,
   $it$Obtusángulo y escaleno$it$,
   $it$A$it$,
   $it$Correcto. Tiene un ángulo recto, y como los tres ángulos son distintos, los tres lados también lo son.$it$,
   $it$Un equilátero tiene sus tres ángulos de $60^\circ$: no puede tener uno recto.$it$,
   $it$Acutángulo exige que los tres ángulos sean menores que $90^\circ$, y acá hay uno que mide exactamente $90^\circ$.$it$,
   $it$Obtusángulo exige un ángulo **mayor** que $90^\circ$. El mayor de estos es exactamente $90^\circ$.$it$,
   null, $it$triangulos/confunde-clasificacion-por-lados-y-angulos$it$, $it$triangulos/confunde-clasificacion-por-lados-y-angulos$it$, null),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.4), 80,
   $it$¿Se puede construir un triángulo con lados de $2$, $3$ y $6$ cm?$it$,
   $it$Sí, porque son tres longitudes distintas$it$,
   $it$Sí, porque $2 + 3 + 6 = 11$$it$,
   $it$No, porque $2 + 3$ es menor que $6$$it$,
   $it$No, porque ningún lado mide lo mismo$it$,
   $it$C$it$,
   $it$Que sean distintas no basta. Hay que comprobar que la suma de los dos menores supere al mayor.$it$,
   $it$El perímetro no dice nada sobre si el triángulo existe. Lo que decide es la desigualdad triangular.$it$,
   $it$Correcto. $2 + 3 = 5$, que es menor que $6$: los dos lados cortos no alcanzan a unirse en los extremos del largo.$it$,
   $it$Un triángulo escaleno tiene los tres lados distintos y existe perfectamente. El problema acá es otro.$it$,
   $it$triangulos/ignora-la-desigualdad-triangular$it$, $it$triangulos/ignora-la-desigualdad-triangular$it$, null, null),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.3), 90,
   $it$¿Cuánto mide cada ángulo interior de un triángulo equilátero?$it$,
   $it$$90^\circ$$it$,
   $it$$60^\circ$$it$,
   $it$$45^\circ$$it$,
   $it$$120^\circ$$it$,
   $it$B$it$,
   $it$Un triángulo con tres ángulos rectos sumaría $270^\circ$, muy por encima de $180^\circ$.$it$,
   $it$Correcto. Los tres son iguales y suman $180^\circ$: $180 \div 3 = 60^\circ$.$it$,
   $it$Se repartió $180^\circ$ entre cuatro, o se dividió $90^\circ$ entre dos.$it$,
   $it$Se repartió $360^\circ$ entre tres. El total de un triángulo es $180^\circ$.$it$,
   null, null, $it$triangulos/suma-de-angulos-distinta-de-180$it$, $it$triangulos/suma-de-angulos-distinta-de-180$it$),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.2), 100,
   $it$Un ángulo **exterior** de un triángulo es igual a:$it$,
   $it$el ángulo interior adyacente$it$,
   $it$$180^\circ$ menos la suma de los tres interiores$it$,
   $it$el mayor de los ángulos interiores$it$,
   $it$la suma de los dos interiores no adyacentes$it$,
   $it$D$it$,
   $it$El exterior y su interior adyacente son **suplementarios**: juntos suman $180^\circ$, así que solo son iguales si ambos miden $90^\circ$.$it$,
   $it$La suma de los tres interiores ya es $180^\circ$, así que eso daría siempre cero.$it$,
   $it$No hay ninguna relación general con el mayor de los interiores.$it$,
   $it$Correcto. Como el exterior suplementa al adyacente, y los tres interiores suman $180^\circ$, queda igual a la suma de los otros dos.$it$,
   $it$triangulos/angulo-exterior-mal-relacionado$it$, null, $it$triangulos/angulo-exterior-mal-relacionado$it$, null),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.1), 110,
   $it$En un triángulo isósceles, el ángulo distinto mide $40^\circ$. ¿Cuánto mide cada uno de los otros dos?$it$,
   $it$$70^\circ$$it$,
   $it$$140^\circ$$it$,
   $it$$50^\circ$$it$,
   $it$$40^\circ$$it$,
   $it$A$it$,
   $it$Correcto. Los otros dos son iguales y suman $180^\circ - 40^\circ = 140^\circ$, así que cada uno mide $70^\circ$.$it$,
   $it$Ese es el total que suman **entre los dos**. Falta repartirlo.$it$,
   $it$Se usó $90^\circ$ como total de los dos ángulos restantes, que solo valdría si el triángulo fuera rectángulo.$it$,
   $it$Ese es el ángulo dado. Los otros dos son iguales entre sí, pero distintos de este.$it$,
   null, null, $it$triangulos/suma-de-angulos-distinta-de-180$it$, null),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-1.0), 120,
   $it$¿Por qué un triángulo no puede tener dos ángulos rectos?$it$,
   $it$Porque tendría cuatro lados$it$,
   $it$Porque los ángulos rectos solo existen en los cuadriláteros$it$,
   $it$Porque los dos sumarían $180^\circ$ y no quedaría nada para el tercero$it$,
   $it$Sí puede, si es muy grande$it$,
   $it$C$it$,
   $it$La cantidad de lados no cambia por la medida de los ángulos: seguirían siendo tres.$it$,
   $it$Un triángulo rectángulo tiene un ángulo recto perfectamente. El problema es tener **dos**.$it$,
   $it$Correcto. $90^\circ + 90^\circ = 180^\circ$, que es el total disponible: el tercer ángulo tendría que medir $0^\circ$ y el triángulo no cerraría.$it$,
   $it$El tamaño no influye: la suma de los ángulos interiores es $180^\circ$ en todo triángulo.$it$,
   null, null, null, $it$triangulos/suma-de-angulos-distinta-de-180$it$),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-0.9), 130,
   $it$Dos lados de un triángulo miden $5$ y $7$. ¿Entre qué valores puede estar el tercero?$it$,
   $it$Entre $5$ y $7$$it$,
   $it$Entre $2$ y $12$$it$,
   $it$Cualquier valor positivo$it$,
   $it$Entre $0$ y $35$$it$,
   $it$B$it$,
   $it$El tercer lado no tiene por qué quedar entre los otros dos: puede ser el más corto o el más largo.$it$,
   $it$Correcto. Debe ser mayor que $7 - 5 = 2$ y menor que $7 + 5 = 12$, para que los tres lados alcancen a cerrarse.$it$,
   $it$Con un lado de $100$ los otros dos nunca se juntarían. La desigualdad triangular pone un techo y un piso.$it$,
   $it$El $35$ sale de multiplicar los dos lados, que no tiene relación con la condición de cierre.$it$,
   null, null, $it$triangulos/ignora-la-desigualdad-triangular$it$, $it$triangulos/ignora-la-desigualdad-triangular$it$),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-0.8), 140,
   $it$Dos triángulos son **semejantes** cuando:$it$,
   $it$tienen la misma área$it$,
   $it$tienen todos sus lados exactamente iguales$it$,
   $it$tienen el mismo perímetro$it$,
   $it$tienen ángulos iguales y lados proporcionales$it$,
   $it$D$it$,
   $it$Dos triángulos pueden tener la misma área y formas completamente distintas.$it$,
   $it$Eso es ser **congruentes**, o sea idénticos. La semejanza admite tamaños distintos.$it$,
   $it$El perímetro igual tampoco garantiza la misma forma.$it$,
   $it$Correcto. Semejantes es tener la misma forma: ángulos iguales y lados en la misma razón.$it$,
   null, $it$triangulos/semejanza-como-congruencia$it$, null, null),
  ($it$geometria$it$, $it$geometria/triangulos$it$,
   (-0.7), 150,
   $it$Un triángulo de lados $3$, $4$ y $5$ es semejante a otro cuyos dos primeros lados miden $6$ y $8$. ¿Cuánto mide su tercer lado?$it$,
   $it$$10$$it$,
   $it$$7$$it$,
   $it$$5$$it$,
   $it$$9$$it$,
   $it$A$it$,
   $it$Correcto. La razón de semejanza es $2$ ($6 = 3\times 2$ y $8 = 4\times 2$), así que el tercero es $5 \times 2 = 10$.$it$,
   $it$Se sumó $2$ a cada lado en vez de multiplicar por $2$. La semejanza escala por un factor, no suma una constante.$it$,
   $it$Ese es el lado del triángulo original. Si el segundo es más grande, su tercer lado también lo es.$it$,
   $it$Se aplicó un factor de $1{,}8$, que no coincide con la razón que fijan los dos primeros lados.$it$,
   null, $it$triangulos/semejanza-como-congruencia$it$, $it$triangulos/semejanza-como-congruencia$it$, null),

  -- ===========================================================================
  -- geometria/circulo
  -- ===========================================================================
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-1.5), 10,
   $it$¿Qué relación hay entre el diámetro y el radio de una circunferencia?$it$,
   $it$El diámetro es la mitad del radio$it$,
   $it$Son iguales$it$,
   $it$El diámetro es el doble del radio$it$,
   $it$El diámetro es el radio al cuadrado$it$,
   $it$C$it$,
   $it$Es al revés: el radio es la mitad del diámetro.$it$,
   $it$El radio va del centro al borde; el diámetro cruza la circunferencia entera pasando por el centro.$it$,
   $it$Correcto. $d = 2r$: el diámetro son dos radios alineados.$it$,
   $it$La relación es de doble, no de cuadrado, y además elevar mezclaría unidades distintas.$it$,
   $it$circulo/confunde-radio-con-diametro$it$, $it$circulo/confunde-radio-con-diametro$it$, null, null),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-1.38), 20,
   $it$Si el radio de una circunferencia mide $5$ cm, ¿cuánto mide su diámetro?$it$,
   $it$$10$ cm$it$,
   $it$$2{,}5$ cm$it$,
   $it$$25$ cm$it$,
   $it$$5$ cm$it$,
   $it$A$it$,
   $it$Correcto. $d = 2r = 2 \times 5 = 10$ cm.$it$,
   $it$Se dividió por $2$. El diámetro es mayor que el radio, no menor.$it$,
   $it$Se elevó al cuadrado. La relación entre radio y diámetro es un factor $2$.$it$,
   $it$Ese es el radio. El diámetro lo duplica.$it$,
   null, $it$circulo/confunde-radio-con-diametro$it$, null, $it$circulo/confunde-radio-con-diametro$it$),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-1.27), 30,
   $it$¿Cuál es la fórmula del **perímetro** de una circunferencia de radio $r$?$it$,
   $it$$\pi r^2$$it$,
   $it$$\pi r$$it$,
   $it$$4r$$it$,
   $it$$2\pi r$$it$,
   $it$D$it$,
   $it$Esa es la fórmula del **área**, que se mide en unidades cuadradas.$it$,
   $it$Ese es la mitad del perímetro: corresponde al arco de media circunferencia.$it$,
   $it$Esa sería la fórmula del perímetro de un cuadrado de lado $r$.$it$,
   $it$Correcto. $P = 2\pi r$, o equivalentemente $\pi d$.$it$,
   $it$circulo/confunde-area-con-perimetro$it$, null, null, null),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-1.15), 40,
   $it$¿Cuál es la fórmula del **área** de un círculo de radio $r$?$it$,
   $it$$2\pi r$$it$,
   $it$$\pi r^2$$it$,
   $it$$\pi r$$it$,
   $it$$2\pi r^2$$it$,
   $it$B$it$,
   $it$Esa es la fórmula del **perímetro**. El área se mide en unidades cuadradas, así que el radio tiene que aparecer elevado.$it$,
   $it$Correcto. $A = \pi r^2$.$it$,
   $it$Falta elevar el radio al cuadrado.$it$,
   $it$Sobra el factor $2$: se mezclaron las dos fórmulas.$it$,
   $it$circulo/confunde-area-con-perimetro$it$, null, $it$circulo/olvida-elevar-el-radio$it$, null),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-1.04), 50,
   $it$¿Cuál es el área de un círculo de radio $3$ cm? (deja el resultado en función de $\pi$)$it$,
   $it$$6\pi$ cm$^2$$it$,
   $it$$3\pi$ cm$^2$$it$,
   $it$$9\pi$ cm$^2$$it$,
   $it$$36\pi$ cm$^2$$it$,
   $it$C$it$,
   $it$Ese es el **perímetro**: $2\pi(3)$. El área usa el radio al cuadrado.$it$,
   $it$Falta elevar el radio: $A = \pi r^2$, no $\pi r$.$it$,
   $it$Correcto. $A = \pi (3)^2 = 9\pi$ cm$^2$.$it$,
   $it$Se usó el diámetro ($6$) en lugar del radio, y además al cuadrado.$it$,
   $it$circulo/confunde-area-con-perimetro$it$, $it$circulo/olvida-elevar-el-radio$it$, null, $it$circulo/confunde-radio-con-diametro$it$),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-0.92), 60,
   $it$¿Cuál es el perímetro de una circunferencia de radio $4$ cm? (en función de $\pi$)$it$,
   $it$$8\pi$ cm$it$,
   $it$$16\pi$ cm$it$,
   $it$$4\pi$ cm$it$,
   $it$$2\pi$ cm$it$,
   $it$A$it$,
   $it$Correcto. $P = 2\pi r = 2\pi(4) = 8\pi$ cm.$it$,
   $it$Ese es el **área**: $\pi(4)^2$. Un perímetro no lleva el radio al cuadrado.$it$,
   $it$Falta el factor $2$: el perímetro es $2\pi r$, no $\pi r$.$it$,
   $it$Se perdió el radio: quedó solo la constante.$it$,
   null, $it$circulo/confunde-area-con-perimetro$it$, null, null),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-0.81), 70,
   $it$El número $\pi$ vale aproximadamente:$it$,
   $it$$3{,}00$$it$,
   $it$$22$$it$,
   $it$$1{,}41$$it$,
   $it$$3{,}14$$it$,
   $it$D$it$,
   $it$Es una aproximación muy gruesa: $\pi$ pasa de $3$ por algo más de una décima.$it$,
   $it$El $22$ aparece en la aproximación $\frac{22}{7}$, pero solo dividido por $7$.$it$,
   $it$Ese es aproximadamente $\sqrt{2}$, que es otra constante.$it$,
   $it$Correcto. $\pi \approx 3{,}14159\dots$, y es la razón entre el perímetro y el diámetro de cualquier circunferencia.$it$,
   null, null, null, null),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-0.69), 80,
   $it$Un círculo tiene diámetro $10$ cm. ¿Cuál es su área? (en función de $\pi$)$it$,
   $it$$100\pi$ cm$^2$$it$,
   $it$$25\pi$ cm$^2$$it$,
   $it$$10\pi$ cm$^2$$it$,
   $it$$20\pi$ cm$^2$$it$,
   $it$B$it$,
   $it$Se usó el diámetro como si fuera el radio. Primero hay que dividirlo por $2$.$it$,
   $it$Correcto. El radio es $5$, así que $A = \pi(5)^2 = 25\pi$ cm$^2$.$it$,
   $it$Falta elevar al cuadrado, y además se usó el diámetro.$it$,
   $it$Se usó la fórmula del **perímetro** y encima con el diámetro como radio: $2\pi(10) = 20\pi$. El área lleva el radio al cuadrado.$it$,
   $it$circulo/confunde-radio-con-diametro$it$, null, $it$circulo/olvida-elevar-el-radio$it$, $it$circulo/confunde-area-con-perimetro$it$),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-0.58), 90,
   $it$Si el radio de un círculo se **duplica**, ¿qué pasa con su área?$it$,
   $it$Se duplica$it$,
   $it$Queda igual$it$,
   $it$Se cuadruplica$it$,
   $it$Se multiplica por ocho$it$,
   $it$C$it$,
   $it$El área depende del radio **al cuadrado**: al duplicar el radio, el factor también se eleva.$it$,
   $it$El área cambia: es proporcional a $r^2$.$it$,
   $it$Correcto. $A = \pi(2r)^2 = 4\pi r^2$: el área queda multiplicada por $4$.$it$,
   $it$Ese es el factor del **volumen** de un cuerpo al duplicar sus dimensiones, porque ahí el exponente es $3$.$it$,
   $it$circulo/escala-lineal-en-el-area$it$, $it$circulo/escala-lineal-en-el-area$it$, null, null),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-0.46), 100,
   $it$¿Cuánto mide el **arco** de un semicírculo de radio $6$ cm? (en función de $\pi$)$it$,
   $it$$6\pi$ cm$it$,
   $it$$12\pi$ cm$it$,
   $it$$3\pi$ cm$it$,
   $it$$18\pi$ cm$it$,
   $it$A$it$,
   $it$Correcto. El arco es la mitad del perímetro: $\frac{2\pi(6)}{2} = 6\pi$ cm.$it$,
   $it$Ese es el perímetro de la circunferencia **completa**. El semicírculo tiene la mitad.$it$,
   $it$Se dividió dos veces por $2$: el arco de media circunferencia es $\pi r$, no $\frac{\pi r}{2}$.$it$,
   $it$Ese es el **área** del semicírculo: $\frac{\pi(6)^2}{2} = 18\pi$ cm$^2$. Acá se pide la longitud del arco, que es una distancia.$it$,
   null, null, null, null),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-0.35), 110,
   $it$¿Cuál es el área de un sector circular de $90^\circ$ en un círculo de radio $4$ cm? (en función de $\pi$)$it$,
   $it$$16\pi$ cm$^2$$it$,
   $it$$8\pi$ cm$^2$$it$,
   $it$$2\pi$ cm$^2$$it$,
   $it$$4\pi$ cm$^2$$it$,
   $it$D$it$,
   $it$Esa es el área del círculo **completo**. Un sector de $90^\circ$ es una cuarta parte.$it$,
   $it$Se tomó la mitad del círculo. $90^\circ$ de $360^\circ$ es un cuarto, no un medio.$it$,
   $it$Se dividió por $8$: eso correspondería a un sector de $45^\circ$.$it$,
   $it$Correcto. $\frac{90}{360} = \frac{1}{4}$ del área total: $\frac{\pi(4)^2}{4} = 4\pi$ cm$^2$.$it$,
   null, null, null, null),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-0.23), 120,
   $it$Una circunferencia tiene perímetro $20\pi$ cm. ¿Cuánto mide su radio?$it$,
   $it$$20$ cm$it$,
   $it$$10$ cm$it$,
   $it$$40$ cm$it$,
   $it$$\sqrt{20}$ cm$it$,
   $it$B$it$,
   $it$Ese es el **diámetro**. El radio es su mitad.$it$,
   $it$Correcto. De $2\pi r = 20\pi$ se sigue que $r = 10$ cm.$it$,
   $it$Se multiplicó por $2$ en vez de dividir.$it$,
   $it$Se despejó como si la fórmula tuviera el radio al cuadrado, que es la del área.$it$,
   $it$circulo/confunde-radio-con-diametro$it$, null, $it$circulo/confunde-radio-con-diametro$it$, $it$circulo/confunde-area-con-perimetro$it$),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (-0.12), 130,
   $it$Un círculo tiene área $36\pi$ cm$^2$. ¿Cuánto mide su radio?$it$,
   $it$$18$ cm$it$,
   $it$$36$ cm$it$,
   $it$$6$ cm$it$,
   $it$$12$ cm$it$,
   $it$C$it$,
   $it$Se dividió por $2$ en vez de sacar la raíz cuadrada.$it$,
   $it$Se tomó el número tal cual, sin despejar. En $A = \pi r^2$ hay que sacar la raíz.$it$,
   $it$Correcto. De $\pi r^2 = 36\pi$ queda $r^2 = 36$, así que $r = 6$ cm.$it$,
   $it$Ese es el diámetro, que es el doble del radio.$it$,
   null, $it$circulo/olvida-elevar-el-radio$it$, null, $it$circulo/confunde-radio-con-diametro$it$),
  ($it$geometria$it$, $it$geometria/circulo$it$,
   (0.0), 140,
   $it$Una corona circular está formada por dos círculos concéntricos de radios $5$ cm y $3$ cm. ¿Cuál es su área? (en función de $\pi$)$it$,
   $it$$16\pi$ cm$^2$$it$,
   $it$$4\pi$ cm$^2$$it$,
   $it$$34\pi$ cm$^2$$it$,
   $it$$2\pi$ cm$^2$$it$,
   $it$A$it$,
   $it$Correcto. Es la diferencia de las dos áreas: $\pi(25) - \pi(9) = 16\pi$ cm$^2$.$it$,
   $it$Se restaron los radios antes de elevar: $(5-3)^2 = 4$. Hay que elevar cada radio **primero** y restar después.$it$,
   $it$Se sumaron las dos áreas en vez de restarlas. La corona es el anillo que queda entre los dos círculos.$it$,
   $it$Se restaron los radios sin elevar al cuadrado ni multiplicar por $\pi$ correctamente.$it$,
   null, $it$circulo/olvida-elevar-el-radio$it$, null, $it$circulo/olvida-elevar-el-radio$it$),

  -- ===========================================================================
  -- geometria/areas
  -- ===========================================================================
  ($it$geometria$it$, $it$geometria/areas$it$,
   (-0.8), 10,
   $it$¿Cuál es el área de un rectángulo de $4$ cm por $6$ cm?$it$,
   $it$$24$ cm$^2$$it$,
   $it$$20$ cm$it$,
   $it$$10$ cm$^2$$it$,
   $it$$12$ cm$^2$$it$,
   $it$A$it$,
   $it$Correcto. El área del rectángulo es base por altura: $4 \times 6 = 24$ cm$^2$.$it$,
   $it$Ese es el **perímetro**: $2(4) + 2(6)$. Además está en centímetros, no en centímetros cuadrados.$it$,
   $it$Se sumaron los dos lados. El área se obtiene multiplicándolos.$it$,
   $it$Se dividió el área por $2$, que es la división de la fórmula del **triángulo**. El rectángulo no la lleva.$it$,
   null, $it$areas/confunde-area-con-perimetro$it$, $it$areas/confunde-area-con-perimetro$it$, null),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (-0.68), 20,
   $it$¿Cuál es el área de un cuadrado de lado $7$ cm?$it$,
   $it$$28$ cm$^2$$it$,
   $it$$14$ cm$^2$$it$,
   $it$$7$ cm$^2$$it$,
   $it$$49$ cm$^2$$it$,
   $it$D$it$,
   $it$Ese es el **perímetro**: $4 \times 7$.$it$,
   $it$Se sumaron dos lados. El área multiplica lado por lado.$it$,
   $it$Ese es un solo lado.$it$,
   $it$Correcto. $A = 7 \times 7 = 49$ cm$^2$.$it$,
   $it$areas/confunde-area-con-perimetro$it$, $it$areas/confunde-area-con-perimetro$it$, null, null),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (-0.55), 30,
   $it$¿Cuál es el área de un triángulo de base $10$ cm y altura $6$ cm?$it$,
   $it$$60$ cm$^2$$it$,
   $it$$16$ cm$^2$$it$,
   $it$$30$ cm$^2$$it$,
   $it$$32$ cm$^2$$it$,
   $it$C$it$,
   $it$Falta dividir por $2$. Ese es el área del **paralelogramo** de igual base y altura; el triángulo es su mitad.$it$,
   $it$Se sumaron base y altura. El área las multiplica.$it$,
   $it$Correcto. $A = \frac{10 \times 6}{2} = 30$ cm$^2$.$it$,
   $it$Ese es el perímetro de un rectángulo de $10$ por $6$: $2(10+6)$. Acá se pide superficie, y el triángulo además es la mitad.$it$,
   $it$areas/olvida-dividir-por-dos-en-el-triangulo$it$, $it$areas/confunde-area-con-perimetro$it$, null, $it$areas/confunde-area-con-perimetro$it$),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (-0.43), 40,
   $it$¿Cuál es la fórmula del área de un triángulo?$it$,
   $it$$b \cdot h$$it$,
   $it$$\dfrac{b \cdot h}{2}$$it$,
   $it$$b + h$$it$,
   $it$$2(b + h)$$it$,
   $it$B$it$,
   $it$Esa es la del paralelogramo o rectángulo. El triángulo es exactamente su mitad.$it$,
   $it$Correcto. $A = \frac{b \cdot h}{2}$.$it$,
   $it$Sumar base y altura no da una superficie: el área siempre multiplica dos longitudes.$it$,
   $it$Esa es la fórmula del perímetro de un rectángulo.$it$,
   $it$areas/olvida-dividir-por-dos-en-el-triangulo$it$, null, $it$areas/confunde-area-con-perimetro$it$, $it$areas/confunde-area-con-perimetro$it$),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (-0.31), 50,
   $it$¿Cuál es el área de un paralelogramo de base $8$ cm y altura $5$ cm?$it$,
   $it$$26$ cm$^2$$it$,
   $it$$13$ cm$^2$$it$,
   $it$$20$ cm$^2$$it$,
   $it$$40$ cm$^2$$it$,
   $it$D$it$,
   $it$Ese es el perímetro si los lados midieran $8$ y $5$, pero la altura no es un lado del paralelogramo.$it$,
   $it$Se sumaron base y altura.$it$,
   $it$Se dividió por $2$. Esa división corresponde al **triángulo**, no al paralelogramo.$it$,
   $it$Correcto. $A = b \cdot h = 8 \times 5 = 40$ cm$^2$.$it$,
   $it$areas/confunde-area-con-perimetro$it$, $it$areas/confunde-area-con-perimetro$it$, null, null),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (-0.18), 60,
   $it$¿En qué unidades se expresa un área?$it$,
   $it$En unidades cuadradas, como cm$^2$$it$,
   $it$En unidades simples, como cm$it$,
   $it$En unidades cúbicas, como cm$^3$$it$,
   $it$En grados$it$,
   $it$A$it$,
   $it$Correcto. El área multiplica dos longitudes, así que la unidad también queda elevada al cuadrado.$it$,
   $it$Esas son las unidades de una longitud o de un perímetro.$it$,
   $it$Esas son las de un **volumen**, que multiplica tres longitudes.$it$,
   $it$Los grados miden ángulos, no superficies.$it$,
   null, $it$areas/confunde-area-con-perimetro$it$, $it$volumenes/confunde-volumen-con-area$it$, null),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (-0.06), 70,
   $it$Un trapecio tiene bases de $6$ cm y $10$ cm, y altura $4$ cm. ¿Cuál es su área?$it$,
   $it$$240$ cm$^2$$it$,
   $it$$32$ cm$^2$$it$,
   $it$$20$ cm$^2$$it$,
   $it$$64$ cm$^2$$it$,
   $it$B$it$,
   $it$Se multiplicaron las tres medidas. La fórmula promedia las bases antes de multiplicar por la altura.$it$,
   $it$Correcto. $A = \frac{(6+10)}{2} \times 4 = 8 \times 4 = 32$ cm$^2$.$it$,
   $it$Se sumaron las tres medidas.$it$,
   $it$Se sumaron las bases y se multiplicó por la altura sin dividir por $2$.$it$,
   null, null, $it$areas/confunde-area-con-perimetro$it$, $it$areas/olvida-dividir-por-dos-en-el-triangulo$it$),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (0.06), 80,
   $it$Dos rectángulos tienen el **mismo perímetro**. ¿Qué se puede afirmar de sus áreas?$it$,
   $it$Son iguales$it$,
   $it$El más alargado tiene mayor área$it$,
   $it$El área es siempre la mitad del perímetro$it$,
   $it$Pueden ser muy distintas$it$,
   $it$D$it$,
   $it$No se sigue. Un rectángulo de $1 \times 9$ y uno de $3 \times 7$ tienen perímetro $20$ y áreas de $9$ y $21$.$it$,
   $it$Con el mismo perímetro pasa justo al revés: el de $1 \times 9$ tiene área $9$ y el de $5 \times 5$, $25$. Alargar la figura le quita área.$it$,
   $it$No hay ninguna relación fija entre área y perímetro: dependen de la forma.$it$,
   $it$Correcto. Con el mismo perímetro, mientras más parecida al cuadrado sea la figura, mayor es su área.$it$,
   $it$areas/mismo-perimetro-misma-area$it$, null, $it$areas/confunde-area-con-perimetro$it$, null),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (0.18), 90,
   $it$Si se **duplican** los lados de un cuadrado, ¿qué pasa con su área?$it$,
   $it$Se duplica$it$,
   $it$Queda igual$it$,
   $it$Se cuadruplica$it$,
   $it$Se multiplica por ocho$it$,
   $it$C$it$,
   $it$El área multiplica dos longitudes, y las dos se duplicaron: el factor aparece dos veces.$it$,
   $it$El área cambia: depende del tamaño del lado.$it$,
   $it$Correcto. $(2\ell)^2 = 4\ell^2$: el área queda multiplicada por $4$.$it$,
   $it$Ese es el factor del **volumen** al duplicar las aristas, donde el factor aparece tres veces.$it$,
   $it$areas/escala-lineal-en-el-area$it$, $it$areas/escala-lineal-en-el-area$it$, null, null),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (0.31), 100,
   $it$¿Cuál es el área de un rectángulo de $3$ m de largo por $200$ cm de ancho?$it$,
   $it$$600$ m$^2$$it$,
   $it$$6$ m$^2$$it$,
   $it$$203$ m$^2$$it$,
   $it$$600$ cm$^2$$it$,
   $it$B$it$,
   $it$Se multiplicaron $3$ y $200$ sin igualar las unidades: quedaron metros por centímetros.$it$,
   $it$Correcto. $200$ cm $= 2$ m, así que $A = 3 \times 2 = 6$ m$^2$.$it$,
   $it$Se sumaron las dos medidas, y además en unidades distintas.$it$,
   $it$El valor sale de multiplicar sin convertir, y la unidad tampoco corresponde: $600$ cm$^2$ es una superficie diminuta.$it$,
   $it$areas/opera-con-unidades-distintas$it$, null, $it$areas/opera-con-unidades-distintas$it$, $it$areas/opera-con-unidades-distintas$it$),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (0.43), 110,
   $it$Un cuadrado tiene área $64$ cm$^2$. ¿Cuánto mide su lado?$it$,
   $it$$8$ cm$it$,
   $it$$32$ cm$it$,
   $it$$16$ cm$it$,
   $it$$64$ cm$it$,
   $it$A$it$,
   $it$Correcto. Si $\ell^2 = 64$, entonces $\ell = 8$ cm.$it$,
   $it$Se dividió por $2$ en vez de sacar la raíz cuadrada.$it$,
   $it$Se dividió por $4$, que es el número de lados: eso serviría para pasar de perímetro a lado, no de área.$it$,
   $it$Ese es el área. El lado se obtiene sacándole la raíz.$it$,
   null, null, $it$areas/confunde-area-con-perimetro$it$, null),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (0.55), 120,
   $it$A un rectángulo de $10$ cm por $6$ cm se le recorta un cuadrado de $2$ cm de lado. ¿Cuál es el área que queda?$it$,
   $it$$58$ cm$^2$$it$,
   $it$$60$ cm$^2$$it$,
   $it$$56$ cm$^2$$it$,
   $it$$64$ cm$^2$$it$,
   $it$C$it$,
   $it$Se restaron $2$ en vez del área del cuadrado, que es $2^2 = 4$.$it$,
   $it$Ese es el área del rectángulo completo, sin descontar el recorte.$it$,
   $it$Correcto. $10 \times 6 = 60$ cm$^2$, menos $2 \times 2 = 4$ cm$^2$, quedan $56$ cm$^2$.$it$,
   $it$Se sumó el área del recorte en vez de restarla.$it$,
   null, null, null, null),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (0.68), 130,
   $it$Un triángulo tiene área $24$ cm$^2$ y base $8$ cm. ¿Cuánto mide su altura?$it$,
   $it$$3$ cm$it$,
   $it$$6$ cm$it$,
   $it$$16$ cm$it$,
   $it$$192$ cm$it$,
   $it$B$it$,
   $it$Se dividió el área por la base sin considerar el $2$ de la fórmula. De $\frac{8h}{2} = 24$ queda $4h = 24$.$it$,
   $it$Correcto. $\frac{8 \times h}{2} = 24$, o sea $4h = 24$ y $h = 6$ cm.$it$,
   $it$Se multiplicó por $2$ donde había que dividir, o se restó la base del área.$it$,
   $it$Se multiplicó el área por la base. Para despejar la altura hay que dividir.$it$,
   $it$areas/olvida-dividir-por-dos-en-el-triangulo$it$, null, null, null),
  ($it$geometria$it$, $it$geometria/areas$it$,
   (0.8), 140,
   $it$Un terreno mide $1.500$ m$^2$. ¿A cuántas hectáreas equivale? ($1$ ha $= 10.000$ m$^2$)$it$,
   $it$$15$ ha$it$,
   $it$$1{,}5$ ha$it$,
   $it$$150$ ha$it$,
   $it$$0{,}15$ ha$it$,
   $it$D$it$,
   $it$Se dividió por $100$. El factor entre hectárea y metro cuadrado es $10.000$.$it$,
   $it$Se dividió por $1.000$.$it$,
   $it$Se multiplicó en vez de dividir. Al pasar a una unidad **más grande** el número baja.$it$,
   $it$Correcto. $1.500 \div 10.000 = 0{,}15$ ha.$it$,
   $it$areas/opera-con-unidades-distintas$it$, $it$areas/opera-con-unidades-distintas$it$, $it$areas/opera-con-unidades-distintas$it$, null),

  -- ===========================================================================
  -- geometria/volumenes
  -- ===========================================================================
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (0.0), 10,
   $it$¿Cuál es el volumen de un cubo de arista $3$ cm?$it$,
   $it$$9$ cm$^3$$it$,
   $it$$27$ cm$^3$$it$,
   $it$$12$ cm$^3$$it$,
   $it$$54$ cm$^3$$it$,
   $it$B$it$,
   $it$Ese es el área de **una cara**: $3 \times 3$. El volumen multiplica las tres dimensiones.$it$,
   $it$Correcto. $V = 3 \times 3 \times 3 = 27$ cm$^3$.$it$,
   $it$Se multiplicó la arista por el número de aristas de una cara. El volumen no cuenta aristas.$it$,
   $it$Esa es la **superficie total** del cubo: seis caras de $9$ cm$^2$ cada una.$it$,
   $it$volumenes/confunde-volumen-con-area$it$, null, null, $it$volumenes/confunde-volumen-con-area$it$),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (0.13), 20,
   $it$¿En qué unidades se expresa un volumen?$it$,
   $it$En unidades cúbicas, como cm$^3$$it$,
   $it$En unidades cuadradas, como cm$^2$$it$,
   $it$En unidades simples, como cm$it$,
   $it$En grados$it$,
   $it$A$it$,
   $it$Correcto. El volumen multiplica tres longitudes, así que la unidad queda elevada al cubo.$it$,
   $it$Esas son las de un **área**, que multiplica dos longitudes.$it$,
   $it$Esas son las de una longitud.$it$,
   $it$Los grados miden ángulos.$it$,
   null, $it$volumenes/confunde-volumen-con-area$it$, null, null),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (0.26), 30,
   $it$¿Cuál es el volumen de una caja rectangular de $2$ cm × $3$ cm × $4$ cm?$it$,
   $it$$9$ cm$^3$$it$,
   $it$$12$ cm$^3$$it$,
   $it$$24$ cm$^3$$it$,
   $it$$52$ cm$^3$$it$,
   $it$C$it$,
   $it$Se sumaron las tres medidas. El volumen las multiplica.$it$,
   $it$Se multiplicaron solo dos de las tres dimensiones: eso da el área de una cara.$it$,
   $it$Correcto. $V = 2 \times 3 \times 4 = 24$ cm$^3$.$it$,
   $it$Esa es la **superficie total** de la caja, la suma de sus seis caras.$it$,
   null, $it$volumenes/confunde-volumen-con-area$it$, null, $it$volumenes/confunde-volumen-con-area$it$),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (0.39), 40,
   $it$¿Cuál es la fórmula del volumen de un cilindro de radio $r$ y altura $h$?$it$,
   $it$$2\pi r h$$it$,
   $it$$\pi r^2$$it$,
   $it$$\pi r h$$it$,
   $it$$\pi r^2 h$$it$,
   $it$D$it$,
   $it$Esa es el área **lateral** del cilindro, la superficie del manto desenrollado.$it$,
   $it$Esa es el área de la base. Falta multiplicar por la altura.$it$,
   $it$Falta elevar el radio al cuadrado: la base es un círculo de área $\pi r^2$.$it$,
   $it$Correcto. Volumen de un prisma o cilindro es área de la base por altura: $\pi r^2 h$.$it$,
   $it$volumenes/confunde-volumen-con-area$it$, $it$volumenes/olvida-el-area-de-la-base$it$, $it$volumenes/olvida-el-area-de-la-base$it$, null),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (0.52), 50,
   $it$¿Cuál es el volumen de un cilindro de radio $2$ cm y altura $5$ cm? (en función de $\pi$)$it$,
   $it$$10\pi$ cm$^3$$it$,
   $it$$20\pi$ cm$^3$$it$,
   $it$$40\pi$ cm$^3$$it$,
   $it$$100\pi$ cm$^3$$it$,
   $it$B$it$,
   $it$Falta elevar el radio al cuadrado: se calculó $\pi r h$ en vez de $\pi r^2 h$.$it$,
   $it$Correcto. $V = \pi (2)^2 (5) = 20\pi$ cm$^3$.$it$,
   $it$Se agregó un factor $2$ de más, probablemente arrastrado de la fórmula del perímetro.$it$,
   $it$Se elevó la altura en vez del radio.$it$,
   $it$volumenes/olvida-el-area-de-la-base$it$, null, null, null),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (0.65), 60,
   $it$¿A cuántos centímetros cúbicos equivale $1$ litro?$it$,
   $it$$1.000$ cm$^3$$it$,
   $it$$100$ cm$^3$$it$,
   $it$$10$ cm$^3$$it$,
   $it$$1.000.000$ cm$^3$$it$,
   $it$A$it$,
   $it$Correcto. $1$ L $= 1.000$ cm$^3$, que es el volumen de un cubo de $10$ cm de arista.$it$,
   $it$Ese es el factor entre metros y centímetros para longitudes, no para capacidad.$it$,
   $it$Ese factor tampoco corresponde: un cubo de $10$ cm de lado tiene $10^3$ cm$^3$.$it$,
   $it$Ese es el factor entre metro cúbico y centímetro cúbico: $1$ m$^3 = 1.000$ L.$it$,
   null, $it$volumenes/confunde-litros-con-metros-cubicos$it$, $it$volumenes/confunde-litros-con-metros-cubicos$it$, $it$volumenes/confunde-litros-con-metros-cubicos$it$),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (0.78), 70,
   $it$Si se **duplica** la arista de un cubo, ¿qué pasa con su volumen?$it$,
   $it$Se duplica$it$,
   $it$Se cuadruplica$it$,
   $it$Se multiplica por ocho$it$,
   $it$Queda igual$it$,
   $it$C$it$,
   $it$El volumen multiplica tres longitudes, y las tres se duplicaron.$it$,
   $it$Ese es el factor del **área**, donde el factor aparece dos veces. En el volumen aparece tres.$it$,
   $it$Correcto. $(2a)^3 = 8a^3$: el volumen queda multiplicado por $8$.$it$,
   $it$El volumen depende del tamaño de la arista, así que cambia.$it$,
   $it$volumenes/escala-lineal-en-el-volumen$it$, $it$volumenes/escala-lineal-en-el-volumen$it$, null, $it$volumenes/escala-lineal-en-el-volumen$it$),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (0.92), 80,
   $it$Un cubo tiene volumen $125$ cm$^3$. ¿Cuánto mide su arista?$it$,
   $it$$25$ cm$it$,
   $it$$41{,}7$ cm$it$,
   $it$$62{,}5$ cm$it$,
   $it$$5$ cm$it$,
   $it$D$it$,
   $it$Se sacó la raíz cuadrada. En un cubo hay que sacar la raíz **cúbica**, porque son tres dimensiones.$it$,
   $it$Se dividió por $3$. El $3$ es un exponente, no un factor.$it$,
   $it$Se dividió por $2$.$it$,
   $it$Correcto. $5 \times 5 \times 5 = 125$, así que la arista mide $5$ cm.$it$,
   $it$volumenes/confunde-volumen-con-area$it$, null, null, null),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (1.05), 90,
   $it$Un estanque mide $2$ m × $1$ m × $0{,}5$ m. ¿Cuántos litros de agua caben?$it$,
   $it$$1$ L$it$,
   $it$$1.000$ L$it$,
   $it$$100$ L$it$,
   $it$$1.000.000$ L$it$,
   $it$B$it$,
   $it$Ese es el volumen en **metros cúbicos**, no en litros. Falta convertir.$it$,
   $it$Correcto. $V = 2 \times 1 \times 0{,}5 = 1$ m$^3$, y $1$ m$^3 = 1.000$ L.$it$,
   $it$Se usó un factor de $100$ entre metro cúbico y litro. El factor correcto es $1.000$.$it$,
   $it$Ese es el factor entre metro cúbico y **centímetro** cúbico, no litros.$it$,
   $it$volumenes/confunde-litros-con-metros-cubicos$it$, null, $it$volumenes/confunde-litros-con-metros-cubicos$it$, $it$volumenes/confunde-litros-con-metros-cubicos$it$),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (1.18), 100,
   $it$Un prisma tiene base triangular de base $6$ cm y altura $4$ cm, y una longitud de $10$ cm. ¿Cuál es su volumen?$it$,
   $it$$120$ cm$^3$$it$,
   $it$$240$ cm$^3$$it$,
   $it$$20$ cm$^3$$it$,
   $it$$60$ cm$^3$$it$,
   $it$A$it$,
   $it$Correcto. El área de la base triangular es $\frac{6 \times 4}{2} = 12$ cm$^2$, y $12 \times 10 = 120$ cm$^3$.$it$,
   $it$El área de la base se calculó sin dividir por $2$: se usó $6 \times 4 = 24$ en vez de $12$.$it$,
   $it$Se sumaron las tres medidas.$it$,
   $it$Se multiplicaron solo dos de las tres medidas, o se dividió el resultado por $2$ una vez de más.$it$,
   null, $it$areas/olvida-dividir-por-dos-en-el-triangulo$it$, null, $it$volumenes/olvida-el-area-de-la-base$it$),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (1.31), 110,
   $it$Un cilindro tiene volumen $100\pi$ cm$^3$ y radio $5$ cm. ¿Cuál es su altura?$it$,
   $it$$20$ cm$it$,
   $it$$10$ cm$it$,
   $it$$4$ cm$it$,
   $it$$2$ cm$it$,
   $it$C$it$,
   $it$Se dividió por el radio sin elevarlo al cuadrado: el área de la base es $\pi(5)^2 = 25\pi$, no $5\pi$.$it$,
   $it$Se dividió por el **diámetro** ($10$) como si fuera el área de la base. La base es un círculo de área $\pi(5)^2$.$it$,
   $it$Correcto. $\pi(5)^2 h = 100\pi$, o sea $25h = 100$ y $h = 4$ cm.$it$,
   $it$Se tomó el área de la base como el doble de lo que es ($50$ en vez de $25$), y quedó la mitad de la altura.$it$,
   $it$volumenes/olvida-el-area-de-la-base$it$, null, null, null),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (1.44), 120,
   $it$Un tarro cilíndrico tiene radio $10$ cm y altura $20$ cm. Tomando $\pi \approx 3{,}14$, ¿cuántos litros contiene aproximadamente?$it$,
   $it$$62{,}8$ L$it$,
   $it$$0{,}628$ L$it$,
   $it$$628$ L$it$,
   $it$$6{,}28$ L$it$,
   $it$D$it$,
   $it$El volumen en cm$^3$ es $6.280$; al pasar a litros hay que dividir por $1.000$, no por $100$.$it$,
   $it$Se dividió por $10.000$. El factor entre centímetro cúbico y litro es $1.000$.$it$,
   $it$Ese es el volumen en cm$^3$ dividido por $10$: quedó a un paso de la conversión.$it$,
   $it$Correcto. $V = 3{,}14 \times 100 \times 20 = 6.280$ cm$^3$, y $6.280 \div 1.000 = 6{,}28$ L.$it$,
   $it$volumenes/confunde-litros-con-metros-cubicos$it$, $it$volumenes/confunde-litros-con-metros-cubicos$it$, $it$volumenes/confunde-litros-con-metros-cubicos$it$, null),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (1.57), 130,
   $it$Si se duplica la arista de un cubo, ¿cómo cambian su **superficie total** y su **volumen**?$it$,
   $it$Los dos se duplican$it$,
   $it$La superficie se cuadruplica y el volumen se multiplica por ocho$it$,
   $it$La superficie se duplica y el volumen se cuadruplica$it$,
   $it$Los dos se multiplican por ocho$it$,
   $it$B$it$,
   $it$Solo las longitudes se duplican. La superficie y el volumen crecen más rápido, porque combinan varias longitudes.$it$,
   $it$Correcto. La superficie depende de $a^2$, así que crece $2^2 = 4$ veces; el volumen depende de $a^3$ y crece $2^3 = 8$ veces.$it$,
   $it$Los factores están corridos: la superficie va con el exponente $2$ y el volumen con el $3$.$it$,
   $it$El factor $8$ corresponde solo al volumen. La superficie crece cuatro veces.$it$,
   $it$volumenes/escala-lineal-en-el-volumen$it$, null, $it$volumenes/escala-lineal-en-el-volumen$it$, $it$volumenes/escala-lineal-en-el-volumen$it$),
  ($it$geometria$it$, $it$geometria/volumenes$it$,
   (1.7), 140,
   $it$Un cubo de arista $6$ cm se corta en cubitos de arista $2$ cm. ¿Cuántos cubitos se obtienen?$it$,
   $it$$3$$it$,
   $it$$9$$it$,
   $it$$27$$it$,
   $it$$18$$it$,
   $it$C$it$,
   $it$Ese es cuántos cubitos caben a lo **largo** de una arista. Hay que contar en las tres direcciones.$it$,
   $it$Se contó en dos direcciones: eso da los cubitos de una sola capa.$it$,
   $it$Correcto. Caben $3$ en cada dirección, así que son $3 \times 3 \times 3 = 27$. Se comprueba con los volúmenes: $216 \div 8 = 27$.$it$,
   $it$Se multiplicó por $2$ el resultado de una capa, en vez de considerar las tres capas.$it$,
   $it$volumenes/escala-lineal-en-el-volumen$it$, $it$volumenes/confunde-volumen-con-area$it$, null, null),

  -- ===========================================================================
  -- geometria/pitagoras
  -- ===========================================================================
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (0.8), 10,
   $it$El teorema de Pitágoras relaciona:$it$,
   $it$los ángulos de cualquier triángulo$it$,
   $it$los lados de cualquier triángulo$it$,
   $it$el área y el perímetro de un triángulo$it$,
   $it$los lados de un triángulo **rectángulo**$it$,
   $it$D$it$,
   $it$El teorema habla de longitudes, no de ángulos. Lo que suma $180^\circ$ son los ángulos interiores, y eso es otra propiedad.$it$,
   $it$Solo vale si el triángulo tiene un ángulo recto. En cualquier otro la igualdad no se cumple.$it$,
   $it$No relaciona área con perímetro: relaciona los cuadrados de tres longitudes.$it$,
   $it$Correcto. En un triángulo rectángulo, el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos.$it$,
   null, $it$pitagoras/aplica-el-teorema-en-triangulo-no-rectangulo$it$, null, null),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (0.95), 20,
   $it$En un triángulo rectángulo, la **hipotenusa** es:$it$,
   $it$el lado más corto$it$,
   $it$el lado opuesto al ángulo recto, y siempre el más largo$it$,
   $it$cualquiera de los dos lados que forman el ángulo recto$it$,
   $it$la altura del triángulo$it$,
   $it$B$it$,
   $it$Es al revés: la hipotenusa es siempre el lado más largo, porque se opone al ángulo mayor.$it$,
   $it$Correcto. La hipotenusa se opone al ángulo recto y supera a cualquiera de los catetos.$it$,
   $it$Esos son los **catetos**: los dos lados que forman el ángulo recto.$it$,
   $it$La altura es un segmento auxiliar, no uno de los tres lados.$it$,
   $it$pitagoras/confunde-cateto-con-hipotenusa$it$, null, $it$pitagoras/confunde-cateto-con-hipotenusa$it$, null),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (1.1), 30,
   $it$Un triángulo rectángulo tiene catetos de $3$ y $4$ cm. ¿Cuánto mide su hipotenusa?$it$,
   $it$$7$ cm$it$,
   $it$$25$ cm$it$,
   $it$$5$ cm$it$,
   $it$$12$ cm$it$,
   $it$C$it$,
   $it$Se sumaron los catetos sin elevarlos al cuadrado. El teorema relaciona los cuadrados.$it$,
   $it$Ese es $c^2$: $9 + 16 = 25$. Falta el último paso, sacar la raíz cuadrada.$it$,
   $it$Correcto. $c^2 = 3^2 + 4^2 = 9 + 16 = 25$, así que $c = 5$ cm.$it$,
   $it$Se multiplicaron los catetos. Ese producto sirve para el área ($\frac{3\times 4}{2}$), no para la hipotenusa.$it$,
   $it$pitagoras/suma-los-lados-sin-elevar$it$, $it$pitagoras/olvida-la-raiz-final$it$, null, null),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (1.25), 40,
   $it$Un triángulo rectángulo tiene catetos de $6$ y $8$ cm. ¿Cuánto mide su hipotenusa?$it$,
   $it$$10$ cm$it$,
   $it$$14$ cm$it$,
   $it$$100$ cm$it$,
   $it$$2$ cm$it$,
   $it$A$it$,
   $it$Correcto. $c^2 = 36 + 64 = 100$, así que $c = 10$ cm.$it$,
   $it$Se sumaron los catetos directamente, sin elevar al cuadrado.$it$,
   $it$Ese es $c^2$. Falta sacar la raíz.$it$,
   $it$Se restaron los catetos. Para la hipotenusa los cuadrados se **suman**; restar sirve para hallar un cateto.$it$,
   null, $it$pitagoras/suma-los-lados-sin-elevar$it$, $it$pitagoras/olvida-la-raiz-final$it$, $it$pitagoras/resta-donde-corresponde-sumar$it$),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (1.4), 50,
   $it$En un triángulo rectángulo la hipotenusa mide $13$ cm y un cateto $5$ cm. ¿Cuánto mide el otro cateto?$it$,
   $it$$18$ cm$it$,
   $it$$\sqrt{194}$ cm$it$,
   $it$$8$ cm$it$,
   $it$$12$ cm$it$,
   $it$D$it$,
   $it$Se sumaron las dos medidas. Además, un cateto nunca puede ser mayor que la hipotenusa.$it$,
   $it$Se sumaron los cuadrados ($169 + 25$) en vez de restarlos. Ese cálculo da la hipotenusa de otro triángulo, no el cateto que falta.$it$,
   $it$Se restaron las medidas sin elevarlas al cuadrado: $13 - 5$. La resta va entre los **cuadrados**.$it$,
   $it$Correcto. $b^2 = 13^2 - 5^2 = 169 - 25 = 144$, así que $b = 12$ cm.$it$,
   $it$pitagoras/suma-los-lados-sin-elevar$it$, $it$pitagoras/resta-donde-corresponde-sumar$it$, $it$pitagoras/suma-los-lados-sin-elevar$it$, null),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (1.6), 60,
   $it$¿Es rectángulo un triángulo de lados $5$, $12$ y $13$?$it$,
   $it$No, porque los tres lados son distintos$it$,
   $it$Sí, porque $5^2 + 12^2 = 13^2$$it$,
   $it$No, porque $5 + 12 \neq 13$$it$,
   $it$Sí, porque $13$ es un número primo$it$,
   $it$B$it$,
   $it$Un triángulo rectángulo puede perfectamente tener los tres lados distintos: este lo es.$it$,
   $it$Correcto. $25 + 144 = 169 = 13^2$: el recíproco del teorema confirma que hay un ángulo recto.$it$,
   $it$Que los dos lados menores sumen más que el mayor solo garantiza que el triángulo **existe**. Para el ángulo recto hay que comparar los cuadrados.$it$,
   $it$Que un lado sea primo no dice nada sobre los ángulos.$it$,
   null, null, $it$pitagoras/suma-los-lados-sin-elevar$it$, null),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (1.8), 70,
   $it$¿Es rectángulo un triángulo de lados $4$, $5$ y $6$?$it$,
   $it$Sí, porque $4 + 5 > 6$$it$,
   $it$Sí, porque los lados son consecutivos$it$,
   $it$No, porque $4^2 + 5^2 = 41$ y $6^2 = 36$$it$,
   $it$No se puede saber sin conocer los ángulos$it$,
   $it$C$it$,
   $it$Esa condición solo asegura que el triángulo se puede construir, no que tenga un ángulo recto.$it$,
   $it$Que los lados sean consecutivos no implica nada sobre los ángulos: $3$, $4$, $5$ también lo son y ese sí es rectángulo.$it$,
   $it$Correcto. Como $41 \neq 36$, no se cumple el teorema y el triángulo no es rectángulo. De hecho, al ser $41 > 36$, el ángulo mayor es agudo.$it$,
   $it$Sí se puede: el recíproco del teorema permite decidirlo solo con los lados.$it$,
   $it$pitagoras/suma-los-lados-sin-elevar$it$, $it$pitagoras/aplica-el-teorema-en-triangulo-no-rectangulo$it$, null, null),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (2.0), 80,
   $it$¿Cuánto mide la **diagonal** de un rectángulo de $3$ cm por $4$ cm?$it$,
   $it$$5$ cm$it$,
   $it$$7$ cm$it$,
   $it$$12$ cm$it$,
   $it$$14$ cm$it$,
   $it$A$it$,
   $it$Correcto. La diagonal parte el rectángulo en dos triángulos rectángulos de catetos $3$ y $4$: mide $\sqrt{9+16} = 5$ cm.$it$,
   $it$Se sumaron los lados sin elevar al cuadrado.$it$,
   $it$Ese es el **área** del rectángulo, no una longitud.$it$,
   $it$Ese es el perímetro.$it$,
   null, $it$pitagoras/suma-los-lados-sin-elevar$it$, null, null),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (2.15), 90,
   $it$¿Cuánto mide la diagonal de un cuadrado de lado $5$ cm?$it$,
   $it$$10$ cm$it$,
   $it$$25$ cm$it$,
   $it$$5$ cm$it$,
   $it$$5\sqrt{2}$ cm$it$,
   $it$D$it$,
   $it$Se sumaron los dos lados. La diagonal es la hipotenusa de un triángulo de catetos $5$ y $5$, y vale bastante menos que $10$.$it$,
   $it$Ese es el área del cuadrado, no una longitud. Aplicando el teorema queda $d^2 = 25 + 25 = 50$, y todavía falta sacar la raíz.$it$,
   $it$Ese es el lado. La diagonal siempre es más larga que el lado.$it$,
   $it$Correcto. $d = \sqrt{5^2 + 5^2} = \sqrt{50} = 5\sqrt{2} \approx 7{,}07$ cm.$it$,
   $it$pitagoras/suma-los-lados-sin-elevar$it$, $it$pitagoras/olvida-la-raiz-final$it$, null, null),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (2.3), 100,
   $it$¿Cuál es la distancia entre los puntos $(0, 0)$ y $(3, 4)$ del plano?$it$,
   $it$$7$$it$,
   $it$$5$$it$,
   $it$$12$$it$,
   $it$$1$$it$,
   $it$B$it$,
   $it$Se sumaron las coordenadas. La distancia es la hipotenusa de un triángulo de catetos $3$ y $4$.$it$,
   $it$Correcto. $d = \sqrt{3^2 + 4^2} = \sqrt{25} = 5$.$it$,
   $it$Se multiplicaron las coordenadas.$it$,
   $it$Se restaron las coordenadas entre sí. La resta va entre coordenadas del **mismo** eje, y acá el origen está en cero.$it$,
   $it$pitagoras/suma-los-lados-sin-elevar$it$, null, null, $it$pitagoras/distancia-sin-restar-coordenadas$it$),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (2.5), 110,
   $it$Una escalera de $5$ m se apoya en una pared, con su base a $3$ m del muro. ¿A qué altura llega?$it$,
   $it$$8$ m$it$,
   $it$$2$ m$it$,
   $it$$4$ m$it$,
   $it$$\sqrt{34}$ m$it$,
   $it$C$it$,
   $it$Se sumaron las dos medidas. La escalera es la hipotenusa: la altura tiene que ser **menor** que $5$ m.$it$,
   $it$Se restaron las medidas sin elevarlas al cuadrado. La resta va entre los cuadrados: $25 - 9$.$it$,
   $it$Correcto. $h^2 = 5^2 - 3^2 = 25 - 9 = 16$, así que $h = 4$ m.$it$,
   $it$Se sumaron los cuadrados en vez de restarlos. Acá el $5$ es la hipotenusa, así que su cuadrado es del que se resta.$it$,
   $it$pitagoras/suma-los-lados-sin-elevar$it$, $it$pitagoras/suma-los-lados-sin-elevar$it$, null, $it$pitagoras/resta-donde-corresponde-sumar$it$),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (2.7), 120,
   $it$¿Cuál es la distancia entre los puntos $(1, 2)$ y $(4, 6)$?$it$,
   $it$$5$$it$,
   $it$$7$$it$,
   $it$$\sqrt{57}$$it$,
   $it$$13$$it$,
   $it$A$it$,
   $it$Correcto. Las diferencias son $4-1 = 3$ y $6-2 = 4$, así que $d = \sqrt{9 + 16} = 5$.$it$,
   $it$Se sumaron las diferencias ($3 + 4$) sin elevarlas al cuadrado.$it$,
   $it$Se elevaron las cuatro coordenadas y se sumaron: $1+4+16+36 = 57$. Primero hay que restar coordenada con coordenada del mismo eje.$it$,
   $it$Se sumaron las cuatro coordenadas.$it$,
   null, $it$pitagoras/suma-los-lados-sin-elevar$it$, $it$pitagoras/distancia-sin-restar-coordenadas$it$, $it$pitagoras/distancia-sin-restar-coordenadas$it$),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (2.85), 130,
   $it$¿Cuánto mide la altura de un triángulo **equilátero** de lado $6$ cm?$it$,
   $it$$6$ cm$it$,
   $it$$3$ cm$it$,
   $it$$\sqrt{45}$ cm$it$,
   $it$$3\sqrt{3}$ cm$it$,
   $it$D$it$,
   $it$La altura siempre es menor que el lado: cae dentro del triángulo.$it$,
   $it$Ese es la mitad del lado, o sea el cateto de la base, no la altura.$it$,
   $it$Se usó $6$ y $3$ como catetos y se sumaron sus cuadrados. Acá el $6$ es la **hipotenusa**, así que se resta: $36 - 9$.$it$,
   $it$Correcto. La altura parte el equilátero en dos triángulos rectángulos de hipotenusa $6$ y cateto $3$: $h = \sqrt{36-9} = \sqrt{27} = 3\sqrt{3} \approx 5{,}2$ cm.$it$,
   $it$pitagoras/confunde-cateto-con-hipotenusa$it$, null, $it$pitagoras/resta-donde-corresponde-sumar$it$, null),
  ($it$geometria$it$, $it$geometria/pitagoras$it$,
   (3.0), 140,
   $it$Una caja mide $3$ cm × $4$ cm × $12$ cm. ¿Cuánto mide la varilla más larga que cabe dentro, en línea recta?$it$,
   $it$$19$ cm$it$,
   $it$$13$ cm$it$,
   $it$$12$ cm$it$,
   $it$$5$ cm$it$,
   $it$B$it$,
   $it$Se sumaron las tres aristas. La diagonal es mucho más corta que recorrer los tres bordes.$it$,
   $it$Correcto. Se aplica el teorema dos veces: la diagonal de la base es $\sqrt{9+16} = 5$, y con la altura queda $\sqrt{25 + 144} = \sqrt{169} = 13$ cm.$it$,
   $it$Esa es la arista más larga. La diagonal del cuerpo la supera, porque también recorre las otras dos dimensiones.$it$,
   $it$Esa es la diagonal de la **base**. Falta combinarla con la altura de $12$ cm.$it$,
   $it$pitagoras/suma-los-lados-sin-elevar$it$, null, null, null)

)
insert into public.questions
  (topic, module_id, difficulty, order_index,
   question, option_a, option_b, option_c, option_d, correct_option,
   error_a, error_b, error_c, error_d,
   misconception_a_id, misconception_b_id, misconception_c_id, misconception_d_id)
select i.topic, m.id, i.difficulty, i.order_index,
       i.question, i.option_a, i.option_b, i.option_c, i.option_d, i.correct_option,
       i.error_a, i.error_b, i.error_c, i.error_d,
       xa.id, xb.id, xc.id, xd.id
from items i
left join public.modules m        on m.slug  = i.module_slug
left join public.misconceptions xa on xa.slug = i.mis_a
left join public.misconceptions xb on xb.slug = i.mis_b
left join public.misconceptions xc on xc.slug = i.mis_c
left join public.misconceptions xd on xd.slug = i.mis_d
-- Idempotente por (topic, question). Reaplicar NO actualiza un ítem ya
-- cargado: para corregirlo, editarlo en Admin → Preguntas o borrarlo primero.
where not exists (
  select 1 from public.questions q
   where q.topic = i.topic and q.question = i.question
);

-- -----------------------------------------------------------------------------
-- Verificación (correr después de aplicar)
-- -----------------------------------------------------------------------------
--   select count(*) from public.questions where topic = 'geometria';
--   -- esperado: 100 (más lo que ya hubiera)
--
--   -- Ningún ítem sin módulo: delataría un module_slug mal escrito.
--   select id from public.questions where topic = 'geometria' and module_id is null;
--   -- 0 filas
--
--   -- Ningún distractor perdió su idea errónea en el join.
--   select id, question from public.questions q
--    where topic = 'geometria'
--      and misconception_a_id is null and misconception_b_id is null
--      and misconception_c_id is null and misconception_d_id is null;
--   -- revisar: un ítem sin ninguna catalogada puede ser legítimo, varios no
--
--   -- La clave repartida (R-35): ninguna letra debe pasar del 40 %.
--   select correct_option, count(*) from public.questions
--    where topic = 'geometria' group by 1 order by 1;
--
-- Reversión: delete from public.questions where topic = 'geometria';
--            delete from public.misconceptions where slug in ('geometria/confunde-el-factor-entre-unidades', 'geometria/convierte-en-el-sentido-contrario', 'geometria/clasifica-el-angulo-por-apariencia', …);
