-- Banco del eje de probabilidad y estadística — primera tanda
-- 100 ítems · topic `probabilidad` · 41 ideas erróneas nuevas
--
-- GENERADA por scripts/generar_migracion_items.py desde el JSON de la tanda.
-- No editar a mano: corregir el JSON, volver a verificar y regenerar. Un cambio
-- hecho acá se pierde en la siguiente regeneración y deja de estar verificado.
--
-- Verificada con scripts/verificar_items.py, que comprueba lo que este banco
-- aprendió a golpes: clave repartida entre las cuatro letras (R-35), una sola
-- alternativa correcta, las cuatro explicaciones escritas, la correcta sin idea
-- errónea, LaTeX con escape simple (047) y cobertura de dificultad sin huecos.
--
-- 100 ítems repartidos en los seis módulos del eje, cubriendo toda la escala
-- [-3, 3] con al menos 6 ítems por tramo de 1,0 logit.
--
-- REQUIERE la migración 055 aplicada (los módulos del eje). Antes de 055 el eje
-- no existía: cero módulos y cero ítems, y sin módulo el `left join` de esta
-- migración dejaría los 100 ítems con `module_id` en null y en silencio (T-119).
--
-- Cuarto y último eje del temario construido con la skill `banco-de-items`. Como
-- geometría, se escribe sin banco previo: no hay ningún `topic` de probabilidad
-- ni de estadística en `questions`.
--
-- `difficulty` es una HIPÓTESIS EDITORIAL, no una medición (R-17).

-- -----------------------------------------------------------------------------
-- 1. Ideas erróneas nuevas
-- -----------------------------------------------------------------------------
-- Van ANTES de los ítems y en el mismo archivo: el `left join` de abajo
-- resuelve por slug, así que si no existen todavía los ítems entrarían con
-- `misconception_*_id` en null y en silencio.
--
-- `on conflict (slug) do nothing`: si una ya está catalogada, se respeta la
-- que hay. Reaplicar contenido no pisa una corrección hecha en el panel.

insert into public.misconceptions (slug, name, description, module_id)
select v.slug, v.name, v.description, m.id
  from (values
    ($it$datos/confunde-frecuencia-con-dato$it$, $it$Confunde el valor de la variable con su frecuencia$it$, $it$Usar cuando entrega el dato donde se pedía cuántas veces aparece, o al revés. NO usar si el error es de suma.$it$, $it$probabilidad/datos$it$),
    ($it$datos/frecuencia-relativa-como-absoluta$it$, $it$Entrega el conteo donde se pedía la proporción$it$, $it$Usar cuando responde con la frecuencia absoluta una pregunta por la relativa o por el porcentaje.$it$, $it$probabilidad/datos$it$),
    ($it$datos/frecuencia-relativa-invertida$it$, $it$Divide el total por la frecuencia en vez de la frecuencia por el total$it$, $it$Usar cuando el resultado es mayor que 1 o el recíproco del correcto. La frecuencia relativa nunca pasa de 1.$it$, $it$probabilidad/datos$it$),
    ($it$datos/acumulada-como-simple$it$, $it$Usa la frecuencia simple donde se pedía la acumulada$it$, $it$Usar cuando la pregunta dice «hasta», «como máximo» o «al menos» y responde solo con la frecuencia de ese valor.$it$, $it$probabilidad/datos$it$),
    ($it$datos/lee-el-grafico-por-la-posicion$it$, $it$Decide con la posición de la barra en vez de su altura$it$, $it$Usar cuando elige la primera o la última barra, o la más angosta, para responder cuál es la más frecuente.$it$, $it$probabilidad/datos$it$),
    ($it$datos/lee-mal-la-escala-del-eje$it$, $it$Compara alturas sin mirar la escala del eje$it$, $it$Usar cuando concluye a partir del tamaño visual de las barras ignorando dónde empieza el eje o cuánto vale cada división.$it$, $it$probabilidad/datos$it$),
    ($it$datos/confunde-el-angulo-con-el-porcentaje$it$, $it$Lee el ángulo de un sector circular como si fuera su porcentaje$it$, $it$Usar cuando dice que un sector de 90° es el 90 %. La vuelta completa son 360°, no 100.$it$, $it$probabilidad/datos$it$),
    ($it$datos/confunde-el-porcentaje-con-la-cantidad$it$, $it$Entrega el porcentaje donde se pedía la cantidad de casos$it$, $it$Usar cuando responde «25» a cuántas personas son el 25 % de un total distinto de 100.$it$, $it$probabilidad/datos$it$),
    ($it$datos/lee-mal-el-intervalo$it$, $it$Ubica mal un dato que cae en el borde de un intervalo$it$, $it$Usar cuando pone un valor en el intervalo equivocado por no leer el corchete cerrado y el paréntesis abierto.$it$, $it$probabilidad/datos$it$),
    ($it$estadistica/confunde-poblacion-con-muestra$it$, $it$Intercambia población y muestra$it$, $it$Usar cuando llama población al grupo encuestado o muestra al total del que se quiere concluir.$it$, $it$probabilidad/datos$it$),
    ($it$estadistica/confunde-cualitativa-con-cuantitativa$it$, $it$Clasifica como cuantitativa una variable que no se mide con números$it$, $it$Usar con color, marca, comuna o preferencia. Que se pueda codificar con un número no la hace cuantitativa.$it$, $it$probabilidad/datos$it$),
    ($it$estadistica/confunde-discreta-con-continua$it$, $it$Mezcla variable discreta con variable continua$it$, $it$Usar cuando llama continua a un conteo (hermanos, goles) o discreta a una medición (estatura, tiempo).$it$, $it$probabilidad/datos$it$),
    ($it$estadistica/media-sin-dividir-por-n$it$, $it$Suma los datos y no divide por cuántos son$it$, $it$Usar cuando entrega la suma total como si fuera el promedio.$it$, $it$probabilidad/tendencia-central$it$),
    ($it$estadistica/mediana-sin-ordenar$it$, $it$Toma el dato del medio sin ordenar la lista$it$, $it$Usar cuando entrega el valor que está físicamente al centro de la lista tal como venía escrita.$it$, $it$probabilidad/tendencia-central$it$),
    ($it$estadistica/mediana-par-toma-uno-solo$it$, $it$Con cantidad par de datos elige uno de los dos centrales$it$, $it$Usar cuando no promedia los dos valores del centro. NO usar si el error fue no ordenar.$it$, $it$probabilidad/tendencia-central$it$),
    ($it$estadistica/confunde-moda-con-frecuencia$it$, $it$Entrega cuántas veces se repite en vez del dato que se repite$it$, $it$Usar cuando responde la frecuencia máxima donde se pedía la moda.$it$, $it$probabilidad/tendencia-central$it$),
    ($it$estadistica/confunde-las-tres-medidas$it$, $it$Intercambia media, mediana y moda$it$, $it$Usar cuando entrega una medida de tendencia central por otra sin que haya error de cálculo.$it$, $it$probabilidad/tendencia-central$it$),
    ($it$estadistica/media-ignora-la-frecuencia$it$, $it$Promedia los valores de una tabla sin ponderar por su frecuencia$it$, $it$Usar cuando promedia las categorías como si cada una apareciera una sola vez.$it$, $it$probabilidad/tendencia-central$it$),
    ($it$estadistica/promedia-los-promedios$it$, $it$Promedia promedios de grupos de distinto tamaño$it$, $it$Usar cuando saca el promedio de dos promedios sin pesar cuántos datos hay en cada grupo.$it$, $it$probabilidad/tendencia-central$it$),
    ($it$estadistica/la-mediana-se-mueve-con-los-extremos$it$, $it$Cree que un dato extremo arrastra a la mediana igual que a la media$it$, $it$Usar cuando afirma que cambiar el dato más grande cambia la mediana. La mediana depende de la posición, no del valor.$it$, $it$probabilidad/tendencia-central$it$),
    ($it$posicion/cuartil-como-cuarta-parte-del-valor$it$, $it$Divide el valor por cuatro en vez de buscar la posición$it$, $it$Usar cuando calcula un cuartil operando con el dato y no con el lugar que ocupa en la lista ordenada.$it$, $it$probabilidad/posicion$it$),
    ($it$posicion/percentil-como-porcentaje-de-logro$it$, $it$Lee el percentil como el porcentaje de respuestas correctas$it$, $it$Usar cuando dice que estar en el percentil 90 es haber contestado bien el 90 % de la prueba.$it$, $it$probabilidad/posicion$it$),
    ($it$posicion/mediana-no-es-q2$it$, $it$No reconoce que el segundo cuartil es la mediana$it$, $it$Usar cuando trata Q2 y la mediana como dos medidas distintas, o cuando confunde Q1 o Q3 con el centro.$it$, $it$probabilidad/posicion$it$),
    ($it$posicion/rango-intercuartil-mal-restado$it$, $it$Suma los cuartiles o los resta al revés$it$, $it$Usar cuando entrega Q3 + Q1, Q1 − Q3 o el promedio de los dos donde iba Q3 − Q1.$it$, $it$probabilidad/posicion$it$),
    ($it$posicion/lee-mal-el-cajon$it$, $it$Lee los extremos de la caja como el mínimo y el máximo$it$, $it$Usar cuando confunde las partes del diagrama de cajón: la caja va de Q1 a Q3 y los bigotes llegan a los extremos.$it$, $it$probabilidad/posicion$it$),
    ($it$dispersion/rango-mal-calculado$it$, $it$Suma o promedia los extremos en vez de restarlos$it$, $it$Usar cuando el rango sale como suma, promedio o total de los datos.$it$, $it$probabilidad/dispersion$it$),
    ($it$dispersion/desviacion-sin-raiz$it$, $it$Entrega la varianza donde se pedía la desviación estándar$it$, $it$Usar cuando falta (o sobra) el paso de la raíz cuadrada entre varianza y desviación.$it$, $it$probabilidad/dispersion$it$),
    ($it$dispersion/dispersion-cambia-al-sumar-constante$it$, $it$Cree que sumar una constante a todos los datos cambia la dispersión$it$, $it$Usar cuando dice que el rango o la desviación se corren junto con el promedio. Sumar traslada, no estira.$it$, $it$probabilidad/dispersion$it$),
    ($it$dispersion/confunde-nivel-con-dispersion$it$, $it$Deduce del promedio cuánto se dispersan los datos, o al revés$it$, $it$Usar cuando afirma que más desviación significa notas más altas, o que igual promedio significa igual dispersión.$it$, $it$probabilidad/dispersion$it$),
    ($it$dispersion/desviacion-negativa$it$, $it$Acepta una desviación estándar negativa o mayor que el rango$it$, $it$Usar cuando no reconoce que la desviación sale de cuadrados y por eso nunca es negativa.$it$, $it$probabilidad/dispersion$it$),
    ($it$azar/favorables-sobre-desfavorables$it$, $it$Pone los casos desfavorables en el denominador$it$, $it$Usar cuando escribe 3/5 donde iban 3 de 8: la regla de Laplace divide por el TOTAL, no por el resto.$it$, $it$probabilidad/azar$it$),
    ($it$azar/probabilidad-fuera-de-cero-uno$it$, $it$Entrega una probabilidad negativa, mayor que 1 o en escala equivocada$it$, $it$Usar cuando el resultado no puede ser una probabilidad: 100, 1,5, −0,3 o el número de casos a secas.$it$, $it$probabilidad/azar$it$),
    ($it$azar/cuenta-mal-el-espacio-muestral$it$, $it$Cuenta mal los casos totales$it$, $it$Usar cuando el denominador no corresponde al total de resultados posibles: suma donde había que multiplicar, o cuenta de menos.$it$, $it$probabilidad/azar$it$),
    ($it$azar/resultados-compuestos-como-equiprobables$it$, $it$Trata como equiprobables resultados que no lo son$it$, $it$Usar con las sumas de dos dados o con «una cara y un sello»: hay más maneras de obtener unos que otros.$it$, $it$probabilidad/azar$it$),
    ($it$azar/olvida-que-no-hay-reposicion$it$, $it$Mantiene el total del espacio muestral tras una extracción sin reposición$it$, $it$Usar cuando repite la misma fracción en la segunda extracción sin descontar la bolita que ya salió.$it$, $it$probabilidad/azar$it$),
    ($it$reglas/complemento-mal-calculado$it$, $it$Calcula la probabilidad de que no ocurra restando de algo que no es 1$it$, $it$Usar cuando resta de 100, de 0,5 o simplemente cambia el signo.$it$, $it$probabilidad/reglas$it$),
    ($it$reglas/suma-sin-restar-la-interseccion$it$, $it$Suma las probabilidades de dos eventos que pueden ocurrir juntos$it$, $it$Usar cuando aplica P(A)+P(B) sin descontar P(A∩B). NO usar si los eventos sí son excluyentes.$it$, $it$probabilidad/reglas$it$),
    ($it$reglas/confunde-excluyentes-con-independientes$it$, $it$Trata «no pueden ocurrir juntos» como «no se influyen»$it$, $it$Usar cuando multiplica probabilidades de eventos excluyentes, o cuando llama independientes a los que se excluyen.$it$, $it$probabilidad/reglas$it$),
    ($it$reglas/suma-donde-va-producto$it$, $it$Suma probabilidades de eventos que deben ocurrir los dos$it$, $it$Usar cuando responde P(A)+P(B) donde iba P(A)·P(B), típico en «y» y en «al menos uno».$it$, $it$probabilidad/reglas$it$),
    ($it$reglas/condicional-usa-el-total-equivocado$it$, $it$En una probabilidad condicional divide por el total general$it$, $it$Usar cuando no reduce el espacio muestral al grupo que la condición ya fijó.$it$, $it$probabilidad/reglas$it$),
    ($it$reglas/falacia-del-jugador$it$, $it$Cree que los resultados pasados cambian la probabilidad del próximo$it$, $it$Usar cuando dice que después de varias caras «toca» sello. La moneda no tiene memoria.$it$, $it$probabilidad/reglas$it$)
  ) as v(slug, name, description, module_slug)
  left join public.modules m on m.slug = v.module_slug
on conflict (slug) do nothing;

-- -----------------------------------------------------------------------------
-- 2. Ítems
-- -----------------------------------------------------------------------------

with items (topic, module_slug, difficulty, order_index,
            question, option_a, option_b, option_c, option_d, correct_option,
            error_a, error_b, error_c, error_d,
            mis_a, mis_b, mis_c, mis_d) as (
  values

  -- ===========================================================================
  -- probabilidad/datos
  -- ===========================================================================
  ($it$probabilidad$it$::text, $it$probabilidad/datos$it$::text,
   (-3.0)::double precision, 10::int,
   $it$En una tabla de frecuencias, la **frecuencia absoluta** de un dato es:$it$::text,
   $it$el valor del dato$it$::text,
   $it$la cantidad de veces que ese dato aparece$it$::text,
   $it$el total de datos de la tabla$it$::text,
   $it$el porcentaje que representa el dato$it$::text,
   $it$B$it$::text,
   $it$Ese es el dato mismo. La frecuencia responde otra pregunta: cuántas veces aparece.$it$::text,
   $it$Correcto. La frecuencia absoluta cuenta cuántas veces aparece ese dato en los datos recogidos.$it$::text,
   $it$Ese es el total, que se obtiene sumando **todas** las frecuencias.$it$::text,
   $it$Ese es el porcentaje, que sale de dividir la frecuencia por el total. La absoluta es el conteo a secas.$it$::text,
   $it$datos/confunde-frecuencia-con-dato$it$::text, null::text, null::text, $it$datos/frecuencia-relativa-como-absoluta$it$::text),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.91), 20,
   $it$Una tabla registra cuántos hermanos tienen los estudiantes de un curso: $0$ hermanos, $4$ estudiantes; $1$ hermano, $9$; $2$ hermanos, $5$; $3$ hermanos, $2$. ¿Cuántos estudiantes tienen $2$ hermanos?$it$,
   $it$$2$$it$,
   $it$$20$$it$,
   $it$$9$$it$,
   $it$$5$$it$,
   $it$D$it$,
   $it$Ese es el valor de la variable —la cantidad de hermanos—, no cuántos estudiantes lo tienen.$it$,
   $it$Ese es el total de estudiantes del curso: $4+9+5+2$.$it$,
   $it$Esa es la frecuencia mayor de la tabla, pero corresponde a los que tienen $1$ hermano.$it$,
   $it$Correcto. La fila del $2$ tiene frecuencia $5$: son cinco estudiantes.$it$,
   $it$datos/confunde-frecuencia-con-dato$it$, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.83), 30,
   $it$Con la misma tabla ($0$: $4$; $1$: $9$; $2$: $5$; $3$: $2$), ¿cuántos estudiantes tiene el curso?$it$,
   $it$$20$$it$,
   $it$$6$$it$,
   $it$$4$$it$,
   $it$$9$$it$,
   $it$A$it$,
   $it$Correcto. $4+9+5+2 = 20$ estudiantes.$it$,
   $it$Se sumaron los valores de la variable ($0+1+2+3$) en vez de las frecuencias.$it$,
   $it$Esa es solo la primera frecuencia. El total suma las cuatro filas.$it$,
   $it$Esa es la frecuencia más alta, no el total.$it$,
   null, $it$datos/confunde-frecuencia-con-dato$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.74), 40,
   $it$En un gráfico de barras, ¿cómo se reconoce la categoría más frecuente?$it$,
   $it$Es la primera barra de la izquierda$it$,
   $it$Es la barra más angosta$it$,
   $it$Es la barra más alta$it$,
   $it$Es la última barra de la derecha$it$,
   $it$C$it$,
   $it$El orden de las barras es una convención de quien dibuja el gráfico y no dice nada sobre la frecuencia.$it$,
   $it$Todas las barras tienen el mismo ancho: lo que cambia de una a otra es la altura.$it$,
   $it$Correcto. La altura de cada barra representa su frecuencia, así que la más alta es la más frecuente.$it$,
   $it$La posición de una barra la decide quien arma el gráfico: no indica frecuencia.$it$,
   $it$datos/lee-el-grafico-por-la-posicion$it$, $it$datos/lee-mal-la-escala-del-eje$it$, null, $it$datos/lee-el-grafico-por-la-posicion$it$),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.65), 50,
   $it$La **frecuencia relativa** de un dato es:$it$,
   $it$la cantidad de veces que aparece$it$,
   $it$la suma de todas las frecuencias$it$,
   $it$su frecuencia dividida por el total$it$,
   $it$el dato que más se repite$it$,
   $it$C$it$,
   $it$Esa es la frecuencia **absoluta**. La relativa la compara con el total.$it$,
   $it$Esa suma es el total de datos.$it$,
   $it$Correcto. Se divide la frecuencia del dato por el total, y por eso siempre queda entre $0$ y $1$.$it$,
   $it$Ese es la **moda**, que es otra cosa.$it$,
   $it$datos/frecuencia-relativa-como-absoluta$it$, null, null, $it$estadistica/confunde-las-tres-medidas$it$),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.56), 60,
   $it$De $20$ estudiantes, $5$ llegaron atrasados. ¿Cuál es la frecuencia relativa de los atrasados?$it$,
   $it$$0{,}25$$it$,
   $it$$5$$it$,
   $it$$4$$it$,
   $it$$20$$it$,
   $it$A$it$,
   $it$Correcto. $5 \div 20 = 0{,}25$, o sea una cuarta parte del curso.$it$,
   $it$Esa es la frecuencia absoluta. La relativa se obtiene dividiéndola por el total.$it$,
   $it$Se dividió al revés ($20 \div 5$). Una frecuencia relativa nunca puede ser mayor que $1$.$it$,
   $it$Ese es el total de estudiantes.$it$,
   null, $it$datos/frecuencia-relativa-como-absoluta$it$, $it$datos/frecuencia-relativa-invertida$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.48), 70,
   $it$En un curso de $25$ estudiantes, $10$ practican fútbol. ¿Qué porcentaje del curso es?$it$,
   $it$$10\%$$it$,
   $it$$25\%$$it$,
   $it$$2{,}5\%$$it$,
   $it$$40\%$$it$,
   $it$D$it$,
   $it$Ese es el conteo leído como si fuera un porcentaje. Diez de $25$ no es el $10\%$.$it$,
   $it$Ese es el total del curso, no la parte que juega fútbol.$it$,
   $it$Se dividió al revés ($25 \div 10$). El porcentaje compara la parte con el total, en ese orden.$it$,
   $it$Correcto. $10 \div 25 = 0{,}4$, y $0{,}4$ es el $40\%$.$it$,
   $it$datos/frecuencia-relativa-como-absoluta$it$, null, $it$datos/frecuencia-relativa-invertida$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.39), 80,
   $it$La **frecuencia acumulada** de un valor es:$it$,
   $it$su frecuencia multiplicada por el total$it$,
   $it$su frecuencia más las de los valores anteriores$it$,
   $it$el total de datos menos su frecuencia$it$,
   $it$la frecuencia del valor que más se repite en la tabla$it$,
   $it$B$it$,
   $it$Multiplicar por el total no acumula nada: da un número sin significado en la tabla.$it$,
   $it$Correcto. Acumular es ir sumando: responde «cuántos hay hasta acá».$it$,
   $it$Esos son los datos que **no** toman ese valor, que es otra cuenta.$it$,
   $it$Esa es la frecuencia de la moda.$it$,
   null, null, null, $it$estadistica/confunde-moda-con-frecuencia$it$),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.3), 90,
   $it$Con la tabla de hermanos ($0$: $4$; $1$: $9$; $2$: $5$; $3$: $2$), ¿cuántos estudiantes tienen **como máximo** $1$ hermano?$it$,
   $it$$13$$it$,
   $it$$9$$it$,
   $it$$4$$it$,
   $it$$5$$it$,
   $it$A$it$,
   $it$Correcto. $4 + 9 = 13$: es la frecuencia acumulada hasta el $1$.$it$,
   $it$Esos son solo los que tienen exactamente $1$ hermano. «Como máximo $1$» incluye también a los que tienen $0$.$it$,
   $it$Esos son solo los que no tienen hermanos.$it$,
   $it$Esa es la frecuencia del $2$, que ya queda fuera de «como máximo $1$».$it$,
   null, $it$datos/acumulada-como-simple$it$, $it$datos/acumulada-como-simple$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.21), 100,
   $it$En un gráfico circular, un sector ocupa el $25\%$ de un total de $80$ personas. ¿A cuántas personas corresponde?$it$,
   $it$$25$$it$,
   $it$$80$$it$,
   $it$$20$$it$,
   $it$$60$$it$,
   $it$C$it$,
   $it$Ese es el porcentaje escrito como si fuera la cantidad. El $25\%$ solo son $25$ personas cuando el total es $100$.$it$,
   $it$Ese es el total, o sea el círculo completo.$it$,
   $it$Correcto. El $25\%$ de $80$ es $80 \div 4 = 20$ personas.$it$,
   $it$Esas son las personas que quedan **fuera** del sector: el $75\%$ restante.$it$,
   $it$datos/confunde-el-porcentaje-con-la-cantidad$it$, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.13), 110,
   $it$En un gráfico circular, ¿qué porcentaje del total representa un sector de $90^\circ$?$it$,
   $it$$90\%$$it$,
   $it$$25\%$$it$,
   $it$$50\%$$it$,
   $it$$9\%$$it$,
   $it$B$it$,
   $it$Se leyó el ángulo como si fuera el porcentaje. La vuelta completa son $360^\circ$, no $100$.$it$,
   $it$Correcto. $90^\circ$ de $360^\circ$ es la cuarta parte: el $25\%$.$it$,
   $it$Ese sería un sector de $180^\circ$, o sea medio círculo.$it$,
   $it$Se corrió la coma. Para pasar de ángulo a porcentaje hay que dividir por $360$, no por $10$.$it$,
   $it$datos/confunde-el-angulo-con-el-porcentaje$it$, null, null, $it$datos/confunde-el-angulo-con-el-porcentaje$it$),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-2.04), 120,
   $it$Para saber qué opinan los $1.200$ estudiantes de un colegio se encuesta a $100$. Esos $100$ son:$it$,
   $it$la población$it$,
   $it$el censo$it$,
   $it$la variable$it$,
   $it$la muestra$it$,
   $it$D$it$,
   $it$La población son los $1.200$: el grupo completo sobre el que se quiere concluir.$it$,
   $it$Un censo es preguntarle a los $1.200$, o sea a la población entera.$it$,
   $it$La variable es lo que se mide —la opinión—, no quiénes responden.$it$,
   $it$Correcto. La muestra es la parte de la población que efectivamente se observa.$it$,
   $it$estadistica/confunde-poblacion-con-muestra$it$, $it$estadistica/confunde-poblacion-con-muestra$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-1.95), 130,
   $it$El color de ojos de un grupo de personas es una variable:$it$,
   $it$cuantitativa discreta$it$,
   $it$cuantitativa continua$it$,
   $it$acumulada$it$,
   $it$cualitativa$it$,
   $it$D$it$,
   $it$Cuantitativa es la que se mide con números. El color no lo es, aunque se le pueda asignar un código.$it$,
   $it$Continua es la que admite cualquier valor intermedio, como la estatura.$it$,
   $it$«Acumulada» no es un tipo de variable, sino un tipo de frecuencia.$it$,
   $it$Correcto. Es una cualidad, no una cantidad: sus valores son categorías.$it$,
   $it$estadistica/confunde-cualitativa-con-cuantitativa$it$, $it$estadistica/confunde-cualitativa-con-cuantitativa$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-1.86), 140,
   $it$La cantidad de hermanos de una persona es una variable cuantitativa:$it$,
   $it$continua$it$,
   $it$discreta$it$,
   $it$cualitativa$it$,
   $it$sin frecuencia$it$,
   $it$B$it$,
   $it$Continua es la que admite valores intermedios, como la estatura o el tiempo. Nadie tiene $2{,}4$ hermanos.$it$,
   $it$Correcto. Es un conteo: solo toma valores enteros y separados.$it$,
   $it$Sí se mide con números, así que es cuantitativa.$it$,
   $it$Toda variable de un conjunto de datos tiene frecuencias; eso no la clasifica.$it$,
   $it$estadistica/confunde-discreta-con-continua$it$, null, $it$estadistica/confunde-cualitativa-con-cuantitativa$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-1.78), 150,
   $it$Una tabla reparte $30$ datos en cuatro categorías, con frecuencias $8$, $7$, $6$ y $x$. ¿Cuánto vale $x$?$it$,
   $it$$30$$it$,
   $it$$21$$it$,
   $it$$9$$it$,
   $it$$7$$it$,
   $it$C$it$,
   $it$Ese es el total de datos, no la frecuencia que falta.$it$,
   $it$Esa es la suma de las tres frecuencias conocidas, que todavía hay que restar del total.$it$,
   $it$Correcto. $8+7+6 = 21$, y $30 - 21 = 9$.$it$,
   $it$Se repitió una frecuencia ya usada. La que falta se despeja del total.$it$,
   null, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-1.69), 160,
   $it$En un histograma con intervalos $[0, 10)$, $[10, 20)$ y $[20, 30)$, ¿en cuál se cuenta un dato igual a $20$?$it$,
   $it$En $[20, 30)$$it$,
   $it$En $[10, 20)$$it$,
   $it$En los dos$it$,
   $it$En ninguno$it$,
   $it$A$it$,
   $it$Correcto. El corchete cerrado incluye el extremo inicial, así que el $20$ abre el intervalo $[20, 30)$.$it$,
   $it$El paréntesis del final deja el $20$ **fuera** de ese intervalo: $[10, 20)$ llega hasta valores menores que $20$.$it$,
   $it$Los intervalos de un histograma no se superponen: cada dato cae en uno solo, y por eso se escriben así.$it$,
   $it$Sí cae en uno: el $20$ está dentro del recorrido de la tabla.$it$,
   null, $it$datos/lee-mal-el-intervalo$it$, $it$datos/lee-mal-el-intervalo$it$, $it$datos/lee-mal-el-intervalo$it$),
  ($it$probabilidad$it$, $it$probabilidad/datos$it$,
   (-1.6), 170,
   $it$Un gráfico de barras dibuja su eje vertical partiendo en $90$ en vez de en $0$. ¿Qué efecto tiene?$it$,
   $it$Ninguno, porque los valores están escritos$it$,
   $it$Exagera visualmente las diferencias entre las barras$it$,
   $it$Hace que las frecuencias sean menores$it$,
   $it$Convierte las frecuencias en porcentajes$it$,
   $it$B$it$,
   $it$Los valores están, pero lo primero que se lee de un gráfico es la altura relativa, y esa queda distorsionada.$it$,
   $it$Correcto. Al cortar el eje, una diferencia pequeña se ve enorme: el gráfico dice más de lo que muestran los datos.$it$,
   $it$Las frecuencias son exactamente las mismas; lo que cambia es cómo se ven.$it$,
   $it$Para eso habría que dividir cada frecuencia por el total; mover el eje no lo hace.$it$,
   $it$datos/lee-mal-la-escala-del-eje$it$, null, $it$datos/lee-mal-la-escala-del-eje$it$, null),

  -- ===========================================================================
  -- probabilidad/tendencia-central
  -- ===========================================================================
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-2.4), 10,
   $it$La **media aritmética** (promedio) de un conjunto de datos es:$it$,
   $it$el dato que más se repite$it$,
   $it$la diferencia entre el mayor y el menor$it$,
   $it$el dato que queda al centro$it$,
   $it$la suma de los datos dividida por cuántos son$it$,
   $it$D$it$,
   $it$Ese es la **moda**.$it$,
   $it$Ese es el **rango**, que mide dispersión y no tendencia central.$it$,
   $it$Ese es la **mediana**, y solo después de ordenarlos.$it$,
   $it$Correcto. Se suman todos los datos y se divide por la cantidad de datos.$it$,
   $it$estadistica/confunde-las-tres-medidas$it$, null, $it$estadistica/confunde-las-tres-medidas$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-2.31), 20,
   $it$¿Cuál es el promedio de $4$, $6$ y $8$?$it$,
   $it$$6$$it$,
   $it$$4$$it$,
   $it$$18$$it$,
   $it$$8$$it$,
   $it$A$it$,
   $it$Correcto. $(4+6+8) \div 3 = 18 \div 3 = 6$.$it$,
   $it$Ese es el menor de los datos.$it$,
   $it$Esa es la suma de los tres datos. Falta dividir por $3$.$it$,
   $it$Ese es el mayor de los datos.$it$,
   null, null, $it$estadistica/media-sin-dividir-por-n$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-2.23), 30,
   $it$La **mediana** de un conjunto de datos es:$it$,
   $it$el promedio de todos los datos del conjunto$it$,
   $it$el dato que más se repite$it$,
   $it$el valor central de los datos ordenados$it$,
   $it$el mayor de los datos$it$,
   $it$C$it$,
   $it$Ese es la media. La mediana no se calcula sumando.$it$,
   $it$Ese es la moda.$it$,
   $it$Correcto. Se ordenan los datos de menor a mayor y se toma el del centro; con cantidad par, el promedio de los dos centrales.$it$,
   $it$Ese es el máximo, que sirve para el rango.$it$,
   $it$estadistica/confunde-las-tres-medidas$it$, $it$estadistica/confunde-las-tres-medidas$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-2.14), 40,
   $it$¿Cuál es la mediana de los datos $2$, $9$, $5$?$it$,
   $it$$9$$it$,
   $it$$2$$it$,
   $it$$5$$it$,
   $it$$16$$it$,
   $it$C$it$,
   $it$Ese es el dato que está al centro de la lista **tal como venía escrita**. Antes hay que ordenarla.$it$,
   $it$Ese es el menor de los tres.$it$,
   $it$Correcto. Ordenados quedan $2$, $5$, $9$: el del centro es el $5$.$it$,
   $it$Esa es la suma de los datos, que sirve para la media, no para la mediana.$it$,
   $it$estadistica/mediana-sin-ordenar$it$, null, null, $it$estadistica/confunde-las-tres-medidas$it$),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-2.05), 50,
   $it$La **moda** de un conjunto de datos es:$it$,
   $it$el dato que más veces se repite$it$,
   $it$el dato del centro$it$,
   $it$el promedio de los datos$it$,
   $it$la cantidad de datos distintos$it$,
   $it$A$it$,
   $it$Correcto. La moda es el valor más frecuente, y puede haber más de uno.$it$,
   $it$Ese es la mediana.$it$,
   $it$Ese es la media.$it$,
   $it$Esa es otra cuenta y no es una medida de tendencia central.$it$,
   null, $it$estadistica/confunde-las-tres-medidas$it$, $it$estadistica/confunde-las-tres-medidas$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.96), 60,
   $it$¿Cuál es la moda de los datos $3$, $3$, $8$, $10$, $11$?$it$,
   $it$$8$$it$,
   $it$$2$$it$,
   $it$$7$$it$,
   $it$$3$$it$,
   $it$D$it$,
   $it$Esa es la mediana: el dato del centro una vez ordenados.$it$,
   $it$Esa es la cantidad de veces que se repite la moda, no la moda.$it$,
   $it$Ese es el promedio de los cinco datos.$it$,
   $it$Correcto. El $3$ es el único dato que aparece dos veces.$it$,
   $it$estadistica/confunde-las-tres-medidas$it$, $it$estadistica/confunde-moda-con-frecuencia$it$, $it$estadistica/confunde-las-tres-medidas$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.88), 70,
   $it$¿Cuál es la mediana de $2$, $4$, $6$ y $10$?$it$,
   $it$$4$$it$,
   $it$$5$$it$,
   $it$$6$$it$,
   $it$$22$$it$,
   $it$B$it$,
   $it$Ese es uno de los dos datos centrales. Con cantidad par hay que promediarlos.$it$,
   $it$Correcto. Los dos centrales son $4$ y $6$: $(4+6) \div 2 = 5$.$it$,
   $it$Ese es el otro dato central, y por lo mismo tampoco es la mediana.$it$,
   $it$Esa es la suma de los cuatro datos.$it$,
   $it$estadistica/mediana-par-toma-uno-solo$it$, null, $it$estadistica/mediana-par-toma-uno-solo$it$, $it$estadistica/confunde-las-tres-medidas$it$),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.79), 80,
   $it$En un grupo, $3$ estudiantes sacaron un $5$ y $2$ estudiantes sacaron un $7$. ¿Cuál es el promedio del grupo?$it$,
   $it$$5{,}8$$it$,
   $it$$6$$it$,
   $it$$29$$it$,
   $it$$12$$it$,
   $it$A$it$,
   $it$Correcto. $(5 \cdot 3 + 7 \cdot 2) \div 5 = 29 \div 5 = 5{,}8$.$it$,
   $it$Se promediaron las dos notas sin considerar que no las sacó la misma cantidad de gente: el $5$ pesa más porque son tres.$it$,
   $it$Esa es la suma de todas las notas. Falta dividir por los $5$ estudiantes.$it$,
   $it$Esa es la suma de las dos notas distintas, sin frecuencias ni división.$it$,
   null, $it$estadistica/media-ignora-la-frecuencia$it$, $it$estadistica/media-sin-dividir-por-n$it$, $it$estadistica/media-ignora-la-frecuencia$it$),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.7), 90,
   $it$El promedio de las notas de $10$ estudiantes es $5{,}0$. ¿Cuánto suman todas las notas?$it$,
   $it$$15$$it$,
   $it$$5$$it$,
   $it$$50$$it$,
   $it$$0{,}5$$it$,
   $it$C$it$,
   $it$Se sumaron el promedio y la cantidad de estudiantes. Para recuperar la suma hay que multiplicarlos.$it$,
   $it$Ese es el promedio, no la suma.$it$,
   $it$Correcto. El promedio es la suma dividida por $10$, así que la suma es $5{,}0 \cdot 10 = 50$.$it$,
   $it$Se dividió el promedio por $10$. Para volver a la suma hay que multiplicar.$it$,
   null, null, null, $it$estadistica/media-sin-dividir-por-n$it$),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.61), 100,
   $it$Un estudiante tiene $6$, $5$ y $7$ en sus tres primeras pruebas. ¿Qué nota necesita en la cuarta para quedar con promedio $6$?$it$,
   $it$$7$$it$,
   $it$$6$$it$,
   $it$$24$$it$,
   $it$$4$$it$,
   $it$B$it$,
   $it$Con un $7$ el promedio quedaría en $6{,}25$: es más de lo necesario.$it$,
   $it$Correcto. Para promediar $6$ con cuatro notas necesita sumar $24$, y lleva $18$: le falta un $6$.$it$,
   $it$Esa es la suma que debe alcanzar entre las cuatro notas, no la nota que falta.$it$,
   $it$Con un $4$ la suma llega a $22$ y el promedio queda en $5{,}5$.$it$,
   null, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.53), 110,
   $it$En una lista de sueldos, el más alto se reemplaza por uno mucho mayor. ¿Qué medida cambia más?$it$,
   $it$Ninguna de las dos cambia$it$,
   $it$La mediana$it$,
   $it$Las dos cambian igual$it$,
   $it$La media$it$,
   $it$D$it$,
   $it$La media sí cambia, y bastante.$it$,
   $it$La mediana depende de la **posición** del dato central, no de cuánto vale el más alto: sigue siendo el mismo dato del centro.$it$,
   $it$No cambian igual: justamente por eso se informan las dos.$it$,
   $it$Correcto. La media suma todos los valores, así que un dato muy grande la arrastra hacia arriba.$it$,
   null, $it$estadistica/la-mediana-se-mueve-con-los-extremos$it$, $it$estadistica/la-mediana-se-mueve-con-los-extremos$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.44), 120,
   $it$En los datos $2$, $3$, $4$, $4$, $100$, ¿qué medida representa mejor al grupo?$it$,
   $it$La media, porque usa todos los datos del conjunto$it$,
   $it$Da lo mismo: las tres dan el mismo valor$it$,
   $it$El rango, porque muestra la diferencia$it$,
   $it$La mediana, porque el $100$ no la arrastra$it$,
   $it$D$it$,
   $it$Usa todos los datos, y ese es el problema: la media da $22{,}6$, un valor que no se parece a ninguno de los cinco.$it$,
   $it$No dan lo mismo: la media es $22{,}6$ y la mediana, $4$.$it$,
   $it$El rango mide dispersión, no representa al grupo con un valor típico.$it$,
   $it$Correcto. La mediana es $4$, que sí describe al grupo. Un dato extremo mueve la media, no la posición central.$it$,
   $it$estadistica/la-mediana-se-mueve-con-los-extremos$it$, null, $it$estadistica/confunde-las-tres-medidas$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.35), 130,
   $it$Un grupo de $10$ estudiantes promedió $4{,}0$ y otro de $30$ promedió $6{,}0$. ¿Cuál es el promedio de los $40$ juntos?$it$,
   $it$$5{,}0$$it$,
   $it$$5{,}5$$it$,
   $it$$10{,}0$$it$,
   $it$$4{,}5$$it$,
   $it$B$it$,
   $it$Se promediaron los dos promedios como si los grupos fueran del mismo tamaño. El segundo tiene el triple de estudiantes.$it$,
   $it$Correcto. $(10 \cdot 4 + 30 \cdot 6) \div 40 = 220 \div 40 = 5{,}5$.$it$,
   $it$Esa es la suma de los dos promedios, que no es un promedio de nada.$it$,
   $it$Ese valor está por debajo incluso del promedio simple: el grupo grande empuja hacia arriba, no hacia abajo.$it$,
   $it$estadistica/promedia-los-promedios$it$, null, $it$estadistica/media-sin-dividir-por-n$it$, $it$estadistica/promedia-los-promedios$it$),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.26), 140,
   $it$Si a todos los datos de un conjunto se les suma $2$, el promedio:$it$,
   $it$queda igual$it$,
   $it$se duplica$it$,
   $it$aumenta en $2$$it$,
   $it$no se puede saber$it$,
   $it$C$it$,
   $it$El promedio sí se mueve: todos los datos se corrieron hacia arriba.$it$,
   $it$Duplicar sería multiplicar por $2$, que es otra operación.$it$,
   $it$Correcto. Si cada dato sube $2$, la suma sube $2n$ y el promedio sube exactamente $2$.$it$,
   $it$Sí se puede saber, y sin conocer los datos: sumar una constante corre el promedio esa misma cantidad.$it$,
   null, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.18), 150,
   $it$En los datos $8$, $8$, $9$ y $12$, ¿cuál es la mediana?$it$,
   $it$$8{,}5$$it$,
   $it$$8$$it$,
   $it$$9$$it$,
   $it$$9{,}25$$it$,
   $it$A$it$,
   $it$Correcto. Los centrales son $8$ y $9$: $(8+9) \div 2 = 8{,}5$.$it$,
   $it$Ese es uno de los dos datos centrales; con cantidad par hay que promediar los dos.$it$,
   $it$Ese es el otro dato central, y tampoco es la mediana por sí solo.$it$,
   $it$Ese es el promedio de los cuatro datos, no la mediana.$it$,
   null, $it$estadistica/mediana-par-toma-uno-solo$it$, $it$estadistica/mediana-par-toma-uno-solo$it$, $it$estadistica/confunde-las-tres-medidas$it$),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.09), 160,
   $it$En un conjunto, dos datos distintos se repiten la misma cantidad máxima de veces. Entonces el conjunto:$it$,
   $it$no tiene moda$it$,
   $it$tiene dos modas$it$,
   $it$tiene como moda el promedio de los dos$it$,
   $it$tiene como moda el mayor de los dos$it$,
   $it$B$it$,
   $it$Sí tiene: hay dos valores que alcanzan la frecuencia máxima.$it$,
   $it$Correcto. Un conjunto puede ser bimodal, y las dos modas se informan.$it$,
   $it$Promediarlos daría un valor que quizá no aparece ni una vez en los datos.$it$,
   $it$Que un valor sea mayor no lo hace más frecuente: los dos se repiten lo mismo.$it$,
   null, null, $it$estadistica/confunde-las-tres-medidas$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/tendencia-central$it$,
   (-1.0), 170,
   $it$El promedio de $5$ datos es $12$. Se agrega un sexto dato igual a $18$. ¿Cuál es el nuevo promedio?$it$,
   $it$$15$$it$,
   $it$$12$$it$,
   $it$$30$$it$,
   $it$$13$$it$,
   $it$D$it$,
   $it$Se promedió el promedio viejo con el dato nuevo, como si los seis datos pesaran lo mismo que uno solo.$it$,
   $it$El promedio sí sube: el dato agregado está por sobre los anteriores.$it$,
   $it$Esa es la suma del promedio anterior y el dato nuevo, sin dividir.$it$,
   $it$Correcto. Los cinco datos suman $60$; con el sexto, $78$, y $78 \div 6 = 13$.$it$,
   $it$estadistica/promedia-los-promedios$it$, null, $it$estadistica/media-sin-dividir-por-n$it$, null),

  -- ===========================================================================
  -- probabilidad/posicion
  -- ===========================================================================
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-1.6), 10,
   $it$Los **cuartiles** dividen un conjunto de datos ordenados en:$it$,
   $it$cuatro grupos con la misma cantidad de datos$it$,
   $it$cuatro grupos del mismo ancho$it$,
   $it$cuatro grupos elegidos por el investigador$it$,
   $it$dos mitades iguales$it$,
   $it$A$it$,
   $it$Correcto. Cada cuarto contiene aproximadamente el $25\%$ de los datos, aunque los tramos midan distinto.$it$,
   $it$No: los tramos entre cuartiles pueden ser muy distintos de ancho. Lo que se reparte parejo es la **cantidad de datos**.$it$,
   $it$Los cuartiles salen de los datos ordenados, no de una decisión.$it$,
   $it$Eso lo hace la mediana, que es un solo corte.$it$,
   null, null, null, $it$posicion/mediana-no-es-q2$it$),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-1.51), 20,
   $it$El segundo cuartil, $Q_2$, coincide siempre con:$it$,
   $it$la media$it$,
   $it$la moda$it$,
   $it$la mediana$it$,
   $it$el máximo$it$,
   $it$C$it$,
   $it$La media puede estar en cualquier parte; $Q_2$ es un corte por posición.$it$,
   $it$La moda es el dato más frecuente y no tiene por qué estar al centro.$it$,
   $it$Correcto. $Q_2$ deja el $50\%$ de los datos bajo sí: es la mediana.$it$,
   $it$El máximo es el último dato, no el central.$it$,
   $it$estadistica/confunde-las-tres-medidas$it$, $it$estadistica/confunde-las-tres-medidas$it$, null, $it$posicion/mediana-no-es-q2$it$),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-1.43), 30,
   $it$Si en un conjunto de datos $Q_1 = 12$, eso significa que:$it$,
   $it$hay $12$ datos bajo el primer cuartil$it$,
   $it$el $12\%$ de los datos está bajo el promedio$it$,
   $it$el $25\%$ de los datos es menor o igual que $12$$it$,
   $it$el primer cuartil es la cuarta parte de $12$$it$,
   $it$C$it$,
   $it$El $12$ es el **valor** del cuartil, no una cantidad de datos.$it$,
   $it$El $12$ no es un porcentaje: es el valor donde cae el corte.$it$,
   $it$Correcto. El primer cuartil deja bajo sí una cuarta parte de los datos.$it$,
   $it$Un cuartil no se calcula dividiendo el valor por $4$: se busca la posición en la lista ordenada.$it$,
   $it$datos/confunde-frecuencia-con-dato$it$, null, null, $it$posicion/cuartil-como-cuarta-parte-del-valor$it$),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-1.34), 40,
   $it$En los datos ordenados $2$, $4$, $6$, $8$, $10$, $12$, $14$, $16$, ¿cuál es $Q_1$?$it$,
   $it$$5$$it$,
   $it$$4$$it$,
   $it$$9$$it$,
   $it$$8$$it$,
   $it$A$it$,
   $it$Correcto. La mitad inferior es $2$, $4$, $6$, $8$, y su mediana es $(4+6) \div 2 = 5$.$it$,
   $it$Ese es el segundo dato. El primer cuartil es la mediana de la mitad inferior, que tiene cuatro datos.$it$,
   $it$Esa es la mediana de los ocho datos, o sea $Q_2$.$it$,
   $it$Ese es el cuarto dato: contar hasta la cuarta posición no da el primer cuartil.$it$,
   null, null, $it$posicion/mediana-no-es-q2$it$, $it$posicion/cuartil-como-cuarta-parte-del-valor$it$),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-1.25), 50,
   $it$Con los mismos datos $2$, $4$, $6$, $8$, $10$, $12$, $14$, $16$, ¿cuál es $Q_3$?$it$,
   $it$$12$$it$,
   $it$$14$$it$,
   $it$$16$$it$,
   $it$$13$$it$,
   $it$D$it$,
   $it$Ese es el primer dato de la mitad superior, no su centro.$it$,
   $it$Ese es el penúltimo dato de la lista.$it$,
   $it$Ese es el máximo, que es donde termina el bigote del diagrama, no la caja.$it$,
   $it$Correcto. La mitad superior es $10$, $12$, $14$, $16$, y su mediana es $(12+14) \div 2 = 13$.$it$,
   null, null, $it$posicion/lee-mal-el-cajon$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-1.16), 60,
   $it$Si $Q_1 = 5$ y $Q_3 = 13$, ¿cuánto vale el **rango intercuartílico**?$it$,
   $it$$18$$it$,
   $it$$8$$it$,
   $it$$9$$it$,
   $it$$-8$$it$,
   $it$B$it$,
   $it$Se sumaron los dos cuartiles. El rango intercuartílico es una diferencia.$it$,
   $it$Correcto. $Q_3 - Q_1 = 13 - 5 = 8$: es el ancho de la caja, donde vive el $50\%$ central.$it$,
   $it$Ese es el promedio de los dos cuartiles, que no mide dispersión.$it$,
   $it$Se restó al revés. Como $Q_3 \geq Q_1$, el resultado nunca es negativo.$it$,
   $it$posicion/rango-intercuartil-mal-restado$it$, null, $it$posicion/rango-intercuartil-mal-restado$it$, $it$posicion/rango-intercuartil-mal-restado$it$),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-1.08), 70,
   $it$El **percentil 40** de un conjunto de datos es el valor que:$it$,
   $it$deja bajo sí el $40\%$ de los datos$it$,
   $it$corresponde al $40\%$ del valor del dato mayor$it$,
   $it$aparece $40$ veces$it$,
   $it$es el $40\%$ del promedio$it$,
   $it$A$it$,
   $it$Correcto. Los percentiles reparten los datos ordenados en cien partes.$it$,
   $it$El percentil no se calcula sacándole un porcentaje al máximo: es una posición en la lista.$it$,
   $it$Eso sería una frecuencia, no un percentil.$it$,
   $it$El promedio no interviene: los percentiles son medidas de posición.$it$,
   null, $it$posicion/cuartil-como-cuarta-parte-del-valor$it$, $it$datos/confunde-frecuencia-con-dato$it$, $it$posicion/cuartil-como-cuarta-parte-del-valor$it$),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.99), 80,
   $it$Un estudiante quedó en el **percentil 90** de una prueba. Eso significa que:$it$,
   $it$contestó bien el $90\%$ de las preguntas$it$,
   $it$obtuvo $90$ puntos$it$,
   $it$superó al $90\%$ de quienes rindieron$it$,
   $it$el $90\%$ de quienes rindieron le ganó$it$,
   $it$C$it$,
   $it$El percentil no habla de cuántas respuestas acertó, sino de cómo le fue **comparado con los demás**.$it$,
   $it$El percentil no es un puntaje: es una posición relativa dentro del grupo.$it$,
   $it$Correcto. El percentil 90 deja bajo sí al $90\%$ del grupo.$it$,
   $it$Está al revés: en el percentil 90 son pocos los que quedan por encima.$it$,
   $it$posicion/percentil-como-porcentaje-de-logro$it$, $it$posicion/percentil-como-porcentaje-de-logro$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.9), 90,
   $it$En un diagrama de cajón, los dos extremos de la **caja** representan:$it$,
   $it$el mínimo y el máximo$it$,
   $it$$Q_1$ y $Q_3$$it$,
   $it$la media y la mediana$it$,
   $it$los percentiles $10$ y $90$$it$,
   $it$B$it$,
   $it$Esos son los extremos de los **bigotes**, no de la caja.$it$,
   $it$Correcto. La caja va del primer al tercer cuartil, así que encierra el $50\%$ central de los datos.$it$,
   $it$La media no aparece en el diagrama de cajón; la mediana es la línea de adentro.$it$,
   $it$El diagrama estándar se construye con cuartiles, no con esos percentiles.$it$,
   $it$posicion/lee-mal-el-cajon$it$, null, $it$posicion/lee-mal-el-cajon$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.81), 100,
   $it$En un diagrama de cajón, la línea dibujada **dentro** de la caja es:$it$,
   $it$el rango$it$,
   $it$la media$it$,
   $it$la moda$it$,
   $it$la mediana$it$,
   $it$D$it$,
   $it$El rango es una distancia, no una línea del gráfico.$it$,
   $it$La media no se dibuja en el diagrama de cajón estándar.$it$,
   $it$La moda tampoco: el diagrama se arma con posiciones, no con frecuencias.$it$,
   $it$Correcto. Es $Q_2$, o sea la mediana, y por eso no siempre queda al centro de la caja.$it$,
   null, $it$estadistica/confunde-las-tres-medidas$it$, $it$estadistica/confunde-las-tres-medidas$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.73), 110,
   $it$En un diagrama de cajón, la mediana quedó dibujada mucho más cerca de $Q_1$ que de $Q_3$. Eso indica que:$it$,
   $it$hay un error en el gráfico, porque la mediana va al centro$it$,
   $it$la media es igual a la mediana$it$,
   $it$hay más datos en la mitad superior$it$,
   $it$el $25\%$ superior de los datos está más estirado$it$,
   $it$D$it$,
   $it$No es un error: la mediana parte la caja en dos mitades con **igual cantidad de datos**, no de igual ancho.$it$,
   $it$El diagrama no muestra la media, y nada obliga a que coincidan.$it$,
   $it$Cada cuarto tiene la misma cantidad de datos por construcción; lo que cambia es el ancho.$it$,
   $it$Correcto. Entre la mediana y $Q_3$ hay la misma cantidad de datos que entre $Q_1$ y la mediana, pero repartidos en un tramo más largo.$it$,
   $it$posicion/lee-mal-el-cajon$it$, null, $it$posicion/lee-mal-el-cajon$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.64), 120,
   $it$En un curso de $40$ estudiantes, ¿cuántos quedan bajo el primer cuartil de las notas?$it$,
   $it$$25$$it$,
   $it$$10$$it$,
   $it$$4$$it$,
   $it$$1$$it$,
   $it$B$it$,
   $it$Ese es el porcentaje ($25\%$) escrito como si fuera la cantidad de estudiantes.$it$,
   $it$Correcto. El $25\%$ de $40$ es $10$ estudiantes.$it$,
   $it$Se dividió por $10$ o se contó un cuarto de cada diez: el cuarto de $40$ es $10$.$it$,
   $it$Los cuartiles son tres cortes, pero el primero deja bajo sí una cuarta parte del curso, no a una persona.$it$,
   $it$datos/confunde-el-porcentaje-con-la-cantidad$it$, null, $it$posicion/cuartil-como-cuarta-parte-del-valor$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.55), 130,
   $it$Dos cursos tienen la misma mediana, pero el cajón de uno es mucho más ancho que el del otro. ¿Qué se puede afirmar?$it$,
   $it$Que el de caja ancha tiene mejores notas$it$,
   $it$Que el de caja ancha tiene más estudiantes$it$,
   $it$Que en el de caja ancha las notas están más repartidas$it$,
   $it$Que hay un error, porque con igual mediana las cajas deben ser iguales$it$,
   $it$C$it$,
   $it$El nivel lo marca la mediana, y es la misma en los dos. El ancho habla de otra cosa.$it$,
   $it$El ancho de la caja no depende de cuántos estudiantes hay: los cuartiles reparten porcentajes.$it$,
   $it$Correcto. La caja es el rango intercuartílico: más ancha significa un $50\%$ central más disperso.$it$,
   $it$No hay error: dos grupos con la misma mediana pueden tener dispersiones muy distintas.$it$,
   $it$dispersion/confunde-nivel-con-dispersion$it$, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.46), 140,
   $it$Si todos los datos de un conjunto son iguales, ¿cuánto vale su rango intercuartílico?$it$,
   $it$$0$$it$,
   $it$El valor del dato$it$,
   $it$$1$$it$,
   $it$No se puede calcular$it$,
   $it$A$it$,
   $it$Correcto. $Q_1$ y $Q_3$ valen lo mismo que todos los datos, así que su diferencia es $0$.$it$,
   $it$Se entregó el dato en vez de la distancia entre cuartiles.$it$,
   $it$El rango intercuartílico es una diferencia entre dos valores iguales, no una constante fija.$it$,
   $it$Sí se puede: los cuartiles existen igual, solo que coinciden.$it$,
   null, $it$datos/confunde-frecuencia-con-dato$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.38), 150,
   $it$El percentil $50$ coincide con:$it$,
   $it$la media$it$,
   $it$la mediana y $Q_2$$it$,
   $it$$Q_1$$it$,
   $it$el rango intercuartílico$it$,
   $it$B$it$,
   $it$La media es un promedio, no un corte de posición, y puede caer en cualquier parte.$it$,
   $it$Correcto. Los tres nombres describen el mismo corte: el que deja la mitad de los datos bajo sí.$it$,
   $it$$Q_1$ deja bajo sí el $25\%$, no el $50\%$.$it$,
   $it$Ese es una distancia entre dos cortes, no un corte.$it$,
   $it$estadistica/confunde-las-tres-medidas$it$, null, $it$posicion/mediana-no-es-q2$it$, $it$posicion/rango-intercuartil-mal-restado$it$),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.29), 160,
   $it$En una lista ordenada de $100$ notas, ¿qué lugar ocupa aproximadamente el percentil $25$?$it$,
   $it$El lugar $4$$it$,
   $it$El lugar $75$$it$,
   $it$El lugar $50$$it$,
   $it$El lugar $25$$it$,
   $it$D$it$,
   $it$Se dividió por $4$ el número de percentil en vez de ubicar la posición dentro de los $100$ datos.$it$,
   $it$Ese es el percentil $75$, o sea $Q_3$.$it$,
   $it$Ese es el percentil $50$, o sea la mediana.$it$,
   $it$Correcto. Con $100$ datos, el percentil $25$ cae cerca del vigésimo quinto.$it$,
   $it$posicion/cuartil-como-cuarta-parte-del-valor$it$, null, $it$posicion/mediana-no-es-q2$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/posicion$it$,
   (-0.2), 170,
   $it$Las notas de un curso tienen mínimo $2{,}0$, $Q_1 = 4{,}0$, mediana $5{,}0$, $Q_3 = 6{,}0$ y máximo $7{,}0$. ¿Qué porcentaje del curso tiene nota entre $4{,}0$ y $6{,}0$?$it$,
   $it$Un $50\%$$it$,
   $it$Un $100\%$$it$,
   $it$Un $25\%$$it$,
   $it$No se puede saber sin las notas$it$,
   $it$A$it$,
   $it$Correcto. De $Q_1$ a $Q_3$ está siempre el $50\%$ central de los datos.$it$,
   $it$Entre el mínimo y el máximo está el $100\%$; entre $Q_1$ y $Q_3$, la mitad.$it$,
   $it$Ese es el porcentaje que hay entre dos cuartiles **consecutivos**, y acá hay dos tramos.$it$,
   $it$Sí se puede: para eso sirven los cuartiles, aunque no se conozca cada nota.$it$,
   null, $it$posicion/lee-mal-el-cajon$it$, null, null),

  -- ===========================================================================
  -- probabilidad/dispersion
  -- ===========================================================================
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (-0.8), 10,
   $it$El **rango** de un conjunto de datos es:$it$,
   $it$la suma del mayor y el menor$it$,
   $it$el promedio del mayor y el menor$it$,
   $it$la diferencia entre el mayor y el menor$it$,
   $it$la cantidad de datos distintos$it$,
   $it$C$it$,
   $it$Sumar los extremos no mide cuánto se separan: dos grupos muy distintos pueden dar la misma suma.$it$,
   $it$Ese promedio es un valor central, no una medida de cuánto se dispersan los datos.$it$,
   $it$Correcto. El rango es máximo menos mínimo, y por eso se mide en las mismas unidades que los datos.$it$,
   $it$Eso es un conteo de categorías.$it$,
   $it$dispersion/rango-mal-calculado$it$, $it$dispersion/rango-mal-calculado$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (-0.7), 20,
   $it$¿Cuál es el rango de los datos $4$, $9$, $2$ y $15$?$it$,
   $it$$30$$it$,
   $it$$17$$it$,
   $it$$13$$it$,
   $it$$8{,}5$$it$,
   $it$C$it$,
   $it$Esa es la suma de los cuatro datos.$it$,
   $it$Se sumaron los extremos en vez de restarlos.$it$,
   $it$Correcto. El mayor es $15$ y el menor es $2$: $15 - 2 = 13$.$it$,
   $it$Ese es el promedio de los dos extremos.$it$,
   $it$dispersion/rango-mal-calculado$it$, $it$dispersion/rango-mal-calculado$it$, null, $it$dispersion/rango-mal-calculado$it$),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (-0.6), 30,
   $it$¿Qué mide la **desviación estándar**?$it$,
   $it$cuánto se alejan los datos del promedio$it$,
   $it$cuál es el dato más frecuente$it$,
   $it$cuál es el valor central de todos los datos$it$,
   $it$cuántos datos hay$it$,
   $it$A$it$,
   $it$Correcto. Es una medida de dispersión: dice qué tan repartidos están los datos alrededor de su media.$it$,
   $it$Esa es la moda.$it$,
   $it$Eso lo miden la media o la mediana.$it$,
   $it$Ese es el tamaño del conjunto.$it$,
   null, $it$estadistica/confunde-las-tres-medidas$it$, $it$dispersion/confunde-nivel-con-dispersion$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (-0.5), 40,
   $it$Si todos los datos de un conjunto son iguales, su desviación estándar es:$it$,
   $it$igual al valor de los datos$it$,
   $it$$1$$it$,
   $it$imposible de calcular$it$,
   $it$$0$$it$,
   $it$D$it$,
   $it$La desviación no se parece al valor de los datos: mide distancias, y acá no hay ninguna.$it$,
   $it$Se tomó $1$ como si fuera la desviación mínima. El mínimo es $0$, y se alcanza justo cuando no hay ninguna diferencia entre los datos.$it$,
   $it$Sí se puede calcular, y da cero.$it$,
   $it$Correcto. Ningún dato se aleja del promedio, así que todas las distancias son cero.$it$,
   $it$dispersion/confunde-nivel-con-dispersion$it$, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (-0.4), 50,
   $it$¿Puede la desviación estándar de un conjunto de datos ser $-2$?$it$,
   $it$Sí, si los datos son negativos$it$,
   $it$No: se calcula con una raíz de cuadrados$it$,
   $it$Sí, si el promedio es mayor que los datos$it$,
   $it$Solo si hay más datos bajo el promedio que sobre él$it$,
   $it$B$it$,
   $it$Los datos pueden ser negativos, pero la distancia al promedio no: se eleva al cuadrado antes de sumar.$it$,
   $it$Correcto. Es una raíz cuadrada de una suma de cuadrados: vale $0$ o más.$it$,
   $it$Las diferencias negativas y positivas se cuadran justamente para que no se cancelen ni den negativo.$it$,
   $it$La cantidad de datos a cada lado del promedio no cambia el signo.$it$,
   $it$dispersion/desviacion-negativa$it$, null, $it$dispersion/desviacion-negativa$it$, $it$dispersion/desviacion-negativa$it$),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (-0.3), 60,
   $it$La **varianza** de un conjunto de datos es:$it$,
   $it$el cuadrado de la desviación estándar$it$,
   $it$la raíz cuadrada de la desviación estándar$it$,
   $it$lo mismo que el rango$it$,
   $it$la diferencia entre la media y la mediana$it$,
   $it$A$it$,
   $it$Correcto. Se promedian los cuadrados de las distancias a la media; sacarle la raíz devuelve la desviación estándar.$it$,
   $it$Está al revés: la desviación estándar es la raíz de la varianza.$it$,
   $it$El rango solo usa dos datos; la varianza usa todos.$it$,
   $it$Esa diferencia habla de la forma de la distribución, no de su dispersión.$it$,
   null, $it$dispersion/desviacion-sin-raiz$it$, $it$dispersion/rango-mal-calculado$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (-0.2), 70,
   $it$Si la varianza de un conjunto es $9$, ¿cuánto vale su desviación estándar?$it$,
   $it$$81$$it$,
   $it$$4{,}5$$it$,
   $it$$3$$it$,
   $it$$9$$it$,
   $it$C$it$,
   $it$Se elevó al cuadrado otra vez. La varianza ya es el cuadrado.$it$,
   $it$Se dividió por $2$ en vez de sacar la raíz cuadrada.$it$,
   $it$Correcto. $\sqrt{9} = 3$.$it$,
   $it$Esa es la varianza misma: falta el paso de la raíz.$it$,
   $it$dispersion/desviacion-sin-raiz$it$, null, null, $it$dispersion/desviacion-sin-raiz$it$),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (-0.1), 80,
   $it$Si la desviación estándar de un conjunto es $5$, ¿cuánto vale su varianza?$it$,
   $it$$5$$it$,
   $it$$25$$it$,
   $it$$2{,}5$$it$,
   $it$$\sqrt{5}$$it$,
   $it$B$it$,
   $it$Esa es la desviación estándar; la varianza es su cuadrado.$it$,
   $it$Correcto. La varianza es el cuadrado de la desviación: $5^2 = 25$.$it$,
   $it$Se dividió por $2$ en vez de elevar al cuadrado.$it$,
   $it$Se sacó la raíz cuando había que hacer lo contrario.$it$,
   $it$dispersion/desviacion-sin-raiz$it$, null, null, $it$dispersion/desviacion-sin-raiz$it$),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (0.0), 90,
   $it$Los datos $2$, $2$, $6$, $6$ tienen promedio $4$. ¿Cuál es su desviación estándar?$it$,
   $it$$4$$it$,
   $it$$0$$it$,
   $it$$16$$it$,
   $it$$2$$it$,
   $it$D$it$,
   $it$Esa es la **varianza**: el promedio de los cuadrados de las distancias. Falta sacarle la raíz.$it$,
   $it$Sería $0$ solo si todos los datos fueran iguales, y acá hay dos valores distintos.$it$,
   $it$Esa es la suma de los cuadrados de las distancias, antes de dividir por $4$ y de sacar la raíz.$it$,
   $it$Correcto. Cada dato está a distancia $2$ del promedio, así que la desviación estándar es $2$.$it$,
   $it$dispersion/desviacion-sin-raiz$it$, null, $it$dispersion/desviacion-sin-raiz$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (0.1), 100,
   $it$Dos cursos tienen el mismo promedio, pero uno tiene desviación estándar $0{,}4$ y el otro $1{,}8$. ¿Qué se puede afirmar?$it$,
   $it$Que el de $1{,}8$ tiene mejores notas$it$,
   $it$Que hay un error, porque con igual promedio la desviación debe ser igual$it$,
   $it$Que el de $1{,}8$ tiene más estudiantes$it$,
   $it$Que el de $1{,}8$ tiene notas más disparejas$it$,
   $it$D$it$,
   $it$El nivel lo marca el promedio, y es el mismo en los dos cursos.$it$,
   $it$No hay error: es justamente para eso que se informa la desviación junto al promedio.$it$,
   $it$La desviación no depende de cuántos datos hay, sino de cuánto se separan.$it$,
   $it$Correcto. Más desviación estándar significa notas más repartidas alrededor del mismo promedio.$it$,
   $it$dispersion/confunde-nivel-con-dispersion$it$, $it$dispersion/confunde-nivel-con-dispersion$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (0.2), 110,
   $it$Si a todos los datos de un conjunto se les suma $3$, la desviación estándar:$it$,
   $it$aumenta en $3$$it$,
   $it$queda igual$it$,
   $it$se triplica$it$,
   $it$se reduce a la tercera parte$it$,
   $it$B$it$,
   $it$Eso le pasa al **promedio**. La desviación mide distancias entre los datos, y esas no cambian.$it$,
   $it$Correcto. Sumar una constante corre todos los datos lo mismo: la nube se traslada, no se estira.$it$,
   $it$Triplicar sería multiplicar los datos, que sí cambia las distancias.$it$,
   $it$Sumar no achica nada.$it$,
   $it$dispersion/dispersion-cambia-al-sumar-constante$it$, null, $it$dispersion/dispersion-cambia-al-sumar-constante$it$, $it$dispersion/dispersion-cambia-al-sumar-constante$it$),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (0.3), 120,
   $it$Si todos los datos de un conjunto se multiplican por $2$, la desviación estándar:$it$,
   $it$queda igual$it$,
   $it$aumenta en $2$$it$,
   $it$se duplica$it$,
   $it$se cuadruplica$it$,
   $it$C$it$,
   $it$Multiplicar sí cambia las distancias entre los datos: la nube se estira.$it$,
   $it$Sumar $2$ no haría nada; multiplicar por $2$ no suma $2$.$it$,
   $it$Correcto. Todas las distancias al promedio se duplican, así que la desviación también.$it$,
   $it$Se cuadruplica la **varianza**, porque ahí las distancias van al cuadrado.$it$,
   $it$dispersion/dispersion-cambia-al-sumar-constante$it$, null, null, $it$dispersion/desviacion-sin-raiz$it$),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (0.4), 130,
   $it$¿Cuál de estos dos conjuntos tiene mayor dispersión: $A = \{5, 5, 5, 5\}$ o $B = \{1, 4, 6, 9\}$?$it$,
   $it$$B$, porque sus datos se separan entre sí$it$,
   $it$$A$, porque sus datos son mayores$it$,
   $it$Los dos igual, porque tienen la misma cantidad de datos$it$,
   $it$$A$, porque todos sus datos son iguales$it$,
   $it$A$it$,
   $it$Correcto. En $A$ la dispersión es $0$; en $B$ los datos van de $1$ a $9$.$it$,
   $it$El tamaño de los datos no es dispersión: en $A$ todos valen lo mismo y no hay ninguna separación.$it$,
   $it$La cantidad de datos no dice nada sobre cuánto se separan.$it$,
   $it$Que todos sean iguales es exactamente lo contrario de tener dispersión.$it$,
   null, $it$dispersion/confunde-nivel-con-dispersion$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (0.5), 140,
   $it$El **rango** es especialmente sensible a:$it$,
   $it$la cantidad de datos$it$,
   $it$un solo dato extremo$it$,
   $it$el orden en que se anotan los datos$it$,
   $it$la unidad de medida elegida$it$,
   $it$B$it$,
   $it$Se puede calcular igual con $5$ o con $500$ datos.$it$,
   $it$Correcto. Como solo usa el máximo y el mínimo, un único dato lejano lo dispara.$it$,
   $it$El rango no cambia si se reordenan los datos.$it$,
   $it$Cambiar de unidad cambia el número, pero no lo vuelve más ni menos sensible.$it$,
   null, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (0.6), 150,
   $it$Un conjunto de datos tiene rango $0$. ¿Qué se puede afirmar?$it$,
   $it$Que no hay datos$it$,
   $it$Que hay la misma cantidad de datos altos y bajos$it$,
   $it$Que el promedio es $0$$it$,
   $it$Que todos los datos son iguales$it$,
   $it$D$it$,
   $it$Si no hubiera datos no habría rango que calcular.$it$,
   $it$El rango no cuenta datos: mide la distancia entre los extremos.$it$,
   $it$El promedio es el valor repetido, que puede ser cualquiera.$it$,
   $it$Correcto. El máximo y el mínimo coinciden, así que no queda ningún valor distinto en medio.$it$,
   null, null, $it$dispersion/confunde-nivel-con-dispersion$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (0.7), 160,
   $it$Dos grupos tienen desviación estándar $1{,}2$ y $3{,}5$. ¿Cuál es más **homogéneo**?$it$,
   $it$El de $1{,}2$$it$,
   $it$El de $3{,}5$$it$,
   $it$Los dos igual$it$,
   $it$Falta saber el promedio$it$,
   $it$A$it$,
   $it$Correcto. Homogéneo es parecerse entre sí, y eso es tener poca dispersión.$it$,
   $it$Más desviación es justamente lo contrario: los datos están más repartidos.$it$,
   $it$Las desviaciones son distintas, así que la dispersión también.$it$,
   $it$Para comparar dispersión basta la desviación; el promedio dice dónde está el grupo, no qué tan parejo es.$it$,
   null, $it$dispersion/confunde-nivel-con-dispersion$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/dispersion$it$,
   (0.8), 170,
   $it$Una prueba tiene promedio $500$ puntos y desviación estándar $100$. Un estudiante obtuvo $600$. ¿Qué se puede decir de su puntaje?$it$,
   $it$Que obtuvo un $20\%$ más de respuestas correctas$it$,
   $it$Que superó al $100\%$ de quienes rindieron$it$,
   $it$Que está una desviación estándar sobre el promedio$it$,
   $it$Que está en el máximo posible$it$,
   $it$C$it$,
   $it$El puntaje no es un porcentaje de logro, y $600$ no es un $20\%$ más de respuestas correctas.$it$,
   $it$La desviación no dice a cuánta gente superó; para eso sirven los percentiles.$it$,
   $it$Correcto. $600 = 500 + 100$: está exactamente a una desviación estándar del promedio.$it$,
   $it$Nada indica que $600$ sea el máximo: puede haber puntajes más altos.$it$,
   $it$posicion/percentil-como-porcentaje-de-logro$it$, $it$posicion/percentil-como-porcentaje-de-logro$it$, null, null),

  -- ===========================================================================
  -- probabilidad/azar
  -- ===========================================================================
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (0.0), 10,
   $it$Según la regla de Laplace, la probabilidad de un evento se calcula como:$it$,
   $it$casos favorables dividido por casos desfavorables$it$,
   $it$casos totales dividido por casos favorables$it$,
   $it$casos favorables dividido por casos totales$it$,
   $it$casos favorables multiplicado por casos totales$it$,
   $it$C$it$,
   $it$El denominador es el **total**, no lo que queda fuera.$it$,
   $it$Al revés daría un número mayor que $1$, que no puede ser una probabilidad.$it$,
   $it$Correcto. Se divide lo que sirve por todo lo que puede pasar, y por eso el resultado queda entre $0$ y $1$.$it$,
   $it$Multiplicar no compara la parte con el todo.$it$,
   $it$azar/favorables-sobre-desfavorables$it$, $it$azar/probabilidad-fuera-de-cero-uno$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (0.12), 20,
   $it$Al lanzar un dado corriente de $6$ caras, ¿cuál es la probabilidad de obtener un $4$?$it$,
   $it$$\dfrac{1}{6}$$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$$\dfrac{4}{6}$$it$,
   $it$$4$$it$,
   $it$A$it$,
   $it$Correcto. Hay una cara favorable de seis posibles.$it$,
   $it$El $4$ terminó en el denominador. El total de casos es $6$, que son las caras del dado.$it$,
   $it$El $4$ es el resultado buscado, no la cantidad de casos favorables: hay una sola cara con un $4$.$it$,
   $it$Una probabilidad nunca puede ser $4$: como máximo vale $1$.$it$,
   null, $it$azar/cuenta-mal-el-espacio-muestral$it$, $it$azar/cuenta-mal-el-espacio-muestral$it$, $it$azar/probabilidad-fuera-de-cero-uno$it$),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (0.24), 30,
   $it$¿Cuál es la probabilidad de obtener un número **par** al lanzar un dado de $6$ caras?$it$,
   $it$$\dfrac{1}{6}$$it$,
   $it$$\dfrac{2}{6}$$it$,
   $it$$\dfrac{1}{3}$$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$D$it$,
   $it$Se contó «par» como un solo caso favorable, pero hay tres caras pares: $2$, $4$ y $6$.$it$,
   $it$Son tres las caras pares —$2$, $4$ y $6$—, así que faltó contar una.$it$,
   $it$Eso equivale a $2$ casos favorables de $6$: faltó contar una de las tres caras pares.$it$,
   $it$Correcto. Son $3$ casos favorables de $6$: $\dfrac{3}{6} = \dfrac{1}{2}$.$it$,
   $it$azar/cuenta-mal-el-espacio-muestral$it$, $it$azar/cuenta-mal-el-espacio-muestral$it$, $it$azar/cuenta-mal-el-espacio-muestral$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (0.36), 40,
   $it$Una bolsa tiene $3$ bolitas rojas y $5$ azules. ¿Cuál es la probabilidad de sacar una roja?$it$,
   $it$$\dfrac{3}{5}$$it$,
   $it$$\dfrac{3}{8}$$it$,
   $it$$\dfrac{1}{3}$$it$,
   $it$$\dfrac{5}{8}$$it$,
   $it$B$it$,
   $it$En el denominador quedaron las azules, o sea los casos **desfavorables**. Van todas las bolitas.$it$,
   $it$Correcto. Hay $3$ rojas entre $3+5 = 8$ bolitas.$it$,
   $it$Se contó una de cada tres, como si hubiera tres colores igual de probables.$it$,
   $it$Esa es la probabilidad de sacar una **azul**.$it$,
   $it$azar/favorables-sobre-desfavorables$it$, null, $it$azar/cuenta-mal-el-espacio-muestral$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (0.48), 50,
   $it$¿Cuánto vale la probabilidad de un evento **seguro**?$it$,
   $it$$1$$it$,
   $it$$100$$it$,
   $it$$0$$it$,
   $it$$0{,}5$$it$,
   $it$A$it$,
   $it$Correcto. Si el evento ocurre siempre, los casos favorables son todos los posibles.$it$,
   $it$El $100$ es el porcentaje. En la escala de probabilidades, el máximo es $1$.$it$,
   $it$Ese es el valor de un evento **imposible**.$it$,
   $it$Ese es el valor de un evento que ocurre la mitad de las veces.$it$,
   null, $it$azar/probabilidad-fuera-de-cero-uno$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (0.6), 60,
   $it$¿Puede la probabilidad de un evento valer $1{,}5$?$it$,
   $it$Sí, si hay muchos casos favorables en juego$it$,
   $it$Sí, si el evento es muy probable$it$,
   $it$No: toda probabilidad está entre $0$ y $1$$it$,
   $it$Solo si se expresa en porcentaje$it$,
   $it$C$it$,
   $it$Por muchos que sean, los casos favorables nunca superan al total: la fracción no pasa de $1$.$it$,
   $it$«Muy probable» se acerca a $1$, nunca lo supera.$it$,
   $it$Correcto. Los casos favorables son parte de los totales, así que el cociente vive en $[0, 1]$.$it$,
   $it$En porcentaje el techo es $100\%$, que es el mismo $1$ escrito de otra forma.$it$,
   $it$azar/probabilidad-fuera-de-cero-uno$it$, $it$azar/probabilidad-fuera-de-cero-uno$it$, null, $it$azar/probabilidad-fuera-de-cero-uno$it$),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (0.72), 70,
   $it$Se lanza una moneda dos veces. ¿Cuántos resultados distintos puede haber?$it$,
   $it$$2$$it$,
   $it$$4$$it$,
   $it$$3$$it$,
   $it$$8$$it$,
   $it$B$it$,
   $it$Esos son los resultados de **un** lanzamiento. Con dos lanzamientos hay más combinaciones.$it$,
   $it$Correcto. Dos opciones en el primer lanzamiento por dos en el segundo: $2 \cdot 2 = 4$.$it$,
   $it$Se contaron «dos caras», «dos sellos» y «una de cada», pero la mixta ocurre de dos maneras: cara-sello y sello-cara.$it$,
   $it$Ese sería el total con **tres** lanzamientos: $2^3$.$it$,
   $it$azar/cuenta-mal-el-espacio-muestral$it$, null, $it$azar/resultados-compuestos-como-equiprobables$it$, $it$azar/cuenta-mal-el-espacio-muestral$it$),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (0.84), 80,
   $it$Se lanza una moneda dos veces. ¿Cuál es la probabilidad de obtener **dos caras**?$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$$\dfrac{1}{3}$$it$,
   $it$$\dfrac{2}{4}$$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$D$it$,
   $it$Esa es la probabilidad de cara en **un** lanzamiento.$it$,
   $it$Se trataron como equiprobables «dos caras», «dos sellos» y «una de cada», pero la mixta pasa el doble de veces.$it$,
   $it$Eso es $\dfrac{1}{2}$ escrito de otra forma: hay un solo resultado favorable de cuatro, no dos.$it$,
   $it$Correcto. De los cuatro resultados posibles, solo cara-cara sirve.$it$,
   null, $it$azar/resultados-compuestos-como-equiprobables$it$, $it$azar/cuenta-mal-el-espacio-muestral$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (0.96), 90,
   $it$Se lanzan dos dados corrientes. ¿Cuántos resultados posibles hay?$it$,
   $it$$12$$it$,
   $it$$6$$it$,
   $it$$11$$it$,
   $it$$36$$it$,
   $it$D$it$,
   $it$Se sumaron las caras de los dos dados. Para contar pares de resultados hay que multiplicar.$it$,
   $it$Esas son las caras de un solo dado.$it$,
   $it$Esas son las **sumas** posibles ($2$ a $12$), que no son igual de probables entre sí.$it$,
   $it$Correcto. Seis resultados del primer dado por seis del segundo: $6 \cdot 6 = 36$.$it$,
   $it$azar/cuenta-mal-el-espacio-muestral$it$, $it$azar/cuenta-mal-el-espacio-muestral$it$, $it$azar/resultados-compuestos-como-equiprobables$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (1.08), 100,
   $it$Se lanzan dos dados. ¿Cuál es la probabilidad de que la **suma** sea $7$?$it$,
   $it$$\dfrac{1}{11}$$it$,
   $it$$\dfrac{1}{6}$$it$,
   $it$$\dfrac{7}{36}$$it$,
   $it$$\dfrac{1}{12}$$it$,
   $it$B$it$,
   $it$Se tomaron las $11$ sumas posibles como si fueran igual de probables, y no lo son: el $7$ sale de seis maneras y el $2$, de una sola.$it$,
   $it$Correcto. Hay $6$ pares que suman $7$ de $36$ posibles: $\dfrac{6}{36} = \dfrac{1}{6}$.$it$,
   $it$Se usó el $7$ como si fuera la cantidad de casos favorables. Los pares que suman $7$ son seis.$it$,
   $it$Ese sería el resultado con un solo caso favorable entre $12$, y ni el numerador ni el denominador corresponden.$it$,
   $it$azar/resultados-compuestos-como-equiprobables$it$, null, $it$azar/cuenta-mal-el-espacio-muestral$it$, $it$azar/cuenta-mal-el-espacio-muestral$it$),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (1.2), 110,
   $it$De una baraja inglesa de $52$ cartas se saca una al azar. ¿Cuál es la probabilidad de que sea de corazones?$it$,
   $it$$\dfrac{1}{52}$$it$,
   $it$$\dfrac{1}{13}$$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$$\dfrac{4}{52}$$it$,
   $it$C$it$,
   $it$Esa es la probabilidad de sacar **una carta determinada**, no una pinta completa.$it$,
   $it$Ese sería el caso de trece cartas iguales; las de corazones son $13$ de $52$, no $1$ de $13$.$it$,
   $it$Correcto. Hay $13$ corazones entre $52$ cartas: $\dfrac{13}{52} = \dfrac{1}{4}$.$it$,
   $it$Ese es el $4$ de las pintas puesto como casos favorables: las pintas son cuatro, pero las cartas favorables son trece.$it$,
   $it$azar/cuenta-mal-el-espacio-muestral$it$, $it$azar/favorables-sobre-desfavorables$it$, null, $it$azar/cuenta-mal-el-espacio-muestral$it$),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (1.32), 120,
   $it$Una bolsa tiene $4$ bolitas rojas y $6$ verdes. Se saca una y **no se devuelve**. ¿Cuántas bolitas quedan para la segunda extracción?$it$,
   $it$$9$$it$,
   $it$$10$$it$,
   $it$$4$$it$,
   $it$$6$$it$,
   $it$A$it$,
   $it$Correcto. Salió una bolita y no volvió: quedan $9$.$it$,
   $it$Ese era el total **antes** de la primera extracción. Sin reposición, el total baja.$it$,
   $it$Esas son las rojas del comienzo, no el total que queda.$it$,
   $it$Esas son las verdes del comienzo.$it$,
   null, $it$azar/olvida-que-no-hay-reposicion$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (1.44), 130,
   $it$En un curso hay $12$ mujeres y $18$ hombres. Se elige a una persona al azar. ¿Cuál es la probabilidad de que sea mujer?$it$,
   $it$$\dfrac{12}{18}$$it$,
   $it$$\dfrac{2}{5}$$it$,
   $it$$\dfrac{3}{5}$$it$,
   $it$$\dfrac{1}{12}$$it$,
   $it$B$it$,
   $it$En el denominador quedaron los hombres, que son los casos desfavorables. Va el curso completo: $30$.$it$,
   $it$Correcto. $\dfrac{12}{30} = \dfrac{2}{5}$.$it$,
   $it$Esa es la probabilidad de que sea **hombre**: $\dfrac{18}{30}$.$it$,
   $it$Ese sería el caso de elegir a una mujer determinada entre las doce.$it$,
   $it$azar/favorables-sobre-desfavorables$it$, null, null, $it$azar/cuenta-mal-el-espacio-muestral$it$),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (1.56), 140,
   $it$Con $3$ poleras y $4$ pantalones distintos, ¿cuántas tenidas diferentes se pueden armar?$it$,
   $it$$7$$it$,
   $it$$1$$it$,
   $it$$34$$it$,
   $it$$12$$it$,
   $it$D$it$,
   $it$Se sumaron las prendas. Sumar cuenta cuántas prendas hay, no cuántas combinaciones.$it$,
   $it$Hay muchas combinaciones posibles, no una sola.$it$,
   $it$Se escribieron los dos números seguidos. Contar combinaciones es multiplicarlos: $3 \cdot 4$.$it$,
   $it$Correcto. Por el principio multiplicativo, cada una de las $3$ poleras se puede usar con cualquiera de los $4$ pantalones: $3 \cdot 4 = 12$.$it$,
   $it$azar/cuenta-mal-el-espacio-muestral$it$, null, $it$azar/cuenta-mal-el-espacio-muestral$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (1.68), 150,
   $it$Una bolsa tiene $4$ bolitas rojas y $6$ verdes. Se sacan dos **sin reposición**. ¿Cuál es la probabilidad de que las dos sean rojas?$it$,
   $it$$\dfrac{2}{15}$$it$,
   $it$$\dfrac{4}{25}$$it$,
   $it$$\dfrac{2}{5}$$it$,
   $it$$\dfrac{8}{19}$$it$,
   $it$A$it$,
   $it$Correcto. $\dfrac{4}{10} \cdot \dfrac{3}{9} = \dfrac{12}{90} = \dfrac{2}{15}$: en la segunda extracción quedan $3$ rojas de $9$ bolitas.$it$,
   $it$Ese es el resultado **con** reposición: $\dfrac{4}{10} \cdot \dfrac{4}{10}$. Acá la primera bolita no vuelve.$it$,
   $it$Esa es la probabilidad de que la **primera** sea roja; falta la segunda extracción.$it$,
   $it$Los totales se sumaron entre sí. Dos extracciones seguidas se multiplican, no se suman.$it$,
   null, $it$azar/olvida-que-no-hay-reposicion$it$, null, $it$reglas/suma-donde-va-producto$it$),
  ($it$probabilidad$it$, $it$probabilidad/azar$it$,
   (1.8), 160,
   $it$Se lanza un dado dos veces. ¿Cuál es la probabilidad de obtener **al menos un** $6$?$it$,
   $it$$\dfrac{1}{3}$$it$,
   $it$$\dfrac{1}{36}$$it$,
   $it$$\dfrac{11}{36}$$it$,
   $it$$\dfrac{2}{6}$$it$,
   $it$C$it$,
   $it$Se sumaron $\dfrac{1}{6} + \dfrac{1}{6}$, y eso cuenta dos veces el caso en que salen dos seises.$it$,
   $it$Esa es la probabilidad de sacar **dos** seises, que es un solo resultado de los $36$.$it$,
   $it$Correcto. Es más corto por el complemento: no sacar ningún $6$ tiene probabilidad $\dfrac{5}{6} \cdot \dfrac{5}{6} = \dfrac{25}{36}$, y $1 - \dfrac{25}{36} = \dfrac{11}{36}$.$it$,
   $it$Es $\dfrac{1}{3}$ sin simplificar: sumar los dos lanzamientos cuenta dos veces el caso en que salen dos seises.$it$,
   $it$reglas/suma-donde-va-producto$it$, null, null, $it$reglas/suma-donde-va-producto$it$),

  -- ===========================================================================
  -- probabilidad/reglas
  -- ===========================================================================
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (1.2), 10,
   $it$Si $P(A) = 0{,}3$, ¿cuánto vale la probabilidad de que $A$ **no** ocurra?$it$,
   $it$$99{,}7$$it$,
   $it$$-0{,}3$$it$,
   $it$$0{,}7$$it$,
   $it$$0{,}3$$it$,
   $it$C$it$,
   $it$Se restó de $100$ pero dejando el $0{,}3$ en escala de probabilidad. O se trabaja en porcentajes ($100 - 30 = 70$) o en probabilidades ($1 - 0{,}3$).$it$,
   $it$Se le cambió el signo. Ninguna probabilidad es negativa.$it$,
   $it$Correcto. El complemento se calcula como $1 - P(A) = 1 - 0{,}3 = 0{,}7$.$it$,
   $it$Esa es la probabilidad de que **sí** ocurra.$it$,
   $it$reglas/complemento-mal-calculado$it$, $it$reglas/complemento-mal-calculado$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (1.32), 20,
   $it$Dos eventos son **excluyentes** cuando:$it$,
   $it$no pueden ocurrir los dos a la vez$it$,
   $it$uno no influye en la probabilidad del otro$it$,
   $it$tienen la misma probabilidad$it$,
   $it$juntos suman probabilidad $1$$it$,
   $it$A$it$,
   $it$Correcto. Su intersección es vacía: si ocurre uno, el otro queda descartado.$it$,
   $it$Esa es la definición de eventos **independientes**, que es otra cosa.$it$,
   $it$Dos eventos pueden ser igual de probables y ocurrir juntos sin problema.$it$,
   $it$Eso ocurre con un evento y su complemento, que es un caso particular.$it$,
   null, $it$reglas/confunde-excluyentes-con-independientes$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (1.44), 30,
   $it$Dos eventos son **independientes** cuando:$it$,
   $it$no pueden ocurrir juntos$it$,
   $it$siempre ocurren juntos$it$,
   $it$tienen la misma cantidad de casos favorables$it$,
   $it$que ocurra uno no cambia la probabilidad del otro$it$,
   $it$D$it$,
   $it$Eso es ser **excluyentes**. Dos eventos excluyentes se influyen al máximo: si pasa uno, el otro ya no puede pasar.$it$,
   $it$Eso sería depender por completo el uno del otro.$it$,
   $it$La cantidad de casos favorables no tiene relación con la independencia.$it$,
   $it$Correcto. Saber que ocurrió $B$ no aporta información sobre $A$, y por eso $P(A \cap B) = P(A) \cdot P(B)$.$it$,
   $it$reglas/confunde-excluyentes-con-independientes$it$, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (1.56), 40,
   $it$Si $A$ y $B$ son **excluyentes**, entonces $P(A \cup B)$ es igual a:$it$,
   $it$$P(A) \cdot P(B)$$it$,
   $it$$P(A) + P(B)$$it$,
   $it$$P(A) + P(B) - P(A) \cdot P(B)$$it$,
   $it$$P(A) - P(B)$$it$,
   $it$B$it$,
   $it$Multiplicar corresponde a que ocurran **los dos**, y dos eventos excluyentes nunca ocurren juntos.$it$,
   $it$Correcto. Como no se superponen, no hay nada que descontar: las probabilidades se suman directo.$it$,
   $it$Ese descuento corresponde a eventos independientes que sí pueden ocurrir juntos. Acá la intersección es $0$.$it$,
   $it$Restar dejaría fuera parte de los casos de $B$, y la unión los incluye a todos.$it$,
   $it$reglas/confunde-excluyentes-con-independientes$it$, null, $it$reglas/confunde-excluyentes-con-independientes$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (1.68), 50,
   $it$Para dos eventos cualesquiera, $P(A \cup B)$ es igual a:$it$,
   $it$$P(A) + P(B) - P(A \cap B)$$it$,
   $it$$P(A) \cdot P(B)$$it$,
   $it$$P(A) + P(B)$$it$,
   $it$$1 - P(A) - P(B)$$it$,
   $it$A$it$,
   $it$Correcto. Se suman las dos probabilidades y se descuenta una vez la parte que comparten.$it$,
   $it$Ese es el cálculo de la intersección para eventos independientes, no el de la unión.$it$,
   $it$Esa fórmula sirve solo si los eventos son excluyentes: si no, los casos comunes quedan contados dos veces.$it$,
   $it$Esa expresión puede dar negativa, así que no puede ser una probabilidad.$it$,
   null, $it$reglas/suma-donde-va-producto$it$, $it$reglas/suma-sin-restar-la-interseccion$it$, $it$reglas/complemento-mal-calculado$it$),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (1.8), 60,
   $it$En un curso, la probabilidad de que un estudiante practique fútbol es $0{,}5$; básquetbol, $0{,}4$; y los dos deportes, $0{,}2$. ¿Cuál es la probabilidad de que practique **al menos uno** de los dos?$it$,
   $it$$0{,}9$$it$,
   $it$$0{,}2$$it$,
   $it$$0{,}7$$it$,
   $it$$0{,}1$$it$,
   $it$C$it$,
   $it$Se sumaron las dos probabilidades sin descontar a quienes practican los dos: esos quedaron contados dos veces.$it$,
   $it$Esa es la probabilidad de practicar **ambos**, que es solo una parte de la respuesta.$it$,
   $it$Correcto. $0{,}5 + 0{,}4 - 0{,}2 = 0{,}7$.$it$,
   $it$Se restaron las dos probabilidades ($0{,}5 - 0{,}4$). La unión suma y descuenta la intersección; no resta.$it$,
   $it$reglas/suma-sin-restar-la-interseccion$it$, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (1.92), 70,
   $it$Si $A$ y $B$ son **independientes**, entonces $P(A \cap B)$ es igual a:$it$,
   $it$$P(A) + P(B)$$it$,
   $it$$P(A) \cdot P(B)$$it$,
   $it$$0$$it$,
   $it$$P(A) - P(B)$$it$,
   $it$B$it$,
   $it$Sumar corresponde a la unión, o sea a que ocurra **alguno** de los dos.$it$,
   $it$Correcto. Que ocurran los dos, sin que uno influya en el otro, es el producto de sus probabilidades.$it$,
   $it$La intersección vale $0$ cuando los eventos son **excluyentes**, que es lo contrario de independientes.$it$,
   $it$La resta se parece a «$A$ pero no $B$», que se calcula con $P(A) - P(A \cap B)$, y no es la intersección.$it$,
   $it$reglas/suma-donde-va-producto$it$, null, $it$reglas/confunde-excluyentes-con-independientes$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (2.04), 80,
   $it$Se lanza una moneda y un dado. ¿Cuál es la probabilidad de obtener cara **y** un $5$?$it$,
   $it$$\dfrac{2}{3}$$it$,
   $it$$\dfrac{1}{8}$$it$,
   $it$$\dfrac{1}{6}$$it$,
   $it$$\dfrac{1}{12}$$it$,
   $it$D$it$,
   $it$Se sumaron $\dfrac{1}{2}$ y $\dfrac{1}{6}$. La palabra «y» pide que ocurran los dos, y eso se multiplica.$it$,
   $it$El denominador no corresponde: los resultados posibles son $2 \cdot 6 = 12$, no $8$.$it$,
   $it$Esa es solo la probabilidad del $5$ en el dado; falta la moneda.$it$,
   $it$Correcto. $\dfrac{1}{2} \cdot \dfrac{1}{6} = \dfrac{1}{12}$, que es uno de los doce resultados posibles.$it$,
   $it$reglas/suma-donde-va-producto$it$, $it$azar/cuenta-mal-el-espacio-muestral$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (2.16), 90,
   $it$Una bolsa tiene $5$ bolitas rojas y $5$ azules. Se sacan dos **sin reposición**. ¿Cuál es la probabilidad de que las dos sean rojas?$it$,
   $it$$\dfrac{1}{4}$$it$,
   $it$$\dfrac{5}{9}$$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$$\dfrac{2}{9}$$it$,
   $it$D$it$,
   $it$Ese es el resultado **con** reposición: $\dfrac{5}{10} \cdot \dfrac{5}{10}$.$it$,
   $it$Esa es solo la segunda fracción del cálculo, sin multiplicarla por la primera.$it$,
   $it$Esa es la probabilidad de que la primera sea roja; falta la segunda extracción.$it$,
   $it$Correcto. $\dfrac{5}{10} \cdot \dfrac{4}{9} = \dfrac{20}{90} = \dfrac{2}{9}$: para la segunda quedan $4$ rojas de $9$ bolitas.$it$,
   $it$azar/olvida-que-no-hay-reposicion$it$, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (2.28), 100,
   $it$La probabilidad condicional $P(A \mid B)$ se lee como:$it$,
   $it$la probabilidad de que ocurra $B$ sabiendo que ocurrió $A$$it$,
   $it$la probabilidad de que ocurra $A$ sabiendo que ocurrió $B$$it$,
   $it$la probabilidad de que ocurran los dos$it$,
   $it$la probabilidad de que ocurra alguno de los dos$it$,
   $it$B$it$,
   $it$Está al revés, y no dan lo mismo: entre quienes tienen fiebre, la proporción de resfriados no es la misma que entre los resfriados, la de fiebre.$it$,
   $it$Correcto. La condición va después de la barra: $B$ ya ocurrió y reduce el espacio muestral.$it$,
   $it$Esa es la intersección, $P(A \cap B)$.$it$,
   $it$Esa es la unión, $P(A \cup B)$.$it$,
   $it$reglas/condicional-usa-el-total-equivocado$it$, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (2.4), 110,
   $it$De $40$ estudiantes, $24$ practican algún deporte y $9$ de esos $24$ son mujeres. Si se elige al azar a alguien **que practica deporte**, ¿cuál es la probabilidad de que sea mujer?$it$,
   $it$$\dfrac{9}{40}$$it$,
   $it$$\dfrac{24}{40}$$it$,
   $it$$\dfrac{3}{8}$$it$,
   $it$$\dfrac{9}{16}$$it$,
   $it$C$it$,
   $it$Se dividió por el curso completo, pero la condición ya restringe el grupo a los $24$ deportistas.$it$,
   $it$Esa es la probabilidad de practicar deporte, que es otra pregunta.$it$,
   $it$Correcto. $\dfrac{9}{24} = \dfrac{3}{8}$: dentro del grupo condicionado el total es $24$.$it$,
   $it$En el denominador quedaron los $16$ que no practican deporte, que son justamente los que la condición excluye.$it$,
   $it$reglas/condicional-usa-el-total-equivocado$it$, $it$reglas/condicional-usa-el-total-equivocado$it$, null, $it$azar/favorables-sobre-desfavorables$it$),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (2.52), 120,
   $it$Se lanza una moneda cuatro veces y salen cuatro caras seguidas. ¿Cuál es la probabilidad de que en el quinto lanzamiento salga cara?$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$Menor que $\dfrac{1}{2}$, porque ya salieron muchas caras$it$,
   $it$$\dfrac{1}{32}$$it$,
   $it$Mayor que $\dfrac{1}{2}$, porque la moneda viene cargada a cara$it$,
   $it$A$it$,
   $it$Correcto. Cada lanzamiento es independiente, así que la probabilidad sigue siendo $\dfrac{1}{2}$.$it$,
   $it$La moneda no recuerda los lanzamientos anteriores: no hay ninguna fuerza que «equilibre» los resultados.$it$,
   $it$Esa es la probabilidad de sacar **cinco** caras seguidas **antes** de empezar a lanzar. Acá cuatro ya ocurrieron.$it$,
   $it$Los resultados pasados no son evidencia de que la moneda esté cargada, y el enunciado no lo dice.$it$,
   null, $it$reglas/falacia-del-jugador$it$, null, $it$reglas/falacia-del-jugador$it$),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (2.64), 130,
   $it$Si $A$ y $B$ son excluyentes con $P(A) = 0{,}4$ y $P(B) = 0{,}3$, ¿cuánto vale $P(A \cap B)$?$it$,
   $it$$0{,}12$$it$,
   $it$$0$$it$,
   $it$$0{,}7$$it$,
   $it$$0{,}1$$it$,
   $it$B$it$,
   $it$Se multiplicaron las probabilidades, que es la regla de eventos **independientes**. Excluyentes es lo contrario: no pueden ocurrir juntos.$it$,
   $it$Correcto. Si no pueden ocurrir a la vez, la intersección es imposible: vale $0$.$it$,
   $it$Esa es la probabilidad de la **unión**, no de la intersección.$it$,
   $it$Se restaron las dos probabilidades ($0{,}4 - 0{,}3$). La resta no entrega la parte común, y con eventos excluyentes esa parte no existe.$it$,
   $it$reglas/confunde-excluyentes-con-independientes$it$, null, null, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (2.76), 140,
   $it$Se lanza un dado tres veces. ¿Cuál es la probabilidad de obtener **al menos un** $6$?$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$$\dfrac{3}{6}$$it$,
   $it$$\dfrac{1}{216}$$it$,
   $it$$\dfrac{91}{216}$$it$,
   $it$D$it$,
   $it$Se sumaron los tres lanzamientos ($\dfrac{1}{6}$ tres veces), y eso cuenta varias veces los casos con dos o tres seises.$it$,
   $it$Es $\dfrac{1}{2}$ sin simplificar: sumar los tres lanzamientos no sirve para «al menos uno».$it$,
   $it$Esa es la probabilidad de sacar **tres** seises.$it$,
   $it$Correcto. Por el complemento: $1 - \left(\dfrac{5}{6}\right)^3 = 1 - \dfrac{125}{216} = \dfrac{91}{216}$.$it$,
   $it$reglas/suma-donde-va-producto$it$, $it$reglas/suma-donde-va-producto$it$, null, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (2.88), 150,
   $it$La urna $A$ tiene $2$ bolitas rojas y $3$ azules; la urna $B$ tiene $4$ rojas y $1$ azul. Se elige una urna al azar y se saca una bolita. ¿Cuál es la probabilidad de que sea roja?$it$,
   $it$$\dfrac{3}{5}$$it$,
   $it$$\dfrac{6}{25}$$it$,
   $it$$\dfrac{6}{5}$$it$,
   $it$$\dfrac{1}{2}$$it$,
   $it$A$it$,
   $it$Correcto. $\dfrac{1}{2} \cdot \dfrac{2}{5} + \dfrac{1}{2} \cdot \dfrac{4}{5} = \dfrac{1}{5} + \dfrac{2}{5} = \dfrac{3}{5}$.$it$,
   $it$Se multiplicaron las dos probabilidades, como si hubiera que sacar roja de las dos urnas.$it$,
   $it$Se sumaron las dos probabilidades sin considerar que cada urna se elige la mitad de las veces. Además, una probabilidad no puede pasar de $1$.$it$,
   $it$Ese es el peso de cada urna, no la probabilidad de sacar una bolita roja.$it$,
   null, $it$reglas/suma-donde-va-producto$it$, $it$azar/probabilidad-fuera-de-cero-uno$it$, null),
  ($it$probabilidad$it$, $it$probabilidad/reglas$it$,
   (3.0), 160,
   $it$Se lanzan dos dados. ¿Cuál es la probabilidad de que la suma sea $8$ **sabiendo** que el primer dado mostró un $5$?$it$,
   $it$$\dfrac{5}{36}$$it$,
   $it$$\dfrac{1}{11}$$it$,
   $it$$\dfrac{1}{6}$$it$,
   $it$$\dfrac{1}{36}$$it$,
   $it$C$it$,
   $it$Se siguió usando los $36$ resultados, pero la condición ya fijó el primer dado: quedan solo $6$ casos posibles.$it$,
   $it$Se tomaron las once sumas posibles como equiprobables, y además se ignoró la condición.$it$,
   $it$Correcto. Con el primer dado en $5$, la suma da $8$ solo si el segundo es $3$: un caso de seis.$it$,
   $it$Ese es uno de los $36$ pares, sin usar que el primer dado ya está determinado.$it$,
   $it$reglas/condicional-usa-el-total-equivocado$it$, $it$azar/resultados-compuestos-como-equiprobables$it$, null, $it$reglas/condicional-usa-el-total-equivocado$it$)

)
insert into public.questions
  (topic, module_id, difficulty, order_index,
   question, option_a, option_b, option_c, option_d, correct_option,
   error_a, error_b, error_c, error_d,
   misconception_a_id, misconception_b_id, misconception_c_id, misconception_d_id)
select i.topic, m.id, i.difficulty, i.order_index,
       i.question, i.option_a, i.option_b, i.option_c, i.option_d, i.correct_option,
       i.error_a, i.error_b, i.error_c, i.error_d,
       xa.id, xb.id, xc.id, xd.id
from items i
left join public.modules m        on m.slug  = i.module_slug
left join public.misconceptions xa on xa.slug = i.mis_a
left join public.misconceptions xb on xb.slug = i.mis_b
left join public.misconceptions xc on xc.slug = i.mis_c
left join public.misconceptions xd on xd.slug = i.mis_d
-- Idempotente por (topic, question). Reaplicar NO actualiza un ítem ya
-- cargado: para corregirlo, editarlo en Admin → Preguntas o borrarlo primero.
where not exists (
  select 1 from public.questions q
   where q.topic = i.topic and q.question = i.question
);

-- -----------------------------------------------------------------------------
-- Verificación (correr después de aplicar)
-- -----------------------------------------------------------------------------
--   select count(*) from public.questions where topic = 'probabilidad';
--   -- esperado: 100 (más lo que ya hubiera)
--
--   -- Ningún ítem sin módulo: delataría un module_slug mal escrito.
--   select id from public.questions where topic = 'probabilidad' and module_id is null;
--   -- 0 filas
--
--   -- Ningún distractor perdió su idea errónea en el join.
--   select id, question from public.questions q
--    where topic = 'probabilidad'
--      and misconception_a_id is null and misconception_b_id is null
--      and misconception_c_id is null and misconception_d_id is null;
--   -- revisar: un ítem sin ninguna catalogada puede ser legítimo, varios no
--
--   -- La clave repartida (R-35): ninguna letra debe pasar del 40 %.
--   select correct_option, count(*) from public.questions
--    where topic = 'probabilidad' group by 1 order by 1;
--
-- Reversión: delete from public.questions where topic = 'probabilidad';
--            delete from public.misconceptions where slug in ('datos/confunde-frecuencia-con-dato', 'datos/frecuencia-relativa-como-absoluta', 'datos/frecuencia-relativa-invertida', …);
