-- Banco de profundización en corriente alterna del track de electrotecnia
-- 42 ítems · topic `electrotecnia_ca` · 6 ideas erróneas nuevas
--
-- GENERADA por scripts/generar_migracion_items.py desde el JSON de la tanda.
-- No editar a mano: corregir el JSON, volver a verificar y regenerar. Un cambio
-- hecho acá se pierde en la siguiente regeneración y deja de estar verificado.
--
-- Verificada con scripts/verificar_items.py, que comprueba lo que este banco
-- aprendió a golpes: clave repartida entre las cuatro letras (R-35), una sola
-- alternativa correcta, las cuatro explicaciones escritas, la correcta sin idea
-- errónea, LaTeX con escape simple (047) y cobertura de dificultad sin huecos.
--
-- 42 ítems de profundización en corriente alterna, repartidos en los seis módulos
-- del bloque de CA del track, cubriendo [-1, 3] con al menos 6 ítems por tramo de
-- 1,0 logit.
--
-- REQUIERE 062 (los módulos) y 063 (el banco general, que declara las ideas
-- erróneas que esta tanda reutiliza). El `on conflict (slug) do nothing` del bloque
-- de misconceptions hace que reaplicar sea inocuo, pero si 063 no se aplicó primero
-- las entradas reutilizadas no existirían y los `misconception_*_id` quedarían en
-- null EN SILENCIO, que es exactamente el modo de fallo de T-119.
--
-- Es el banco de PROFUNDIZACIÓN, no el de entrada: `electrotecnia` es su
-- prerrequisito (ver 065). Cubre el temario de la prueba que motivó este track
-- —reactancia, impedancia, leyes de Kirchhoff en CA, componente real de la
-- corriente y carácter del circuito— con ítems de cálculo, no solo conceptuales.
--
-- Contenido REDACTADO DESDE CERO. Ningún ítem reproduce una pregunta de una prueba
-- existente: los temas son los del temario, los números y los distractores son
-- propios.
--
-- `difficulty` es una HIPÓTESIS EDITORIAL, no una medición (R-17, G-2).

-- -----------------------------------------------------------------------------
-- 1. Ideas erróneas nuevas
-- -----------------------------------------------------------------------------
-- Van ANTES de los ítems y en el mismo archivo: el `left join` de abajo
-- resuelve por slug, así que si no existen todavía los ítems entrarían con
-- `misconception_*_id` en null y en silencio.
--
-- `on conflict (slug) do nothing`: si una ya está catalogada, se respeta la
-- que hay. Reaplicar contenido no pisa una corrección hecha en el panel.

insert into public.misconceptions (slug, name, description, module_id)
select v.slug, v.name, v.description, m.id
  from (values
    ($it$et/ca/componente-real-como-modulo$it$, $it$Confunde la componente real de un fasor con su módulo$it$, $it$Entrega el módulo cuando se pide la parte real (o activa), o al revés. Usar cuando la operación fasorial está bien pero no proyectó sobre el eje que pide la pregunta. Aparece sobre todo al pedir «la componente real de la corriente total».$it$, $it$electrotecnia/ca_senales$it$),
    ($it$et/fasor/suma-sin-descomponer$it$, $it$Suma fasores sin descomponerlos en componentes$it$, $it$Suma módulos y ángulos por separado, como si fueran dos escalares independientes. Sumar fasores exige pasar a forma rectangular, sumar componente a componente y volver a polar. Usar cuando el ángulo del resultado es la suma o el promedio de los ángulos de los sumandos.$it$, $it$electrotecnia/ca_senales$it$),
    ($it$et/impedancia/paralelo-con-formula-de-serie$it$, $it$Aplica en paralelo la regla de la conexión en serie$it$, $it$Suma impedancias que están en paralelo, o suma admitancias de elementos que están en serie. Usar cuando la operación es correcta pero corresponde a la otra topología.$it$, $it$electrotecnia/impedancia$it$),
    ($it$et/impedancia/caracter-por-la-reactancia-mayor$it$, $it$Decide el carácter del circuito mirando la reactancia mayor sin considerar la topología$it$, $it$En serie manda la reactancia de mayor módulo; en paralelo manda la de menor módulo, porque es la que deja pasar más corriente. Usar cuando aplica el criterio de la serie a un circuito paralelo o viceversa.$it$, $it$electrotecnia/impedancia$it$),
    ($it$et/potencia/factor-de-potencia-sin-caracter$it$, $it$Da el factor de potencia sin decir si es en atraso o en adelanto$it$, $it$Trata $\cos\varphi$ como un número suelto. El mismo valor corresponde a dos situaciones opuestas —carga inductiva o capacitiva— que exigen correcciones contrarias. Usar cuando omite o invierte el carácter.$it$, $it$electrotecnia/potencia_ca$it$),
    ($it$et/trifasico/desequilibrado-con-formulas-de-equilibrado$it$, $it$Aplica a un sistema desequilibrado las fórmulas del equilibrado$it$, $it$Usa $\sqrt{3}$, la cancelación del neutro o $P = 3P_F$ en un sistema con cargas distintas por fase. Esas relaciones suponen tres fases idénticas. Usar cuando el error es aplicar el atajo fuera de su hipótesis.$it$, $it$electrotecnia/trifasico$it$)
  ) as v(slug, name, description, module_slug)
  left join public.modules m on m.slug = v.module_slug
on conflict (slug) do nothing;

-- -----------------------------------------------------------------------------
-- 2. Ítems
-- -----------------------------------------------------------------------------

with items (topic, module_slug, difficulty, order_index,
            question, option_a, option_b, option_c, option_d, correct_option,
            error_a, error_b, error_c, error_d,
            mis_a, mis_b, mis_c, mis_d) as (
  values

  -- ===========================================================================
  -- electrotecnia/ca_senales
  -- ===========================================================================
  ($it$electrotecnia_ca$it$::text, $it$electrotecnia/ca_senales$it$::text,
   (-0.8)::double precision, 110::int,
   $it$Una tensión vale $v(t) = 311\operatorname{sen}(314t)$ V. ¿Cuáles son su valor eficaz y su frecuencia?$it$::text,
   $it$$311$ V y $314$ Hz.$it$::text,
   $it$$440$ V y $50$ Hz.$it$::text,
   $it$$220$ V y $314$ Hz.$it$::text,
   $it$$220$ V y $50$ Hz.$it$::text,
   $it$D$it$::text,
   $it$Leíste los dos números tal como aparecen. El $311$ es la **amplitud**, y el eficaz es $311/\sqrt{2}$; el $314$ es $\omega$ en rad/s, y la frecuencia es $\omega/2\pi$.$it$::text,
   $it$Multiplicaste por $\sqrt{2}$ en vez de dividir. El valor eficaz siempre es **menor** que la amplitud, nunca mayor.$it$::text,
   $it$El eficaz está bien, pero $314$ es la frecuencia **angular** en rad/s. Para pasarla a hertz hay que dividir por $2\pi$, y da los $50$ Hz de la red.$it$::text,
   $it$Correcto. $V_{ef} = 311/\sqrt{2} \approx 220$ V y $f = 314/(2\pi) = 50$ Hz: es la red domiciliaria escrita en forma instantánea. Conviene reconocer el par $311$–$314$ de memoria.$it$::text,
   $it$et/ca/eficaz-como-amplitud$it$::text, $it$et/ca/eficaz-como-amplitud$it$::text, $it$et/ca/omega-sin-2pi$it$::text, null::text),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/ca_senales$it$,
   (-0.6), 120,
   $it$Una corriente senoidal de $60$ Hz se atrasa $30^\circ$ respecto de la tensión. ¿A cuánto tiempo equivale ese desfase?$it$,
   $it$$1{,}39$ ms$it$,
   $it$$30$ ms$it$,
   $it$$0{,}5$ ms$it$,
   $it$$8{,}3$ ms$it$,
   $it$A$it$,
   $it$Correcto. Un ciclo completo son $360^\circ$ y dura $T = 1/60 \approx 16{,}7$ ms. Entonces $30^\circ$ son $16{,}7 \times 30/360 \approx 1{,}39$ ms. El puente entre ángulo y tiempo es siempre la fracción de período.$it$,
   $it$Tomaste el número del ángulo y le pusiste unidades de tiempo. Grados y milisegundos no son intercambiables: hay que pasar por el período de la señal, que depende de la frecuencia.$it$,
   $it$Dividiste $30$ por $60$, mezclando el ángulo con la frecuencia. La cuenta correcta usa el período, no la frecuencia: $T\cdot(30/360)$.$it$,
   $it$Ese es medio período ($180^\circ$). El desfase pedido es de $30^\circ$, o sea la duodécima parte del ciclo, no la mitad.$it$,
   null, $it$et/fasor/desfase-como-retardo-en-segundos$it$, $it$et/ca/periodo-y-frecuencia-invertidos$it$, $it$et/fasor/desfase-como-retardo-en-segundos$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/ca_senales$it$,
   (-0.4), 130,
   $it$¿Cuál es la **componente real** del fasor $\vec{I} = 10\angle{-60^\circ}$ A?$it$,
   $it$$10$ A$it$,
   $it$$8{,}66$ A$it$,
   $it$$5$ A$it$,
   $it$$-8{,}66$ A$it$,
   $it$C$it$,
   $it$Ese es el **módulo**. La componente real es su proyección sobre el eje horizontal: $|I|\cos\theta$, y solo coincide con el módulo si el ángulo es cero.$it$,
   $it$Usaste el seno en vez del coseno: $10\operatorname{sen}60^\circ = 8{,}66$. Eso es la componente **imaginaria** en módulo. La proyección sobre el eje real siempre lleva coseno.$it$,
   $it$Correcto. $\operatorname{Re}(\vec{I}) = 10\cos(-60^\circ) = 10 \times 0{,}5 = 5$ A. En forma rectangular, $\vec{I} = 5 - j8{,}66$ A. Con la tensión como referencia, esta es la componente **activa** de la corriente.$it$,
   $it$Ese es el valor de la componente **imaginaria**, que sí es negativa por el ángulo de $-60^\circ$. La real, en cambio, es positiva: el coseno de $-60^\circ$ vale $+0{,}5$.$it$,
   $it$et/ca/componente-real-como-modulo$it$, $it$et/ca/componente-real-como-modulo$it$, null, $it$et/ca/componente-real-como-modulo$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/ca_senales$it$,
   (-0.2), 140,
   $it$Dos corrientes llegan a un nodo: $\vec{I_1} = 3\angle 0^\circ$ A e $\vec{I_2} = 4\angle 90^\circ$ A. ¿Cuánto vale la corriente total?$it$,
   $it$$7\angle 90^\circ$ A$it$,
   $it$$7\angle 45^\circ$ A$it$,
   $it$$12\angle 90^\circ$ A$it$,
   $it$$5\angle 53{,}1^\circ$ A$it$,
   $it$D$it$,
   $it$Sumaste los módulos y te quedaste con uno de los ángulos. Sumar fasores exige pasarlos a forma rectangular: $3 + j4$, y recién entonces volver a polar.$it$,
   $it$Sumaste los módulos y promediaste los ángulos. Ninguna de las dos operaciones es válida: el módulo del resultado no es la suma salvo que los fasores estén alineados.$it$,
   $it$Multiplicaste los módulos. En una suma fasorial no hay producto; el producto de módulos aparece al **multiplicar** complejos, y ahí además los ángulos se suman.$it$,
   $it$Correcto. $3 + j4$ tiene módulo $\sqrt{9+16} = 5$ y ángulo $\arctan(4/3) = 53{,}1^\circ$. Este es el mismo triángulo $3$-$4$-$5$ que aparece en las impedancias, ahora con corrientes.$it$,
   $it$et/fasor/suma-sin-descomponer$it$, $it$et/fasor/suma-sin-descomponer$it$, $it$et/fasor/suma-sin-descomponer$it$, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/ca_senales$it$,
   (0.1), 150,
   $it$¿Cuánto vale el valor medio de una tensión senoidal a lo largo de **un ciclo completo**?$it$,
   $it$Cero.$it$,
   $it$$0{,}637\,V_m$.$it$,
   $it$$0{,}707\,V_m$.$it$,
   $it$$V_m$.$it$,
   $it$A$it$,
   $it$Correcto. El semiciclo positivo y el negativo tienen la misma área con signos opuestos, así que se cancelan. Por eso un multímetro en modo continua marca $0$ sobre una senoidal pura, y por eso el valor eficaz —que promedia el **cuadrado**— es el que sirve.$it$,
   $it$Ese es el valor medio de **media onda** o de una onda rectificada de onda completa: $2V_m/\pi$. Sobre un ciclo entero, sin rectificar, la mitad negativa cancela a la positiva.$it$,
   $it$Ese es el valor **eficaz**, $V_m/\sqrt{2}$. Media y eficaz son promedios distintos: uno promedia la señal y el otro su cuadrado, y por eso el eficaz nunca da cero.$it$,
   $it$El máximo se alcanza en un solo instante de cada semiciclo. El promedio de una señal no puede ser igual a su valor máximo salvo que la señal sea constante.$it$,
   null, $it$et/ca/valor-medio-no-nulo$it$, $it$et/ca/valor-medio-no-nulo$it$, $it$et/ca/eficaz-como-amplitud$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/ca_senales$it$,
   (0.3), 160,
   $it$En notación fasorial, ¿por qué derivar respecto del tiempo equivale a multiplicar por $j\omega$?$it$,
   $it$Porque la derivada de una senoidal es otra senoidal de la misma frecuencia, adelantada $90^\circ$ y con la amplitud multiplicada por $\omega$.$it$,
   $it$Porque $j$ representa la unidad de tiempo en el plano complejo.$it$,
   $it$Porque al derivar se pierde la componente continua de la señal.$it$,
   $it$Porque $\omega$ es la pendiente media de la senoidal.$it$,
   $it$A$it$,
   $it$Correcto. $\frac{d}{dt}[A\operatorname{sen}(\omega t)] = A\omega\cos(\omega t) = A\omega\operatorname{sen}(\omega t + 90^\circ)$. Multiplicar por $j$ es exactamente rotar $90^\circ$, y multiplicar por $\omega$ es escalar la amplitud. De ahí salen $Z_L = j\omega L$ y $Z_C = 1/(j\omega C)$.$it$,
   $it$$j$ no representa tiempo: representa una rotación de $90^\circ$ en el plano complejo. Que aparezca al derivar es consecuencia de que la derivada de un seno es un coseno, no de una interpretación temporal.$it$,
   $it$Que la derivada elimine la componente continua es cierto, pero es un efecto lateral y no explica de dónde salen el $j$ ni el $\omega$. Además, en régimen senoidal puro esa componente ya es cero.$it$,
   $it$La pendiente media de una senoidal a lo largo de un ciclo es cero. Lo que $\omega$ escala es la pendiente **instantánea** máxima, que es proporcional a la frecuencia.$it$,
   null, null, null, $it$et/ca/omega-sin-2pi$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/ca_senales$it$,
   (0.6), 170,
   $it$Un osciloscopio muestra una senoidal de $8$ divisiones de pico a pico, con la escala vertical en $5$ V por división. ¿Cuál es el valor eficaz?$it$,
   $it$$40$ V$it$,
   $it$$28{,}3$ V$it$,
   $it$$14{,}1$ V$it$,
   $it$$20$ V$it$,
   $it$C$it$,
   $it$Ese es el valor de **pico a pico**: $8 \times 5 = 40$ V. Faltan dos pasos: dividir por dos para llegar a la amplitud y por $\sqrt{2}$ para llegar al eficaz.$it$,
   $it$Dividiste el pico a pico por $\sqrt{2}$, saltándote la división por dos. El eficaz se calcula desde la **amplitud**, que es la mitad del pico a pico.$it$,
   $it$Correcto. Pico a pico $= 40$ V, amplitud $V_m = 20$ V, y $V_{ef} = 20/\sqrt{2} \approx 14{,}1$ V. Es la cadena completa que hay que recorrer al leer un osciloscopio, que muestra la onda y no su valor eficaz.$it$,
   $it$Ese es $V_m$, la amplitud. Es el paso intermedio correcto, pero falta dividir por $\sqrt{2}$ para llegar al eficaz.$it$,
   $it$et/ca/eficaz-como-amplitud$it$, $it$et/ca/eficaz-como-amplitud$it$, null, $it$et/ca/eficaz-como-amplitud$it$),

  -- ===========================================================================
  -- electrotecnia/reactancia
  -- ===========================================================================
  ($it$electrotecnia_ca$it$, $it$electrotecnia/reactancia$it$,
   (-0.4), 110,
   $it$Un inductor de $200$ mH se conecta a una red de $50$ Hz. ¿Cuánto vale su reactancia?$it$,
   $it$$62{,}8\,\Omega$$it$,
   $it$$10\,\Omega$$it$,
   $it$$0{,}016\,\Omega$$it$,
   $it$$6{,}28\,\Omega$$it$,
   $it$A$it$,
   $it$Correcto. $X_L = 2\pi f L = 314 \times 0{,}2 = 62{,}8\,\Omega$. La secuencia es siempre la misma: $f \to \omega$ multiplicando por $2\pi$, la inductancia a henry, y recién entonces el producto.$it$,
   $it$Usaste $f$ en vez de $\omega$: $50 \times 0{,}2 = 10$. Falta el factor $2\pi$, y se nota porque el resultado correcto es $6{,}28$ veces mayor.$it$,
   $it$Invertiste el producto, aplicándole al inductor la fórmula del capacitor. Lo que calculaste es una susceptancia en siemens, no una reactancia.$it$,
   $it$Perdiste un factor de diez en la conversión de los milihenry: $200$ mH son $0{,}2$ H, no $0{,}02$ H.$it$,
   null, $it$et/ca/omega-sin-2pi$it$, $it$et/reactancia/xc-sin-invertir$it$, $it$et/unidades/prefijos-mal-convertidos$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/reactancia$it$,
   (-0.2), 120,
   $it$Un capacitor tiene una reactancia de $80\,\Omega$ a $50$ Hz. ¿Cuánto vale a $200$ Hz?$it$,
   $it$$320\,\Omega$$it$,
   $it$$40\,\Omega$$it$,
   $it$$80\,\Omega$$it$,
   $it$$20\,\Omega$$it$,
   $it$D$it$,
   $it$Multiplicaste por cuatro, que es lo que le pasaría a un **inductor**. La reactancia capacitiva tiene la frecuencia en el denominador: si la frecuencia se cuadruplica, $X_C$ se divide por cuatro.$it$,
   $it$Dividiste por dos, como si la dependencia fuera con $\sqrt{f}$ o con la mitad del cambio. La relación es inversamente proporcional a $f$: cuatro veces más frecuencia, cuatro veces menos reactancia.$it$,
   $it$La reactancia de un capacitor depende de la frecuencia, siempre. Lo único que no depende es la capacitancia, que es una propiedad del componente.$it$,
   $it$Correcto. $X_C = 1/(\omega C)$ es inversamente proporcional a la frecuencia: al pasar de $50$ a $200$ Hz la frecuencia se cuadruplica y la reactancia baja a $80/4 = 20\,\Omega$. Por eso un capacitor deja pasar bien las señales rápidas y bloquea la continua.$it$,
   $it$et/reactancia/xc-crece-con-la-frecuencia$it$, null, $it$et/reactancia/xc-crece-con-la-frecuencia$it$, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/reactancia$it$,
   (0.0), 130,
   $it$En una red de $60$ Hz se necesita una reactancia capacitiva de $50\,\Omega$. ¿Qué capacitancia hay que usar?$it$,
   $it$$18{,}9$ mF$it$,
   $it$$53\,\mu\text{F}$$it$,
   $it$$3{,}3\,\mu\text{F}$$it$,
   $it$$18{,}9\,\mu\text{F}$$it$,
   $it$B$it$,
   $it$El número corresponde a otro despeje y además el prefijo está tres órdenes de magnitud arriba. Un capacitor de $18{,}9$ mF es un banco industrial, no un componente de $50\,\Omega$ a red.$it$,
   $it$Correcto. De $X_C = 1/(\omega C)$ sale $C = 1/(\omega X_C) = 1/(377 \times 50) \approx 5{,}3\times10^{-5}$ F $= 53\,\mu\text{F}$. Conviene despejar en símbolos antes de reemplazar.$it$,
   $it$Usaste $f = 60$ en vez de $\omega = 377$ en algún punto del despeje, o dividiste de más. El factor $2\pi$ tiene que aparecer exactamente una vez.$it$,
   $it$Calculaste $1/(\omega \times ...)$ con los factores mezclados. El control es directo: con $53\,\mu\text{F}$, $X_C = 1/(377 \times 53\times10^{-6}) = 50\,\Omega$; con $18{,}9\,\mu\text{F}$ da unos $140\,\Omega$.$it$,
   $it$et/unidades/prefijos-mal-convertidos$it$, null, $it$et/ca/omega-sin-2pi$it$, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/reactancia$it$,
   (0.3), 140,
   $it$En un capacitor ideal alimentado con CA, ¿qué relación de fase hay entre la corriente y la tensión?$it$,
   $it$La corriente atrasa $90^\circ$ a la tensión.$it$,
   $it$Están en fase.$it$,
   $it$La corriente adelanta $90^\circ$ a la tensión.$it$,
   $it$El desfase es de $180^\circ$.$it$,
   $it$C$it$,
   $it$Ese es el comportamiento del **inductor**. En el capacitor pasa lo contrario, y es fácil de recordar por la fórmula: $i = C\,dv/dt$, así que la corriente es máxima cuando la tensión cambia más rápido, o sea cuando la tensión pasa por cero.$it$,
   $it$El desfase nulo es propio del resistor. En un elemento que almacena energía siempre hay un desfase de $90^\circ$, con un signo u otro.$it$,
   $it$Correcto. En el capacitor la corriente adelanta $90^\circ$ (la parte ICE de la mnemotecnia «ELI the ICE man»), y su impedancia es $Z_C = -jX_C = X_C\angle{-90^\circ}$. El ángulo negativo de la impedancia es la otra cara del ángulo positivo de la corriente.$it$,
   $it$Un desfase de $180^\circ$ significaría una corriente exactamente opuesta a la tensión, o sea potencia media negativa: el elemento estaría entregando energía todo el tiempo. Ningún componente pasivo hace eso.$it$,
   $it$et/reactancia/desfase-invertido$it$, null, null, $it$et/reactancia/desfase-invertido$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/reactancia$it$,
   (0.5), 150,
   $it$Sobre un inductor ideal de $X_L = 25\,\Omega$ hay $100$ V eficaces. ¿Qué corriente circula y qué potencia activa consume?$it$,
   $it$$4$ A y $400$ W.$it$,
   $it$$0$ A, porque el inductor bloquea la alterna.$it$,
   $it$$2500$ A y $0$ W.$it$,
   $it$$4$ A y $0$ W.$it$,
   $it$D$it$,
   $it$La corriente está bien, pero los $400$ W son la potencia **reactiva** en var. En un inductor ideal la tensión y la corriente están a $90^\circ$, y $\cos 90^\circ = 0$: la potencia activa es cero.$it$,
   $it$El inductor bloquea los **cambios** de corriente, no la corriente alterna: su reactancia es finita y por él circulan los $4$ A. Lo que bloquea la alterna casi por completo es una reactancia muy grande, no cualquier inductor.$it$,
   $it$Multiplicaste en vez de dividir. La reactancia cumple el mismo papel que la resistencia en la ley de Ohm: divide a la tensión para dar la corriente.$it$,
   $it$Correcto. $I = V/X_L = 100/25 = 4$ A, y $P = VI\cos 90^\circ = 0$. El inductor toma $400$ var: energía que va y vuelve cada ciclo sin consumirse. Que $P = 0$ no significa que no circule corriente.$it$,
   $it$et/reactancia/disipa-potencia$it$, null, $it$et/ohm/multiplica-en-vez-de-dividir$it$, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/reactancia$it$,
   (0.8), 160,
   $it$Un inductor y un capacitor tienen, a $60$ Hz, $X_L = 30\,\Omega$ y $X_C = 30\,\Omega$. Si la frecuencia **baja** a $30$ Hz, ¿qué pasa?$it$,
   $it$Las dos reactancias se mantienen iguales entre sí.$it$,
   $it$$X_L$ pasa a $60\,\Omega$ y $X_C$ a $15\,\Omega$: el circuito se vuelve inductivo.$it$,
   $it$$X_L$ pasa a $15\,\Omega$ y $X_C$ a $60\,\Omega$: el circuito se vuelve capacitivo.$it$,
   $it$Las dos se reducen a la mitad.$it$,
   $it$C$it$,
   $it$Solo coinciden en la frecuencia de resonancia, que acá es $60$ Hz. En cualquier otra frecuencia se separan, porque una crece y la otra decrece.$it$,
   $it$Invertiste las dos dependencias. $X_L = \omega L$ baja al bajar la frecuencia, y $X_C = 1/(\omega C)$ sube. Por debajo de la resonancia manda siempre el capacitor.$it$,
   $it$Correcto. Al bajar la frecuencia a la mitad, $X_L$ se divide por dos y $X_C$ se multiplica por dos. Con $X_C > X_L$ la reactancia neta es capacitiva. Esa es la regla general: por debajo de $f_0$, capacitivo; por encima, inductivo.$it$,
   $it$Solo la reactancia inductiva baja. La capacitiva hace lo contrario, y por eso las dos curvas se cruzan en un punto —la resonancia— en vez de bajar juntas.$it$,
   $it$et/reactancia/xc-crece-con-la-frecuencia$it$, $it$et/reactancia/xl-baja-con-la-frecuencia$it$, null, $it$et/reactancia/xc-crece-con-la-frecuencia$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/reactancia$it$,
   (1.0), 170,
   $it$Un inductor de $30\,\Omega$ de reactancia y un capacitor de $30\,\Omega$ de reactancia se conectan **en paralelo** a la misma fuente de CA. ¿Cuánta corriente entrega la fuente?$it$,
   $it$El doble de la de cada rama.$it$,
   $it$Cero, idealmente: las dos corrientes de rama se cancelan.$it$,
   $it$La misma que circula por una rama.$it$,
   $it$$\sqrt{2}$ veces la de una rama.$it$,
   $it$B$it$,
   $it$Sumarías los módulos, y eso valdría si las dos corrientes estuvieran en fase. Están a $180^\circ$ una de otra: una adelanta $90^\circ$ a la tensión y la otra la atrasa $90^\circ$.$it$,
   $it$Correcto. Con reactancias iguales, $I_L$ e $I_C$ tienen el mismo módulo y sentidos opuestos: se cancelan en el nodo. Es la resonancia **paralelo**, y por dentro sigue circulando corriente entre las dos ramas aunque la fuente no entregue casi nada.$it$,
   $it$Ese sería el resultado si una de las dos ramas no existiera. Con las dos presentes hay cancelación, no dominio de una sobre la otra.$it$,
   $it$El $\sqrt{2}$ aparecería si las dos corrientes estuvieran a $90^\circ$. Están a $180^\circ$, que es el caso de cancelación total.$it$,
   $it$et/impedancia/suma-aritmetica-de-modulos$it$, null, null, $it$et/impedancia/suma-aritmetica-de-modulos$it$),

  -- ===========================================================================
  -- electrotecnia/impedancia
  -- ===========================================================================
  ($it$electrotecnia_ca$it$, $it$electrotecnia/impedancia$it$,
   (0.0), 110,
   $it$Un circuito serie tiene $R = 60\,\Omega$ y $X_C = 80\,\Omega$. Escribe su impedancia en forma polar.$it$,
   $it$$100\angle{-53{,}1^\circ}\,\Omega$$it$,
   $it$$100\angle 53{,}1^\circ\,\Omega$$it$,
   $it$$140\angle{-53{,}1^\circ}\,\Omega$$it$,
   $it$$20\angle{-53{,}1^\circ}\,\Omega$$it$,
   $it$A$it$,
   $it$Correcto. $|Z| = \sqrt{60^{2}+80^{2}} = 100\,\Omega$ y $\theta = \arctan(-80/60) = -53{,}1^\circ$. El signo negativo es lo que dice que el circuito es capacitivo y que la corriente adelanta.$it$,
   $it$El módulo está bien, el signo del ángulo no. Una reactancia **capacitiva** entra como $-jX_C$: su ángulo es negativo. El positivo corresponde al caso inductivo.$it$,
   $it$Sumaste los dos valores. $R$ y $X$ son perpendiculares en el plano complejo: se combinan con Pitágoras, no sumando.$it$,
   $it$Restaste los dos valores. La resta aparece entre $X_L$ y $X_C$, que se oponen entre sí; entre la resistencia y una reactancia nunca hay resta.$it$,
   null, $it$et/impedancia/angulo-con-signo-cambiado$it$, $it$et/impedancia/suma-aritmetica-de-modulos$it$, $it$et/impedancia/suma-aritmetica-de-modulos$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/impedancia$it$,
   (0.2), 120,
   $it$Dos impedancias, $Z_1 = 4 + j3\,\Omega$ y $Z_2 = 6 - j8\,\Omega$, se conectan **en serie**. ¿Cuál es la impedancia total?$it$,
   $it$$10 + j11\,\Omega$$it$,
   $it$$15\angle{-8^\circ}\,\Omega$$it$,
   $it$$2 - j11\,\Omega$$it$,
   $it$$10 - j5\,\Omega$$it$,
   $it$D$it$,
   $it$Sumaste los módulos de las partes imaginarias sin respetar sus signos: $+3$ y $-8$ no dan $+11$. En forma rectangular hay que sumar cada componente **con su signo**.$it$,
   $it$Sumaste los módulos ($5 + 10 = 15$) y promediaste los ángulos. Los complejos se suman en forma **rectangular**; en polar solo se multiplican y dividen con comodidad.$it$,
   $it$Restaste las partes reales. La suma en serie es suma en las dos componentes; el signo de la parte imaginaria viene de cada impedancia, no de la operación.$it$,
   $it$Correcto. En serie las impedancias se suman como números complejos: parte real con parte real ($4+6 = 10$) e imaginaria con imaginaria ($+3-8 = -5$). El resultado es capacitivo, aunque uno de los sumandos fuera inductivo.$it$,
   $it$et/impedancia/reactancias-sin-restarse$it$, $it$et/impedancia/suma-aritmetica-de-modulos$it$, null, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/impedancia$it$,
   (0.5), 130,
   $it$Un resistor de $40\,\Omega$ y una reactancia inductiva de $30\,\Omega$ están **en paralelo**. ¿Cuánto vale el módulo de la impedancia equivalente?$it$,
   $it$$70\,\Omega$$it$,
   $it$$50\,\Omega$$it$,
   $it$$24\,\Omega$$it$,
   $it$$17{,}1\,\Omega$$it$,
   $it$C$it$,
   $it$Sumaste, que es la regla de la **serie** y además sin tener en cuenta que son perpendiculares. En paralelo el equivalente tiene que quedar por debajo del menor de los dos, o sea por debajo de $30\,\Omega$.$it$,
   $it$Ese es el módulo que darían $40$ y $30$ **en serie**: $\sqrt{1600+900} = 50$. Es el mismo triángulo, pero aplicado a la topología equivocada.$it$,
   $it$Correcto. Con dos elementos, $Z = \dfrac{Z_1 Z_2}{Z_1+Z_2} = \dfrac{40 \times j30}{40+j30}$. El módulo es $\dfrac{40 \times 30}{50} = 24\,\Omega$: se dividen los productos de módulos por el módulo de la suma.$it$,
   $it$Aplicaste la fórmula del paralelo de resistencias con los módulos sin cuidar la parte compleja del denominador: $1/(1/40+1/30) = 17{,}1$. Ese resultado vale solo si los dos elementos son del mismo tipo, y acá uno es resistivo y el otro reactivo.$it$,
   $it$et/impedancia/paralelo-con-formula-de-serie$it$, $it$et/impedancia/paralelo-con-formula-de-serie$it$, null, $it$et/impedancia/suma-aritmetica-de-modulos$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/impedancia$it$,
   (0.7), 140,
   $it$Un circuito **paralelo** tiene una rama inductiva de $X_L = 2\,\Omega$ y una capacitiva de $X_C = 10\,\Omega$, alimentadas por la misma fuente. ¿Qué carácter tiene el circuito?$it$,
   $it$Capacitivo, porque $X_C$ es la reactancia de mayor valor.$it$,
   $it$Resistivo, porque las dos reactancias se compensan.$it$,
   $it$Inductivo, porque la rama de menor reactancia es la que más corriente conduce.$it$,
   $it$Depende de la resistencia que haya en paralelo con ellas.$it$,
   $it$C$it$,
   $it$Ese criterio es el de la conexión en **serie**, donde manda la reactancia de mayor módulo porque las dos llevan la misma corriente. En paralelo las dos ven la misma tensión, y quien manda es la que deja pasar más corriente: la de reactancia **menor**.$it$,
   $it$Se compensarían solo si fueran iguales, que es la condición de resonancia. Acá $X_L = 2$ y $X_C = 10$: las corrientes de rama son $V/2$ y $V/10$, muy distintas entre sí.$it$,
   $it$Correcto. $I_L = V/2$ es cinco veces mayor que $I_C = V/10$, así que la corriente total atrasa: el circuito es inductivo. En paralelo conviene razonar con **admitancias**, donde $B_L = 1/X_L$ es el término dominante.$it$,
   $it$Una resistencia en paralelo cambia el factor de potencia y el ángulo, pero no puede invertir el signo de la parte reactiva: la resistencia solo aporta conductancia, que es real.$it$,
   $it$et/impedancia/caracter-por-la-reactancia-mayor$it$, $it$et/impedancia/caracter-por-la-reactancia-mayor$it$, null, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/impedancia$it$,
   (0.9), 150,
   $it$Un circuito paralelo tiene tres ramas: $R = 20\,\Omega$, $X_L = 10\,\Omega$ y $X_C = 20\,\Omega$. ¿Cuánto vale la admitancia total?$it$,
   $it$$0{,}05 - j0{,}05$ S$it$,
   $it$$0{,}05 + j0{,}15$ S$it$,
   $it$$0{,}05 - j0{,}15$ S$it$,
   $it$$0{,}05 + j0{,}05$ S$it$,
   $it$A$it$,
   $it$Correcto. $Y = \dfrac{1}{R} + j\left(\dfrac{1}{X_C} - \dfrac{1}{X_L}\right) = 0{,}05 + j(0{,}05 - 0{,}1) = 0{,}05 - j0{,}05$ S. La susceptancia neta es negativa: el circuito es inductivo, como corresponde a la rama de menor reactancia.$it$,
   $it$Sumaste las dos susceptancias en vez de restarlas ($0{,}1 + 0{,}05$) y encima con signo positivo. Inductor y capacitor aportan susceptancias de signo **opuesto**, igual que aportan reactancias de signo opuesto.$it$,
   $it$El signo está bien pero el módulo no: sumaste las dos susceptancias en vez de restarlas. La resta da $0{,}05$, no $0{,}15$.$it$,
   $it$El módulo está bien, el signo no. En admitancia el capacitor aporta $+jB_C$ y el inductor $-jB_L$; acá domina el inductor, así que la parte imaginaria neta es negativa.$it$,
   null, $it$et/impedancia/reactancias-sin-restarse$it$, $it$et/impedancia/reactancias-sin-restarse$it$, $it$et/admitancia/invierte-solo-el-modulo$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/impedancia$it$,
   (1.2), 160,
   $it$En el mismo circuito paralelo del problema anterior ($Y = 0{,}05 - j0{,}05$ S) se aplican $100$ V eficaces. ¿Cuánto vale la **componente real** de la corriente total?$it$,
   $it$$7{,}07$ A$it$,
   $it$$10$ A$it$,
   $it$$0$ A, porque las reactancias no aportan corriente real.$it$,
   $it$$5$ A$it$,
   $it$D$it$,
   $it$Ese es el **módulo** de la corriente total: $|Y|\,V = 0{,}0707 \times 100$. La componente real es solo su proyección sobre el eje de la tensión, y vale menos.$it$,
   $it$Duplicaste. La componente real de la corriente es $V \times G$, con $G = 1/R = 0{,}05$ S: da $5$ A. Un $10$ saldría con $R = 10\,\Omega$, que no es el dato.$it$,
   $it$Al revés: la componente real la aporta justamente la rama resistiva, y es la única que consume potencia. Lo que no aportan las reactancias es componente **real**, pero el resistor sigue ahí.$it$,
   $it$Correcto. $\vec{I} = \vec{V}\vec{Y} = 100(0{,}05 - j0{,}05) = 5 - j5$ A: la componente real es $5$ A. Y tiene sentido físico — la parte real de la corriente es exactamente la que circula por el resistor.$it$,
   $it$et/ca/componente-real-como-modulo$it$, null, $it$et/reactancia/disipa-potencia$it$, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/impedancia$it$,
   (1.4), 170,
   $it$Un circuito serie RLC tiene $R = 5\,\Omega$, $X_L = 16\,\Omega$ y $X_C = 4\,\Omega$, alimentado con $130$ V eficaces. ¿Cuánto vale la corriente?$it$,
   $it$$10$ A, atrasada $67{,}4^\circ$$it$,
   $it$$6{,}3$ A, atrasada $76^\circ$$it$,
   $it$$13$ A, adelantada $67{,}4^\circ$$it$,
   $it$$10$ A, adelantada $67{,}4^\circ$$it$,
   $it$A$it$,
   $it$Correcto. $X = 16-4 = 12\,\Omega$ inductivos, $|Z| = \sqrt{5^{2}+12^{2}} = 13\,\Omega$ e $I = 130/13 = 10$ A. El ángulo es $\arctan(12/5) = 67{,}4^\circ$ y, por ser inductivo, la corriente **atrasa**.$it$,
   $it$Sumaste las dos reactancias ($16+4 = 20$) en vez de restarlas, y con eso $|Z| = \sqrt{25+400} \approx 20{,}6\,\Omega$. $X_L$ y $X_C$ están a $180^\circ$ una de otra: se restan.$it$,
   $it$El $13$ es el módulo de la **impedancia**, no el de la corriente: falta dividir los $130$ V por él. Y el sentido del desfase está invertido: con $X_L > X_C$ el circuito es inductivo.$it$,
   $it$El módulo está bien pero el desfase está al revés. La reactancia neta es inductiva ($+12\,\Omega$), así que el ángulo de la impedancia es positivo y el de la corriente, negativo: atrasa.$it$,
   null, $it$et/impedancia/reactancias-sin-restarse$it$, $it$et/ohm/multiplica-en-vez-de-dividir$it$, $it$et/impedancia/angulo-con-signo-cambiado$it$),

  -- ===========================================================================
  -- electrotecnia/potencia_ca
  -- ===========================================================================
  ($it$electrotecnia_ca$it$, $it$electrotecnia/potencia_ca$it$,
   (0.4), 110,
   $it$Un circuito toma $\vec{I} = 5 - j5$ A de una fuente de $100\angle 0^\circ$ V. ¿Cuánta potencia **activa** consume?$it$,
   $it$$707$ W$it$,
   $it$$500$ W$it$,
   $it$$1000$ W$it$,
   $it$$0$ W$it$,
   $it$B$it$,
   $it$Usaste el módulo de la corriente: $100 \times 7{,}07$. Eso es la potencia **aparente** en VA. La activa exige proyectar la corriente sobre la tensión, o sea usar solo su componente real.$it$,
   $it$Correcto. Con la tensión como referencia, $P = V \times \operatorname{Re}(\vec{I}) = 100 \times 5 = 500$ W. La componente imaginaria, $-j5$ A, da la reactiva: $Q = 500$ var inductivos.$it$,
   $it$Sumaste las dos componentes de la corriente como si fueran una sola. La parte real y la imaginaria son perpendiculares: no se suman aritméticamente.$it$,
   $it$Habría potencia activa nula solo si la corriente fuera puramente imaginaria. Acá tiene componente real de $5$ A, que es exactamente la que produce trabajo.$it$,
   $it$et/ca/componente-real-como-modulo$it$, null, $it$et/potencia/aparente-como-suma-aritmetica$it$, $it$et/reactancia/disipa-potencia$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/potencia_ca$it$,
   (0.7), 120,
   $it$Un motor consume $3$ kW con factor de potencia $0{,}6$ en atraso. ¿Cuánta potencia reactiva toma?$it$,
   $it$$1{,}8$ kvar$it$,
   $it$$5$ kvar$it$,
   $it$$4$ kvar$it$,
   $it$$2$ kvar$it$,
   $it$C$it$,
   $it$Multiplicaste la activa por el factor de potencia. La reactiva sale de $Q = P\tan\varphi$, y con $\cos\varphi = 0{,}6$ la tangente vale $0{,}8/0{,}6 = 1{,}33$.$it$,
   $it$Ese es $S = P/\cos\varphi = 3/0{,}6 = 5$ kVA, la potencia **aparente**. La reactiva es el otro cateto: $Q = \sqrt{S^{2}-P^{2}} = \sqrt{25-9} = 4$ kvar.$it$,
   $it$Correcto. $S = 5$ kVA y $Q = \sqrt{5^{2}-3^{2}} = 4$ kvar. Es el triángulo $3$-$4$-$5$ otra vez, ahora en potencias. Equivale a $Q = P\tan\varphi = 3 \times 1{,}33 = 4$ kvar.$it$,
   $it$Restaste $5-3$. Activa, reactiva y aparente forman un triángulo **rectángulo**: la reactiva es un cateto, y se obtiene con Pitágoras, no restando la hipotenusa.$it$,
   $it$et/potencia/fp-sin-coseno$it$, null, null, $it$et/potencia/aparente-como-suma-aritmetica$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/potencia_ca$it$,
   (0.9), 130,
   $it$Dos cargas se conectan en paralelo a la misma red: una de $P_1 = 4$ kW, $Q_1 = 3$ kvar inductivos, y otra de $P_2 = 2$ kW, $Q_2 = 1$ kvar capacitivos. ¿Cuál es la potencia aparente total?$it$,
   $it$$10$ kVA$it$,
   $it$$6$ kVA$it$,
   $it$$7{,}2$ kVA$it$,
   $it$$6{,}3$ kVA$it$,
   $it$D$it$,
   $it$Sumaste los cuatro números. Las activas sí se suman entre sí y las reactivas entre sí, pero las reactivas de distinto signo se **restan**, y el total activo y reactivo se combinan con Pitágoras.$it$,
   $it$Ese es solo $P_T$. Falta incorporar los $2$ kvar netos, que hacen que la instalación tenga que dimensionarse para algo más que los $6$ kW útiles.$it$,
   $it$Sumaste las dos reactivas en vez de restarlas ($3+1 = 4$). Una carga inductiva y una capacitiva aportan reactiva de signo opuesto: se compensan parcialmente, y en eso se basa la corrección del factor de potencia.$it$,
   $it$Correcto. $P_T = 4+2 = 6$ kW y $Q_T = 3-1 = 2$ kvar inductivos netos. Entonces $S = \sqrt{36+4} \approx 6{,}3$ kVA. Las potencias se suman por componentes, exactamente como los fasores.$it$,
   $it$et/potencia/aparente-como-suma-aritmetica$it$, $it$et/potencia/reactiva-se-consume$it$, $it$et/impedancia/reactancias-sin-restarse$it$, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/potencia_ca$it$,
   (1.2), 140,
   $it$Una instalación de $10$ kW tiene $\cos\varphi = 0{,}7$ en atraso y se quiere llevar a $0{,}95$. ¿Qué potencia reactiva capacitiva hay que agregar?$it$,
   $it$$10{,}2$ kvar$it$,
   $it$$3{,}3$ kvar$it$,
   $it$$6{,}9$ kvar$it$,
   $it$$2{,}5$ kvar$it$,
   $it$C$it$,
   $it$Ese es $Q_1$, la reactiva **inicial** ($10 \times \tan 45{,}6^\circ$). Compensarla entera llevaría el factor de potencia a $1$, no a $0{,}95$; y sobrecompensar es un problema real, porque deja la instalación capacitiva.$it$,
   $it$Ese es $Q_2$, la reactiva que la instalación debe **conservar** para quedar en $0{,}95$: $10 \times \tan 18{,}2^\circ = 3{,}3$ kvar. Lo que hay que agregar es la diferencia con la inicial.$it$,
   $it$Correcto. $Q_C = P(\tan\varphi_1 - \tan\varphi_2) = 10(1{,}02 - 0{,}33) \approx 6{,}9$ kvar. La activa no cambia: los capacitores solo cancelan reactiva.$it$,
   $it$No corresponde a ninguno de los dos términos de la fórmula. Conviene calcular los dos ángulos por separado —$\arccos 0{,}7$ y $\arccos 0{,}95$—, sus tangentes, y recién entonces restar.$it$,
   $it$et/potencia/corrige-fp-con-el-elemento-equivocado$it$, null, null, $it$et/potencia/fp-sin-coseno$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/potencia_ca$it$,
   (1.4), 150,
   $it$Dos cargas distintas tienen el mismo factor de potencia, $0{,}8$: una en atraso y la otra en adelanto. ¿En qué se diferencian?$it$,
   $it$En nada eléctricamente: el factor de potencia las describe por completo.$it$,
   $it$La primera consume reactiva inductiva y la segunda capacitiva; se corrigen con elementos opuestos.$it$,
   $it$La segunda consume menos potencia activa que la primera.$it$,
   $it$La segunda no consume potencia aparente.$it$,
   $it$B$it$,
   $it$El número es el mismo, pero el signo del ángulo no: $+36{,}9^\circ$ contra $-36{,}9^\circ$. Conectadas juntas se compensan entre sí; tratadas como iguales, cualquier corrección va a empeorar una de las dos.$it$,
   $it$Correcto. En atraso la corriente va detrás de la tensión (carga inductiva, $Q > 0$); en adelanto va delante (carga capacitiva, $Q < 0$). Por eso el factor de potencia siempre se informa con su carácter: «$0{,}8$ en atraso» y «$0{,}8$ en adelanto» piden correcciones contrarias.$it$,
   $it$Con el mismo $\cos\varphi$ y la misma aparente, la activa es la misma: $P = S\cos\varphi$. Lo que cambia es el **signo** de la reactiva, no el valor de la activa.$it$,
   $it$Toda carga con corriente y tensión no nulas tiene potencia aparente. Lo que puede ser nula es la activa (si $\cos\varphi = 0$) o la reactiva (si $\cos\varphi = 1$), y acá no es ninguno de los dos casos.$it$,
   $it$et/potencia/factor-de-potencia-sin-caracter$it$, null, $it$et/potencia/factor-de-potencia-sin-caracter$it$, $it$et/potencia/reactiva-se-consume$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/potencia_ca$it$,
   (1.6), 160,
   $it$Un circuito serie tiene $R = 12\,\Omega$ y $X_L = 16\,\Omega$ y circulan por él $5$ A eficaces. ¿Cuáles son $P$, $Q$ y $S$?$it$,
   $it$$P = 300$ W, $Q = 400$ var, $S = 500$ VA$it$,
   $it$$P = 400$ W, $Q = 300$ var, $S = 500$ VA$it$,
   $it$$P = 300$ W, $Q = 400$ var, $S = 700$ VA$it$,
   $it$$P = 700$ W, $Q = 0$ var, $S = 700$ VA$it$,
   $it$A$it$,
   $it$Correcto. $P = I^{2}R = 25 \times 12 = 300$ W, $Q = I^{2}X_L = 25 \times 16 = 400$ var y $S = I^{2}|Z| = 25 \times 20 = 500$ VA. El triángulo de potencias es el de impedancias escalado por $I^{2}$: mismos ángulos, misma forma.$it$,
   $it$Intercambiaste $R$ y $X_L$. La potencia activa la produce la **resistencia** y la reactiva la reactancia; cambiarlas de lugar invierte el carácter del circuito.$it$,
   $it$$P$ y $Q$ están bien, pero $S$ lo obtuviste sumándolos. La aparente es la hipotenusa: $\sqrt{300^{2}+400^{2}} = 500$ VA, no $700$.$it$,
   $it$Sumaste $R$ y $X_L$ como si el circuito fuera puramente resistivo de $28\,\Omega$. La reactancia no aporta potencia activa, y por eso $Q$ no puede ser cero mientras haya $X_L$.$it$,
   null, $it$et/potencia/formula-con-la-variable-equivocada$it$, $it$et/potencia/aparente-como-suma-aritmetica$it$, $it$et/impedancia/suma-aritmetica-de-modulos$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/potencia_ca$it$,
   (1.8), 170,
   $it$¿Por qué las distribuidoras penalizan a los clientes industriales con factor de potencia bajo?$it$,
   $it$Porque la energía reactiva se pierde en calor dentro de la red.$it$,
   $it$Porque el cliente consume más energía activa de la que declara.$it$,
   $it$Porque el factor de potencia bajo baja la frecuencia del sistema.$it$,
   $it$Porque la corriente adicional obliga a sobredimensionar conductores y transformadores y aumenta las pérdidas $I^{2}R$ de la red.$it$,
   $it$D$it$,
   $it$La reactiva en sí no se disipa: va y vuelve. Lo que sí se disipa es la pérdida $I^{2}R$ **provocada** por la corriente extra que la reactiva obliga a hacer circular, y esa es la pérdida real.$it$,
   $it$La activa es la que es y está medida. El problema no es que consuma más energía útil, sino que para entregarle esa energía la red tiene que transportar más corriente.$it$,
   $it$La frecuencia del sistema la sostiene el balance entre generación y demanda de potencia **activa**. El factor de potencia afecta a la tensión y a las pérdidas, no a la frecuencia.$it$,
   $it$Correcto. Con $\cos\varphi = 0{,}5$, entregar los mismos kW exige el doble de corriente, y las pérdidas en los conductores —proporcionales al **cuadrado** de la corriente— se cuadruplican. La penalización traslada ese costo a quien lo genera.$it$,
   $it$et/potencia/reactiva-se-consume$it$, $it$et/potencia/reactiva-se-consume$it$, null, null),

  -- ===========================================================================
  -- electrotecnia/resonancia
  -- ===========================================================================
  ($it$electrotecnia_ca$it$, $it$electrotecnia/resonancia$it$,
   (0.8), 110,
   $it$Un RLC serie tiene $R = 10\,\Omega$, $L = 100$ mH y $C = 10\,\mu\text{F}$. ¿Cuánto vale $\omega_0$?$it$,
   $it$$1000$ rad/s$it$,
   $it$$159$ rad/s$it$,
   $it$$10^{6}$ rad/s$it$,
   $it$$100$ rad/s$it$,
   $it$A$it$,
   $it$Correcto. $\omega_0 = \dfrac{1}{\sqrt{LC}} = \dfrac{1}{\sqrt{0{,}1 \times 10^{-5}}} = \dfrac{1}{10^{-3}} = 1000$ rad/s. La resistencia no entra: solo fija el $Q$ del circuito.$it$,
   $it$Ese es $f_0$ en hertz ($1000/2\pi \approx 159$ Hz), no $\omega_0$. La pregunta pide la frecuencia angular, que es la que sale directamente de $1/\sqrt{LC}$.$it$,
   $it$Olvidaste la raíz cuadrada: $1/(LC) = 10^{6}$. Con la raíz, $\sqrt{10^{-6}} = 10^{-3}$ y el resultado baja tres órdenes de magnitud.$it$,
   $it$Metiste $R$ en la cuenta, o perdiste un prefijo. La frecuencia de resonancia depende **solo** de $L$ y $C$; $R$ aparece en el factor de calidad, no acá.$it$,
   null, $it$et/ca/omega-sin-2pi$it$, null, $it$et/resonancia/frecuencia-depende-de-r$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/resonancia$it$,
   (1.1), 120,
   $it$Para el mismo circuito ($R = 10\,\Omega$, $L = 100$ mH, $\omega_0 = 1000$ rad/s), ¿cuánto vale el factor de calidad $Q$?$it$,
   $it$$0{,}1$$it$,
   $it$$100$$it$,
   $it$$10$$it$,
   $it$$1000$$it$,
   $it$C$it$,
   $it$Invertiste la razón: calculaste $R/(\omega_0 L)$. El factor de calidad de un circuito serie es $Q = \omega_0 L/R$, y una resistencia **menor** da un $Q$ mayor, no menor.$it$,
   $it$Multiplicaste por diez de más, o usaste $L = 1$ H. Con $L = 0{,}1$ H la reactancia en resonancia es $\omega_0 L = 100\,\Omega$, y dividida por $R = 10\,\Omega$ da $10$.$it$,
   $it$Correcto. $Q = \dfrac{\omega_0 L}{R} = \dfrac{1000 \times 0{,}1}{10} = 10$. Con eso el ancho de banda es $BW = \omega_0/Q = 100$ rad/s, y la sobretensión sobre $L$ y $C$ es diez veces la de la fuente.$it$,
   $it$Ese es $\omega_0$, no $Q$. El factor de calidad es adimensional: es un cociente entre dos magnitudes en ohm.$it$,
   $it$et/resonancia/q-y-ancho-de-banda-directos$it$, $it$et/unidades/prefijos-mal-convertidos$it$, null, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/resonancia$it$,
   (1.4), 130,
   $it$Un filtro resonante tiene $f_0 = 455$ kHz y ancho de banda de $10$ kHz. ¿Cuánto vale su factor de calidad?$it$,
   $it$$45{,}5$$it$,
   $it$$4550$$it$,
   $it$$0{,}022$$it$,
   $it$$465$$it$,
   $it$A$it$,
   $it$Correcto. $Q = f_0/BW = 455/10 = 45{,}5$. Es el valor típico de un filtro de frecuencia intermedia de radio AM, cuya banda de $10$ kHz es exactamente la que ocupa una emisora.$it$,
   $it$Multiplicaste por el ancho de banda en vez de dividir, o mezclaste los prefijos. Un $Q$ de $4550$ describiría un filtro extraordinariamente selectivo, con un ancho de banda de solo $100$ Hz.$it$,
   $it$Invertiste la razón: eso es $BW/f_0$. El factor de calidad mide **selectividad**, así que crece cuando el ancho de banda es chico frente a la frecuencia central.$it$,
   $it$Sumaste $455 + 10$. La relación entre $Q$, $f_0$ y $BW$ es multiplicativa, no aditiva: las tres magnitudes no comparten unidad.$it$,
   null, $it$et/resonancia/q-y-ancho-de-banda-directos$it$, $it$et/resonancia/q-y-ancho-de-banda-directos$it$, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/resonancia$it$,
   (1.7), 140,
   $it$En un RLC serie **por debajo** de su frecuencia de resonancia, ¿cómo se comporta el circuito?$it$,
   $it$Inductivo: la corriente atrasa a la tensión.$it$,
   $it$Resistivo puro.$it$,
   $it$Capacitivo: la corriente adelanta a la tensión.$it$,
   $it$Depende del valor de $R$.$it$,
   $it$C$it$,
   $it$Ese es el comportamiento **por encima** de la resonancia, donde $X_L$ ya superó a $X_C$. Por debajo pasa lo contrario, porque $X_C = 1/(\omega C)$ crece a medida que la frecuencia baja.$it$,
   $it$El circuito es resistivo puro **en** la resonancia, exactamente en $f_0$. A cualquier otra frecuencia hay reactancia neta, de un signo o del otro.$it$,
   $it$Correcto. Por debajo de $f_0$, $X_C > X_L$ y la reactancia neta es capacitiva: la corriente adelanta. La regla completa es «capacitivo abajo, resistivo en $f_0$, inductivo arriba», y describe la curva entera.$it$,
   $it$$R$ determina cuánta corriente circula y qué tan marcado es el pico, pero no el signo de la reactancia neta, que depende solo de $X_L$ y $X_C$.$it$,
   $it$et/reactancia/xc-crece-con-la-frecuencia$it$, $it$et/resonancia/reactancias-se-anulan-fisicamente$it$, null, $it$et/resonancia/frecuencia-depende-de-r$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/resonancia$it$,
   (1.9), 150,
   $it$Un RLC serie en resonancia tiene $R = 4\,\Omega$ y se alimenta con $20$ V eficaces. ¿Qué potencia disipa?$it$,
   $it$$0$ W: en resonancia las reactancias se cancelan.$it$,
   $it$$5$ W$it$,
   $it$$80$ W$it$,
   $it$$100$ W$it$,
   $it$D$it$,
   $it$Lo que se cancela es la reactancia, no la resistencia. En resonancia el circuito es resistivo puro y disipa **más** que en cualquier otra frecuencia, porque es cuando circula la corriente máxima.$it$,
   $it$Ese es el valor de la corriente en ampere, no de la potencia. Falta el último paso: multiplicar por la tensión, o elevar al cuadrado y multiplicar por $R$.$it$,
   $it$Multiplicaste $20 \times 4$. Ese producto no corresponde a ninguna fórmula de potencia con estos datos: con tensión y resistencia hay que usar $V^{2}/R$.$it$,
   $it$Correcto. En resonancia $|Z| = R = 4\,\Omega$, así que $I = 20/4 = 5$ A y $P = I^{2}R = 25 \times 4 = 100$ W. También $P = V^{2}/R = 400/4$, porque el factor de potencia vale $1$.$it$,
   $it$et/resonancia/reactancias-se-anulan-fisicamente$it$, null, null, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/resonancia$it$,
   (2.1), 160,
   $it$Si en un RLC serie se **cuadruplica** la capacitancia sin tocar $L$, ¿qué le pasa a la frecuencia de resonancia?$it$,
   $it$Se cuadruplica.$it$,
   $it$Se reduce a la cuarta parte.$it$,
   $it$Se reduce a la mitad.$it$,
   $it$No cambia.$it$,
   $it$C$it$,
   $it$El sentido está invertido y el factor también. $C$ está en el **denominador** y bajo una raíz: al aumentarla, la frecuencia baja, y lo hace como $1/\sqrt{C}$.$it$,
   $it$El sentido es el correcto, pero el factor no: la raíz cuadrada de $4$ es $2$, así que la frecuencia se divide por dos y no por cuatro.$it$,
   $it$Correcto. $f_0 = 1/(2\pi\sqrt{LC})$: multiplicar $C$ por $4$ multiplica $\sqrt{LC}$ por $2$, y la frecuencia se divide por $2$. Es la razón de que para sintonizar una banda entera de radio se necesite un capacitor variable de gran rango.$it$,
   $it$$f_0$ es independiente de $R$, no de $C$. Cambiar $L$ o $C$ mueve la resonancia; cambiar $R$ solo cambia la forma del pico.$it$,
   null, null, null, $it$et/resonancia/frecuencia-depende-de-r$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/resonancia$it$,
   (2.2), 170,
   $it$Un circuito tanque (RLC paralelo) se usa como filtro **rechaza-banda**. ¿Por qué funciona?$it$,
   $it$Porque en resonancia presenta impedancia máxima y bloquea el paso de esa frecuencia hacia la carga.$it$,
   $it$Porque en resonancia presenta impedancia nula y cortocircuita esa frecuencia.$it$,
   $it$Porque la resistencia disipa la frecuencia no deseada en forma de calor.$it$,
   $it$Porque desplaza la frecuencia no deseada fuera de la banda útil.$it$,
   $it$A$it$,
   $it$Correcto. En resonancia paralelo las susceptancias se cancelan y la admitancia queda en $1/R$: impedancia máxima. Puesto **en serie** con la señal, el tanque bloquea justo la frecuencia de resonancia y deja pasar el resto.$it$,
   $it$Esa es la resonancia **serie**. Un RLC serie sí presenta impedancia mínima en $f_0$, y puesto **en paralelo** con la señal actúa como rechaza-banda derivando esa frecuencia a masa. Son dos formas distintas de conseguir el mismo efecto.$it$,
   $it$La resistencia disipa lo que circula por ella, sin discriminar frecuencias. La selectividad la produce la combinación $L$-$C$, no la resistencia; $R$ solo controla qué tan angosto es el rechazo.$it$,
   $it$Un circuito lineal no desplaza frecuencias: las atenúa o las deja pasar. Generar frecuencias nuevas exige un elemento no lineal, como un mezclador.$it$,
   null, $it$et/resonancia/impedancia-maxima-en-serie$it$, null, null),

  -- ===========================================================================
  -- electrotecnia/trifasico
  -- ===========================================================================
  ($it$electrotecnia_ca$it$, $it$electrotecnia/trifasico$it$,
   (1.2), 110,
   $it$En un sistema trifásico, ¿qué relación hay entre la tensión de línea y la de fase en conexión **triángulo**?$it$,
   $it$$V_L = \sqrt{3}\,V_F$$it$,
   $it$$V_L = V_F$$it$,
   $it$$V_L = 3\,V_F$$it$,
   $it$$V_F = \sqrt{3}\,V_L$$it$,
   $it$B$it$,
   $it$Esa es la relación de la conexión **estrella**. En triángulo cada devanado está conectado directamente entre dos líneas, así que ve la tensión de línea completa.$it$,
   $it$Correcto. En triángulo $V_L = V_F$ y el $\sqrt{3}$ aparece en las corrientes; en estrella es al revés. Conviene memorizar la pareja completa, porque cada conexión tiene su factor en un solo lado.$it$,
   $it$El factor $3$ no aparece nunca entre tensiones de línea y de fase: es siempre $\sqrt{3}$, que viene de la geometría de dos fasores a $120^\circ$.$it$,
   $it$Está invertido y además con el factor de la estrella. En ninguna de las dos conexiones la tensión de fase supera a la de línea.$it$,
   $it$et/trifasico/confunde-fase-con-linea$it$, null, $it$et/trifasico/suma-aritmetica-de-fases$it$, $it$et/trifasico/raiz-de-tres-invertida$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/trifasico$it$,
   (1.5), 120,
   $it$Tres impedancias iguales de $20\,\Omega$ se conectan en **triángulo** a una red de $380$ V. ¿Cuánto vale la corriente de línea?$it$,
   $it$$19$ A$it$,
   $it$$11$ A$it$,
   $it$$57$ A$it$,
   $it$$32{,}9$ A$it$,
   $it$D$it$,
   $it$Ese es $I_F = V_F/Z = 380/20 = 19$ A, la corriente de **fase**, o sea la que circula por cada impedancia. En triángulo la de línea es $\sqrt{3}$ veces mayor.$it$,
   $it$Dividiste la tensión por $\sqrt{3}$ antes de usarla, como si la conexión fuera estrella. En triángulo cada impedancia ve los $380$ V completos.$it$,
   $it$Multiplicaste por $3$ en vez de por $\sqrt{3}$. Las tres corrientes de fase no se suman aritméticamente en un vértice: se combinan dos de ellas a $120^\circ$.$it$,
   $it$Correcto. $I_F = 380/20 = 19$ A e $I_L = \sqrt{3} \times 19 \approx 32{,}9$ A. El orden importa: primero la corriente de fase con la tensión de fase, después el $\sqrt{3}$ para pasar a línea.$it$,
   $it$et/trifasico/confunde-fase-con-linea$it$, $it$et/trifasico/raiz-de-tres-invertida$it$, $it$et/trifasico/suma-aritmetica-de-fases$it$, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/trifasico$it$,
   (1.8), 130,
   $it$Una carga trifásica equilibrada consume $15$ kVA con $\cos\varphi = 0{,}8$. ¿Cuánta potencia reactiva total toma?$it$,
   $it$$12$ kvar$it$,
   $it$$9$ kvar$it$,
   $it$$3$ kvar$it$,
   $it$$18{,}8$ kvar$it$,
   $it$B$it$,
   $it$Ese es $P = S\cos\varphi = 15 \times 0{,}8 = 12$ kW, la potencia **activa**. La reactiva usa el seno: $S\operatorname{sen}\varphi$.$it$,
   $it$Correcto. Con $\cos\varphi = 0{,}8$, $\operatorname{sen}\varphi = 0{,}6$, así que $Q = 15 \times 0{,}6 = 9$ kvar. También sale por Pitágoras: $\sqrt{15^{2}-12^{2}} = 9$.$it$,
   $it$Restaste $15-12$. El triángulo de potencias es rectángulo: la reactiva es un cateto y se obtiene con Pitágoras o con el seno, nunca restando la hipotenusa de un cateto.$it$,
   $it$Dividiste por el factor de potencia en vez de multiplicar por el seno. La reactiva nunca puede superar a la aparente, que es la hipotenusa del triángulo.$it$,
   $it$et/potencia/fp-sin-coseno$it$, null, $it$et/potencia/aparente-como-suma-aritmetica$it$, $it$et/potencia/fp-sin-coseno$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/trifasico$it$,
   (2.1), 140,
   $it$Un motor trifásico de $380$ V toma $30$ A de línea con $\cos\varphi = 0{,}88$ y tiene un rendimiento del $90\,\%$. ¿Qué potencia mecánica entrega?$it$,
   $it$$17{,}4$ kW$it$,
   $it$$15{,}6$ kW$it$,
   $it$$19{,}3$ kW$it$,
   $it$$9$ kW$it$,
   $it$B$it$,
   $it$Esa es la potencia **eléctrica absorbida**: $\sqrt{3} \times 380 \times 30 \times 0{,}88 \approx 17{,}4$ kW. Falta aplicar el rendimiento: parte de esa potencia se pierde en el cobre, el hierro y el rozamiento.$it$,
   $it$Correcto. $P_{abs} = \sqrt{3}\,V_L I_L \cos\varphi \approx 17{,}4$ kW, y $P_{mec} = 0{,}9 \times 17{,}4 \approx 15{,}6$ kW. Rendimiento y factor de potencia son cosas distintas: uno mide pérdidas, el otro desfase.$it$,
   $it$Dividiste por el rendimiento en vez de multiplicar. Un motor entrega **menos** de lo que absorbe: el rendimiento siempre reduce.$it$,
   $it$Aplicaste el rendimiento sobre un valor que no lleva el $\sqrt{3}$, o mezclaste los factores. Conviene calcular primero la potencia absorbida completa y recién después multiplicar por $0{,}9$.$it$,
   null, null, null, $it$et/trifasico/potencia-sin-raiz-de-tres$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/trifasico$it$,
   (2.3), 150,
   $it$En una instalación con cargas **desequilibradas** en estrella con neutro, ¿qué corriente circula por el neutro?$it$,
   $it$Cero, como en cualquier sistema trifásico.$it$,
   $it$La suma aritmética de las tres corrientes de fase.$it$,
   $it$La suma **fasorial** de las tres corrientes de fase, que ya no se cancela.$it$,
   $it$Un tercio de la corriente de la fase más cargada.$it$,
   $it$C$it$,
   $it$La cancelación exige que las tres corrientes tengan el mismo módulo. Con cargas distintas eso no ocurre, y por el neutro circula la corriente de desbalance: por eso en instalaciones domiciliarias el neutro no se dimensiona a la ligera.$it$,
   $it$Sumar módulos daría un valor mucho mayor que el real, porque ignora los $120^\circ$ de desfase. Incluso desequilibradas, las tres corrientes siguen apuntando en direcciones distintas y se compensan en parte.$it$,
   $it$Correcto. $\vec{I_N} = \vec{I_a} + \vec{I_b} + \vec{I_c}$, siempre. Lo que cambia es que en el caso equilibrado esa suma da cero y en el desequilibrado no. El neutro es, literalmente, el camino de retorno de lo que no se cancela.$it$,
   $it$No hay ninguna regla de tercios. La corriente del neutro depende de los módulos **y** de los ángulos de las tres corrientes, y hay que calcularla como suma de fasores.$it$,
   $it$et/trifasico/desequilibrado-con-formulas-de-equilibrado$it$, $it$et/trifasico/suma-aritmetica-de-fases$it$, null, $it$et/trifasico/desequilibrado-con-formulas-de-equilibrado$it$),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/trifasico$it$,
   (2.5), 160,
   $it$¿Por qué el arranque **estrella-triángulo** limita la corriente de partida de un motor?$it$,
   $it$Porque en estrella cada devanado recibe $V_L/\sqrt{3}$, y la corriente de línea de arranque cae a un tercio de la que tendría en triángulo.$it$,
   $it$Porque en estrella los devanados quedan en serie y se suma su impedancia.$it$,
   $it$Porque en estrella el motor arranca con una frecuencia menor.$it$,
   $it$Porque la conexión en estrella agrega una resistencia de arranque en serie.$it$,
   $it$A$it$,
   $it$Correcto. La tensión por devanado baja en $\sqrt{3}$, así que la corriente de fase baja en $\sqrt{3}$ y la de línea, que en estrella iguala a la de fase, termina siendo un **tercio** de la de triángulo. El par también cae a un tercio: por eso el método solo sirve para arranques en vacío o con poca carga.$it$,
   $it$En estrella los devanados no quedan en serie: quedan conectados entre una línea y el punto neutro común. Lo que cambia es la tensión que ve cada uno, no su asociación.$it$,
   $it$La frecuencia la impone la red y no cambia con la conexión. Arrancar con frecuencia reducida es lo que hace un variador de frecuencia, que es otro método distinto.$it$,
   $it$No se agrega ningún componente: se reconecta el mismo bobinado. El arranque con resistencias estatóricas existe, pero es otro método y sí disipa energía.$it$,
   null, $it$et/trifasico/confunde-fase-con-linea$it$, null, null),
  ($it$electrotecnia_ca$it$, $it$electrotecnia/trifasico$it$,
   (2.6), 170,
   $it$¿Cuántos vatímetros hacen falta, como mínimo, para medir la potencia activa total de un sistema trifásico de **tres conductores**, equilibrado o no?$it$,
   $it$Uno.$it$,
   $it$Tres, uno por fase.$it$,
   $it$Dos.$it$,
   $it$Cuatro, tres de fase y uno de neutro.$it$,
   $it$C$it$,
   $it$Con un solo vatímetro alcanza únicamente si el sistema es **equilibrado** y se dispone de neutro accesible: se mide una fase y se multiplica por tres. La pregunta pide el caso general, sin suponer equilibrio.$it$,
   $it$Tres funcionan, pero no son el mínimo. Es el método de tres vatímetros, que exige acceso al neutro; en un sistema de tres conductores ese punto puede no existir.$it$,
   $it$Correcto. Es el método de los dos vatímetros, consecuencia del teorema de Blondel (1893): con $n$ conductores bastan $n-1$ vatímetros. La suma algebraica de las dos lecturas da la potencia total, esté o no equilibrado el sistema.$it$,
   $it$En un sistema de tres conductores no hay neutro que medir. Y aunque lo hubiera, el teorema de Blondel dice que con cuatro conductores bastan tres vatímetros, nunca cuatro.$it$,
   $it$et/trifasico/desequilibrado-con-formulas-de-equilibrado$it$, null, null, $it$et/trifasico/suma-aritmetica-de-fases$it$)

)
insert into public.questions
  (topic, module_id, difficulty, order_index,
   question, option_a, option_b, option_c, option_d, correct_option,
   error_a, error_b, error_c, error_d,
   misconception_a_id, misconception_b_id, misconception_c_id, misconception_d_id)
select i.topic, m.id, i.difficulty, i.order_index,
       i.question, i.option_a, i.option_b, i.option_c, i.option_d, i.correct_option,
       i.error_a, i.error_b, i.error_c, i.error_d,
       xa.id, xb.id, xc.id, xd.id
from items i
left join public.modules m        on m.slug  = i.module_slug
left join public.misconceptions xa on xa.slug = i.mis_a
left join public.misconceptions xb on xb.slug = i.mis_b
left join public.misconceptions xc on xc.slug = i.mis_c
left join public.misconceptions xd on xd.slug = i.mis_d
-- Idempotente por (topic, question). Reaplicar NO actualiza un ítem ya
-- cargado: para corregirlo, editarlo en Admin → Preguntas o borrarlo primero.
where not exists (
  select 1 from public.questions q
   where q.topic = i.topic and q.question = i.question
);

-- -----------------------------------------------------------------------------
-- Verificación (correr después de aplicar)
-- -----------------------------------------------------------------------------
--   select count(*) from public.questions where topic = 'electrotecnia_ca';
--   -- esperado: 42 (más lo que ya hubiera)
--
--   -- Ningún ítem sin módulo: delataría un module_slug mal escrito.
--   select id from public.questions where topic = 'electrotecnia_ca' and module_id is null;
--   -- 0 filas
--
--   -- Ningún distractor perdió su idea errónea en el join.
--   select id, question from public.questions q
--    where topic = 'electrotecnia_ca'
--      and misconception_a_id is null and misconception_b_id is null
--      and misconception_c_id is null and misconception_d_id is null;
--   -- revisar: un ítem sin ninguna catalogada puede ser legítimo, varios no
--
--   -- La clave repartida (R-35): ninguna letra debe pasar del 40 %.
--   select correct_option, count(*) from public.questions
--    where topic = 'electrotecnia_ca' group by 1 order by 1;
--
-- Reversión: delete from public.questions where topic = 'electrotecnia_ca';
--            delete from public.misconceptions where slug in ('et/ca/componente-real-como-modulo', 'et/fasor/suma-sin-descomponer', 'et/impedancia/paralelo-con-formula-de-serie', …);
